### ISSUE TITLE
Protocolos especiales del curso

### ISSUE THREAD

**Issue by sitoro** [IIC2233-2016-1/syllabus#10]
Esta es una pregunta algo personal pero puede servirle a alguien que le ocurra algo parecido más adelante.
Hoy jueves 10 de marzo yo Sebastián Toro me accidenté en la mañana y producto de eso me esguincé el codo derecho y pasé todo el día en la clínica.
1.- Debido a esto no pude asistir a clases ni rendir la actividad ni el control (si es que hubo). Ante eso me debo conformar con el "no te preocupes, te evaluaremos con un 1 pero al final se borra la peor nota", o puedo hacer algo al respecto (tengo licencia médica obviamente) ?
2.- Como resultado de mi accidente mi brazo derecho estará inutilizable por dos semanas, significando esto que estaré en clara desventaja al programar (por no decir que casi no podría hacerlo) tanto en las clases venideras como ante la tarea 1 si es publicada dentro de ese lapso. Qué medidas se tomarían con mi situación en este particular curso?
De antemano agradezco por su comprensión de mi situación :)
Nota: Es predecible que otra persona está escribiendo esto por mí, pues yo no estoy en condiciones de hacerlo u.u

**Comment by bcsaldias** [comment]
Hola Sebastián,

Si quieres tratar estos temas con la coordinación del curso te invito a escribirme con copia a Jaime, quienes te podremos dar una respuesta más satisfactoria. Nos reservamos este espacio de Issues solo para las dudas de materia y relacionados.

Saludos !

**Comment by bcsaldias** [comment]
Hola Sebastián,

En primer lugar espero que ya estés cuidando tu lesión.

Si quieres tratar estos temas con la coordinación del curso te invito a escribirme con copia a Jaime, quienes te podremos dar una respuesta más satisfactoria. Nos reservamos este espacio de Issues solo para las dudas de materia y relacionados.

Saludos !

**Comment by bcsaldias** [comment]
Hola Sebastián,

En primer lugar espero que ya estés cuidando tu lesión.

Si quieres tratar estos temas con la coordinación del curso te invito a escribirme con copia a Jaime, quienes te podremos dar una respuesta más satisfactoria. Nos reservamos este espacio de Issues solo para las dudas de materia y relacionados.

Saludos !
