### ISSUE TITLE
Dudas Id subastas creadas

### ISSUE THREAD

**Issue by gbordoni** [IIC2233-2016-1/syllabus#100]
Cuando un usuario crea una subasta nueva, en que me baso para crearle un id a esa subasta?

saludos

**Comment by otro-felipe** [comment]
El id de la nueva subasta debe ser igual al id mas alto que exista en el sistema + 1.

**Comment by gantunesr** [comment]
¿Puede ser un id aleatorio que aun no ha sido utilizado?

**Comment by flobarrios** [comment]
Hola! En #65 lo respondieron. Si se puede

**Comment by fgvenegas** [comment]
Felcitaciones, eres la Issue numero 100 :+1:
