### ISSUE TITLE
Funcion subastas disponibles

### ISSUE THREAD

**Issue by rmant** [IIC2233-2016-1/syllabus#101]
Una pregunta, en el enunciado, en la parte de mostrar las subastas disponibles, dice :

> Se deberá dar la opción de buscar por nombre de producto o tipo de producto.

Esto se refiere a que, dentro de una subasta ya seleccionada, pueda buscar dentro de sus productos? O bien buscar todas las subastas que contengan ese producto, o tipo de producto. Gracias!

**Comment by tamycova** [comment]
Buscar todas las subastas que contengan ese producto o tipo de producto, y una vez que se seleccione una particular poder ver toda su info (lo que sale al final de ese párrafo en el enunciado)

**Comment by rmant** [comment]
Gracias!
