### ISSUE TITLE
Consultas: Subastas por usuario involucrado

### ISSUE THREAD

**Issue by sormazabal** [IIC2233-2016-1/syllabus#102]
En el enunciado dice: "Ingresando el nombre de usuario, se deberan mostrar todas
las subastas en la que este se haya visto involucrado (comprador, vendedor, o apostador)."

No me queda muy claro si esto se refiere a que tengo que mostrar las subastas activas y las finalizadas en que haya participado el usuario o sólo las activas en las que este se haya involucrado.

**Comment by sormazabal** [comment]
Otra cosa, tengo que indicar en el output del programa si el usuario participó en esa subasta como comprador, vendedor o aposador?

**Comment by flobarrios** [comment]
Activas y finalizadas !

**Comment by sormazabal** [comment]
gracias!! oye, y debo indicar si el usuario fue apostador, vendedor o comprador?

**Comment by flobarrios** [comment]
Si! Debes especificar eso
