### ISSUE TITLE
¿Que pasa cuando se multa a alguien ya multado?

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#103]
Solo quiero saver que deveria hacer en ese caso.

**Comment by Geeermy** [comment]
Hola! (de nuevo jaja). Tiene que pagar ambas. No será baneado hasta que venza alguna de ellas (la primera, en particular). Puede pagar en el orden que desee también, pero debería pagar la que vence primero, obviamente.
Saludos (nuevamente)!

**Comment by perojas3** [comment]
Y que pasa con una multa si la otra ya vencio?

**Comment by Geeermy** [comment]
Si una multa ya venció, básicamente se va baneado y pierde todos sus productos, por lo que puedes considerar esa multa como vencida también (ya no tiene sentido tenerla vigente).
