### ISSUE TITLE
¿Que pasa cuando termina una subasta y nadie ha apostado?

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#104]
Requiero saber esto para continuar con el codigo.

**Comment by Geeermy** [comment]
Hola! La subasta finaliza, no hay un ganador y el producto se queda con el dueño que quería venderlo. Una buena opción para filtrar sería poner al ganador como el dueño original, pero eso lo puedes dejar a criterio y explicitado en el README. Saludos!
