### ISSUE TITLE
Menu - Subastas disponibles

### ISSUE THREAD

**Issue by matnagra** [IIC2233-2016-1/syllabus#105]
En las funcionalidades en una parte sale "Apostar en una subasta: Para apostar en una subasta, el usuario debe haber seleccionado alguna".
Esto quiere decir que "Apostar subastas" no debe aparecer en el menú inicial, sino que debe estar dentro de "Subastas disponibles", que es donde el usuario selecciona una subasta.

**Comment by bamavrakis** [comment]
Hola!
Exacto.
Saludos

**Comment by IsaacConDosA** [comment]
@bamavrakis Hola!, para seleccionar una subasta, deben ingresar el id de la subasta cierto? salu3
