### ISSUE TITLE
Contradiccion sistema de apuestas y mostrar subastas 

### ISSUE THREAD

**Issue by rmant** [IIC2233-2016-1/syllabus#106]
En el sistema de apuesta se nos indica que el usuario no tiene acceso a saber cual es la apuesta que hizo el usuario que va ganando, solo se puede mostrar el precio actual

> Notar que los usuarios no pueden ver el máximo que ha apostado cada uno, solo pueden ver el precio actual de la subasta y el ganador actual.

Sin embargo, el enunciado también dice que cuando el usuario selecciona una subasta, dentro de los atributos que se imprimen, nos piden imprimir el historial de apuestas, lo que le daría acceso a saber cuanto apostó cada uno.

> Al seleccionar una subasta, se debe mostrar su información relevante (nombre de producto, precio, historial de apuestas, tiempo restante) y se dará la opción de apostar.

¿Qué hacemos al respecto? 
Gracias!

**Comment by jpdattas** [comment]
#81 Acá me respondieron eso
