### ISSUE TITLE
No entiendo el sistema de apuestas

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#107]
El pdf literalmente dice, y cito: "Al apostar, el usuario esta indicando la cantidad maxima que esta dispuesto a pagar en ese momento. Si es el primer postor, entonces el precio actual del producto seria simplemente un MercadiPeso mayor al precio inicial. Asi, si un usuario apuesta una cantidad menor a la maxima ingresada por el ganador vigente,el precio actual del producto seria un MercadiPeso mayor a la cantidad ingresada por el segundo postor, salvo que el ganador actual seguira siendo el primero. En cambio, si el segundo postor ingresara un maximo mayor, el precio actual sera un MercadiPeso mayor a la cantidad del primer postor, siendo el segundo ahora el ganador. Notar que los usuarios no pueden ver el maximo que ha apostado cada uno, solo pueden ver el precio actual de la subasta y el ganador actual. En caso de que ambos apuesten el mismo maximo, el precio actual seria ese mismo, pero el primer postor seria considerado el ganador actual. Si apuesta una cantidad menor o igual al precio actual, la apuesta no sera ingresada."

Toda esta cosa no la entiendo ¿Gana el que halla apotado más o no?

**Comment by Geeermy** [comment]
Hola (por tercera vez)! Esto fue explicado con más detalle en #49 para que le eches un vistazo (la respuesta de @bamavrakis ). Si quedas con dudas trataré de explicarlo nuevamente lo mejor posible.
Saludos x 3!

**Comment by perojas3** [comment]
Entonces ¿Gana el que más apuesta, pero tiene que pagar +1 que el anterior?
¿Puedo suponer que esta prohibido apostar menos del precio?

**Comment by bamavrakis** [comment]
Hola!
Si a lo primero, y no a lo segundo.
Saludos!

**Comment by perojas3** [comment]
Y si alguien gana con más de lo que tiene,y es multado ¿Puedo borrarlo del historial?
