### ISSUE TITLE
Rigor atributos

### ISSUE THREAD

**Issue by jpdattas** [IIC2233-2016-1/syllabus#111]
Hola. quería saber si los atributos de las clases tienen que tener necesariamente los tipos del enunciado. 

Por ejemplo para las id, hasta ahora las guardo como str. Hasta ahora no supondría ninguna ventaja pasarlas a int (quizás algo de eficiencia?)

**Comment by negebauer** [comment]
@jpdattas Tu modelamiento queda a tu criterio. Si hay datos que guardas distinto a como se te entregan déjalo especificado en el README para una mejor corrección.
Eso si, te recuerdo que los ids tienen que ser **únicos** (esto es ~~mucho~~ más fácil guardándolos como int)
