### ISSUE TITLE
Buscar subasta

### ISSUE THREAD

**Issue by IsaacConDosA** [IIC2233-2016-1/syllabus#112]
Hola!
Para buscar una subasta por nombre de producto, los usuarios deben ingresar el nombre COMPLETO del producto para que les aparezca o pueden poner algo general como: "auto azul" y les debe aparecer todas las subastas en que aparezcan esas palabras en los productos?
Saludos

**Comment by bamavrakis** [comment]
Hola!
Eso queda a tu criterio, pero recuerda especificarlo en el README.
Saludos.

**Comment by dasotosilva19** [comment]
hola!
Colgándome de la pregunta en subastas disponibles, primero deben aparecer TODAS las subastas disponibles y luego buscar alguna especifica, o primero se debe seleccionar el producto especifico para obtener las subastas disponibles con este producto, o queda a mi criterio??
Es una duda pequeña pero quiero resolverla.
Saludos.

**Comment by negebauer** [comment]
@dasotosilva19 El primer caso, deben aparecer todas y luego buscar alguna específica
