### ISSUE TITLE
Clases

### ISSUE THREAD

**Issue by Zepk** [IIC2233-2016-1/syllabus#113]
Acabo de leer en una isssue vieja, que ya esta cerrada, que exigen el uso de clases en la tarea.

La cosa es que yo ya tengo la tarea prácticamente lista, y aunque algún uso de clases tengo, no es demasiado ( solo tengo 2 clases), la mayor parte de los datos los trabajo directamente como listas y diccionarios porque era mucho mas cómodo y lógico, solo para las cosas que me parecieron mas fáciles de trabajar usando clases las usé.

Por otra parte en el enunciado no se especifica que todo tenga que ser modelado en base a clases, solo que se tienen que usar (cosa que hago).

Asi que escribo para preguntar que pasa si envio mi tarea tal y como está?

**Comment by andresfdezc** [comment]
Hola!

Uno de los objetivos explícitos de esta tarea es aplicar programación orientada a objetos (y lo es en todo el curso). Es importante que tu tarea esté bien modelada en ese sentido, porque es algo que se va a evaluar. Si consideras que no son necesarias nuevas clases, puedes arriesgarte a dejarlo así. Te recomiendo realizar el diagrama de clases que debes entregar y mirar si te hace sentido. Si tu diagrama no describe completamente lo que hace tu programa, entonces reconsidéralo.

**Comment by Zepk** [comment]
Ya, entonces si mi diagrama de clases describe a mi programa, está bien?

Porque mi programa tiene muchas funciones que no pertenecen a ninguna clase, en ese caso bastaría con que inventara cualquier clase, y metiera la función dentro, y ahora si podría hacer un diagrama de clases con sentido, pese a no tener por ejemplo ninguna clase para representar a los productos

**Comment by andresfdezc** [comment]
Si es que tienes demasiadas funciones sueltas, entonces es probable que te faltan clases. Probablemente esas funciones correspondan a métodos de alguna o varias entidades que no estás modelando. No trates de forzar el diagrama en función de tu código, debiese ser al revés.

EDIT: Si tu diagrama describe tu programa completamente, está bien, pero el diagrama debe tener sentido.

**Comment by Zepk** [comment]
Ya, pero si, mi código cumple con lo que piden (todas las funcionalidades), pero no tengo una clase "Producto" no hay ningún problema con eso?

Porque en mi codigo solo tengo una clase para los usuarios y otra para modelar el comportamiento de la fecha

Puedo explicar aca como funciona mi código? 
sin poner nada de codigo, claro
O eso es como hacer trampa?

**Comment by andresfdezc** [comment]
La modelación de tu tarea (y no solo que estén todas la funcionalidades) importa y eso se reflejará en la nota, pues es un objetivo explícito de la tarea. Te sugiero leer el enunciado de nuevo y contrastarlo con lo que hiciste, pues a mi parecer hay más que solo 2 clases que son evidentes a partir de la estructura de MercadoPreso.

NO expliques tu código acá.
