### ISSUE TITLE
Funciones 

### ISSUE THREAD

**Issue by IsaacConDosA** [IIC2233-2016-1/syllabus#114]
En un diagrama de clases, en donde van las funciones "sueltas"? salu3

**Comment by bamavrakis** [comment]
Hola!
Si modelaste correctamente el problema, no deberían haber funciones "sueltas".
Saludos!

**Comment by IsaacConDosA** [comment]
@bamavrakis Es que hice funciones que no son de ninguna clase, por ejemplo, para mostrar el menú, hice una función.

**Comment by FernandoPieressa** [comment]
Hasta donde tengo entendido en los diagramas de clases no se ponen funciones que no tienen que ver con las clases como el de mostrar menu

**Comment by negebauer** [comment]
@ifcarrera Para agregar funciones del menu en tu diagrama podrías hacer una clase Menu que las contenga y hacer algo como

```
menu = Menu()
menu.start()
```

Que se encargue de llamar a tus globales

**Comment by IsaacConDosA** [comment]
@negebauer Qué sentido tendría hacer esto? Me refiero a que hay un puro menú, no entiendo por qué hacer una clase Menú. Me pasa lo mismo con la lectura de archivos, tengo funciones que se encargan de eso, debería hacer una clase Leer archivos?

**Comment by negebauer** [comment]
@ifcarrera Podría ser una clase `ManagerArchivos` o algo por el estilo
En Ingeniería de Software te enseñaran por que si tiene sentido un objeto Menú, por ahora puedes conformarte con creerme.
Si quieres saber más puedes investigar lo que es un _singleton_

Algo común que se hace cuando se tienen funciones globales es agruparlas en una clase _Sistema_

**Comment by IsaacConDosA** [comment]
Gracias !!

**Comment by MortizDX** [comment]
Tengo una duda relacionada. Tengo un grupo de funciones que la uso en un par de módulos que tengo hasta el momento ¿es necesario que sean métodos de los objetos entonces? Que las uso en varios aspectos de la tarea para ahorrar líneas de código.

**Comment by negebauer** [comment]
@MortizDX Depende de que tan relacionadas están esas funciones. Intenta siempre agrupar las funciones dentro de una clase. Si son funciones generales que no tienen relación alguna con una instancia puedes agruparlas en un objeto con métodos estáticos, algo como `math.sqrt()`

**Comment by MortizDX** [comment]
Mm, entonces cada vez que quiera aplicar alguna de mis funciones generales ¿tendría que "objetizar" la variable a la que quiera aplicar esas funciones?

**Comment by negebauer** [comment]
@MortizDX Supongo que con "objetizar" te refieres a instanciar. Si los métodos son estáticos no tendrías que hacer eso.

**Comment by MortizDX** [comment]
Estuve viendo esto de nuevo (estaba revisando otras cosas del programa) y no entiendo bien como es que usar métodos estáticos permite utilizar las mismas funciones sin instanciarlas, ya que igual hay que ingresar el input que necesito para aplicar el método ¿no?

**Comment by negebauer** [comment]
@MortizDX Puedes reformular tu pregunta?

**Comment by MortizDX** [comment]
Tengo algunas funciones por si solas (no son métodos) que usan distintos modulos de mi tarea. Estas funciones reciben cierto input (distinto para cada vez que lo llaman) y devuelven un valor según lo que hagan.

Mi pregunta es, ya que nos piden que todo sea un objeto, ¿de qué forma puedo hacerlo lo mismo sin necesidad de tener que instanciar ese input cada vez que lo quiera utilizar, tal como mi función original?

**Comment by otro-felipe** [comment]
En Python es buena practica colocar todos estos métodos en un modulo llamado **utils**. La idea es que este módulo contenga todas las funciones "auxiliares" que no están directamente relacionadas con tus clases, sino que hacen mas de ayuda para otros métodos (por ejemplo, que dada dos listas calcule todas las combinaciones posibles). Los métodos que estén estrechamente ligados a una clase puedes declararlos como un método estático. Un método estático no necesita que exista una instancia de la clase para usarlo (de hecho, no recibe el típico `self` de los métodos de clase) sino que solo recibe los parámetros.

Para usar estos métodos se hace de la siguiente forma: `NombreClase.metodo_estatico()`.

Por ejemplo:

``` python
class Producto:
    # BLABLABLA
    @staticmethod
    def filtrar_productos(lista_productos, tipo):
        pass
```

Ahora para filtrar una lista de productos dado un cierto tipo puedes usar el método `Producto.filtrar_productos(logged_user.productos, selected_type)`. De esta manera todas las funciones que tienen que ver con los productos las tienes en la clase `Producto` y si en tu IDE escribes `Producto.` el autocompletador te deberia mostrar todos los métodos disponibles que tienes para trabajar con los productos (es uno de los beneficios de modelar los problemas de esta forma).

**Comment by MortizDX** [comment]
Muchísimas gracias, eso me aclaró un montón.

**Comment by negebauer** [comment]
El ejemplo de @MainScientist no puede estar mejor!
