### ISSUE TITLE
Apuesta máxima subastas actuales

### ISSUE THREAD

**Issue by IsaacConDosA** [IIC2233-2016-1/syllabus#115]
Hola! 
Esto es referido al archivo subastasact.txt
En el historial de las subastas aparece en el último lugar el ganador actual. El precio que tiene puesto es el actual de la subasta o el máximo?? De ser el máximo, como sabemos en que va la actual?
(Hablo de lo que está en subastasact.txt. Sí entiendo esa parte de precio actual y máximo)

**Comment by otro-felipe** [comment]
En el archivo las tuplas van como usuario, apuesta maxima. Es decir, el precio en el que esta el producto se encuentra en la llave `"precio"` y los montos maximos que apuesta cada usuario estan en la tupla.

**Comment by IsaacConDosA** [comment]
@MainScientist entonces la apuesta actual (apuesta anterior + 1) no van en el historial, se pone solo la maxima?? :open_mouth:

**Comment by otro-felipe** [comment]
asi es como viene en los archivos :) el precio actual es solo uno, de todas formas puedes calcular el precio en cualquier momento de la subasta sabiendo las apuestas maximas que vienen en el historial. Cabe destacar que **nunca** debes mostrar las apuestas maximas a los demas usuarios a la hora de mostrar una subasta (a excepcion de la parte del hackeo).
