### ISSUE TITLE
Diagrama de clases

### ISSUE THREAD

**Issue by FernandoPieressa** [IIC2233-2016-1/syllabus#116]
Algún formato especifico para el diagrama de clases? o tiene que ser a mano, o con algo en particular?

**Comment by otro-felipe** [comment]
No sé exactamente si puede ser entregado a mano, de todas formas te recomiendo mucho usar algun programa externo (asi es mucho más fácil editarlo en caso de que hagas algun cambio). Yo el semestre pasado usé [NClass](http://nclass.sourceforge.net).

**Comment by FernandoPieressa** [comment]
Lo hago con Nclass, pero despues no necesitare pasarlo a algun formato? porque si el ayudante corrector no tiene Nclass no va a poder abrir mi archivo

**Comment by fgvenegas** [comment]
Podrias sacarle un pantallazo y mandar la foto ( ͡° ͜ʖ ͡°)

**Comment by agmardones** [comment]
NClass tiene la opción de exportar en pdf o JPEG
