### ISSUE TITLE
Duda sobre baneos

### ISSUE THREAD

**Issue by bmarinb** [IIC2233-2016-1/syllabus#117]
Al banear un usuario mi código lo elimina de la lista de usuarios. Por lo tanto desaparecerá también del txt en las siguientes ejecuciones. ¿Hay algún problema con esto?

Esto ya que como no se debe impedir que se reutilice el nombre de usuario, si no lo borro de la lista de usuarios entonces no podré crear un usuario con ese nombre.
La otra opción es simplemente impedir la reutilización de los nombres de usuario de usuarios baneados

**Comment by otro-felipe** [comment]
Está bien eliminarlos de la lista de usuarios. Ten siempre en consideracion que un usuario baneado no puede volver a registrarse otro usuario con el mismo **correo electronico** de la cuenta que fue baneada.

**Comment by bmarinb** [comment]
Un detalle no menor me surgió con respecto a eliminar a los usuarios de la lista de usuarios.

La primera vez que se ejecuta el código hay varios usuarios baneados según el txt, por lo tanto debo eliminarlos de la lista de usuarios.

SI se guardan estas eliminaciones de usuarios en usuarios.txt entonces en las siguientes ejecuciones del programa no se va  a requerir eliminar a los usuarios baneados de la lista de usuarios 
(al menos los baneados de la vez anterior, pues pueden haber nuevos baneados por haber ingresado una nueva fecha, pero estos no están en el txt)

Por lo tanto el código que elimina a los usuarios baneados de la lista de usuarios tendrá sentido solo en la primera ejecución del programa. Esto me lleva a la conclusión de que el archivo banea2.txt es innecesario pues sería exactamente igual a eliminar inicialmente a los usuarios baneados en banea2.txt del usuarios.txt y luego no tiene ningún efecto

**Comment by negebauer** [comment]
@bmarinb El archivo banea2.txt si es necesario ya que debes **impedir** que se registre un nuevo usuario con un **correo electrónico** baneado.

**Comment by bmarinb** [comment]
Comprendo.
