### ISSUE TITLE
Usuarios inexistentes

### ISSUE THREAD

**Issue by spiza** [IIC2233-2016-1/syllabus#119]
Hola!

Tengo una duda que me está haciendo pasarlo muy mal..

Lo que pasa es que al ingresar la fecha de prueba ( 2016-03-22 22:22:22), y comprobar las subastas que se deberían cerrar, me encuentro con que en las subastas que deberían cerrarse por fecha, ninguno de los usuarios que aparecen como subastadores existen en la base de datos de personas.txt...

Por ejemplo la subasta "id": 58422870297; el comprador es idiaz11, usuario que si se busca en personas.txt con ese username, no existe! tampoco existen ninguno de los usuarios que apostaron en esa subasta.. 

Hay algo que no estoy viendo bien??? Algo se me está pasando??? Porfavor help :'(

**Comment by aaossa** [comment]
Hola, me parece que no estás usando los archivos mas recientes (tuvimos una issue sobre esto abierta unos días). En el nuevo archivo `usuarios.txt` si aparece el usuario `idiaz11`:

```
{
    "nombre": "Ian Diaz",
    "clave": "In3FWe",
    "dinero": 281063,
    "correo electronico": "lockmanhorace@gleason.com",
    "usuario": "idiaz11",
    "productos": [
      28594940112
    ]
  }
```

**EDIT:** Encontré la issue, es #31

**Comment by spiza** [comment]
😭😭😭😭😭😭😭😭

Me iba a dar en los c*****s con una piedra

Gracias!

Enviado desde mi iPhone
