### ISSUE TITLE
¿Se considera como hackeo?

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#121]
Una duda con la parte del hackeo ¿en que modo se considera hackeo algo? ¿Si modifico los datos en los .txt para mi conveniencia con un programa, se considera eso como hackeo? ¿o debo actuar DENTRO del mismo sistema MercadoPreso (es decir, actuar sobre nuestro programa que corre todos los procesos? No me queda bien claro eso.

**Comment by negebauer** [comment]
@MortizDX El hackeo es a parte de MercadoPreso. Aquí hay algo más de info #39.
Lo segundo que dices, hacer un programa que te modifique otro programa, está por lejos fuera del scope de esta tarea

**Comment by MortizDX** [comment]
Entonces, ¿lo puedo ver como una versión 2.0 del sistema MercadoPreso? (solo con las funciones que necesito, claro)

**Comment by negebauer** [comment]
@MortizDX Si

**Comment by MortizDX** [comment]
Ok, muchas gracias!
