### ISSUE TITLE
¿Para que el hakeo tiene que ver otras subastas?

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#122]
Solo para saber. ¿Por qué el hackeo tiene que ver otras subastas para calcular el precio que debería entregar?

**Comment by Geeermy** [comment]
Hola!
Veámoslo de esta forma: Estoy participando en una subasta, pero a la vez, estoy vendiendo algo a través de una subasta, y ese producto se va a vender **antes** que termine la subasta en la que participo. Entonces, en el fondo, voy a tener más dinero para invertir que el que sale actualmente en mi cuenta. Ese es un motivo **importante** por el que no solo me debo quedar con lo que tiene cada usuario en su cuenta al momento de estudiar mis posibilidades para apostar.
Saludos!
