### ISSUE TITLE
Porque un objeto esta siendo subastado en 2 subastas

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#124]
Se que alguien ya pregunto esto, pero sylabus no me deja encontrarlo.
Hay 2 subastas que estan ofreciendo el mismo producto. ¿Que hago cuando ambas terminan? ¿A quien le entrego el producto?

**Comment by gbordoni** [comment]
Me sumo a la pregunta...me parece ilogico que un mismo objeto este subastandose en dos subastas distintas...por ejemplo:

```
{
    "fecha_termino": "2016-05-27 02:56:35",
    "id": 75666817851,
    "fecha_inicio": "2016-01-19 17:54:40",
    "precio": 191461,
    "vendedor": "jdavidparra",
    "productos": [
      74841735893
    ]
```

```
{
    "fecha_termino": "2016-07-06 00:31:59",
    "id": 20435849131,
    "fecha_inicio": "2016-02-05 04:10:42",
    "precio": 162261,
    "vendedor": "jdavidparra",
    "productos": [
      74841735893
    ]
```

Se que la respuesta mas logica es "se le entrega al producto al comprador cuya subasta termine primero", pero esto de verdad me esta trayendo problemas al momento de cerrar las subastas. Como cierro la otra subasta si ya no hay producto que subastar? El codigo que escribi no esta preparado para eso -.-

**Comment by otro-felipe** [comment]
Es ilogico, pero es porque el sistema permite que un usuario pueda subastar sus productos mas de una vez (desde este punto de vista es un descuido del usuario) lamentablemente su codigo debe estar preparado para manejar este tipo de situaciones, la forma en que lo hagas queda a tu eleccion, puedes hacerlo de la forma en que mas te acomode, lo importante es que tu programa no se caiga.

**Comment by ehdonoso** [comment]
si dos de esas subastas vencieron puedo sacar una de ellas "random" y tomarla y la otra anularla?

**Comment by negebauer** [comment]
@ehdonoso Toma en cuenta la que tiene fecha de vencimiento más pronta
