### ISSUE TITLE
Historial que aparece en subastasact.txt/subastasfin.txt

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#125]
Estoy confundido con respecto al historial que aparece allí ¿aparecen solos los "ganadores" en un instante, no todas las apuestas ingresadas? Lo pregunto al estar todos los valores ordenados, por lo que no me calza que en algún momento un usuario haya realizado una apuesta menor a la apuesta "real" de un usuario anterior.

> Así, si un usuario apuesta una cantidad menor a la máxima ingresada por el ganador vigente,
> el precio actual del producto sería un MercadiPeso mayor a la cantidad ingresada por el segundo postor, salvo que el ganador actual seguiría siendo el primero

**Comment by Geeermy** [comment]
Hola!
Aparece solo el ganador en ese momento junto al precio con el que gana. Recuerda que el precio que adquiere la subasta no es el máximo propuesto por un apostador, sino que el precio con el que ninguno de los otros subastadores lo supera. Veamos esta situación:

Subastador 1: Apuesta máximo 1000
Subastador 2: Apuesta máximo 2000
Subastador 3: Apuesta máximo 1500
Precio final subasta: 1501 -> Ganador, Subastador 2

Ahora, metamos a un cuarto subastador:
Subastador 4: Apuesta máximo 1800
Precio final subasta: 1801 -> Ganador, Subastador 2

Ese es el ejemplo al que hace referencia la cita que pones. Puedo apostar más que el precio actual, pero si hay un subastador que pone como máximo un valor mayor al que yo ponga, de todas formas me ganará (salvo que lo haré pagar más).
Espero que te haya quedado más claro ahora :)
Saludos!

PD: Recuerda que uno **no puede saber** el máximo propuesto por cada subastador, solo conoce el precio actual de la subasta.
