### ISSUE TITLE
Inconsistencia archivos

### ISSUE THREAD

**Issue by isarovic** [IIC2233-2016-1/syllabus#126]
Revisando la parte de trayectoria de los productos en mi programa me percaté que por ejemplo en el archivo subastasfin.txt el vendedor no tiene los productos que vendió en el archivo usuarios.txt, (como si efectivamente los hubiera vendido), pero el usuario comprador no tiene esos los productos en el archivo usuarios.txt, ¿Cómo puede ser que ninguno los tenga?, de hecho hay casos que el archivo los tiene otro usuario:

Ej: subastasfin.txt:
      id subasta: 26985381887
      comprador: naraya
      vendedor: bnavarrete11
      productos: 31134115378

Luego en usuarios.txt:
      naraya: no tiene el producto
      bnavarrete11: no tiene el producto

```
  acortes11: TIENE el producto
```

Ademas el producto no esta en ninguna otra subasta activa o finalizada, ¿Cómo llegó ahí?

No tengo claro si será un error, pero me parece más lógico que eso debiera estar actualizado en usuarios.txt, osea que naraya tuviera el producto, por lo menos yo estaba haciendo el archivo subastasfin.txt con esa información actualizada.
¿Cómo debo entenderlo entonces?

**Comment by cggutierrez** [comment]
creo que ya explicaron eso, no hay que complicarse y solamente imaginarse que quien lo compro "se lo regalo" a quien lo tiene  (da igual para efectos de programar según lo que entendí, solamente consideralo como error de los archivos)

**Comment by isarovic** [comment]
Oka gracias =)
