### ISSUE TITLE
Duda formato archivo

### ISSUE THREAD

**Issue by Cnmoya** [IIC2233-2016-1/syllabus#127]
Buenas, revise el foro pero no logre encontrar algo que respondiera una duda que tengo.

Es posible que el archivo este escrito en una unica linea?
ej:
`{"nombre":"SophieWilliams","clave":"LIp903","dinero":451504,....}

sin que haya 
`"\n"`
en el archivo.

Muchas Gracias.

**Comment by otro-felipe** [comment]
Si
