### ISSUE TITLE
Multas

### ISSUE THREAD

**Issue by IsaacConDosA** [IIC2233-2016-1/syllabus#128]
Si un usuario tiene más de una multa, en el archivo multa, habrían dos multas por separado con el mismo usuario o aparece una sola vez con la suma de las multas?

**Comment by Geeermy** [comment]
Hola! 
Esto no se explicita en el enunciado, pero deberías dejarlo como **multas separadas**, ya que los plazos de vencimiento podrían diferir (y muy probablemente lo harán). Si las mezclas, tendrías que necesariamente eliminar la segunda fecha de vencimiento (dejar la que vence más temprano) y obligarías al usuario a pagar todo de inmediato, en vez de pagarlas una por una. Espero que se entienda por qué es mejor dejarlas separadas :)
Saludos!

**Comment by jicortes2** [comment]
Cuando el usuario va a pagar una multa, puedo obligarlo a pagar la que esta más próxima a vencer?
