### ISSUE TITLE
Trayectoria de los productos

### ISSUE THREAD

**Issue by IsaacConDosA** [IIC2233-2016-1/syllabus#129]
Hay que considerar la trayectoria desde dónde estaban cuando ustedes nos entregaron los archivos .txt verdad?? O considerar la trayectoria mientras el usuario está loggeado??

**Comment by Geeermy** [comment]
Hola! 
Lo primero... puedes considerar que el tiempo "no transcurre" mientras el usuario está conectado, así que no te estreses con eso :) (ahora, recuerda que dependiendo de la fecha que ingreses al conectarte, algunas cosas podrían cambiar).
Saludos!
