### ISSUE TITLE
Ponderación entre MidTerm y FinalTest

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#13]
Hola, una consulta bastante sencilla pero que no queda bien claro del programa del curso. Uno de los requisitos de aprobación es que entre el midterm y el exámen debe haber un promedio ponderado igual o mayor a 3.5 ¿pero cuál ponderación tiene cada nota? ¿40-60 aprox. acaso?

**Comment by jecastro1** [comment]
Hola

El ponderador de cada evaluación es el mismo que para el cálculo de la nota
final. Así el ponderador del midterm es 0.15 y el del examen es 0.20

Para calcular un promedio ponderado se multiplica cada cosa por su
ponderador, y eso se divide por la suma de todos los ponderadores.

Saludos!

**Comment by MortizDX** [comment]
Aah, dale, era más o menos lo que creía entonces ¡muchas gracias por la aclaración!
