### ISSUE TITLE
Ranking

### ISSUE THREAD

**Issue by spiza** [IIC2233-2016-1/syllabus#130]
"Ranking de vendedores: Se debera mostrar una lista con los 10 usuarios que más dinero han
obtenido debido a ventas en subastas."

No me queda claro este punto.. Se supone que tengo que recalcular cuánto han ganado todos los usuarios? O simplemente es un ranking de los 10 usuarios con más plata (la plata en este programa no crece de los árboles, sino que se obtiene a través de subastas o ventas en la tienda del pueblo)

Gracias :D!

**Comment by Geeermy** [comment]
Hola! Como dice el enunciado "(...) **debido a** ventas en subastas"
Es decir, a través de las subastas **finalizadas**, debes obtener los 10 usuarios que más han obtenido dinero por ellas. Lo que tengan actualmente no nos interesa.
Saludos!
