### ISSUE TITLE
Tarea 01 Deudas

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233-2016-1/syllabus#132]
En el programa de hackeo, si durante mi análisis me doy cuenta que antes de que acabe la subasta que se desea ganar a toda costa, un usuario ya presenta una deuda, ¿a ese usuario lo descarto como un potencial competidor de la subasta aunque tenga dinero? o analizo sus objetos y ganancias que tiene y tendría antes que caduque la deuda para ver  si es capaz de pagar la deuda a tiempo y aun asi tener suficiente dinero para participar en esa subasta

por ejemplo (para dejar clara mi duda)
La subasta esta a 5000 y solo hay un usuario, llamado "Juancho " (no se porque el nobmre)
Juancho tiene 30.000 hasta ahora
Juancho debe 100.000
Juancho posee en objetos como 70.000
Juancho ganara 15.000 antes que caduque la deuda (por otra subasta que termina despues de la subasta de 5000)

por lo tanto, proyectando esa información, él seria capaz de apostar hasta 15000 mas en la subasta y finalmente quedaría sin deuda. Por lo tanto mi programa deberia decirle que apueste mas de 20.000 para que asi nadie le gana

Considero ese pensamiento en el hackeo, o simplemente si tiene deuda, lo descarto y analizo el "potencial peligro" de los otros usuarios para ver cuanto hay que apostar y por lo tanto mi programa deberia decirle que apueste mas de 5000 nomas??

Espero que se lograra entender mi duda

**Comment by Geeermy** [comment]
Hola! Se entiende perfectamente :)
En esta parte igual vamos a ser más flexibles con la corrección, ya que no especificamos exactamente **cómo** debes hacerlo, lo importante es que encuentres una buena solución para el problema que te planteamos. Respondiendo a tu duda, lo que se pide exactamente es un monto para el que **ningún otro competidor pueda ganar**, entonces, incluir el estudio de las deudas y su posible pago es bastante válido (recordando considerar el vencimiento de las multas). Recuerda especificar este tipo de decisiones en el READ ME para facilitar la corrección de tu solución.
Espero que haya quedado claro. Saludos!

**Comment by Hernan4444** [comment]
Quedo perfectamente claro, otra pregunta,
sobre ningún otro competidor pueda ganar, se refiere a los competidores que están hasta ahora en la subasta o de **todos** los usuarios disponibles

**Comment by Geeermy** [comment]
**Solo** los que participan en la subasta. Por eso, citando la tarea: _Recuerda que los resultados pueden ir cambiando a medida que se añaden competidores a la subasta_
:)

**Comment by otro-felipe** [comment]
PD: Juancho se llamaba el gato del Edgar (Jaidefinichon)
