### ISSUE TITLE
Formato de reescritura - vars

### ISSUE THREAD

**Issue by bmarinb** [IIC2233-2016-1/syllabus#133]
Si mi parser puede leer el código independientemente de las líneas en las que esté escrito:
¿Puedo reescribir los archivos sin mantener de forma estricta el formato en el que los entregaron?
Ejemplo
Pasar de esto     

```
    "dimensiones": [                         
      1,
      2,
      1
    ],
```

 a esto

```
 "dimensiones":  [1, 2, 1]
```

y

¿Se puede usar vars?

**Comment by aaossa** [comment]
Como dice en #99 tu parser debe ser capaz de leer los archivos independiente de los espacios que estos tengan. Y, como dice en #48, debes guardarlos de tal manera que los puedas leer después.

Por lo tanto puedes escribir los archivos como quieras, siempre y cuando puedas volver a leerlos con el parser.

Sobre `vars`, te responderán los @IIC2233-2016-1/tareos en #65.
