### ISSUE TITLE
[T01] Lista Productos

### ISSUE THREAD

**Issue by sitoro** [IIC2233-2016-1/syllabus#134]
El enunciado dice que el programa debe tener la siguiente funcionalidad:

> Lista de productos: Se muestran todos los productos en el sistema que están en una subasta o en
> la tienda de productos de MercadoPreso. Por cada producto se debe imprimir su nombre, rating
> y todos los atributos pertenecientes únicamente al tipo de producto.

El problema es que entre subastas y la tienda existen demasiados productos como para mostrarlos en consola sin saturarla (solo en la tienda hay 500 productos). Entonces:
¿Aún así deben imprimirse en consola todos los productos juntos (con la información de cada uno) tal como lo indica el enunciado?

Edit: Lo mismo sucede con "Lista de subastas finalizadas" las que con facilidad llegan a ser más de 1000

**Comment by bamavrakis** [comment]
Hola!
Como lo hagas queda a tu criterio, pero la funcionalidad debe permitir mostrar todos los productos (tal vez no "de una"). Recuerda escribir en el README lo que decidiste para este asunto.
Saludos!
