### ISSUE TITLE
[T01] Dinero ganado

### ISSUE THREAD

**Issue by agmardones** [IIC2233-2016-1/syllabus#135]
Hola! Incluyendo el dinero ganado para hacer el ranking me entró una duda: Debería incluir el dinero que gana una persona que ganó una subasta por un precio menor al valor real del producto? En ese caso, la persona ganaría dinero ( precioproducto - preciosubasta), al igual que el caso de un vendedor  que termina subastando un producto por una cantidad menor al precio real del producto, en ese caso perdería plata.
En general, las apuestas y precios de subastas finalizadas hacen quedar con dinero negativo a todos los usuarios con esta lógica :c

**Comment by Geeermy** [comment]
Hola! Citando la tarea: _Ranking de vendedores: Se deberá mostrar una lista con los 10 usuarios que más dinero han obtenido debido a ventas en subastas._
Dicho esto, sin importar cuánto haya costado el producto antes, lo que a ti te interesa es lo que ganan con la subasta (en todas las que hayan hecho). Da lo mismo si los usuarios pierden dinero con respecto al costo del producto... muchas veces lo hacen en la vida real :c (y está bien, si en el fondo son productos usados).
Espero haber respondido. Saludos! :)

**Comment by agmardones** [comment]
Gracias!
