### ISSUE TITLE
Hackeo

### ISSUE THREAD

**Issue by IsaacConDosA** [IIC2233-2016-1/syllabus#136]
Holaa, tengo dudas respecto al hackeo. Ya leí las anteriores issues pero no me quedó del todo claro. 
A qué se refieren a que debe ser un programa aparte?
No puedo siemplemente importar los otros modulos, pero obviamente el modulo "hackeo" no se lo voy a entregar al dueño de la empresa, me lo dejo para mi, pero ocupando los modulos que ya escribí.?
No sé si me expliqué bien. 
gracias !

**Comment by Geeermy** [comment]
Hola!
En muy resumidas cuentas, lo que queremos es que entregues:
Tarea1.py
Hackeo.py
A eso nos referimos con programas separados. Si quieres importar funcionalidades de Tarea1.py en Hackeo.py, se puede (no te vamos a pedir que escribas un parser dos veces, tranquilo jaja).
Saludos! :)

**Comment by IsaacConDosA** [comment]
@Geeermy O sea en el fondo, subo todos los archivos, incluyendo el de hackeo a la misma carpeta T01?
Gracias por tu respuesta

**Comment by Geeermy** [comment]
Exacto :) De nada!

**Comment by IsaacConDosA** [comment]
@Geeermy La idea del hackeo es apostar 1 sola vez para asegurarnos de ganar la subasta?
O apostar la menor cantidad de dinero posible?

**Comment by Geeermy** [comment]
La idea es obtener la menor cantidad de dinero posible para **ganar definitivamente, apostando una sola vez**, como para hacerlo y despreocuparte de la subasta jaja. Podrías tirar un valor infinitamente grande y ganar siempre, pero esa no es la idea, por eso les pedimos el estudio a los competidores.
Saludos!
