### ISSUE TITLE
[T01] Producto no encontrado

### ISSUE THREAD

**Issue by agmardones** [IIC2233-2016-1/syllabus#137]
Busqué si es que y lo habían preguntado, pero no encontré. El usuario "afigueroa" tiene el producto con id 19535292404, el cual no está en productos.txt, quería agregar las trayectorias de los productos desde los archivos originales, ignoro esto?

**Comment by Geeermy** [comment]
Ups, no sé qué pasó ahí. Ignóralo no más, eso ya es error de los archivos en concreto. En la corrección vamos a vigilar todo ese tipo de cosas, así que no te preocupes :)
Saludos!

**Comment by agmardones** [comment]
Gracias de nuevo! jajaja

**Comment by Geeermy** [comment]
De nada! Lo voy a dejar abierto más tiempo por si algún otro compañero tuyo tiene el mismo problema :) (todos deberían jaja)
