### ISSUE TITLE
Guardar archivos

### ISSUE THREAD

**Issue by IsaacConDosA** [IIC2233-2016-1/syllabus#138]
Hola, cuando revisen la tarea con archivos diferentes a los que nos entregaron, estos mantendrán el orden en que aparece la información?
Por ejemplo: 

>  "nombre": "Deckard & Quinn Co. -- Chemical Rocket Pack (Tail Friendly)",
>     "precio de hipoteca": 18592,
>     "nuevo": "Nuevo",
>     "altura": 63,
>     "rating": "4",
>     "tipo": "Plantas de Jardin",
>     "id": 72545037865,
>     "color": "rojo" <

Cuando actualizo los archivos, los guardo en el mismo orden, entonces si cambian el orden, mi programa probablemente muera (porque las actualizaciones las guardaré en otro orden)
salu3

**Comment by IsaacConDosA** [comment]
Dije muchas veces orden u.u

**Comment by otro-felipe** [comment]
El orden de las variables puede ser completamente aleatorio. No es necesario que el orden en que guardes tus archivos sea igual a los archivos de entrada siempre y cuando conserves el formato json :)
