### ISSUE TITLE
Problema con ciclo for

### ISSUE THREAD

**Issue by cggutierrez** [IIC2233-2016-1/syllabus#139]
la verdad ni se como explicar el error que me da, ya que al hacer 2 for, donde uno solo imprime y el otro parte exactamente igual imprimiendo pero sirve para otra cosa (lo de imprimir lo hice para probar) el primero funciona sin errores mientras que el segundo me tira error

adjunto el codigo (ya que no revela nada importante de la tarea)

```
    for i in range(0,len(subastasact)):    
        print(subastasact[i].fecha_termino)

```

```
for i in range(0,len(subastasact)):     #actualiza subastas actuales y finalizadas
    print(subastasact[i].fecha_termino)
    fechadesubasta=str(...
```

.
.
.
2016-08-29 03:21:20
2016-09-19 03:28:29
2016-03-21 06:54:40
Traceback (most recent call last):
  File ".../Desktop/tarea/tarea 1.py", line 152, in <module>
    print(subastasact[i].fecha_termino)
TypeError: 'NoneType' object is not subscriptable

alguna idea de que pasa o como se puede solucionar? ya que solo el primer print funciona mientras que el segundo lo hice para comparar posibles errores, pero es lo mismo y tira error

**Comment by aaossa** [comment]
Bueno, no se ve muy bien el código que pusiste, pero lo que te dice el error es que estas tratando de tomar el índice (`[i]`) de algo que es del tipo `None`.

Posible razón: En algun momento del loop estas cambiando `subastasact` por `None`.

**PS:** Para colocar código correctamente usa [estos ejemplos](https://guides.github.com/features/mastering-markdown/) y recuerda usar 4 espacios (` `) dentro del`for`

**Comment by cggutierrez** [comment]
ahí arregle el código como pude, por lo demas me parece raro que tome un `None`, ya que estoy casi seguro que almenos no intencionalmente no puse ningun 'None' en el for,  ademas, deberia imprimir algunas lineas de subasta.fecha_termino pero no tira ninguna (las que puse son del primer for)

**Comment by cggutierrez** [comment]
solucionado, gracias!
(tenia errores acortando la lista subastasact dentro del ciclo)
