### ISSUE TITLE
Problema intentando hacer la barra vertical

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2233-2016-1/syllabus#14]
Hola! Estaba intentando hacer la barra vertical (en codecademy), pero no sè como escribirla. No la puedo copiar. Vi tambièn las formas que se sugieren en la página, pero de las que he intentado no me ha servido ninguna.
¿Còmo se hace para esctibir Alt + 124? ¿Funciona? ¿Hay que presionar Alt y al mismo tiempo 124 o es de otra forma?
Gracias

**Comment by aaossa** [comment]
¿Hablas de `|` (_vertical bar_)? Depende de la configuración de tu teclado. Al menos en el mío es presionando la tecla a la izquierda del 1 (donde está `°`). 

Sobre la combinación de teclas, al menos hasta donde recuerdo es escribir 124 (`1`, `2`, `4`) mientras tienes `Alt` presionado.

Lo que podrías hacer sería abrir algun editor de texto simple (tipo block de notas) y probar las combinaciones de teclas y las teclas que menos usas para "encontrar" la _vertical bar_.

**Comment by negebauer** [comment]
Otra cosa que podrías probar es abrir un teclado virtual (como se hace esto depende de que sistema tienes, en Windows me parece mucho que esta en accesibilidad, en mac directo desde la barra superior si tienes configurado que se muestren opciones de teclado ahí)
Luego es jugar con las teclas hasta que veas aparecer la _vertical bar_

**Comment by AlfonsoIgnacioV** [comment]
Lo intenté también, pero incluso con el teclado, los caracteres que se escriben usando Ctrl + Alt por alguna razón no se escriben en consola.

**Comment by negebauer** [comment]
Que sistema operativo tienes? Que teclado (físico) tienes? Que fuente de entrada tienes definida?

**Comment by AlfonsoIgnacioV** [comment]
Estoy usando un teclado QWERTY desde Windows 10. ¿A qué te refieres con la entrada (fuente)? ¿Tipo de letra? Según yo es estándar. Gracias

**Comment by AlfonsoIgnacioV** [comment]
Comento también que la interfaz no tiene una opción para hacer paste sobre ella, es decir es imposible copiar la barra y pegarla en ella. Usar Alt + 124 tampoco me dio resultados.

**Comment by jecastro1** [comment]
Hola

Tu problema es sumamente extraño :cry: . Yo hice el tutorial completo y pude pegar un texto arbitrario en la "consola online". 

Trata de pedir ayuda presencialmente, idealmente mañana después de la ayudantía.

Por último adjunto [este link](https://discuss.codecademy.com/t/my-keyboard-does-not-allow-me-to-type-a-character-used-in-a-codecademy-lesson-what-should-i-do/29228) del soporte de Codecademy, sólo para tener todos los antecedentes en un mismo lugar.

Saludos, ojalá se te solucione.

**Comment by mjjunemann** [comment]
Cuando se hacen teclas de forma alt + número es necesario tener un numberpad no funcionan en caso contrario, en que tienes tu teclado ? Qwerty español latino americano , americano (us) , España ?

**Comment by mjjunemann** [comment]
Además en windows 10 en la cmd /powershell para activar copy/paste debes entrar a las properties y marcas que está activado 

Saludos

**Comment by AlfonsoIgnacioV** [comment]
Hola de nuevo :)
En realidad no estoy seguro que clase de teclado es. Es en español si (tiene la eñe).
¿Còmo es lo de las properties? Igual querría ver eso mañana, pero yo creo que en ayudantía. 
De todas maneras muchísimas gracias
Saludos :)

**Comment by aaossa** [comment]
Solucionado hoy en la ayudantía al cambiar la configuración de idioma a `ES - Español (Chile)`, por lo que para hacer el caracter `|` basta con presionar la tecla a la izquierda del `1` (la que tiene `°`) :grin:
