### ISSUE TITLE
Manual del usuario: ¿explicar funcionamiento del programa o indicar como usarlo?

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#141]
Mi duda es tal como indica el título ¿el archivo README.md debe explicar como funcionar el programa o debe indicar los pasos que debe seguir el usuario a la hora de interactuar con él? ¿hasta que nivel de detalle se debe adentrar en cualquier caso? ¿Hay algún ejemplo al respecto que pueda tomar como base a seguir? Lo pregunto porque me confunde un poco que el pdf diga que "comente sus alcances y el funcionamiento de su sistema" (que me da a entender que es explicar los procesos de por medio) pero que lo mencione como un "manual del usuario" (de que se debe preocupar el usuario solamente de hacer)

**Comment by Geeermy** [comment]
Hola! No hay una estructura predeterminada a seguir para el README.md, así que el nivel de detalle será el que tú quieras darle. La gracia del READ ME es que nos permite a los ayudantes corregirles la tarea de forma más rápida y eficiente, ya que nos pueden indicar las cosas que **implementan y que no**, por lo que no perdemos tanto tiempo viendo el código. Así que, respondiendo tu pregunta, te recomendaría más profundizar en su uso, ya que el funcionamiento debiese ser como dice el enunciado (salvo las cosas que hayan sido bajo tu criterio, esas sería bueno que las indicaras). Espero haber despejado tus dudas :)
Saludos! (y trata de dormir jaja)

**Comment by tamycova** [comment]
@MortizDX revisa #143
