### ISSUE TITLE
"Copiar" instancias

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#142]
Una consulta que debí haber hecho hace tiempo, pero que recién ahora probando cosas me he puesto a cuestionar. Cuando instancio una clase en una variable temporal (en un `for` por ejemplo) y luego esa variable temporal la meto como variable en una función que quiera modificar esa variable ¿la función solo modifica la "copia" o está modificando al objeto original?

Mi pregunta, en términos más simples y directos, al instanciar algo que ya estaba definido en otra parte ¿python realiza una "copia" aparte de ella o ambos se tratan del mismo? Estuve leyendo un poco al respecto, pero no estoy 100% si es así.

**Comment by tamycova** [comment]
Hola, no sé si entendí tu pregunta muy bien, pero te dejo este ejemplo. Si te fijas con la `id()` (que te entrega un int único para el objeto, [revisa la documentación de python para saber más](https://docs.python.org/2/library/functions.html#id)) es claro que siempre se esta trabajando sobre el mismo objeto. 

![ejemplo](https://cloud.githubusercontent.com/assets/11545206/14066251/fb5e9178-f41a-11e5-8243-8a8a9a01ed43.png)

**Comment by MortizDX** [comment]
Por ahí iba mi pregunta. Muchas gracias!
