### ISSUE TITLE
PROTIPS README 

### ISSUE THREAD

**Issue by tamycova** [IIC2233-2016-1/syllabus#143]
Hola! Muchos han preguntado acerca de qué deben poner en el **README**. Este se pide para darles una oportunidad de clarificar sus decisiones de modelación y especificar cosas que no estaban en el enunciado, de esta forma facilita la corrección por parte de los ayudantes (generalmente, a mejor calidad de README, menor probabilidad de entrar a luchar en recorrecciones) aquí van algunas recomendaciones:
### Dejar claro lo que **NO** pudieron implementar y lo que no funciona a la perfección, esto puede sonar innecesario pero permite que el ayudante se enfoque en lo que sí podría subir su puntaje.
- No explicar cómo se les ocurrió hacer lo que sí funciona, a menos que hayan asumido cosas que no estaban en el enunciado y deban especificarlas. 
-  Si hay algún pedazo de código relevante, como el algoritmo de hackeo en este caso, y que creen que podría ser necesario una explicación de su lógica, darla. 
-  Si su repo esta desordenado o la modularización no es clara pueden poner una **descripción muy breve** de lo que contiene cada módulo. 
- **Sean concisos, pero que no falte nada**
-  **_Sean concisos, pero que no falte nada._**
-  Siempre se agradece el uso del humor. 

Por último, recordar que el README no es un archivo .txt, es .md lo que significa que pueden agregarle distintos estilos (colores, destacados, tablas, código), [les recomiendo este editor](http://dillinger.io/). 

**EXTRA**: si van a explicar que hace especificamente un metodo no lo coloquen en el README mismo, pueden hacerlo directamente comentando el metodo en su archivo por ejemplo:

``` python
class Corrector:

    def __init__(self):
          pass

    # Este metodo coloca un 1 en las tareas que recibe
    def corregir(self, tarea):
        self.tarea.nota  = 1 
               return tarea

```
# PD: SEAN CONCISOS PERO QUE NO FALTE NADA

**Comment by fgvenegas** [comment]
Extra: si van a explicar que hace especificamente un metodo no lo coloquen en el README mismo, pueden hacerlo directamente comentando el metodo en su archivo por ejemplo:

``` python
class Corrector:

    def __init__(self):
          pass

    # Este metodo coloca un 1 en las tareas que recibe
    def corregir(self, tarea):
        self.tarea.nota  = 1 
               return tarea

```

**EDIT de @aaossa:**

Si quieren ser mas formales pueden usar alguna convención de documentación. Google tiene la suya, Python tiene otra y hay muchas mas. La de Python es [la **PEP287** conocida como **reST**](https://www.python.org/dev/peps/pep-0287/). Lo más básico es documentar así:

``` python
def funcion(argumento):
    """
    Mi funcion hace X con el argumento
    """
    return argumento_modificado
```

Lo importante es que expliquen qué hace la función y que si saben que alguna parte puede quedar complicada de entender o tienen alguna función mágica **usen los comentarios/documentación para que el ayudante entienda sus intenciones** #eso

:grin:
