### ISSUE TITLE
Donde se envia el diagrama de clases?

### ISSUE THREAD

**Issue by FernandoPieressa** [IIC2233-2016-1/syllabus#144]
En el enunciado sale via siding pero no veo ningun cuestionario o algo donde lo pueda enviar

**Comment by jecastro1** [comment]
Hola Fernando,

Colocaré el cuestionario hoy en la tarde.

Saludos

**Comment by cggutierrez** [comment]
aprovechando el issue, como debe ser el formato el diagrama? totalmente en word, imagenes de paint en word, fotos del cuaderno en word?

**Comment by FernandoPieressa** [comment]
Gracias!

@cggutierrez lee la issue #116
