### ISSUE TITLE
Profundidad del hackeo

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#145]
Al explorar las posibilidades de los "rivales" en la subasta que queremos nosotros ganar ¿consideramos que las apuestas en otras subastas están "fijas" o que pueden variar? Por ejemplo, que el rival vaya perdiendo una subasta x (que termina antes de la que nosotros buscamos) y que tenga posibilidades de ganar en esa apostando todo su dinero allí, pero al hacer eso pierde sus posibilidades de ganar en la subasta que nosotros estamos buscando (por lo que las apuestas "varian" en ese caso) ¿es muy rebuscado llegar hasta ese punto de análisis o lo debe abarcar el hackeo?

**Comment by Geeermy** [comment]
Hola! Esto igual es importante, así que voy a dejar esto abierto hasta la entrega.
En esta parte seremos más flexibles, así que si quieres añadir eso al análisis (o cualquier otra cosa), especifícalo en el READ ME y evaluaremos considerando eso :). Pero de todas formas, para responder un poco tu inquietud, te voy a decir lo siguiente:
Lo importante es que el hackeo retorne el valor para el que **ningún** otro subastador pueda ganar. Esto significa que _deberías_ considerar el **peor** caso posible para ti como apostador.
Entonces, debes preguntarte, ¿Cuál sería el peor caso en una subasta donde uno de mis competidores está subastando?, y ¿cuál sería el peor caso en una subasta donde el dueño del producto es uno de mis competidores?
Lo voy a plantear de esa forma, la respuesta es evidente, así que saca las conclusiones tú jaja.
Saludos!
