### ISSUE TITLE
 properties y metodos abstractos en diagrama de clases

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2233-2016-1/syllabus#146]
Hola! Mi duda es si una property en el diagrama de clases:
a) No aparece.
b) Aparece como un método, ya que lo es en rigor.
c) Aparece como un atributo, ya que se comporta como tal.

Y sobre los métodos abstractos (y clases abstractas), se representan en diagrama de forma especial?
Gracias! :)

**Comment by tamycova** [comment]
Hola! Las properties van como atributos y las clases abstractas llevan su nombre en cursiva, [lee esto!](http://www.oxfordmathcenter.com/drupal7/node/35)
