### ISSUE TITLE
¿Como hago las trayectorias teniendo en cuenta las multas?

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#148]
Las multas no especifican que objetos se vendio. Y cuando compras un objeto en la tienda no queda ningun registro de eso.
Por ejemplo, si alguien se endeuda, y hipoteca un objeto, otra persona lo compra, y este tambien tiene que hipotecarlo, no queda ningun registro de que paso por las manos del primero, luego a la tienda, y despues a las manos del segundo.
¿Que hago en ese caso?

**Comment by otro-felipe** [comment]
Una forma de enfrentar este problema es creando tu propio archivo para almacenar las trayectorias. Esta información no está en las multas ya que aun no han sido pagadas y por lo tanto no existe forma de saber si se va a pagar con un producto o no, es por eso que mi recomendación es crear un archivo especialmente dedicado a almacenar esta información.

**Comment by perojas3** [comment]
Eso se podría hacer, pero es a partir de el momento en que se hace el código, todas las hechas anteriormente a en los txt oficiales no serian tomadas en cuenta. ¿Que hago para ese caso?

**Comment by Geeermy** [comment]
Hola! Muchos se han confundido un poco por la palabra "trayectoria", así que te lo simplificaré de esta forma:
Lo único que pedimos en esta parte es que pongas:
1. El usuario al que pertenece el producto actualmente (o si pertenece a la tienda)
2. Las subastas en las que ha participado (de donde se desprenden dos dueños: ganador de la subasta y creador de la subasta)
Eso es lo que se entenderá como "trayectoria". Como en los archivos de texto que te entregamos no se recopiló la información de ventas en la tienda, o el pago de multas con productos, no es necesario que tú lo hagas. Con lo explicitado arriba basta.
Saludos!
