### ISSUE TITLE
Diagrama de clases

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233-2016-1/syllabus#149]
Cual es la estructura esperada del diagrama en referencia a los métodos y atributos. Busco en Internet y algunos solo ponen el nombre del atributo y métodos; otros ponen el nombre del atributo seguido de 2 puntos y el tipo de elemento que piden (str, int, list, etc) otros ponen el método e indican que elementos pide y otros ponen el método pero indican que elemento sale de ese método.
¿que estructura sigo?

Otra pregunta: 
Y aunque el titulo dice que es diagrama de clases, ¿se pone aparte los nombre de las funciones implementadas y que piden o solo clases?

**Comment by bamavrakis** [comment]
Hola!
La idea es que se entienda el diagrama, no hay una convención sobre como poner los atributos y métodos, pero para los atributos debes escribir el nombre y el tipo de dato, y para los métodos, el nombre y los argumentos (con su tipo)
Saludos!

**Comment by dtfuller** [comment]
Hola, una nueva consulta!

El diagrama debe ser de **todas** las clases usadas en el programa, o con las que se refieren al modelo de datos estamos listo? 

Saludos ;)

**Comment by rmant** [comment]
Que pasa si yo no cree las funciones como metodos de una clase, sino que como funciones generales que reciben clases como argumento? Mi diagrama de clases solo tendria nombre, y atributos? Gracias!

**Comment by bamavrakis** [comment]
@dtfuller  Debes incluir todas las clases usadas en el programa en el diagrama .
@rmant Eso significa que tienes mal modelado el sistema.

Saludos!

**Comment by perojas3** [comment]
Yo tengo cada una de las 6 clases independientes ¿Eso afecta?

**Comment by CrescenteUC** [comment]
Hola! yo cree clases especiales para leer los txt. Esas no se relacionan con las demás (Usuario, Producto, etc.) ¿Las pongo?

**Comment by negebauer** [comment]
@CrescenteUC Si, tienes que tener **todas** las clases
@perojas3 No, está bien

**Comment by rmant** [comment]
@bamavrakis si mi programa funciona perfecto porque tengo mal modelado el sistema?

**Comment by otro-felipe** [comment]
@rmant Si bien la _idea_ de los códigos y programas es que funcionen, esto no es lo más importante. A la hora de desarrollar software, además de que el programa haga lo que se le pidió que hiciera, debes preocuparte enormemente por que el código esté bien escrito y modelado. 

Es decir: Las clases con sus atributos y métodos respectivos, las interfaces, las clases abstractas, que todo el código esté bien ordenado, usar nombres descriptivos en las variables y métodos, usar muchos métodos lo más concisos posibles (que cada método haga una sola cosa), crear tantas clases como tenga sentido y que todas las funciones estén en un módulo (o clase) en donde tengan sentido que estén.

Esto es incluso más importante que el código funcione, ya que una buena modelación y un buen orden conllevan a un código mucho más manejable y **extensible**. Un código al cual agregarle una funcionalidad adicional no es ningún problema y un código en el cual los _bugs_ no tienen lugar donde esconderse.

Es por esto que la preocupación principal de esta tarea es que aprendan que los programas, además de funcionar, estén bien modelados. Un programa con el código desordenado, con todas las funciones en el mismo archivo es:
- **Difícil de leer.** Varias veces tienes que trabajar en equipo y un código así puede ser extremadamente contraproducente.
- **Difícil de _debuguear_.** Un error que siempre te tira al mismo archivo podría significar cualquier cosa y si tus métodos y variables no tienen nombres descriptivos, encontrar el lugar del error podría tomarte mucho (**mucho**) mas tiempo del que debería.
- **Difícil de extender.** A medida que tus proyectos crezcan y llegues a más usuarios te gustaría agregar nuevas funcionalidades para ir renovando el sistema (como te puedes fijar, todas las aplicaciones están en constante desarrollo). Esto es casi imposible de hacer si tienen un código mal modelado (si tienes que hacer un nuevo tipo de productos y no tienes las bondades del _override_ o incluso de la herencia, escribir y hacer compatible ese producto con el resto de tu sistema podría llegar a ser casi imposible).

Si bien en esta tarea no les vamos a pedir que sus variables tengan nombres descriptivos ni que dividan todo en métodos, sí les vamos a pedir que usen el paradigma de orientación a objetos y que le saquen todo el provecho posible, ya que es esto lo que hace que un código no sucumba en la oscuridad ni se quede atrás por una mala modelación.

**Lo más importante no es que el código funcione, sino que esté bien escrito.**

_Para los que estén más interesados en este tema les recomiendo el libro [Clean Code](http://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882) los ejemplos están en Java, pero las ideas generales se entienden. (Además podrían aprovecharlo como excusa para aprender este lenguaje tan hermoso)._

**Comment by rmant** [comment]
@MainScientist Gracias por la respuesta! Voy a averiguar sobre el tema! 
SIn embargo, a casi 3 horas de la entrega, veo dificil reescribir todo el modelamiento de mi programa, y me da la impresion de que mi codigo está, dentro de lo que se puede, ordenado, lo tengo separado en varios modulos para que se entienda bien. ¿Mi puntaje se debería ver afectado por no escribir las funciones como métodos? Hasta lo que llevo del curso, no sabía que eso era una mala práctica. Saludos!

**Comment by tamycova** [comment]
@rmant Sí, lo lamento mucho pero tu puntaje se verá afectado. Uno de los objetivos de la tarea es aplicar conceptos de programación orientada a objetos para modelar un problema, y la interacción entre objetos por medio de métodos es la base de este paradigma de programación (si las funcione externas se encargan de la interacción con el objeto esto definitivamente no es OOP). Puedes revisar la materia de OOP o buscar su definición en internet, y como futura recomendación acércate a un ayudante durante la elaboración de la tarea para poder resolver tus dudas y ver si vas por bien camino con los objetivos de esta.
