### ISSUE TITLE
[No es del Curso][Un poco de ayuda con PYGAME]

### ISSUE THREAD

**Issue by cdonoso** [IIC2233-2016-1/syllabus#15]
Alguno que haya usado pygame, sabe como eliminar una superficie? Estoy haciendo un pequeño juego, pero no puedo eliminar un enemigo/personaje principal cuando se le acaba la vida :cry: . Por otra parte alguien sabe como agregar una especie de "battery bar" para simbolizar la vida de mi personaje. 

Saludos.

Gracias!

**Comment by tamycova** [comment]
busca "pygame health bar" en google :)

**Comment by cdonoso** [comment]
Uuuuh bacán! Lo encontré! Muchas gracias @tamycova :smile:
