### ISSUE TITLE
Problema con git 

### ISSUE THREAD

**Issue by camiolguin** [IIC2233-2016-1/syllabus#150]
Hola! Tratando de subir la tarea tuve un problema con git, cada vez que pongo git commit -m me aparece el siguiente error:

```
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address
```

Ingresando git config --local -l y git config --global -l me dice correctamente mi mail y mi nombre, con echo $GIT_COMMITTER_EMAIL y echo $GIT_AUTHOR_EMAIL tambien, pero sigo sin poder commitear nada
Ayudaa

**Comment by aaossa** [comment]
Verifica que escribiste correctamente `user.email` y `user.name` (por ejemplo, si escribiste `user.mail`, sin la **e**, no funcionará). Para ver si está correctamente definido usa:

``` console
$ git config -l
```

dentro de la carpeta de tu repo.

**PS:** Cuando haces `git config user.email`, ¿aparece tu mail correctamente? Es decir, sin comillas por ejemploz

**Comment by camiolguin** [comment]
sii lo revise! me muestra correctamente el email y el nombre:

```
credential.helper=osxkeychain
cami.email=cfolguin@uc.cl
cami.name=Cami
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
core.precomposeunicode=true
remote.origin.url=https://github.com/IIC2233-2016-1/camiolguin-iic2233-repo.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
cami.email=cfolguin@uc.cl
```

**Comment by aaossa** [comment]
Debes usar `user.email`, no `cami.email`. Quizás sea eso. Trata de hacer el setup mostrado por el error nuevamente :grin:

**Comment by camiolguin** [comment]
ahí siiii graciaaas!!
