### ISSUE TITLE
¿Cómo se añaden argumentos en las funciones en Nclass?

### ISSUE THREAD

**Issue by sormazabal** [IIC2233-2016-1/syllabus#151]
Perdón si la pregunta suena un poco tonta, pero no pude encontrar ningún tipo de tutorial del programa.

![pasted_image2](https://cloud.githubusercontent.com/assets/7980453/14087617/49125f94-f501-11e5-989c-8bda59652cf4.png)

No me da la opción de poner "public boolean recalculate_price(prod: int)" para especificar que el método pide un int. (me pone un signo de exclamación y tira un error). ¿Cómo tengo que ingresar el método para que me acepte los argumentos?

**Comment by agmardones** [comment]
public boolean recalculate_price(int prod)

en caso de que tuviera más argumentos: public boolean recalculate_price(int prod, str cosa, float otracosa).

**Comment by sormazabal** [comment]
Gracias! :D
