### ISSUE TITLE
¿El verificador de mails tiene que ser 100% preciso?

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#154]
https://en.m.wikipedia.org/wiki/Email_address
El verificador de mails tiene que entregar los valores correctos en todos los casos.
Por ejemplo debe dejar pasar:
"very.(),:;<>[]\".VERY.\"very@\ \"very\".unusual"@strange.example.com
Ese ejemplo?

**Comment by negebauer** [comment]
No se van a probar mails tan rebuscados
