### ISSUE TITLE
mover tarea

### ISSUE THREAD

**Issue by josetov** [IIC2233-2016-1/syllabus#155]
Hasta ahora he estado trabajando en la tarea guardando todos los .txt y .py en una carpeta en mi escritorio. Los movi todos hacia mi carpeta de T01 y pycharm ya no los quiere ejecutar y me sale este error:
[ [Errno 2] No such file or directory ]
¿Alguna manera para poder correrlos bien nuevamente?

*abri los archivos con with open("usuarios.txt , "r") as f:,  y tengo entendido que si mi codigo esta en la misma ubicacion que el .txt no debiera haber problema

**Comment by jicortes2** [comment]
@josetov  A mi me paso lo mismo, tienes que poner el Run... y elegir denuevo tu archivo, porque el que corres normalmente sigue manteniendo la direccion anterior. Te deberia salir algo asi como "nombre_de_tu_archivo" (1)

**Comment by josetov** [comment]
me resulto! gracias :smile:
