### ISSUE TITLE
Formato diagrama de clases

### ISSUE THREAD

**Issue by IsaacConDosA** [IIC2233-2016-1/syllabus#156]
Hola!! el diagrama se sube como foto o como pdf o como? 
salu3

**Comment by mjjunemann** [comment]
Si esta en algún programa especial, intentar exportar a .pdf, ya que es vectorial deja hacer más zoom si es necesario. Si es una foto tratar de que tenga la mejor resolución posible.

Considera las dos opciones, y ve en cual se ve mejor, siempre tratar de que tenga la mejor resolución por si algo es difícil de leer, para que no perder puntaje por algo ilegible. 

Saludos
