### ISSUE TITLE
tarea con .txt

### ISSUE THREAD

**Issue by tblatrille** [IIC2233-2016-1/syllabus#158]
Mil disculpas si ya lo habían preguntado antes, son demasiados issues y respuestas.
La tarea la subo sin los .txt o los dejo por si acaso?

**Comment by tamycova** [comment]
@tblatrille súbelo sin los .txt por favor (y el que vea esto haga lo mismo).

**Comment by MortizDX** [comment]
He estado un buen rato tratando de hacer el commit sin los .txt (y un par de pdf), pero me está tomando mucho tiempo y no pasa nada. He estado trabajando con el github desktop para Windows y no me había dado problemas ¿pasará lo mismo si lo trato de hacer con la consola o tomaría el mismo tiempo?

**Comment by fgvenegas** [comment]
Porque usan el desktop si se les enseño a usar  la consola!! Siempre se generan problemas con eso. Prueba haciendolo desde la consola. Y borra github desktop, despues de esto

**Comment by MortizDX** [comment]
Porque la consola me dio problemas por culpa de un commit durante una actividad y tuve que cambiar a desktop por tiempo, y como con el desktop no me dio problemas seguí con él. Además de que nunca logré hacer que la consola recordara mi nombre y contraseña, y como luego anunciaron la tarea1, no me di el tiempo de probar la consola nuevamente.

Intentaré borrar los archivos con la consola (ya es pasada la hora, pero solo quiero ver si puedo borrar esos archivos sobrantes) e indicaré si funciona o no.

**EDIT:** Listo, ahí sí, se había quedado en el commit solamente y faltaba push. A considerar para la otra, ¿trae demasiado problemas dejar esos archivos allí? Cómo no se mencionaba en las "Restricciones y alcances" del enunciado dejaba todos los archivos con los que trabajaba en el repositorio.
