### ISSUE TITLE
Sobre arbloes.

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#159]
Entonces. ¿Arboles basicamente consiste en clases que se agrega una clase del mismo tipo?

**Comment by otro-felipe** [comment]
En la práctica es algo parecido a lo que dices, pero lo importante es que entiendas la idea **abstracta** detrás de los árboles más que cómo se ven en el código. Para entender estructuras de datos (y resolver problemas en general) primero debes desentenderte un poco del código y pensarlo de una manera más general.

Un Árbol es una estructura usada para almacenar datos de manera **jerárquica**. Esto quiere decir que los datos están divididos por niveles. Lo puedes pensar como un dato/nodo "padre" que contiene nexos hacia otros datos/nodos "hijos". A su vez cada uno de estos hijos puede ser "padre" de otros datos/nodos también.

Un ejemplo claro de este tipo de estructuras son los diccionarios de Python. Cuando defines un diccionario de Python tienes **un objeto raíz** que tiene **referencias** por medio de llaves hacia otros objetos. Estos otros objetos podrían ser nuevos diccionarios con objetos dentro también y así hasta que un diccionario no contenga ningún otro diccionario dentro. Este tipo de estructuras son los llamados Árboles.

En estricto rigor está bien pensarlo como "clases que se le agregan clases" (aunque estas clases podrían no ser siempre del mismo tipo), pero lo importante es que entiendas el concepto general de Árboles. Una vez que entiendas este concepto puedes adentrarte en los códigos que se encuentran en el material de clases para ver ejemplos de como representarlos y de **cómo recorrerlos** (esto esta en negrita porque una de las cosas más importantes respecto de los árboles es saber y entender las distintas formas de recorrerlos). De todas formas lo primero que hacen en el material de clases es explicarte el concepto de Árbol antes de presentar cualquier código.
