### ISSUE TITLE
Duda acerca de algunas complejidades 

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2233-2016-1/syllabus#160]
Hola, no me queda claro por qué:
1. Setear una slice de una lista toma tiempo O(n+k) (¿no debería ser O(k) debido que estoy cambiando k elementos?)
2. ¿Cuando se busca un elemento en un conjunto, cómo sabe dónde encontrarlo? Dado que solo se demora O(1).
3. ¿Por qué en los peores casos se considera casi siempre O(len(s)*len(t))? No entiendo de dónde viene la multiplicación.
Muchas gracias de antemano
Saludos!

**Comment by jecastro1** [comment]
Hola Alfonso, iré punto por punto

### 1

Sucede que al setear un slice está permitido que lo que se setea sea de distinto tamaño que el slice. Por ejemplo:

``` python
a = list(range(10))
b = list(range(100, 102))
c = list(range(100, 105))
```

``` python
print(a)
print(b)
print(c)
```

```
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[100, 101]
[100, 101, 102, 103, 104]
```
- Fíjate que el slice mide 1 y ahí "inserto" algo de largo 2

``` python
a[1:2] = b
print(a)
print(len(a))
```

```
[0, 100, 101, 2, 3, 4, 5, 6, 7, 8, 9]
11
```
- Ahora fíjate que el slice que mide 7 lo reemplazo por otro que mide 4

``` python
a[3:11] = c
print(a)
print(len(a))
```

```
[0, 100, 101, 100, 101, 102, 103, 104]
8
```

**Intuitivamente** para poder hacer lo de antes tienes que "correr" todos los elementos que están después del slice seteado. En el peor de los casos tendrás que correrlos todos, así que hay gastas tiempo `O(n)`. Además hay que escribir k elementos, así que ahí gastas `O(k)` y logras el tiempo `O(n + k)`

### 2

No es algo que tengas que entender ahora, pero igual trataré de explicarlo.

Supón que yo tengo una lista gigante . También que yo tengo una función `f(x)`, con dominio en los objetos de Python y recorrido en los números enteros del 0 hasta una cantidad razonable. Asume que me demoro un tiempo constante en calcular esta función.

**A grandes rasgos** yo voy a colocar el objeto en la posición donde me diga esta función, o sea `lista[f(x)] = x`. Y para verificar si un elemento está, calculo el valor que da la función matemática y veo el espacio correspondiente en la lista gigante.

Eso a grandes rasgos. Hay detalles, como por ejemplo que es posible encontrar un par de objetos cuyo resultado con `f(x)` sea el mismo. Pero eso se maneja bien.

Lo único con que tienes que quedarte es que efectivamente encontrar un elemento en un set toma O(1).

### 3

Eso sucede justamente en el caso que no quise explicar en el punto dos, o sea cuando colocas en el set **muchos** objetos cuyos `f(x)` da el mismo, porque manejar esos casos se puede pero no es gratis. Esto es **muy poco probable** que ocurra, así que no lo tomaría como referencia para programar.

Espero que te haya dado un poco más de intuición, saludos.
