### ISSUE TITLE
Duda función recorrer_arbol

### ISSUE THREAD

**Issue by agmardones** [IIC2233-2016-1/syllabus#161]
``` python
    def __repr__(self):
        def recorrer_arbol(raiz):
            self.ret += "nodo_id: {}, id_padre: {} -> valor: {}\n".format(raiz.id_nodo, raiz.id_padre, raiz.valor)
            for hijo in raiz.hijos.values():
                recorrer_arbol(hijo)

            return self

        self.ret = ''
        recorrer_arbol(self)

        return self.ret
```

Hola!, de qué sirve que la función recorrer_arbol retorne self?

**Comment by tamycova** [comment]
Hola @agmardones , no afecta en nada en su función (borra la línea y lo verás), sin embargo es considerado correcto por PEP8. Lee  [la guia PEP8](https://www.python.org/dev/peps/pep-0008/#programming-recommendations) para más info.

**Comment by agmardones** [comment]
Gracias @tamycova , pensé que tenía alguna utilidad en el código
