### ISSUE TITLE
Tareas

### ISSUE THREAD

**Issue by IsaacConDosA** [IIC2233-2016-1/syllabus#164]
Holaa, cuantas tareas son en el curso y cuales son las fechas aproximadas?  
Saludos

**Comment by tamycova** [comment]
7 y calcula aprox cada dos semanas desde hoy!

**Comment by mjjunemann** [comment]
Son 6 Tareas + 1 posible recuperativa que borra la peor , y las fechas aproximadas puedes calcularlas tú. Cada tarea tiene un plazo de dos semanas y la siguiente se sube el día de entrega de la anterior a las 23:59 horas.
Este caso fue extraordinario , ya que tuvimos algunos problemas administrativos que no nos permitieron subirla el Lunes.

Saludos

**Comment by abulnes1** [comment]
Hola! Quería saber un poco mas de la tarea recuperativa. La van a subir después de la 6? Y se la mandan a todos cierto? Saludos!
