### ISSUE TITLE
Problema con pycharm

### ISSUE THREAD

**Issue by FernandoPieressa** [IIC2233-2016-1/syllabus#167]
necesito ayuda con pycharm, me tira este error:

![image](https://cloud.githubusercontent.com/assets/13782155/14194268/01e89398-f783-11e5-8690-2b81da1858dc.png)

Despues de eso el demo de la tarea2 me tira error.
En la programaton un ayudante me logro arreglar el problema una vez, creo que el problema era por donde estaba trabajando en el proyecto de pycharm, pero no se como lo arreglo.

**Comment by otro-felipe** [comment]
Hola! Eso se puede arreglar haciendo click derecho en tu carpeta `T02->Mark Directory as... -> Sources Root`.

**Comment by FernandoPieressa** [comment]
Gracias!
