### ISSUE TITLE
ImportError: No module named 'PyQt4'

### ISSUE THREAD

**Issue by isipalma** [IIC2233-2016-1/syllabus#168]
Hola,

Queria preguntar sobre si falta algun archivo en la Tarea 2 pues cuando intento ver la interfaz me aparece el siguiente aviso:

 from PyQt4.QtGui import QApplication
ImportError: No module named 'PyQt4'

No se si es porque no le estoy asignando bien la interfaz o si es que falta algun archivo

Gracias y saludos

**Comment by aaossa** [comment]
Ve la issue que acabamos de hacer con @MainScientist en #169, esperamos que pueda servirte :grin: Cualquier duda extra comentala en la otra issue :+1:
