### ISSUE TITLE
Setup de PyQt4

### ISSUE THREAD

**Issue by aaossa** [IIC2233-2016-1/syllabus#169]
A lo largo del curso usaremos y desarrollaremos interfaces gráficas con esta librería. Como la **Tarea 2** ya se encuentra publicada y en esta se utiliza una interfaz gráfica (que solo debes usar) **debes tener instalado PyQt4**. Sigue las instrucciones según tu sistema operativo. 
## Mac OSX

``` sh
brew install pyqt --with-python3
```

Si por casualidad lo instalaste sin el `--with-python3`, tenemos que borrar la instalación con `brew uninstall pyqt` y volver a instalarlo con el comando de arriba.
## Windows

``` sh
pip install -i https://pypi.binstar.org/petebachant/simple pyqt4
```
## Linux
- Si tienes una distribución Debian-_Like_

``` sh
sudo apt-get install python3-pyqt4
```
- Si tienes una distribución Arch-_Like_

``` sh
sudo pacman -S python-pyqt4
```
# Probando PyQt4

Para asegurarnos que se instaló bien ejecutamos este comando dentro de Python y no debería generar errores:

``` python
import PyQt4
```
# Errores

Si seguiste los pasos y se presenta algun error durante la instalación pregunta en esta misma issue. No olvides agregar tu **sistema operativo** y una **foto del error**

**Ánimo con la tarea** :grin:

**Comment by isipalma** [comment]
muchisimas gracias! eso si en que carpeta debo ubicarme e ingresar pip install -i https://pypi.binstar.org/petebachant/simple pyqt4
porque el cmd no me reconoce el "pip"

**Comment by vlcastillo** [comment]
Después de instalar PyQt4 me tira este error al intentar ejecutar el demo. (Windows 10)

![error](https://cloud.githubusercontent.com/assets/17559905/14195090/c4219d08-f78b-11e5-84da-7458b4a3b6f8.jpg)

**Comment by Geeermy** [comment]
@isipalma Hola! Tu problema probablemente tenga que ver con esto: http://stackoverflow.com/questions/23708898/pip-is-not-recognized-as-an-internal-or-external-command
Es algo común en todo caso, a varios nos ha pasado jaja. Ojalá esto lo solucione!

**Comment by Geeermy** [comment]
@vlcastillo Probablemente tenga que ver con esto: http://stackoverflow.com/questions/19019720/importerror-dll-load-failed-1-is-not-a-valid-win32-application-but-the-dlls
No sé si será eso exactamente, pero podría ir por ahí!

**Comment by Geeermy** [comment]
Y un consejo cabros: Acostúmbrense a buscar sus problemas en google literalmente (yo lo hice así para buscar los enlaces). A veces son cosas simples que pueden solucionar en cosa de minutos, y se ahorran la lata de estar esperando a que nosotros les tengamos una respuesta formal (que podría tomar un tiempo considerable en algunos casos). No es de mala onda, les servirá bastante en general en computación, no solo para este ramo :) Saludos!

**Comment by isipalma** [comment]
Ahi si! el problema era el path, pero ya lo resolvi ;)
Muchisimas gracias n.n

**Comment by stephichau** [comment]
[osx]  Se supone que instale pyqt, pero me sigue apareciendo error al importar PyQt4 :(
<img width="919" alt="screen shot 2016-03-31 at 11 06 25 pm" src="https://cloud.githubusercontent.com/assets/16126322/14195896/4ab73810-f795-11e5-8b65-5a449a77316e.png">

**Comment by cataschaufler** [comment]
Me pasa lo mismo eso si cuando lo instale me salio esto: (se me olvido sacar una foto a la pantalla)
Phonon support is broken
Python modules have been installed and Homebrew's site-packages is not in your Python sys.path, so you will not be able to import the modules this formula installed. If you plan to develop with these modules, please run:
mkdir -p /Users/Cata/Library/Python/2.7/lib/python/site-packages MacBook-Pro-de-Catalina-3:~ Cata$   echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/Cata/Library/Python/2.7/lib/python/site-packages/homebrew.pth
Lo desinstale y instale denuevo y me salio 
Phonon support is broken
intent ver en internet las soluciones que estaban para alguien que tenia algo parecido no funcionaron
http://stackoverflow.com/questions/30933181/installing-ipython-qtconsole-mac-osx-cant-find-pyqt-on-system

**Comment by agmardones** [comment]
Hola, no puedo instalarlo :(
![error](https://cloud.githubusercontent.com/assets/13753000/14196872/d0e06af2-f79e-11e5-88be-2b016dc84282.jpg)

PD: No sabía qué poner en google jajaj

**Comment by otro-felipe** [comment]
@agmardones cual es el error al updatear pip?
EDIT: intenta con este `easy_install -U pip` para updatear pip.

**Comment by agmardones** [comment]
me dejó updatear pip (con tu comando <3), ahora tengo un error más guapo:
![error2](https://cloud.githubusercontent.com/assets/13753000/14198285/ab771788-f7ae-11e5-89ab-286b124e6b12.jpg)

**Comment by Geeermy** [comment]
@agmardones Hola! Una alternativa para tu problema, es hacerlo a través de un archivo .whl. Los pasos a seguir son:
1. Descarga el .whl que corresponda, desde http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyqt4 (ojo que también puedes buscar más librerías acá, te podrían servir a futuro!)
2. Desde consola, usa el comando: pip install ruta/de/mi/archivo.whl (también puedes usar el comando cd para irte a la carpeta donde se encuentre el .whl, así te ahorras la lata de poner la ruta completa).
3. Espera a que se instale todo el paquete, y prueba con "import PyQt4" en la consola para comprobar que se haya instalado correctamente.
La versión que te serviría, a mi parecer, sería la de Python 3.4 de 64 bits: "PyQt4-4.11.4-cp34-none-win_amd64.whl"
Esto también se puede encontrar googleando (http://stackoverflow.com/questions/22640640/how-to-install-pyqt4-on-windows-using-pip), sin embargo, para mí el uso de los .whl por fallas en Windows ha sido bastante frecuente al momento de instalar librerías, así que me vi obligado a explicarlo con un poco más de detalle :)
Espero te sirva. Saludos!

**Comment by agmardones** [comment]
Ahí si, había tratado de hacer eso antes y tampoco me había dejado. El problema que tenía fue haber instalado versiones de python distintas (instalé la 3.5 para ver que traía) y algo pasó que pip se volvió loco, desinstalé todo e instalé sólo python 3.4 y funcionó instalando con el whl (lo comento por si a alguien le llega a pasar). Muchas gracias @Geeermy, @MainScientist

**Comment by Geeermy** [comment]
@agmardones Ahh, sí. Tener versiones distintas de Python suele dejar la embarrada con las librerías :( pero me alegra que lo hayas solucionado. De nada! =)

**Comment by josetov** [comment]
[OS X]
Hoola, la terminal me tira de inmediato "brew: command not found".
¿Deberia colocar el comando "cd" en algún lugar en específico antes de instalar?
![captura de pantalla 2016-04-01 a las 4 00 07 p m](https://cloud.githubusercontent.com/assets/17603206/14217281/7b342762-f823-11e5-8932-cc6e08bb25d4.png)

**Comment by rodolfopalma** [comment]
@josetov Tienes instalado Homebrew? Si no, pega esta línea en tu terminal para instalarlo: `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`.

**Comment by stephichau** [comment]
@rpalmaotero en que carpeta tengo que escribir brew install pyqt --with-python3 ?

**Comment by rodolfopalma** [comment]
@stephichau Con Homebrew correctamente instalado da lo mismo en que carpeta estés al ejecutar el comando.

**Comment by stephichau** [comment]
@rpalmaotero instale Homebrew con el link que pusiste y puse el comando, pero me sigue tirando error al importar PyQt4 ('No module named 'PyQt4')

**Comment by elzambon** [comment]
Hola una vez instalado el Homebrew cuando realizo brew install pyqt --with-python3 tira el error Phonon support is broken que describe que la instalación fue exitosa pero no se puede llamar el modulo desde python. Creo que es lo descrito por stephichau ya que si no tomas en cuenta el error te dice que ya esta instalado y el error que sale cuando se esta instalando es el que comento cataherrera
<img width="518" alt="captura de pantalla 2016-04-01 a las 16 22 57" src="https://cloud.githubusercontent.com/assets/17582470/14218544/35b7adc8-f82b-11e5-9d44-6d07f7b0833d.png">
<img width="691" alt="captura de pantalla 2016-04-01 a las 16 59 41" src="https://cloud.githubusercontent.com/assets/17582470/14218549/3c76fa1a-f82b-11e5-963c-dc2a24b49c64.png">

**Comment by josetov** [comment]
@rpalmaotero me funciono, gracias! ahora se esta instalando pero me aparecio el mismo error que menciona @cataherrera 
![captura de pantalla 2016-04-01 a las 5 07 36 p m](https://cloud.githubusercontent.com/assets/17603206/14218718/63f72c08-f82c-11e5-9588-c0f8acf6f46b.png)

**Comment by mglambert** [comment]
@josetov @cataherrera 
Encontraron la solución del problema? me sale lo mismo :/

**Comment by cataschaufler** [comment]
@mglambert  No aun

**Comment by otro-felipe** [comment]
# Para aquellos que usan MAC OS X

Aquí hay una [buena guía](http://www.pythonschool.net/pyqt/installing-pyqt-on-mac-os-x/) para instalar PyQt4. Se las voy a resumir y a explicar un poco.

### Paso 1: Sistema operativo al día

Verificar que tienen su versión de MAC OS X al día.

### Paso 2: Xcode Command Line Tools.

Deben checkear que tienen las Command Line Tools de Xcode. Para esto pueden hacerlo mediante el siguiente comando en consola:

```
xcode-select -p
```

Si les retorna algo como `/Applications/Xcode.app/Contents/Developer` entonces es porque están bien y pueden seguir.
En caso de no tener las Command Line Tools las pueden bajar con el siguiente comando

```
xcode-select --install
```

Aunque si les interesa adentrarse en programar aplicaciones nativas para iOS les recomiendo que se bajen Xcode entero desde la App Store (ojo que es una descarga mucho mucho más pesada).

### Paso 3: Instalar Qt

Descargar Qt desde [esta página](http://download.qt.io/official_releases/qt/4.8/4.8.6/qt-opensource-mac-4.8.6-1.dmg) e instalarlo.
Si tienen homebrew pueden hacerlo mediante la consola con el comando `brew install qt`.

### Paso 4: Bajar SIP y PyQt

Una vez instalado Qt descarguen el source package de SIP y PyQt para MAC desde estas paginas: [SIP](https://riverbankcomputing.com/software/sip/download) y [PyQt](https://riverbankcomputing.com/software/pyqt/download). 
Una vez descargados muévanlos a una carpeta en común (digamos `Folder`) y descompriman los archivos (hacerles doble click).

### Paso 5: Path a site-packages.

Necesitamos saber donde se encuentra la carpeta site-packages, que es la carpeta que almacena las librerias que descargamos de python.
Para esto debemos escribir lo siguiente en python:

``` python
import site
print(site.getsitepackages()[0])
```

Esto lo pueden hacer en consola:

```
python3
>> import sip
>> sip.getsitepackages()[0]
```

### Paso 5: Instalar SIP.

En la terminal vamos a `Folder/SIP` y escribimos los siguientes comandos:

```
python3 configure.py -d {PATH A SITE-PACKAGES} -arch x86_64
sudo make
sudo make install
```

### Paso 6: Instalar PyQt (Finalmente).

De la forma en que lo hicimos en el paso anterior vamos a `Folder/PyQt` y escribimos los siguientes comandos:

```
python3 configure.py -d {PATH A SITE-PACKAGES}
sudo make
sudo make install
```

_Esta parte se demora e imprime muchas cosas en la consola, si quieren la pueden poner en pantalla completa y pensar que estan hackeando alguna red importante._

### Paso 7: Ver si funciona.

En caso de que no les funcione o hayan tenido algún problema durante la instalación ~~lloren~~ **traten de buscarlo en google en primera instancia**, en caso de ser incapaces de resolverlos por ustedes mismos, pregúntennos (nosotros manejamos mejor el lenguaje de consultas de Google).

**Comment by elzambon** [comment]
Hola @MainScientist cuando hago lo descrito por ti o lo que esta en el link que pusiste me sale el siguiente error. Lo he buscado pero no encuentro la solución:
<img width="567" alt="captura de pantalla 2016-04-03 a las 12 36 14" src="https://cloud.githubusercontent.com/assets/17582470/14233220/dd8e9322-f998-11e5-9792-8ce139025f74.png">

**Comment by otro-felipe** [comment]
@elzambon Tal como dice el mensaje de error: intenta poner `--verbose` al lado de x86_64 para ver mas detalles de tu error :)

**Comment by elzambon** [comment]
@MainScientist 
Mira borre todo para mostrar el procedimiento de nuevo creo que los errores parten de python3 configure.py -d /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4 --use-arch x86_64

Empezamos con el Sip
<img width="1228" alt="sip" src="https://cloud.githubusercontent.com/assets/17582470/14233729/3e5f8e82-f9a7-11e5-80e2-19fc8649eb37.png">
Después tratamos con el otro PyQt:
<img width="804" alt="0" src="https://cloud.githubusercontent.com/assets/17582470/14233733/5ff9dd04-f9a7-11e5-8d06-f7736e0fab90.png">
Me equivoque en la primera linea me falto el --use pero no importa cuando lo hago bien me pide el -q 
<img width="563" alt="captura de pantalla 2016-04-03 a las 14 19 43" src="https://cloud.githubusercontent.com/assets/17582470/14233738/7cabec30-f9a7-11e5-929d-18bbf4e90169.png">
Ahora los errores de poner el -q y todo con --verbose 

<img width="804" alt="1" src="https://cloud.githubusercontent.com/assets/17582470/14233742/a2f2a924-f9a7-11e5-9df5-bef85c7ca4cb.png">
<img width="806" alt="2" src="https://cloud.githubusercontent.com/assets/17582470/14233743/a4566ec2-f9a7-11e5-8905-eaae427faaf8.png">
<img width="803" alt="3" src="https://cloud.githubusercontent.com/assets/17582470/14233744/a683c226-f9a7-11e5-987b-18c9d2404438.png">
<img width="802" alt="4" src="https://cloud.githubusercontent.com/assets/17582470/14233745/aa8a84cc-f9a7-11e5-8f53-ae9cef4e228b.png">
<img width="813" alt="5" src="https://cloud.githubusercontent.com/assets/17582470/14233748/add5cc5e-f9a7-11e5-8049-e88cd9bc6b4f.png">

He buscado pero llega a lo mismo

**Comment by otro-felipe** [comment]
Quizás sea porque la versiónd e qt es qt5. Perdón no pensé que fuese a ser un problema. Intenta usando [esta versión de qt](http://download.qt.io/official_releases/qt/4.8/4.8.6/qt-opensource-mac-4.8.6-1.dmg)

**Comment by alainrochette** [comment]
Hola, por alguna razón no tengo python3.X en mi usr/local/lib...hasta borré y bajé python de nuevo pero todavía no está. Además, no existe un "site-packages" en mi sistema que no sea de python 2.7. También agregue la siguiente linea a mi .bash_profile y nada:
export PYTHONPATH=/usr/local/lib/python3.4/site-packages
Ayuda :(
(MAC OS X 10.11)

**Comment by otro-felipe** [comment]
¿cómo instalaste python?

**Comment by tblatrille** [comment]
Hola tengo problemas para instalar PyQt, he seguido los pasos que le recomendaste a @elzambon, pero aun con qt 4.8 sigo con éste error

<img width="571" alt="captura de pantalla 2016-04-03 a las 22 56 53" src="https://cloud.githubusercontent.com/assets/17602895/14236630/cda18bb2-f9ee-11e5-9632-40554535a3fd.png">

**Comment by alainrochette** [comment]
@MainScientist me lo bajé por python.org. Es posible que alguien me ayude hacer el setup del PyQt durante la ayudantía de hoy?

**Comment by gbordoni** [comment]
Instalé el PyQt4 para ubuntu, pero me aparece el siguiente error:

`Traceback (most recent call last):
  File "/home/gbordoni/syllabus/Tareas/T02/Enunciado/demo.py", line 1, in <module>
    import gui
  File "/home/gbordoni/syllabus/Tareas/T02/Enunciado/gui/__init__.py", line 1, in <module>
    from PyQt4.QtGui import QApplication
ImportError: No module named 'PyQt4'`

Busque para solucionarlo pero no logro hacerlo...el problema es que se instaló para python2.7 y no para el 3 y no logro hacer que funcione..

**Comment by Zanfor** [comment]
Dice que tengo que actualizar pip pero al actualizarlo dice que ya esta actualizado. 
![sin titulo](https://cloud.githubusercontent.com/assets/17620265/14255284/a4aae46c-fa69-11e5-8061-a74f52d07555.png)

**Comment by nithomas** [comment]
Hola, instale PyQt4 (al correrlo por consola, no me tira error), pero al correr el "demo.py" me tira el siguiente error
<img width="1280" alt="screen shot 2016-04-06 at 4 53 52 pm" src="https://cloud.githubusercontent.com/assets/17608648/14330748/6871b5c4-fc18-11e5-8cd5-3875a7519966.png">
<img width="1237" alt="screen shot 2016-04-06 at 4 54 10 pm" src="https://cloud.githubusercontent.com/assets/17608648/14330753/6e43b498-fc18-11e5-93bb-ad4e49efce60.png">
