### ISSUE TITLE
Uso libreria JSON en Tarea01 

### ISSUE THREAD

**Issue by vectorcrumb** [IIC2233-2016-1/syllabus#17]
Seria posible usar la librería incorporada de JSON para facilitar la lectura y escritura de información desde y hacia los archivos de texto?

**Comment by bamavrakis** [comment]
Hola!
no está permitido usar json ni ningún método para facilitar la escritura y lectura, la idea es que lo hagan a mano creando su propio parser.
Saludos!

**Comment by jecastro1** [comment]
Ver #65
