### ISSUE TITLE
Duda recorrecciones

### ISSUE THREAD

**Issue by tblatrille** [IIC2233-2016-1/syllabus#170]
Estimados,
Si tengo un 1.00 en una actividad porque solo lo subimos al repo de mi pareja, debo recorregir o se arreglará? para futuro mejor subir ambos dos la actividad, para evitar tener que recorregir?

**Comment by aaossa** [comment]
Debes mandar a recorregir. Para futuro lo ideal es que ambos entreguen correctamente siguiendo el formato especificado y en la carpeta correcta

**Comment by tblatrille** [comment]
ok, pero la instrucción antes sido se podía subir a solo un repo

**Comment by jecastro1** [comment]
@tblatrille Efectivamente puede subir sólo un compañero, o ambos, da lo mismo. Eso siempre (en este semestre) ha sido así.

Ve el último anuncio que coloqué en SIDING que corrigió algunas notas en el excel.
