### ISSUE TITLE
Uso de estructuras Tarea 2

### ISSUE THREAD

**Issue by isarovic** [IIC2233-2016-1/syllabus#171]
Hola! 
       Entiendo que la idea de la tarea es que usemos nuestras propias estructuras, pero por ejemplo a la hora de no sé, digamos obtener los mapas disponibles que hay para cargar (los .txt) necesito usar  el modulo os, en particular el metodo os.listdir("nombre carpeta"), el cual retorna una lista con archivos. ¿Puedo al menos iterar con esa lista para recorrer los archivos e imprimirlos?. En caso contrario, ¿Alguna otra forma con la que pueda obtener los mapas a cargar que no me retorne una lista?

Saludos!

**Comment by aaossa** [comment]
Un poco tarde, pero por si no lo has visto:

Esta pregunta es parecida a #192 (respondida), lo que muestra una forma de hacer estas cosas similar a la sugerida en #190 (respondida).

**Comment by isarovic** [comment]
Si!, vale gracias! =)
