### ISSUE TITLE
[Codigo] AttributeError

### ISSUE THREAD

**Issue by santiagocruzb** [IIC2233-2016-1/syllabus#173]
Hola! Queria saber si es posible que a partir de un input (str), se pueda transformar y operar como una variable que ya estaba definida previamente?

```
lista = [1,2,3,4]
pregunta = str(input('blabla'))

#asumiendo que pregunta es 'lista'

pregunta.append(0)
print(pregunta)
[1,2,3,4,0]
```

Muchas gracias!

**Comment by rodolfopalma** [comment]
No. Una alternativa es hacer:

``` python
diccionario = {
    "lista": [1, 2, 3, 4]
}
pregunta = input()
diccionario[pregunta].append(0) # Si no existe la llave lanza KeyError
```

**Comment by gafigueroa** [comment]
Otra forma que existe, pero que nosotros no les dejamos usar porque es una mala práctica es utilizar `eval()`

``` python
lista = [1,2,3,4]
pregunta = eval(input('blabla'))

#asumiendo que pregunta es 'lista'

pregunta.append(0)
print(pregunta)
[1,2,3,4,0]
```

Es una mala práctica porque es muy poco seguro y en general siempre se puede hace de otra manera (por ejemplo la de @rpalmaotero). Asi que no lo uses, pero lo dejo aquí para que sepas que existe

**Comment by fgvenegas** [comment]
Pero la de @rpalmaotero en este caso no esta permitida porque no se pueden usar diccionarios

**EDIT @aaossa:** Esto es solo si lo consideras para la Tarea 2, obviamente...
