### ISSUE TITLE
Problema con la ventana de SixPYx

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#175]
Cuando abro la ventana de SixPYx me sale demaciado grande. Les pongo una screenshot en.
¿Que hago? El modificar las dimenciones como dice el pdf no me funciona, solo hace los hexagonos más
![screenshot](https://cloud.githubusercontent.com/assets/14139107/14216362/b7078d56-f81e-11e5-8234-422210eeb38e.png)

 pequeños.

**Comment by otro-felipe** [comment]
¿Que metodo usaste?

**Comment by perojas3** [comment]
Todavia no comienzo con el codigo en sí, estoy experimentando.

**Comment by otro-felipe** [comment]
El método para cambiar la escala de la gui es `gui.set_scale(0.5)`. Entre más chico sea el float que le ingreses a este método, más chica se verá la gui.

**Comment by perojas3** [comment]
A eso me refeia con  "El modificar las dimenciones como dice el pdf no me funciona". Esto es lo que pasa. Los hexagonos cambian de tamaño, pero no puedo cambiar las dimenciones de la ventana :
![screenshot](https://cloud.githubusercontent.com/assets/14139107/14216917/ab03780a-f821-11e5-8f8b-637a26688f4a.png)

**Comment by otro-felipe** [comment]
Qué otros métodos estás usando estás usando?

**Comment by perojas3** [comment]
Hasta ahora, solo estoy familiarizandome, esto es todo lo que he hecho. Como no tiene ningun codigo que se pueda copiar, dudo que imorte que lo muestre:
![screenshot](https://cloud.githubusercontent.com/assets/14139107/14217015/31a101ca-f822-11e5-8bb6-19fe45513c15.png)

**Comment by perojas3** [comment]
No he hecho ningun cambio importante a lo que venia. Puedo mostrarte el codigo?

**Comment by otro-felipe** [comment]
Aaaaaah ok ok ahora sé lo que pasa. Antes de hacer el `gui.init()` debes hacer `gui.set_scale()`.

**Comment by perojas3** [comment]
Me funciono, gracias, entonces hay que cambiar el set_scale.

**Comment by otro-felipe** [comment]
antes del método `gui.init()`debería ser llamado el método `gui.set_scale()`.
