### ISSUE TITLE
[T02][Tipo, color pieza]

### ISSUE THREAD

**Issue by vbarros2** [IIC2233-2016-1/syllabus#176]
He tratado de todas las formas pero no he podido retornar el color o tipo de la pieza del lugar (x,i).
Existe alguna función para esto?

Saludos

VBarros

**Comment by otro-felipe** [comment]
La idea es que almacenes todos estos datos usando tus propias estructuras. La gui solo te proporciona los datos y properties que dice el enunciado, esto es: posición, selected, y number en el caso de las bombas.

**Comment by tmorales1** [comment]
Tupla se considera prohibida entonces?

**Comment by otro-felipe** [comment]
sí
