### ISSUE TITLE
¿Puedo usar variables?

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#177]
El texto dice :

> SIN USAR LAS ESTRUCTURAS DADAS POR PYTHON (listas, diccionarios, sets, etc).

Actualmente me encuentro haciendo la interface, puedo usar variables como por ejemplo:
`
respuesta = input ("Que desea hacer")`

**Comment by flobarrios** [comment]
Hola ! Si puedes. Lo que esta prohibido es usar listas, diccionarios, sets y estructuras de ese tipo
