### ISSUE TITLE
Librerias permitidas y no permitidas en la Tarea 2

### ISSUE THREAD

**Issue by negebauer** [IIC2233-2016-1/syllabus#178]
**Recuerden especificar en su README qué librerías utilizan**

---

La idea es que pregunten acá todas las dudas respecto a módulos, librerías y funciones de python que deseen saber si pueden usarlas o no.
### Librerías permitidas
- time
- os
- random
- sys.exit
### Rotundamente prohibido
- listas `list()`, `[]`
- diccionarios
- sets
- tuple
- estructuras de datos de ese tipo provistas por python

---
## Pero, ¿Qué pasa si una función me retorna una lista? (ej: `os.listdir()`)

Pueden usar funciones que retornen una lista, diccionario, set, tuple, etc. pero no la pueden usar como tal.
Lo que si pueden hacer es Castear el return de dicha función a una de sus propias estructuras, ejemplos de esto en #180 #190 #192

**Comment by perojas3** [comment]
¿Se puede usar `os.listdir()`?

**Comment by fgvenegas** [comment]
Como respondi en #196, si puedes usarlo

**Comment by perojas3** [comment]
¿Incluso si lo que hace es crear una lista?

**Comment by fgvenegas** [comment]
Para evitar que pase eso puedes basarte en la explicacion de #190

**Comment by negebauer** [comment]
Te recomiendo que revises #190 para ver cómo trabajar con algo que te retorna una lista

**Comment by perojas3** [comment]
Lo que yo deseo hacer es que se impriman con listdir en orden con un numero cada uno, y el usuario al seleccionar el numero, se retorne el str del numero que se selecciono. Pero ese link que me dejan solo explica como imprimir los elementos de la lista, no deja claro hasta que punto podemos usara.

**Comment by negebauer** [comment]
Si te fijas en #190 se hace referencia a #180 
Básicamente, puedes crear tu propia lista a partir de una lista que te retorna python (usando *args), pero no más que eso

**Comment by diegosapunar** [comment]
puedo usar listas para almacenar datos auxiliares en una funcion recursiva de mi programa? 
No en la estrutura de datos de mi programa.

**Comment by otro-felipe** [comment]
No se pueden usar listas, si llega a haber algun metodo de python que retorne una lista debes castearlo a tu propia estructura de datos. Saludos.

**Comment by stephichau** [comment]
se puede usar la libreria glob ?

**Comment by tamycova** [comment]
@stephichau  para qué?

**Comment by Meaylwin** [comment]
Se puede usar la libreria tkinter para crear una interfaz que le pregunte al usuario si  quiere crear una partida nueva o cargar una existente?

**Comment by fgvenegas** [comment]
No puedes usar tkinter, si quieres hacer **debes** hacerlo con PyQt4, @MainScientist comenta también que de hacerlo así no hagas otro QApplication sino que instancies tu gui después del gui.init()

**Comment by stephichau** [comment]
@tamycova para ver los archivos dentro de una carpeta :)

**Comment by fgvenegas** [comment]
@Manuel-uc  Recuerda que **no es algo que te estemos evaluando**, sera trabajo extra solamente, si lo haces bien y funciona, bacán, pero si el juego y la tarea falla debido a tu interfaz habrá descuento a no ser que justifiques estas posibles fallas en el readme.

**Comment by Meaylwin** [comment]
gracias @fgvenegas

**Comment by tamycova** [comment]
@stephichau  hazlo con os.listdir(".") pero como retorna lista tienes que pasarla a tu estructura de datos

**Comment by gbordoni** [comment]
se puede usar la libreria random?

**Comment by negebauer** [comment]
@gbordoni para qué?

**Comment by gbordoni** [comment]
random.randint para generar un numero aleatorio?

**Comment by tamycova** [comment]
@gbordoni sí

**Comment by perojas3** [comment]
¿Para que se usa la libreria time?
Digo, funciona con un sistema de time tuple, y las tupas estan prohibidas.

**Comment by stephichau** [comment]
se puede usar try y except?

**Comment by fgvenegas** [comment]
Para que utilizarias try y except? (si se lo que hacen, por lo mismo se específica en tu respuesta)

**Comment by Mieynaudi** [comment]
Hola, 
se puede usar la libreria copy? para utilizar el metodo deepcopy sobre las estructuras de datos en mi programa

**Comment by rodolfopalma** [comment]
Sí, se puede usar copy.

**Comment by vbarros2** [comment]
Como se puede usar os, se puede usar os.listdir??

**Comment by agmardones** [comment]
se puede usar max() y min() sobre una estructura de datos creada por mi?

**Comment by fgvenegas** [comment]
@vbarros2  se ha respondido eso en bastantes issues ya.

**Comment by aaossa** [comment]
@agmardones: Sí, puedes usar max y min sobre tus edds. Recuerda que deberás escribir el código correspondiente a esto en las clases

**Comment by agmardones** [comment]
@aaossa Sorry, no caché el comentario, te refieres a lo que debiese tener implementado en mis clases para que funcione el max() y el min()?

**Comment by aaossa** [comment]
@agmardones  Me refiero a que para que lo que quieres hacer funcione debes definir cierto(s) método(s) en tu clase
