### ISSUE TITLE
[T02][On Move Ended]

### ISSUE THREAD

**Issue by vbarros2** [IIC2233-2016-1/syllabus#179]
Probé la función on_move_ended pero no me funciona, lo que hago es llamar a una función para mover un hexágono para abajo y luego con un on_move_ended llamar a otra función y mover lo para el lado. Lo que ocurre es que me corre ambas a la vez y tira error.

Para ver si yo estaba mal cree dos funciones que quitan la pieza del 0,0 y luego agregan una nueva; al llamar a una y luego a la otra con on_move_ended se me cae el programa por lo mismo.

Hay alguna forma especifica de usar esta función, y por eso no me funciona??

Muchas Gracias

**Comment by otro-felipe** [comment]
Seria muy util si escribieras cual es el codigo del error.
Ojo que el parametro on move ended recibe un **objeto funcion**. Es decir, el nombre de la funcion sin parentesis.

``` python
def move_ended():
    print("termino")

gui.move_piece(on_move_ended=move_ended, ...)
```

**Comment by vbarros2** [comment]
Perfecto, eso era. Mi función tenia atributos, esto no se puede?

**Comment by otro-felipe** [comment]
No, la funcion no recibe ningun parametro (si te fijas toda la informacion se la das tu al momento de crear la funcion, no necesita nada mas).

**Comment by Hernan4444** [comment]
Pero yo acabo de hacerlo con atributos y si me funciono .-. (y los atributos era otro movimiento con otra función en sus atributos)
sera suerte?

**Comment by otro-felipe** [comment]
atributos (asi como variables dentro del codigo) esta bien, pero parametros como `def funcion(p1, p2, ...)`: no se deberian poder.

**Comment by Hernan4444** [comment]
aaa dale gracias :D

**Comment by aaossa** [comment]
Recuerda que si la respuesta te sirvió y/o tu problema está resuelto **cerrar la issue** :grin:
