### ISSUE TITLE
Uso del módulo OS de Python

### ISSUE THREAD

**Issue by sormazabal** [IIC2233-2016-1/syllabus#18]
Hola!
¿Se puede usar el módulo OS de Python para la tarea 1? (http://www.pythonforbeginners.com/os/pythons-os-module)

**Comment by tamycova** [comment]
Sí @sormazabal por lo que sé del módulo sí puedes usarlo! Si se me escapara alguna función que consideres que puede facilitarte mucho el cumplimiento de uno de los objetivos de la tarea entonces pregunta por acá, que función necesitas?

**Comment by sormazabal** [comment]
Muchas gracias @tamycova ! Lo estaba considerando para la parte de interacción con el usuario. Y además me surgió la duda por si es que lo podíamos usar en una actividad que evaluara la materia del tutorial de Codecademy.

**Comment by tamycova** [comment]
De nada! Las lecturas se evalúan en controles o pruebas escritas, si sientes que te podría ayudar para la interacción con el usuario feel free to use it :)

**Comment by jecastro1** [comment]
Ver #65
