### ISSUE TITLE
Uso de *args

### ISSUE THREAD

**Issue by agmardones** [IIC2233-2016-1/syllabus#180]
``` python
class Lista:
    def __init__(self, *args):
        if args:
                for item in args:
                        self.append(item) # Supongan que ya implementé append 
```

Está permitido hacer esto?

**Comment by otro-felipe** [comment]
Si te refieres a la tarea, sí está permitido. ~~creo que~~ no puedes cambiar el tipo de `args` por tu estructura de datos, suponiendo que implementaste append no deberia haber problema.
