### ISSUE TITLE
Entrega Tarea 2 

### ISSUE THREAD

**Issue by mjjunemann** [IIC2233-2016-1/syllabus#181]
Las personas que entregaron su tarea en una carpeta llamada **Tarea_01**, no tendrán descuento ya que se hizo un cambio de enunciado en la forma de entrega. Sin embargo, para la entrega de la Tarea 2 se especifica que la carpeta debe llamarse **T02**. Cualquier otro nombre de la carpeta tendrá una castigo en la nota, y lo más probable es que reciban una nota 1 en la primera instancia de corrección, ya que el script utilizado no recolectara su tarea. Por lo tanto, les pedimos que desde esta tarea en adelante sigan el formato **T0X** para nombrar sus carpetas.

Saludos, Matías.

**Comment by jecastro1** [comment]
### UPDATE

 A partir de la T02 (y la AC05) **no se admitirán recorrecciones por entregar en una carpeta distinta**. Por lo tanto, las entregas que no se hagan con el formato pedido recibirán un **1.0 definitivo**.
