### ISSUE TITLE
Duda __getitem__, __iter__

### ISSUE THREAD

**Issue by agmardones** [IIC2233-2016-1/syllabus#182]
En qué situación se llama a cada uno? Me surgió la duda al hacer:

``` python
for i in MyList:
    print(i)
```

Si no está implementado `__iter__`, llama a `__getitem__`. Cuándo se necesita si o si `__iter__`?

**Comment by otro-felipe** [comment]
Por lo que tengo entendido puedes obviar la existencia de `__iter__` y usar solo `__getitem__`, aunque `__getitem__` podria ser menos eficaz a la hora de iterar, ya que cada vez estas buscando la posicion i para retornarla, en cambio con `__iter__` haces la iteración dentro de un metodo que "recuerda" la última posición donde estaba, por lo que retornar el siguiente elemento es simple.

Tambien supongo que `__iter__` es util a la hora de tener una estructura de datos como un diccionario en que las llaves son strings, por lo que deberias definir tu propio `__iter__` para que el `for i in my_dict:` tenga sentido.

**Comment by agmardones** [comment]
Gracias de nuevo, felipin <3 @MainScientist

**Comment by tamycova** [comment]
@agmardones si estas contento con la respuesta puedes cerrar la issue? asi no se acumulan

**Comment by agmardones** [comment]
sorry, se me había pasado
