### ISSUE TITLE
Problema con PYQT4

### ISSUE THREAD

**Issue by dasotosilva19** [IIC2233-2016-1/syllabus#183]
Hola, al tratar de probar los módulos dados y ver como funcionan, al principio no pude ejecutar ningún código de prueba por que python me decía que no tenia el módulo instalado. Busque el PYQT4 y lo instale pero ahora al probar el código, el error que me arroja es el siguiente:

Traceback (most recent call last):
  File "C:\Users\daniel\Documents\puc tareas\progra avanzada\tareas\T02\Enunciado\main.py", line 1, in <module>
    import gui
  File "C:\Users\daniel\Documents\puc tareas\progra avanzada\tareas\T02\Enunciado\gui__init__.py", line 1, in <module>
    from PyQt4.QtGui import QApplication
ImportError: DLL load failed: %1 no es una aplicación Win32 válida.

La verdad no se si este error se de por algún error de instalación de mi parte o no, pero no puedo hacer mucho de la tarea si no puedo hacer correr estos módulos cuando los necesite

**Comment by aaossa** [comment]
Buscando un poco en Google di con esto, asumiendo Windows:

Descarga para tu versión de Python(3.4) y tu sistema operativo (32 o 64 bits) de PyQt4 de [esta página](http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyqt4) el archivo `.whl` correspondiente. Este archivo te permitirá instalar PyQt usando el comando `pip install archivo.whl` en la misma carpeta en la que se encuentre el archivo. Esto debería permitirte usar PyQt4. Pruebalo y dime que tal te va.

**Comment by aaossa** [comment]
Cerraré esto, cualquier otra duda sobre la instalación y el setup preguntala en [la issue que creamos específicamente para estos problemas](https://github.com/IIC2233-2016-1/syllabus/issues/169) #169
