### ISSUE TITLE
Donde se retorna cuando alguien hace clic

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#185]
Esto viendo como seleccionar un hexagono. De tal manera que seleccionando, se seleccionen los otros 2 nesesarios, y se deseccionen las ya seleccionados. Pero no encuentro la parte del codigo que retorna el espacio que se clikeo ni el lugar del hexagono que se clikeo.
Tampoco encuentro el comando para seleccionar o deseleccionar un hexagono.
Como cada vez que hacemos un click y movemos el mouse se imprime algo. Busque los print en el codigo que venia, pero no encontre ninguno en los modulos de gui. ¿Me podrian ayudar?

**Comment by Hernan4444** [comment]
revisa el modulo "demo.py" ahí esta la interfaz que tiene esos print.

**Comment by perojas3** [comment]
Gracias.
