### ISSUE TITLE
¿Como utiizo el "getpiece(int i, int j)"?

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#186]
En el pdf dice que existe ese metodo para seleccionar una piesa, pero lo utilizo en el demo.init y no pasa nada.

**Comment by otro-felipe** [comment]
Este método **retorna un objeto Piece**. No selecciona una determinada pieza, sino que retorna un objeto de clase `Piece` que corresponde a la pieza en esa posición. Un ejemplo para mostrar como seleccionada la pieza en la posicion 0,0 sería así:

``` python
piece = gui.get_piece(0, 0)
piece.selected = True
```

**Comment by perojas3** [comment]
Eso hago, pero lo hago en el demo.py
¿Se hace en alguna otra parte?

**Comment by otro-felipe** [comment]
No entiendo tu pregunta, puedes utilizar ese método en cualquier parte en donde hayas importado el módulo gui.

**Comment by perojas3** [comment]
Ok, creo que entiendo entonces.

**Comment by FernandoPieressa** [comment]
Yo tengo una duda respecto a eso, que deberia poner si quisiera retornar por ejemplo el tipo de pieza que es?, es decir si pongo piece = gui.get_piece(0, 0) despues me retorne el color de ese objeto pieza o si es una estrella, o bomba, etc... Lei los archivos gui y la clase pieza no tiene ningun atributo de tipo, sino que los saca de una clase de variables

**Comment by lampuerov** [comment]
Una pregunta referente a tu primera respuesta MainScientist. 

Una vez que haces piece.selected = True, la pieza en la posición (0,0) debería aparecer marcada con blanco en sus bordes en la interfaz? Lo pregunto porque trato de hacer introducir 3 bollean de este estilo en mi game_interface.py, en el método piece_section_entered() de la clase, para que queden 3 piezas marcadas con los bordes blancos pero no pasa nada tampoco, y tengo importada la librería gui en este archivo.
