### ISSUE TITLE
Como guardar los boards en una carpeta especifica

### ISSUE THREAD

**Issue by FernandoPieressa** [IIC2233-2016-1/syllabus#187]
Hola, tengo todo lo relacionado con la Tarea 2 en una carpeta, dentro de esa carpeta hay otra carpeta llamada boards, como puedo guardar los tableros que cree dentro de esa carpeta? porque sino me los crea en el mismo lugar que donde se encuentre el archivo python

**Comment by Geeermy** [comment]
Hola! Cuando creas el archivo, en vez de entregarle el nombre, entrégale la ruta que quieres. En tu caso:
`open('boards/tablero.txt','w')`
Pruébalo y me dices si funciona.
Saludos!

**Comment by FernandoPieressa** [comment]
Si funciona, muchas gracias!
