### ISSUE TITLE
Borrar piezas de la GUI

### ISSUE THREAD

**Issue by otro-felipe** [IIC2233-2016-1/syllabus#188]
Faltó poner en el enunciado que las piezas también tienen un método para ser borradas del tablero. Este método es `deleteLater()`. Por lo tanto si quiero borrar la pieza que está en la posición (0,0) debo realizar lo siguiente:

``` python
piece = gui.pop_piece(0, 0)
piece.deleteLater()
```

Saludos.

_Edit: Al parecer yo soy muy ciego y no lei que esto estaba como una footnote en el enunciado, pero nunca esta de más una pequeña recomendacion extra_

**Comment by criscv94** [comment]
@MainScientist No entendí cual es la diferencia entre pop_piece() y deleteLater(), la primera también la quita del tablero o no? Como funciona cada una?

**Comment by otro-felipe** [comment]
con `pop_piece(i, j)` borras la **referencia** que tiene el tablero de la posición (i, j) y retorna la pieza que habia en esa posición. Como que desanclas la pieza de la gui, así, si haces `get_piece(i, j)` despues de `pop_piece` te va a retornar None, porque al hacer pop la gui cree que ya no hay pieza en esa posición. Esto es importante para mover las piezas, ya que si la gui cree que hay una pieza en (i, j), no te va a dejar mover ninguna pieza ahi. El método `deleteLater()` borra **la pieza entera**, pero no su referencia. Es decir, la pieza no sera visible y no podras usar ninguno de sus metodos, pero si no usas `pop_piece`  en la posicion de la pieza que vas a eliminar, el metodo `get_piece` te va a seguir retornando la pieza eliminada.

**Comment by perojas3** [comment]
Trato de hacerlo. Pero me tira un error:

```
  File "C:\Users\Pablo\Desktop\Progra avanzada github\perojas3-iic2233-repo\Tareas\T02\gui\grid.py", line 73, in movePiece
    piece.row = row
AttributeError: 'NoneType' object has no attribute 'row'
```

**Comment by otro-felipe** [comment]
Estás pasándole `None` como parámetro a un método de la gui (`addPiece` o `movePiece`).

**Comment by lampuerov** [comment]
Me tira el mismo error que perojas3, y no estoy haciendo ni add_piece() ni move_piece(). A qué otra cosa se puede deber?

**Comment by agmardones** [comment]
A lo que le estás tratando de hacer .deleteLater() es ```None```, según yo esto es por como actualizas las cosas en la grid (no sé como las guardas), al menos por mi parte, cuando borro una pieza, hago ```pieza = gui.pop_piece(posicion)```, seguido de  ```,pieza.deleteLater()```, (el orden de éstos creo que da igual, luego actualizo la posición en mi grid como "sin pieza" ). Ojalá te sirva!
