### ISSUE TITLE
Obtener tipo pieza add_piece

### ISSUE THREAD

**Issue by ManuelSIlvaCav** [IIC2233-2016-1/syllabus#189]
Cuando se eliminan piezas del tablero y caen nuevas mediante add_piece, existe alguna forma de retornar el tipo de la pieza que se crea random? esto para poder guardarlo y saber el tipo de pieza con la que haacer referencias.
Grax!

**Comment by otro-felipe** [comment]
No existe forma de obtener el tipo de pieza mediante la gui, esto lo debes manejar tu, usando tu estructura de datos.

**Comment by perojas3** [comment]
¿Y como detecto cual es el random que se creo?

**Comment by otro-felipe** [comment]
Puedes hacer el random antes de agregar la pieza, guardarlo en una variable y esa variable usarla para agregar hexágonos a la interfaz.
