### ISSUE TITLE
Asumir input correctos

### ISSUE THREAD

**Issue by cabarra** [IIC2233-2016-1/syllabus#19]
¿Puedo asumir que la persona que use y revise el programa ingresará de forma correcta los datos (que no intentará botar el programa)?

**Comment by robocop6** [comment]
![No](http://i0.kym-cdn.com/entries/icons/original/000/007/423/untitle.JPG)

Saludos!

**Comment by negebauer** [comment]
![No](http://i0.kym-cdn.com/entries/icons/original/000/007/423/untitle.JPG)

**Comment by aaossa** [comment]
Trata de ponerle nombres no tan genericos a las issues, sino todas las preguntas de la tarea 1 se llamarían igual :stuck_out_tongue: 

Creo que ya te quedó clara la respuesta por parte de @robocop6 y @negebauer jajaja
