### ISSUE TITLE
Castear

### ISSUE THREAD

**Issue by spiza** [IIC2233-2016-1/syllabus#190]
Hola! Dos preguntas (condicionales)

1) puedo hacer que mi estructura de listas castee una lista? (Vale decir lista = MiLista(string.split(" ")))

2) si no se puede, qué método es el que me permite Castear cosas? Como se llama?

Gracias :)

**Comment by gafigueroa** [comment]
Mira lo que puedes hacer, es ocupar como referencia la issue #180.

``` python
class Lista():
    def __init__(self,*args):
        for i in args:
            print("Mi argumento es {0}".format(i))
a = Lista(*"Mi oracion de strings".split(" "))
b = Lista("Mi oracion de strings".split(" "))
```

Lo que ocurre en este trozo de codigo, esque `*args`  es una lista de argumentos, y si tu cuando pasas una lista como argumento de una **clase o función**, puedes ocupar el \* para que lo que contiene la lista, sea pasado como argumentos por separado. 

Si te cuesta ver esto, un ejemplo mas directo es: 

``` python
print(*"Mi oracion de strings".split(" "))
print("Mi","oracion","de","strings")

print("Mi oracion de strings".split(" "))
```

Los dos primeros son equivalentes, donde `print(arg1,arg2,arg3, ... argn)` es equivalente a `print(*lista)`.

Espero te sirva esto

**Comment by spiza** [comment]
Buena buena.. o sea, se pueden castear las listas a listaspropias siempre y cuando los argumentos de las listas se pasen como *args, y no como lista en sí misma
