### ISSUE TITLE
Lectura tableros .txt

### ISSUE THREAD

**Issue by andersskog** [IIC2233-2016-1/syllabus#191]
Hola! Se puede usar:

`lineasdedata = data.readlines()`

para leer los archivos? Esto crea una lista, por eso la pregunta.. Si no se puede, cual es la solución a esto?

**Comment by spiza** [comment]
Si no se puede, entonces lee línea por línea.

Saludos

**Comment by andresfdezc** [comment]
Una alternativa es leer línea por línea y almacenar cada string en una estructura de datos que tú hayas definido.
