### ISSUE TITLE
Estructuras en el return de funciones

### ISSUE THREAD

**Issue by vectorcrumb** [IIC2233-2016-1/syllabus#192]
El no poder usar las estructuras de datos internas de python nos limita al momento de usar funciones que retornen objetos como listas, tuplas o diccionarios. Por ejemplo no podremos usar funciones que retornen dos o mas valores empaquetados en un tupla?

**Comment by gafigueroa** [comment]
Si puedes retornar dos o mas objetos, pero siempre y cuando la estructura en la que estan almacenados estos objetos la hayas creado tu.
Por ejemplo tienes la clase MiLista

``` python
retornar = MiLista()
retornar.append(objeto1)
retornar.append(objeto2)
return retornar
```

**Comment by gafigueroa** [comment]
Creo había entendido mal tu pregunta.
Si puedes utilizar funciones de python que retornen listas o tuplas, pero lo que tienes que hacer es después castear ese resultado en tus propias listas.

En la issue #190 dije como se puede hacer para castear una lista en el caso de la función `split()`, eso mismo lo puedes hacer con otras funciones que retornen una estructura.

**Comment by vectorcrumb** [comment]
Ok, entonces el procedimiento estándar es desempaquetar las listas y diccionarios de inmediato mediante el uso de `*args` y `*kwargs` para evitar tratar con esas estructuras fuera de argumentos a funciones?

Preferimos esto:

``` python
class MyDict:
    def __init__(self, a, b, c):
        self.a = a
        self.b = b
        self.c = c

data = {'a': 1, 'b': 2, 'c': 3}
my_dict = MyDict(**data)
```

Antes que esto?

``` python
class MyDict:
    def __init__(self, datos):
        try:
            self.a = datos['a']
            self.b = datos['b']
            self.c = datos['c']
        except KeyError:
            pass

data = {'a': 1, 'b': 2, 'c': 3}
my_dict = MyDict(data)
```
