### ISSUE TITLE
conseguir tipo pieza

### ISSUE THREAD

**Issue by FernandoPieressa** [IIC2233-2016-1/syllabus#194]
que deberia poner si quisiera retornar por ejemplo el tipo de pieza que es?, es decir si pongo `piece = gui.get_piece(0, 0)` despues me retorne el color de ese objeto pieza o si es una estrella, o bomba, etc... Lei los archivos gui y la clase pieza no tiene ningun atributo de tipo, sino que los saca de una clase de variables

**Comment by otro-felipe** [comment]
No se puede retornar el tipo de la pieza usando la gui ese tipo de datos los deben manejar ustedes en sus estructuras de datos. Esto ya fue preguntado aqui #176 y aqui #189. Por favor busquen sus preguntas en las issues antes de hacerlas.

**Comment by FernandoPieressa** [comment]
Perdon, no habia visto la 176 y la 189 pense que se referia a otra cosa
