### ISSUE TITLE
Duda con atributos interfaz

### ISSUE THREAD

**Issue by agmardones** [IIC2233-2016-1/syllabus#195]
No entiendo bien la relación de la gui y la interfaz:

Tengo creada la grid correspondiente a cada juego y quiero asignársela a la interfaz (debería?). Cuando intento algo como:

``` python
import gui
from gui.variables import variables
def create_grid():
    ...
    return grid
class MyInterface(gui.GameInterface):
    grid = None
...
...
interfaz = MyInterface()
interfaz.grid = create_grid()
gui.set_game_interface(interfaz)
gui.run()
```

Al momento de pasar el mouse por alguna pieza y llamar a `piece_section_entered` (dentro de ella intento iterar sobre la grid) me dice que MyInterface.grid es None
Lo otro que intente fue:

``` python
import gui
from gui.variables import variables
def create_grid():
    ...
    return grid

class MyInterface(gui.GameInterface):
    grid = create_grid()
...
...
gui.set_game_interface(MyInterface())
gui.run()
```

o 

``` python
import gui
from gui.variables import variables
class MyInterface(gui.GameInterface):
    grid = None
...
   def create_grid(self):
        ...
        MyInterface.grid = grid # Generada por la funcion
...
gui.set_game_interface(MyInterface())
gui.run()
```

En ambos casos, al llamar a la función mencionada antes, recibo este error:

``` python
    __game.addPiece(i, j, piece_type, on_move_ended, number)
AttributeError: 'NoneType' object has no attribute 'addPiece'
```

Espero se entienda lo que estoy intentando hacer, quiero tener la grid para poder iterar en las funciones de la interfaz.

**Comment by otro-felipe** [comment]
El error me hace pensar que no usaste el metodo `gui.init()`. Verifica que este metodo sea llamado antes de empezar a agregar piezas a la gui.

**Comment by agmardones** [comment]
Sí, lo puse antes de la definición de la clase de interfaz. Gracias @MainScientist
