### ISSUE TITLE
Se puede usar la libreria os?

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#196]
Es que estoy en la parte de usar de dar la opcion de cual tablero en la carpeta boards seleccionar para ser leida.
Y la libreria os tiene comandos para poder hacer eso. Sin embargo no esta mencionado en: https://github.com/IIC2233-2016-1/syllabus/issues/178
En el caso de estar permitido, ¿Se admite el uso de `os.listdir()`? Es que genera una lista con las opciones.
Y en el caso de no estar permitido. ¿De que otra forma puedo leer los archivos .txt dentro de una carpeta?

**Comment by fgvenegas** [comment]
Si, puedes utilizarla, recuerda que todas las preguntas relacionadas a librerias hay que hacerlas en #178, asi mantenemos el orden y evitamos issues demás

**Comment by perojas3** [comment]
ok, gracias.
