### ISSUE TITLE
Prioridad figuras

### ISSUE THREAD

**Issue by andersskog** [IIC2233-2016-1/syllabus#197]
Al importar un tablero, existen varías formas de revisar que figuras existen. Se podría analizar de abajo hacia arriba o por prioridad de las figuras, por ejemplo formar un star en vez de un cluster que se encuentra por debajo. Esto también ocurre cuando hacemos un movimiento, se destruyen ciertas piezas y caen las piezas respectivas.

De que manera debemos hacer este análisis de figuras existentes??
Gracias!

**Comment by tamycova** [comment]
Como no está en el enunciado, hazlo de la forma que más te acomode y especifícalo en el README, ojalá que haya una lógica clara detrás de la decisión.
