### ISSUE TITLE
Referencias externas

### ISSUE THREAD

**Issue by vectorcrumb** [IIC2233-2016-1/syllabus#198]
En el caso que leamos al respecto de alguna estructura de dato y luego decidamos implementarla, es necesario agregar el sitio web, libro, articulo, etc. donde nos informamos al respecto de dicha estructura? Mi duda es principalmente orientada a estructuras como los linked lists, donde es muy difícil implementarlas de una manera distinta a las cuales se enseñan en diversas publicaciones.

**Comment by tamycova** [comment]
cítala, pero lo ideal es que hagas tus propias implementaciones, siempre puedes agregarle un toque personal en funcionalidades :)
