### ISSUE TITLE
Métodos en MyInterface (y no modificar modulos entregados?)

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#199]
El enunciado dice que tenemos que hacer override de todos los métodos de la clase GameInterface y nada más, pero podemos agregar más métodos para hacer todos lo que nos piden y nos parezca necesario, ¿verdad? Pregunto por si acaso, en caso de que de verdad sea tan estricta el sentido de esa oración.

Mi otra duda un poco más práctica es sobre los modulos entregados ¿estos son fijos, es decir, no debemos modificarlos de forma alguna ninguno de ellos o es posible?

**Comment by otro-felipe** [comment]
No es estricto el sentido de esa oracion. Puedes agregarle mas métodos a la `GameInterface`, sin embargo (para el correcto funcionamiento de la tarea), debes hacer override de todos los que salen en el enunciado.

No deben modificar los archivos que les pasamos ¿Que quieres modificar de ellos?

**Comment by MortizDX** [comment]
Ok, comprendo.

Tenía la idea de agregar a la clase Piece las coordinadas que se encuentra en el tablero, pero pensandolo mejor no es necesario. Igual prefiero preguntar ese tipo de cosas por si acaso para evitar problemas.

**Comment by otro-felipe** [comment]
Ah, no no puedes hacer eso, ya que la idea es que toda esa informacion (posicion, tipo) la manejen ustedes.

**Comment by Hernan4444** [comment]
solo para confirmar, si le puedo agregar mas métodos a la interfaz, le puedo agregar el método init?

[edit] Perdon, ya respondieron eso en otro issues

**Comment by Nebula2028** [comment]
Puedo cambiar la línea 28 del modulo grid.py ?
28    def initUI(self):
29        self.setFixedSize(98_variables.SCALE_7.9, 91_variables.SCALE_9)

Cambiar el 91 por 71 por que asi me cabe la ventana del juego en la pantalla del notebook. (El comando set_scale no me sirve ya que este solo modifica el tamaño de las piezas, no de la ventana del juego)

**Comment by negebauer** [comment]
**No puedes modificar los archivos entregados**
Revisa las issues #200 y #175
