### ISSUE TITLE
Duda python

### ISSUE THREAD

**Issue by Pochoclo** [IIC2233-2016-1/syllabus#2]
Hola, tengo instalado python 3.5 en el mac y la verdad no se como instalar python 3.4 (me está dando problemas)
https://fbcdn-sphotos-c-a.akamaihd.net/hphotos-ak-xlt1/v/t34.0-12/12784812_598605070286675_1532738643_n.jpg?oh=4c211097baaa57f30f610c03e2693610&oe=56DAC876&__gda__=1457120720_138e9b8894e85c56489683be582c6977

agradecería si me pueden ayudar!

**Comment by andresfdezc** [comment]
Una forma bruta de hacerlo es desinstalando Python 3.5 si es que tienes [Homebrew](http://brew.sh/) con

`brew uninstall --force python3`

Luego, puedes instalar el release de Python 3.4.4 descargándolo desde [aquí](https://www.python.org/downloads/release/python-344/).

**Comment by Pochoclo** [comment]
Gracias!
