### ISSUE TITLE
Dimensiones del tablero

### ISSUE THREAD

**Issue by wayoalamos** [IIC2233-2016-1/syllabus#200]
El tablero del pdf tiene hasta la fila 8 (la cual va intercalada, solo los con columna impar). Pero al intentar agregar la fila 8 me arroja error list index out of range, creo que el problema es del gui. O estoy teniendo un problema con mi codigo?

**Comment by spiza** [comment]
Son 9 columnas, de distinto tamaño. Revisa el example.txt.

Saludos 

Enviado desde mi iPhone

**Comment by lampuerov** [comment]
Hola!

Tengo un problema con las dimensiones de la interfaz, no cae en mi pantalla con las piezas incluidas. 

En la página 3 del enunciado de la tarea sale especificado que utilicemos el método set scale(float scale): para cambiar el tamaño de la interfaz. Sin embargo, al usar un float scale = 0.4, el único cambio que noto es en el tamaño de las piezas y no en el tamaño de la interfaz.

A continuación muestro lo dicho:

1) Al usar float scale por defecto, es decir, igual a 1
![image](https://cloud.githubusercontent.com/assets/16274933/14241053/cdf2d48c-fa1f-11e5-8be1-0ea683bdb700.png)

2) Al querer cambiar el tamaño de la interfaz, con un float igual a 0.4:
![image](https://cloud.githubusercontent.com/assets/16274933/14241097/174ae6f6-fa20-11e5-94f0-d65970b52995.png)

Se puede ver que el problema persiste y no puedo ver todas las piezas. Qué pasó?, cómo cambio el tamaño de la interfaz realmente?

**Comment by lampuerov** [comment]
Me respondo solo, el cambio se debe hacer en self.SCALE, en el documento variables.py para cambiar el tamaño de la interfaz completa, y no es set_scale como se detalla en el enunciado.

Saludos

**Comment by otro-felipe** [comment]
esto ya fue respondido. Debes llamar a `gui.set_scale()` **antes** del metodo `gui.init()`.

**Comment by lampuerov** [comment]
Gracias, me sirvió

**Comment by aaossa** [comment]
Dupe #175
