### ISSUE TITLE
Tarea 02 Rotacion

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233-2016-1/syllabus#201]
Tengo una pregunta, basado en Hexic, un juego muy parecido al creado por Bucchi. En el juego se rotan las piezas 3 veces en el caso de que no produzcan ningún cambio, para volver a su posicion original.
El problema que tengo es que en nuestro juego cuando hago que rote 3 veces, en la interfaz no se ve la animación de que roto 3 veces, como que lo hace de forma interna y el resultado lo muestra en el juego. ¿¿¿esta bien que haga eso lo tengo que encontrar alguna forma de que muestre la animación de las 3 veces??? si es así, es posible alguna pista, he intentado varias formas pero nada funciona....incluso le pongo alguna función en "on_move_ended" como esperar 2 segundos entre el movimiento de la ultima pieza en una rotación y el movimiento de la primera pieza de la segunda rotación, pero de todos modos no me muestra la animación de eso.
alguna ayudita??
Nota: rotacion en mi caso es mover las 3 piezas de forma seguida

**Comment by otro-felipe** [comment]
Verifica que no tengas las animaciones desactivadas y recuerda que al poner un método como parámetro de otro método lo debes hacer sin parénteses.

**Comment by Hernan4444** [comment]
lo hice así, animación activadas y método esta sin paréntesis, pero de todos modos no me funciona.
cuando solo pido una rotacion, primero rota y luego me llama a la funcion que hace que espere 2 segundos. cuando debe rotar mas de 1 vez, hace todo de forma interna y luego me hace esperar los 2 segundos

**Comment by otro-felipe** [comment]
La segunda rotación debe ir en el método on_move_ended. Algo así:

``` python
def rotar_otravez():
    # Verificar figuras
    # Rotar hexagonos
    pass

# Rotar hexagonos
gui.move_piece(i, j, ultimo_hexagono_rotado, on_move_ended=rotar_otravez)
```

**Comment by Hernan4444** [comment]
Grande!!! me salio :tada: :smile:  Muchas gracias!!

**Comment by sormazabal** [comment]
Tengo el mismo problema: me  muestra en los prints que las piezas cambiaron de lugar, pero no se muestra en el tablero. Le puse lo de on_move_ended=rotar_otravez y aún así no muestra nada. :S

**Comment by otro-felipe** [comment]
no tienes por casualidad las animaciones desactivadas?

**Comment by perojas3** [comment]
No entiendo. Si devo mover 3 hexgonos, cada uno 3 veces. ¿Que pongo en  on_move_ended= si al hacerlo con uno, devo esperar a que pase con los otros? ¿En cual de los 3 devo hacer que revise el tablero, y como evito que lo revise 3 veces?
¿Porque no deve tener parametros, y si no tiene parametros, como la funcion rotar_otraves save con que parametros trabajar?

**Comment by otro-felipe** [comment]
No tiene parametros porque asi fue programada la interfaz. La funcion rotarotravez la creas dentro de cierto scope y, por lo tanto, comparte las variables de ese scope, por eso no necesita recibir parametros.

**Comment by otro-felipe** [comment]
Con respecto a tus primeras dos preguntas, esos son problemas que debes resolver en tu tarea.

**Comment by sormazabal** [comment]
@MainScientist  Ya lo arreglé! Tenía que updatear mi lista de nodos ;D Gracias!

**Comment by perojas3** [comment]
Pero a lo menos dime bien que hace `rotar_otravez`. ¿Como funciona especificamente  `on_move_ended=`? Porque con lo que tengo no veo posible hacer girar 3 al mismo tiempo y luego detenerme a revisar.

**Comment by Hernan4444** [comment]
`on_move_ended=` recibe una función sin paréntesis, la cual después de terminar el movimiento que estaba haciendo, va a ejecutar esa funcion

`rotar_otravez` deberia ser una funcion que toma las 3 piezas que ya fueron rotadas, evalua la situacion y las vuelve a rotar si es necesario

**Comment by perojas3** [comment]
Osea, puedo solo ponerle `on_move_ended=` al ultimo y me deveria funcionar?

**Comment by Hernan4444** [comment]
sip, te deberia funcionar como a mi. Igual tu pregunta se responde probandolo y listo :D

**Comment by perojas3** [comment]
Es que me pasa este gran problema, si la funcion rotar otra vex no tiene parametros, ¿Entonces como esta puede saber cuales deveria rotar? ¿Como le entrego las cordenadas?

**Comment by otro-felipe** [comment]
La función `on_move_ended` no se le entrega ningún parametro cuando es llamada dentro de la gui, por lo que aunque intentes ponerle parámetros, la gui no te los va a entregar.

**Recuerda que al crear un método, éste comparte las variables del scope en que fue creado**. En otras palabras, puedo hacer lo siguiente:

``` python
def metodo(parametro_random):
    def funcion():
        print(parametro_random)
    no_gui.metodo(on_move_ended=funcion)
```

Como ves, la funcion `funcion` no recibe ningún parametro, sin embargo, puede usar los que vienen de la función `método`.

**Comment by perojas3** [comment]
¿Puedo crear funciones dentro de funciones?

**Comment by otro-felipe** [comment]
Sí, python lo permite y está permitido hacer uso de esta funcionalidad en la tarea.
