### ISSUE TITLE
[T02][Asignar variables]

### ISSUE THREAD

**Issue by vbarros2** [IIC2233-2016-1/syllabus#202]
Se puede asignar a cada nodo del tablero una determinada variable?

**Comment by otro-felipe** [comment]
¿Te refieres a algo así?

``` python
hexagono00 = "rojo"
hexagono01 = "verde"
```

**Comment by vbarros2** [comment]
Si, igual asignando las variables con dos for para ahorrar codigo.

**Comment by otro-felipe** [comment]
En la práctica puedes hacerlo, pero recuerda que en la tarea estamos evaluando estructuras de datos, por lo que si no representas la estructura del juego usando materia de EDD, vas a tener un  **descuento considerable** en toda esta parte.

Además de que tu nota se vera **fuertemente afectada** hacerlo de esta manera es una pésima práctica, programar y debuggear un programa con ese approach sería muy difícil,  tendrías que escribir mucho código y a la larga sería contra producente. Por lo que te sugiero **fuertemente** que **no lo hagas así**.

**Comment by vbarros2** [comment]
Perdón, no entendía bien la tarea todavia. Gracias
