### ISSUE TITLE
Tablero inicial

### ISSUE THREAD

**Issue by diegosapunar** [IIC2233-2016-1/syllabus#203]
Al iniciar con un tablero nuevo, pueden haber cualquier tipo de figura? (bombas por ejemplo)

**Comment by tamycova** [comment]
Si, por eso en los mapas guardados se especifíca el timer de la bomba.

**Comment by rmant** [comment]
Osea que cuando el usuario elige crear un tablero aleatorio este puede venir incluso con black_pearls?

**Comment by gbordoni** [comment]
Esta bien poblar el tablero con la expresion del demo "random.choice(variables.HEXAGON_TYPES)" para elegir una ficha al azar o no? Esta expresion selecciona bombas y otros o solo colores simples?

**Comment by otro-felipe** [comment]
No puedes usar la expresión directa, pero si puedes castear `variables.HEXAGON_TYPES` a tu propia estructura de datos y ahí, dependiendo de tu implementación, seleccionar un valor al azar. Ojo que hay más grupos de piezas que los que están en hexagon types.

**Comment by kcsss** [comment]
Existe alguna manera de obtener el tipo de un objeto Pieza, si dejo que el programa genere de forma aleatoria las piezas que voy a introducir, como puedo saber de que tipo son ?

**Comment by spiza** [comment]
Ya lo han respondido antes.. Se supone que detrás del telón debemos manejar en nuestras
Estructuras de datos el problema.

Saludos

Enviado desde mi iPhone
