### ISSUE TITLE
¿Una funcion puede retornar 2 variables?

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#204]
¿Esta permitido que una funcion retorne 2 cosas?
Es que al hacer eso, se genera una tupla si imprimes las funcion. Pero si la devuelves a 2 variables, es como entregar 2 valores a 2 variables distintas.
¿Esto cuenta como tupla?

**Comment by andresfdezc** [comment]
Hola! De forma general, sí se puede hacer lo que dices. Efectivamente la función retornará una tupla y puedes asignar cada elemento de dicha tupla de la siguiente forma:

`variable_1, variable_2 = funcion_que_retorna_tupla_con_dos_elementos()`

**Sin embargo, para la Tarea 2** tienes que entregar (castear) lo que retorne tu función a alguna de tus estructuras de datos propias. Los detalles de esto están en la issue #178 .
