### ISSUE TITLE
piece_clicked retorna seccion 7

### ISSUE THREAD

**Issue by andersskog** [IIC2233-2016-1/syllabus#206]
Al utilizar esta función, ocasionalmente me devuelve seccion = 7. Que puedo hacer para solucionar este error?

**Comment by otro-felipe** [comment]
¿A qué te refieres con seccion = 7 en `get_piece`? La información de la sección sólo es entregada a en el método `piece_section_entered` en la `GameInterface`.

**Comment by ManuelSIlvaCav** [comment]
a mi igual me salio en su momento seccion = 7 pero cuando se llamaba el metodo piece_clicked, era derrepent como para que no se spamiara una pieza :c

**Comment by andersskog** [comment]
si perdon era piece_clicked. Al apretar muchas veces una pieza devuelve seccion = 7.

**Comment by agmardones** [comment]
A mi igual me pasa :(, creo que puede llegar a ser ignorable en el caso de que nunca arroje sección 7 en la primera vez que se obtenga la sección (nunca me ha entregado sección 7 sin hacer click)

**Comment by otro-felipe** [comment]
Qué raro, no he podido hacer que me pase a mi :( ¿En qué circunstancias le retorna sección 7?

**Comment by otro-felipe** [comment]
¿Les pasa también con el demo? De todas formas en ningún momento del juego se debería poder clickear tanto una pieza, por lo que deberían controlar que cuando se clickee una pieza solo se inicie la rotación si no hay otra en curso.

**Comment by icontrerasn** [comment]
Retorna sección 7 cuando no se mueve el cursor después de llamar la función y luego se vuelve a llamar, es decir, dos clicks en el mismo lugar sin mover el cursor. ¿Qué hacemos en este caso? Yo por el momento estoy asumiendo que el usuario no hará esto.

**Comment by otro-felipe** [comment]
Ya caché, pueden asumir que el usuario no va a dejar el mouse quieto :)

**Comment by aaossa** [comment]
Discusion movida a #244
