### ISSUE TITLE
Registro de ayudantías en calendario

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#207]
Sé que en un aviso pasado dijeron que siempre habría ayudantía los Lunes a menos que se dijera lo contrario, pero normalmente había un registro de ellos en el README.md, en el calendario. Para hoy, 4 de Abril, aún no se agregado nada ¿no siempre se indicarán las ayudantías allí?

De forma más directa, la pregunta también va de si hay ayudantía hoy o no (y sobre qué en caso que haya).

**Comment by IsaacConDosA** [comment]
Sumandome a la pregunta; sería bueno que pusieran el día anterior si será necesario traer computador o no, por favor. Saludos

**Comment by andresfdezc** [comment]
Hola! Tal como se avisó **siempre** hay ayudantía, a menos de que se indique lo contrario. Hoy hay y no es necesario que lleven computador. Cuando se necesite les avisaremos, por supuesto.

**Comment by tamycova** [comment]
@ifcarrera  yo te recomiendo siempre llevarlo, así puedes participar/seguir más activamente la ayudantía! y comprobando por ti mismo las cosas, probando otras, etc.

**Comment by IsaacConDosA** [comment]
@tamycova Muchas gracias :smile:

**Comment by tamycova** [comment]
@MortizDX por favor cierra la issue si estas ok con la respuesta!

**Comment by MortizDX** [comment]
Sorry por la demora, muchas gracias por las respuestas a ambos.
