### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by Iruretagoyena** [IIC2233-2016-1/syllabus#208]
Qué debería pasar si el usuario hace click en, por ejemplo, la sección 4 de la ficha que esta en la esquina abajo a la derecha ?
a) Nada
b) Se ignora la sección y se marcan los dos adyacentes
c) Puedo asumir que no hará eso

**Comment by flobarrios** [comment]
Hola !! No deberia pasar nada (a). No puedes asumir que no pasara eso. Saludos!

**Comment by tamycova** [comment]
Revisa el juego que sale en el enunciado cuando juegas es claro lo que tiene que pasar (o no pasar).

**Comment by Iruretagoyena** [comment]
Muchas gracias ! @flobarrios @tamycova

**Comment by tamycova** [comment]
@Diiru cierra la issue si quedaste ok con la respuesta!
