### ISSUE TITLE
Actividad 2 commit a revisar

### ISSUE THREAD

**Issue by FernandoPieressa** [IIC2233-2016-1/syllabus#21]
Hola, tengo una duda sobre la actividad 2, recibí un mensaje del commit que seria revisado para la actividad 2 y me señala un commit a un readme. Yo no subí a git la actividad 2, pero mi compañero si, quería saber si aunque me salga en mi git que corregirán otra cosa, cuando revisen el de mi compañero también me contaran a mi con esa evaluacion.

Gracias

**Comment by jecastro1** [comment]
Hola,

El mensaje deja constancia de cuál fue tu último commit antes del término de la clase. Esto se hace para que sepan cual es el estado que nosotros vimos de su repositorio. 

Para los trabajos en grupo se tienen los siguientes casos:
- Mi compañero entregó y yo también: asegurarse que lo entregado sea igual, pues se revisará cualquier entrega.
- Mi compañero entregó: Se revisará el de tu compañero por los dos.
- Yo entregué: Se revisará tu entrega.

**Comment by FernandoPieressa** [comment]
Muchas gracias!
