### ISSUE TITLE
Animacion

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233-2016-1/syllabus#210]
Despues que se hace un movimiento y crear algunos grupos de piezas iguales que se destruyen, las piezas caen y se agregan nuevas pero  en ese momento mi programa detecta que se creo otro grupo (por las nuevas piezas que caen) que las destruye antes de ver ese grupo. ¿se puede dejar asi? y voy aumentando el puntaje o es necesario que se vea caer esas piezas nuevas y ahi recien que se vean como se destruyen y aumentan el puntaje?

**Comment by otro-felipe** [comment]
La idea del parametro `on_move_ended` es que puedan hacer el checking una vez que caen las piezas. Debes usar este metodo para que se entienda lo que pasa en tu tarea.

**Comment by tamycova** [comment]
Es necesario que se vea, sino podrías estar haciendo desaparecer piezas arbitrariamente y no tenemos como revisarlo @Hernan4444

**Comment by Hernan4444** [comment]
Oka, de todos modos ahora lo logre =D Gracias!!!
