### ISSUE TITLE
problemas import GUI

### ISSUE THREAD

**Issue by tblatrille** [IIC2233-2016-1/syllabus#211]
Hola! Tengo problemas con la interfaz de GUI, en teoría en PYCharm debería reconocerme GUI desde su archivo y al hacer gui. mostrarme sus métodos cosa que no sucede, no se por que esto no pasa, sino que me señala que existen referencias no resueltas
<img width="676" alt="captura de pantalla 2016-04-04 a las 8 26 07 p m" src="https://cloud.githubusercontent.com/assets/17602895/14267065/7d33d0b2-faa3-11e5-9acf-8faef4e81df5.png">

**Comment by negebauer** [comment]
Tienes que abrir la carpeta donde está el main de la tarea y debería arreglarse (ft. @andresfdezc)

**Comment by tblatrille** [comment]
@negebauer  No estoy seguro si entendí dices abrir el .py en en la misma carpeta que la carpeta gui?
De esta manera?
<img width="709" alt="captura de pantalla 2016-04-04 a las 8 36 53 p m" src="https://cloud.githubusercontent.com/assets/17602895/14267254/045d7510-faa5-11e5-81b7-bacf692e7b80.png">

**Comment by otro-felipe** [comment]
PyCharm tiene una maña. Debes hacer click derecho en la carpeta enuciado y poner Mark directory as... -> Sources Root.

**Comment by aaossa** [comment]
Recuerda que si la respuesta te sirvió y tu problema está resuelto puedes cerrar la issue :grin:
