### ISSUE TITLE
Enunciado GameInterface

### ISSUE THREAD

**Issue by JoseDaroch** [IIC2233-2016-1/syllabus#212]
Hola, tengo una duda respecto al archivo que contiene la clase GameInterface (en la carpeta gui)... tengo que modificar de alguna forma sus metodos o solo están como referencia para llamarlos desde otro modulo?, no me quedo muy claro del enunciado.
Gracias!

**Comment by flobarrios** [comment]
Hola !! No debes modificar esos métodos, debes llamarlos desde otro archivo. Fíjate como se usan en demo.py. Saludos!
