### ISSUE TITLE
[T02][Cargar Mapas]

### ISSUE THREAD

**Issue by vbarros2** [IIC2233-2016-1/syllabus#213]
En el example existen grupos de tres hexágonos del mismo color. En mi programa cuando inicio un juego nuevo no pueden haber estos grupos o si no después no sabría cuando eliminarlos, por lo que no puedo guardar un juego con estos grupos en el tablero. Espero me hayan entendido.

Muchas Gracias

VBarros

**Comment by tamycova** [comment]
@vbarros2  no entendí, no puedes asumir que los mapas van a venir sin figuras formadas (clusters, flores, etc).

**Comment by lampuerov** [comment]
Hola, 

Tengo un problema con la ubicación de los archivos .txt y con la forma en que los llamo para leerlos, acá dejo mi código y el error de consola:

`mapa_inicial = Mapa()
    inname = "mapa_juego.txt"
    with open(inname) as infile:
        for i in infile:
            mapa_inicial.escribirtxt(i)
            print(i)`
  File "C:/Users/Luis/repo-syllabus/syllabus/Tareas/T02/Enunciado/demo_mio.py", line 249, in <module>
    with open(inname) as infile:
FileNotFoundError: [Errno 2] No such file or directory: 'mapa_juego.txt'

Necesito una aclaración respecto al manejo de los archivos .txt, donde se guardan cuando los creo y como accedo a ellos. 
Debo aclarar que mi idea es crear una clase Mapa, que contenga un mapa actualizado del juego, para que cada vez que el usuario guarde un mapa, éste se guarde en una lista de mapas.

Saludos

**Comment by otro-felipe** [comment]
Si tienes dudas con respecto al manejo de archivos puedes ver la página 45 de [este documento](https://github.com/IIC2233-2016-1/syllabus/blob/master/Repaso-IIC1103/IIC1103-Python.pdf).

**Comment by lampuerov** [comment]
Ok, lo revisé, utilicé los métodos ahí especificados pero aún así me tira error en la consola :( 

'    matriz = open(inname, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'mapa_juego.txt'' '

Debe ser un problema de directorio. Gracias de todas formas

**Comment by otro-felipe** [comment]
Una cosa que no sale ahí y que podría serte útil es que si quieres escribir un archivo que no ha sido escrito antes, puedes hacerlo con "w+".

Otro problema es que los paths no son relativos al .py que los llama, sino que son relativos al .py que está corriendo. Quizás estás intentando abrir el archivo mapa_juego.txt sin tenerlo "al lado" del archivo py que estás corriendo.

**Comment by lampuerov** [comment]
Lo arreglé especificando el directorio donde está el mapa_juego.txt, traté de todo y fue lo único que funcionó.

Una última duda, cómo puedo especificar una carpeta "mapas" para que se guarden los .txt de los mapas guardados?

Saludos

**Comment by fgvenegas** [comment]
En la carpeta donde tienes el main.py que corre todo, puedes crear otra carpeta que se llame mapas y al momento de guardar el .txt haces

`open("./mapas/nuevo_archivo.txt")  # El "." indica que es el Path de la carpeta actual`
