### ISSUE TITLE
[T02] Error : 'module' object is not callable

### ISSUE THREAD

**Issue by fcorencoret** [IIC2233-2016-1/syllabus#214]
Cuando creo mis metodos para rotar los piece, me los rota correctamente (en la interfaz se rotan) pero me tira este error que no logro identificar porque ocurre. Ademas, el error ocurre en uno de los archivos que nos dan, por lo que no puedo debuggiar facilmente.

<img width="914" alt="screen shot 2016-04-04 at 10 52 18 pm" src="https://cloud.githubusercontent.com/assets/17628128/14269153/54dce738-fab8-11e5-91df-08c87452b80f.png">

Que eso me lleva a esta parte del codigo entregado

<img width="721" alt="screen shot 2016-04-04 at 10 56 30 pm" src="https://cloud.githubusercontent.com/assets/17628128/14269180/8836d044-fab8-11e5-9d69-7a3980c39755.png">

Que puede ser?

**Comment by otro-felipe** [comment]
El problema es que estás usando mal el parámetro `on_move_ended`. Recuerda que este parámetro recibe una **función**.

**Comment by caackermann** [comment]
Me pasaba lo mismo y era porque ocupaba:
`gui.move_piece(i=coord1, j=coord2, piece=pieza, on_move_ended=gui.pop_piece(coord3, coord4))` 
para eliminar la referencia en el mapa a la pieza que queria mover. Lo resolvi cambiando el metodo por
`gui.move_piece(i=coord1, j=coord2, gui.pop_piece(coord3, coord4))`

Por si sirve de algo
