### ISSUE TITLE
[T02] Heredar de clase piece

### ISSUE THREAD

**Issue by caackermann** [IIC2233-2016-1/syllabus#216]
Hola, dado que no se pueden modificar los modulos entregados, se puede crear una nueva clase que herede de alguna entregada? Especificamente, me gustaria hacer una clase que herede de Piece para agregar atributos/metodos.
Gracias

**Comment by otro-felipe** [comment]
En teoría puedes, pero ningún módulo de la gui tiene un método que reciba una pieza, por lo que aunque heredes de la clase `Piece`, no la podrás agregar a la gui.

**Comment by caackermann** [comment]
Ahh tienes razón. Gracias!
