### ISSUE TITLE
Override en métodos de MyInterface()

### ISSUE THREAD

**Issue by dasotosilva19** [IIC2233-2016-1/syllabus#217]
Hola, al hacer el override sobre los método de MyInterface, es posible agregar nuevos parámetros ?, o solo debo limitarme a los que son dados ? Quiero hacer algo con la información que entrega el método pero para hacer eso necesito agregar un parámetro demás a algunos métodos ? 
Saludos.

**Comment by otro-felipe** [comment]
Los parámetros en esos métodos no pueden ser cambiados. ¿Qué quieres agregarle exactamente?
