### ISSUE TITLE
Unas dudas de los controles del juego

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#219]
Desearia saber.
¿Que pasa al pasar el mouse por encima de un hexagono? Se selecciona o nada.
En el caso de que se seleccione, ¿Como retorno la fila y columna de la pieza en que se paso por encima?

Y con lo anterior, ¿Que pasa cuando se clickea? En el caso que se ejecute la rotacion. ¿Pasa como con este juego?
http://zone.msn.com/en/hexic/
Osea, se da la vuelta ensera, y comprueba en cada paso si pasa algo, y luego vuele a la normalidad, ¿O en sixphyx es posible solo hacer una rotacion?

**Comment by ManuelSIlvaCav** [comment]
piece.row y piece.column te tira la posicion de la pieza!

**Comment by gbordoni** [comment]
omg porque no sale eso en el enunciado?? ....

**Comment by otro-felipe** [comment]
Tal como dice @ManuelSIlvaCav tú puedes saber la columna y la fila de una pieza usando esos atributos. Cuando se clickea una pieza en nuestro juego pasa lo mismo que pasa en Hexic, se da la vuelta entera y chequea cada vez, si no pasa nada, vuelve a la posición inicial.

**Comment by gbordoni** [comment]
@MainScientist  y hay algun otro atributo de la clase pieza que NO salga en el enunciado? Por ejemplo uno que te diga que tipo/color de pieza es?

**Comment by otro-felipe** [comment]
No, se ha repetido en varios issues que **no** se puede saber el tipo de pieza por la gui, sino que deben manejar este dato ustedes usando sus estructuras de datos.

**Comment by perojas3** [comment]
¿Y que pasa al hacer click y pasar por encima?
No me han respondido eso
¿Se rota completo sí o no?

**Comment by ManuelSIlvaCav** [comment]
Por como es el juego original, creo q este rota completo hasta volver  a la pos inicial

**Comment by diegosapunar** [comment]
Entonces jugando, basta con apretar un click y deberian girarse 3 hexagonos... es decir no es necesario seleccionar los 3 hexagonos, sino ya con ubicar el puntero en una pieza deberia funcionar.
