### ISSUE TITLE
[Tarea01] Productos-usuarios diccionarios

### ISSUE THREAD

**Issue by tmorales1** [IIC2233-2016-1/syllabus#22]
Una pregunta. Los productos que tienen los usuarios pueden ser un diccionario y no una lista? o es obligación que sea una lista?

**Comment by tamycova** [comment]
@moralillo en personas.txt los productos de los usuarios se encuentran representados con listas. Si consideras que **para efectos de tu modelación** es mejor parsearlos a otra estructura de datos puedes hacerlo!
