### ISSUE TITLE
Crash de interfaz al rotar pieza

### ISSUE THREAD

**Issue by ManuelSIlvaCav** [IIC2233-2016-1/syllabus#220]
Hola! al tratar de hacer que se seleccionen y deseleccionen las piezas a rotar cuando se pasa el mouse por encima, al aplicar la rotacion respectiva como que el metodo piece_section_entered en conjunto con piece.selected al armarse algo trata de calliar piezas que se estan cambiando y pareciera que no existen y me tira el siguiente error

```
Traceback (most recent call last):
  File "C:\Users\Manuel\Desktop\PycharmProjects\Tarea2\gui\piece.py", line 98, in mouseMoveEvent
    self.section_entered(1)
  File "C:\Users\Manuel\Desktop\PycharmProjects\Tarea2\gui\piece.py", line 116, in section_entered
    variables.GAME_INTERFACE.piece_section_entered(section, self)
  File "C:/Users/Manuel/Desktop/PycharmProjects/Tarea2/Main.py", line 41, in piece_section_entered
    p.valor.selected = not p.valor.selected
  File "C:\Users\Manuel\Desktop\PycharmProjects\Tarea2\gui\piece.py", line 61, in selected
    self.__set_selected(value)
  File "C:\Users\Manuel\Desktop\PycharmProjects\Tarea2\gui\piece.py", line 68, in __set_selected
    self.main_label.setPixmap(self._pixmap)
RuntimeError: wrapped C/C++ object of type QLabel has been deleted
```

**Comment by otro-felipe** [comment]
No entiendo bien cuándo se genera tu error. ¿Esto pasa en todos los hexágonos, o solo en la sección de un hexágono que "apunta" a un lugar donde se reemplazaron otros hexágonos? ¿Es posible que no estés usando el método `pop_piece` antes de eliminar las piezas del tablero?

**Comment by ManuelSIlvaCav** [comment]
cuando hago una rotacion y se arma algo en la direccion de la pieza seleccionada me tira el error anterior :c, respecto a pop piece, no creo ya que sino me tiraria el error al tratar de mover las piezas mediante move piece

**Comment by otro-felipe** [comment]
No entiendo bien tu error. ¿Puedes pushear lo que llevas a tu repo?

**Comment by ManuelSIlvaCav** [comment]
okap

**Comment by otro-felipe** [comment]
Este problema pasa porque en tu programa estás guardando referencias a piezas que removiste del tablero. Échale una pasada y mira en qué línea del main se cae el código, te podrá dar alguna idea de dónde estás guardando referencias obsoletas.
