### ISSUE TITLE
Tipos de figuras

### ISSUE THREAD

**Issue by mfuenzalida1** [IIC2233-2016-1/syllabus#221]
Hola, tengo una duda acerca de las figuras que se pueden formar. En la sección de figuras del enunciado listan los tipos de figuras que se deben poder formar en el programa. Sin embargo, en Hexic, cuando uno forma un cluster de 3 hexagonos del mismo color, si hay uno adyacente del mismo color que esta en contacto con 2 de los hexagonos del cluster inicial, se revientan los 4 hexagonos. Y de la misma forma, también se pueden reventar 5 hexagonos si el ultimo esta en contacto con otros 2 de los 4 que hay y es del mismo color.

Mi pregunta es si tenemos que implementar esto, ya que en el enunciado cuando hablan de UN solo color, solo mencionan los clusters de 3 hexagonos(ya sean normales,con bombas o estrellas) y nunca mencionan los clusters de 4 o mas de un mismo color.

**Comment by tamycova** [comment]
Hola @mfuenzalida1 ! Efectivamente tienes que implementarlo. En el enunciado mencionamos que "el cluster más básico se forma cuando tres hexágonos del mismo color se tocan", es decir pueden haber cluster más complejos de 4,5,6,7... etc del mismo color, como en Hexic (no íbamos a poner una figura especifica para cada una, pusimos el cluster más básico para mostrar lo que era un cluster). Finalmente, en la sección puntaje sale:  "al eliminar más de 3 piezas se otorgue más puntaje (3<4<5...)" , eso se refiere evidentemente a los clusters (ya que abajo de esto se específica para el resto de las figuras), es decir al reventar los 4 hexágonos tu programa debe darle más puntaje al jugador que al reventar 3.  Espero que haya quedado claro! Saludos
