### ISSUE TITLE
Termino "castear"

### ISSUE THREAD

**Issue by matnagra** [IIC2233-2016-1/syllabus#222]
He buscado en internet que es lo que significa castear pero no me queda muy claro.
¿Que significa "castear" llevado a esta tarea?

**Comment by negebauer** [comment]
Fíjate en #180 #190 #192 
Básicamente lo que vas a hacer es que cuando python te retorne una lista (u otra estructura) vas a pasarlo a una estructura hecha por ti (porque no puedes ocupar las de python)

**Comment by negebauer** [comment]
Para saber más sobre el término mismo te dejo este articulo de [wikipedia](https://en.wikipedia.org/wiki/Type_conversion)

**Comment by mjjunemann** [comment]
Puede que sea un abuso de notación aquí en python pero se refiere básicamente lo que dice @negebauer, que cuando tengas resultados en estructuras nativas de python lo pases a tus estructuras.

En lenguajes de mayor tipado como JAVA , C# cuando se usa herencia o interfaces (en python no existen), se puede castear una variable para que esta responda al comportamiento de la interfaz o la clase de cual heredan.

Un ejemplo un poco burdo de cuando tienes una lista de animales que todos tienen comportamientos distintos y todos son clases distintas, pero tienen como clase padre Animal, luego cuando quieres manejarlos a todos por igual, tu casteas hacia abajo 

```
ArrayList<Animal> Lista = new ArrayList();
Lista.add((Animal) new Dog("Pezoa"))
Lista.add((Animal) new Duck("MainScientist"))
for(Animal animal: Lista){
    animal.speak() 
}
```

`Lista.add(new Dog('Felipe'))` en un lenguaje como Java te daría un error, diciéndote que no son de la misma clase. 
En donde se ve que hago `(Animal)` ahi estoy casteando a la clase hacia su clase padre y solo puedes ocupar el comportamiento base de la clase padre Animal, los métodos que estén definidos ahi mientras estas casteando la variable, luego puedes castear hacia arriba si lo quieres. 

Esto aveces se usa para manejar clases distintas de una forma igual, no te quedes solamente con estas clases, Humano  también puede haber heredado de Animal, pero un perro con humano se compartan totalmente diferente.
