### ISSUE TITLE
[T02] Commando  __dict__

### ISSUE THREAD

**Issue by fcorencoret** [IIC2233-2016-1/syllabus#224]
Hola, podemos usar el commando '__ dict __' para ver los atributos de un objecto piece?

**Comment by otro-felipe** [comment]
**No se puede acceder a los atributos protegidos de los archivos que les damos.**

**Comment by fcorencoret** [comment]
Y podemos usar el row y column que retorna el piece_clicked?

**Comment by spiza** [comment]
me imagino que sí o no? :O!

**Comment by otro-felipe** [comment]
#219
