### ISSUE TITLE
Duda actividad semestre pasado

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2233-2016-1/syllabus#225]
Hola, En la actividad de functional del semestre pasado AC07, se entregaba una lista de logs y había que encontrar la URL más frecuente. 
¿Se puede usar sort para poder ordenar la lista? El problema de esto es que habría necesariamente que crear la lista de nuevo solamente conteniendo las urls de los logs, para luego poder ordenarla.
Luego, con la función groupby se puede hacer, de hecho. Sin embargo, no se me ocurre ninguna forma de hacerlo si no es primero ordenando por urls, a menos que algo itere por cada elemento y usando tiempo cuadrático, lo cual sería muy ineficiente.

MI duda es entonces: si se puede usar sort, ¿por qué es válido?
O de lo contrario, ¿de qué forma se puede hacer?
Muchas gracias
saludos!

**Comment by rodolfopalma** [comment]
Uno de los pilares de la programación funcional es evitar la mutación del _state_ (los datos) de tu programa. En ese sentido, usar `sort` no sería correcto dado que es un método que modifica tu lista y la ordena _in-place_. La opción correcta es usar `sorted` que hace lo mismo que `sort`, a excepción de que no modifica la lista original y retorna una nueva lista ordenada.
