### ISSUE TITLE
¿Habrá sala de ayudantes este semestre?

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2233-2016-1/syllabus#226]
Eso. En ese caso, ¿qué días la harían y en qué horario? 
Gracias!

**Comment by tamycova** [comment]
Hola! Sí, se viene pronto esa info :)

**Comment by bamavrakis** [comment]
Hola! Acabo de enviar un anuncio por el Siding sobre eso :)

**Comment by perojas3** [comment]
A esa hora no puedo ¿Habran otras?

**Comment by HenryBlairG** [comment]
yo tampoco podré ir y necesito ayuda!!

**Comment by flobarrios** [comment]
Hola ! la próxima será el martes, horario por definir entre modulo 3, 4 o ambos. Saludos!
