### ISSUE TITLE
Problema animacion rotacion simple

### ISSUE THREAD

**Issue by ManuelSIlvaCav** [IIC2233-2016-1/syllabus#227]
Hola !
Al tratar de hacer rotar un movimiento simple y que esta siga hasta su posicion inicial si no se arma nada, esta como que no muestra animacion en la gui, siendo que si pilla alguna combinacion en mitad de la rotacion esta si se muestra....
AYuda pls

**Comment by negebauer** [comment]
@ManuelSIlvaCav  Intenta con #210

**Comment by elzambon** [comment]
Hola tengo el mismo problema al girar no veo la animacion puede ser porque no estoy tomando en cuenta el parámetro function on_move_ended pero la verdad es porque no lo entiendo que espera ese metodo que le pasemos?

**Comment by otro-felipe** [comment]
Por favor revisen #201

**Comment by elzambon** [comment]
Disculpa lo había revisado pero por alguna razón no había visto una parte

**Comment by negebauer** [comment]
Recuerda cerrar la issue si tu problema esta resuelto!
