### ISSUE TITLE
Agregar atributos a la clase MyInterface

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2233-2016-1/syllabus#228]
Hola, aunque el enunciado dice que se haga override de los métodos, ¿se puede agregar cualquier atributo a dicha clase?
gracias
saludos

**Comment by tamycova** [comment]
@AlfonsoIgnacioV  por favor lee las issues anteriores antes de hacer tu pregunta, hemos repetido hasta el cansancio (#218 por ejemplo) que no pueden modificar los archivos. La gui la pueden importar y hacer override a los métodos que salen en el enunciado, pero no se gasten en mirar su código porque no pueden usar sus clases, ni sus atributos (como variables.HEXAGON_TYPES) y menos sus atributos, y si lo hacen serán penalizados severamente. Ustedes tiene que modelar el juego, hagan sus propias clases usando sus propias estructuras de datos. 

[EDIT] Perdón pensé que te referias a la clase Piece, evidentemente la clase MyInterface es tu propia clase ya que estas heredando de otra, puedes ponerle atributos, pero no puedes modificar los archivos que vienen dados.

**Comment by negebauer** [comment]
@AlfonsoIgnacioV Te invito a leer #199

**Comment by AlfonsoIgnacioV** [comment]
Sí, lo había visto :) ... la diferencia es que estaba pensando en agregarle más atributos en vez de mètodos (en estricto rigor es hacer override del init), pero quería saber si es legal para la tarea ya que tal vez sea restrictivo el hecho de agregar más atributos en algún sentido
gracias de nuevo :)

**Comment by tamycova** [comment]
te respondí arriba en el edit!!!

**Comment by AlfonsoIgnacioV** [comment]
acabo de cachar, no me aparecía, ahora recién lo veo
gracias! :)
