### ISSUE TITLE
Duda con tablero inicial

### ISSUE THREAD

**Issue by gbordoni** [IIC2233-2016-1/syllabus#229]
Al agregar piezas para el tablero inicial, si no especifico el tipo de pieza y estas se seleccionan aleatoriamente, se llena de bombas, mirrors, estrellas, etc, y muy pocos hexagonos simples de color. Puedo hacer que en el tablero inicial (obviamente no los que se cargan desde los archivos) aparezcan solo hexagonos de color, hexagonos con estrellas y bombas? Para facilitar el inicio del juego y que no sea tan desordenado todo: 

![captura de pantalla de 2016-04-06 18 13 21](https://cloud.githubusercontent.com/assets/13774052/14333091/54f705b6-fc23-11e5-896d-3e920063c7f8.png)

**Comment by tamycova** [comment]
Sí! especifícalo en el README, incluso intentaría maximizar el número de hexágonos y dejar una probabilidad baja de que parta con bombas/estrellas, sino sería un juego caótico para el que lo juegue por primera vez, de eso ya se encargarán los mapas
