### ISSUE TITLE
Consulta acerca de personas.txt

### ISSUE THREAD

**Issue by Iruretagoyena** [IIC2233-2016-1/syllabus#23]
Hola !
En el pdf se indica los tipos de datos de personas.txt (ojo, sale mal y dice usuarios.txt). Luego dice que para la corrección se utilizaran otros tipos de datos.
Es necesario crear un código que convierta cualquier tipo de texto con esa estructura a algo iterable ( para sacar los valores de las keys) o podemos simplemente copiar y pegar todo a un archivo .py e iterarlo ?
Gracias.

**Comment by tamycova** [comment]
Sí efectivamente el usuarios.txt del enunciado es personas.txt en los archivos generados (ups), y sí debe ser un parser genérico, no puedes simplemente copiar y pegar todo a un archivo.

**Comment by MortizDX** [comment]
Los archivos que usaran para revisar la tarea tendrán el mismo nombre y estructura que los que hay en el repositorio, solo el contenido variaría ¿verdad? ¿o hay que esperar que otras cosas cambien en ellos?

**Comment by bamavrakis** [comment]
Exacto, mismo nombre y estructura y solo el contenido varía :)

**Comment by bamavrakis** [comment]
Hola!, aproveché de cambiar el nombre del archivo a usuarios.txt (ups)
Saludos!
