### ISSUE TITLE
Uso de range() en Tarea2

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#230]
¿Está permitido? Lo pregunto porque tecnicamente retorna una lista... pero podría ser utilizado para recorrer una determinada cantidad de iteraciones, y sino para crear un generador.

**Comment by aaossa** [comment]
Si `range()` retorna una lista NO puedes usarla (a no ser que hagas lo dicho en otras issues). Si `range()` no retorna una lista puedes usarla.

_Hint:_ "Técnicamente"... no retorna una lista, sino que es un iterable

**Comment by MortizDX** [comment]
Oh, es que como retorna una secuencia de números, pensé que retornaba eso, o sino una tupla ¿no es ninguna de ellas?

**Comment by robocop6** [comment]
_ProTip_: NO! Simplemente es un objeto iterable, no una estructura de datos. ¿Te imaginas tener guardados en memoria todos los números de 1 a 10 trillones de trillones... de trillones!? Sería un desperdicio de memoria. Lo que se hace es guardar el inicio, el final, el paso e ir entregando un nuevo número de a uno al iterar.

Es más... Después de la Actividad de hoy... ¡tú ya podrías definir una clase propia `Rango`! Basta con que implementes `__iter__` como método en `Rango`, y preocuparte de que ese método retorne un iterador que vaya entregando el valor que sigue. Ese iterador puede implementarse con una función generadora (así como el generador de ids).
