### ISSUE TITLE
Retornar dos valores de un método

### ISSUE THREAD

**Issue by rmant** [IIC2233-2016-1/syllabus#231]
Podemos retornar dos valores en una funcion, es decir `return a,b`, o esto se considera uso de tuplas? Gracias!

**Comment by flobarrios** [comment]
fijate en lo que dicen en #178, #180, #190. Lo que puedes hacer es que retorne una lista (la que tu implementaste) con dos elementos y trabajar con ellos. Algo como:

``` python
def metodo():
    x = MyList()
    #generas un metodo para agregar los elementos a,b a x
    return x
```
