### ISSUE TITLE
Piezas especiales en los bordes y Rotacion (otro modo)

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233-2016-1/syllabus#233]
Como dice el titulo, ¿que esperan que suceda cuando una pieza especial (star, star mirror y esa negra) están en los extremos y no pueden rotar todo a su alrededor??

Según hexic, cuando una estrella llega a un extremo y no puede rotar todo su alrededor, la trata como una pieza normal, es decir la rota con 2 piezas dependiendo de la sección, ¿usamos eso como solución o realizamos otra medida que la especificamos en el Readme?

Sobre el segundo tema, es posible cambiar en modo de rotación.
Hexic da una vuelta completa en caso de que no pase nada, pero en otros juegos hacen una rotacion y si no pasa nada, lo devuelven altilo a su posición original, no da la vuelta entere
¿puedo usar ese modo, y obviamente lo dejo explicado en el Readme?
o lo dejo como Hexic?

**Comment by gbordoni** [comment]
Me sumo a la pregunta de la rotacion; el hexic que yo habia estado jugando rotaba las piezas una vez en la direccion indicada, y si no pasaba nada las devolvia a su posicion original.

saludos

**Comment by otro-felipe** [comment]
El movimiento es tal cual como funciona en el juego Hexic, es decir, rotar hasta que se forme una figura o se de la vuelta completa, con las notables excepciones de la pieza estrella(una rotacion por click) y mirror (reflexion de piezas en vez de rotacion). Con respecto a las piezas de los bordes, queda a su criterio como manejen el click en una seccion externa y debe ser detallado en el README.

**Comment by Hernan4444** [comment]
Oka muchas gracias :D
