### ISSUE TITLE
¿Al momento de rotar, como obtengo el clockwise?

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#234]
Al hacer click, se obtiene se deveria rotar los hexagonos.
Pero el metodo "piece_clicked" no tiene el clockwise, ¿Como se si este es true o false?

**Comment by negebauer** [comment]
Tienes que heredar de la clase `GameInterface`
Esta tiene un método `reverse clicked` que debes hacerle override que es llamado cuando el usuario cambia el sentido de rotación
Tú tienes que ver cómo hacer que gire en el sentido correcto
