### ISSUE TITLE
Cambiar la velocidad de las animaciones

### ISSUE THREAD

**Issue by vjmoreno** [IIC2233-2016-1/syllabus#236]
Hay alguna manera de hacer mas rápidas las animaciones de las rotaciones de piezas?

**Comment by otro-felipe** [comment]
¿Para qué querrías cambiar la velocidad de las animaciones? ¿Tienes algún inconveniente con la interfaz?

**Comment by tsuarezsaieh** [comment]
En mi PC al menos las animaciones se ven muy lentas!

**Comment by otro-felipe** [comment]
antes de gui.init() puedes poner gui.set_quality("low")

**Comment by vjmoreno** [comment]
Las animaciones son algo lentas, al menos en la app que me bajé para el celular las animaciones son mucho mas rápidas, lo que hace que el juego sea mucho más fluido.
