### ISSUE TITLE
section 7 en piece_clicked

### ISSUE THREAD

**Issue by agmardones** [IIC2233-2016-1/syllabus#239]
Como mencionaron en #206, la función `piece_clicked` retorna seccion 7 en algunas ocasiones, por eso decidí hacer todo con la sección y pieza que entrega `piece_section_entered`, pero como ésta cambia la sección cada vez que se mueve el mouse, a veces pasan *cosas raras cuando se hace click y se mueve el cursor rápidamente por las otras piezas (sin que se termine de rotar la pieza clickeada). Está bien esto y especificarlo en el README, onda sobre como funciona el juego, o debería solucionarlo?

*_las piezas se vuelven locas y se rotan por donde vaya el mouse_

**Comment by otro-felipe** [comment]
Deberías solucionarlo :)

**Comment by ManuelSIlvaCav** [comment]
el piece clicked seccion 7 ocurre cuando se clickear la misma pieza muy rapido al parecer, pero si se deja pasar como 1-2 segundos entre clicks ya no manda piece section 7

**Comment by agmardones** [comment]
Gracias a ambos =)

**Comment by aaossa** [comment]
Discusion movida a #244 
Duplicada de #206
