### ISSUE TITLE
Programa no responde

### ISSUE THREAD

**Issue by noksenberg** [IIC2233-2016-1/syllabus#240]
Al correr la T02 y hacer click sobre una pieza el programa deja de responder. A alguien más le ha pasado? Por qué puede ser?

**Comment by otro-felipe** [comment]
¿Tienes código escrito? ¿Usaste algún `time.sleep()`?

**Comment by noksenberg** [comment]
Si, tengo harto código. No usé eso.

**Comment by otro-felipe** [comment]
alguna operación de tu código podría estar retrasando mucho la ejecución de la gui. Si puedes pushea lo que llevas, así yo le podría dar una pequeña mirada.

**Comment by noksenberg** [comment]
Gracias! Ahí le hice push

**Comment by otro-felipe** [comment]
no veo el push :(

**Comment by noksenberg** [comment]
Le hice push desde mi repositorio! Te puede mandar el código por mail

**Comment by jonnylee719** [comment]
Me puede dar algun consejo? Como blockear el metodo `piece_clicked()` durante la rotacion? Uso `time.sleep()` y todo el gui no funciona...

**Comment by otro-felipe** [comment]
@jonnylee719 ¿Con qué fin usas `time.sleep()`? Para evitar el uso de `sleep`, existe el parámetro `on_move_ended` que recibe una función que se ejecuta una vez terminada la animación. Un pequeño consejo para bloquear la ejecución de un método dada cierta condición: usar if.

@noksenberg ¿Estás teniendo problemas al pushear? Si es así deberías solucionarlo lo más pronto posible para poder subir tus tareas.

**Comment by jonnylee719** [comment]
He intentado con `time.sleep()` y `time.time()` y un boolean de `self.rotating` y una condicion de `if self.rotating(): return`
Ademas cuando enviar `time.sleep()` como parametro a `on_move_ended` no lo ejecuta?

Puedes ver mi codigo en mi repositorio?

**Comment by otro-felipe** [comment]
@jonnylee719 lo que me parece es el problema en tu código es que no veo usado el parámetro `on_move_ended`. En el issue #179 explico cómo se usa el parámetro, intenta usar el ejemplo que puse para ver si entiendes mejor cómo usar ese parámetro.

**Comment by jonnylee719** [comment]
Bueno voy a intentarlo, gracias!

**Comment by noksenberg** [comment]
Ahí si debería estar!

**Comment by jonnylee719** [comment]
@MainScientist Yo puedo llamar la funcion `on_move_ended` con `self.start_rotating` pero asi todavia se puede tener varias `move_piece()` en el mismo tiempo?

**Comment by otro-felipe** [comment]
La idea es que llames a la función en un solo `move_piece()` porque si los llamas en dos, se ejecutaría tu método dos veces. Puedes llamarlo en cualquiera de los tres `move_piece()` (o 5 dependiendo del caso), pero solo en uno debe ir el parámetro.

**Comment by otro-felipe** [comment]
Recuerda que al poner la función como parámetro debe ir sin paréntesis! :)

**Comment by jonnylee719** [comment]
@MainScientist Puedes ver mi codigo si esto es lo que refieres? 
Porque la funcion de `on_move_ended` es llamada cuando termina `move_piece()`, esto significa que puede llamar `piece_clicked()` entre el tiempo de la ultima `piece_clicked()` y la terminacion de la ultima `move_piece()`?

**Comment by noksenberg** [comment]
@MainScientist sigo con el mismo problema, ahí se subió el push!

**Comment by otro-felipe** [comment]
@jonnylee719 claro, puedes llamar un addpiece dentro de la funcion que pongas en `on_move_ended`.

@noksenberg a mí me funciona, intenta desactivando las animaciones.

**Comment by jonnylee719** [comment]
@MainScientist Me equivoque, uno puede llamar `piece_clicked()` antes de la terminacion de la primera `move_piece()`

**Comment by otro-felipe** [comment]
@jonnylee719 si se puede, pero puedes hacer que tu programa ignore estas llamadas si aun no se termina la rotación.

**Comment by jonnylee719** [comment]
Si esto es lo que no entiendo. La unica manera que puedo pensar es mantener un boolean de rotating que es True cuando esta roteado por una cierta tiempo (usando time) antes de volverse a False y False si no. Pero para cambiar el valor de este boolean, si lo pongo en `on_move_ended` ya es demasiado tarde, porque despues del inicio de `move_piece()` y antes de su terminacion, puede llamar `piece_clicked()`.
Entonces hay otra manera de hacer lo?

**Comment by ManuelSIlvaCav** [comment]
Me sumo a lo anterior, que no encuentro una forma optima de blockiar el metodo piece_clicked, porque si es que se empiezan a formar combos, la idea es que tampoco uno se ponga a mover piezas en medio del combo.... y el move ended de add piece y move piece los tengo como llamado a la funcion que chequea las combinaciones con el fin de que se vean las piezas que caen...
Se puede asumir entonces que la persona no va a clickear entre rotaciones o combos???

**Comment by jonnylee719** [comment]
@ManuelSIlvaCav Al final, llegue a una solucion, antes de la primera llamada de `move_piece()` pon un boolean `self.rotating = True` y en el metodo `piece_clicked()` pon una condicion `if self.rotating: return` despues en la finalizacion de una rotacion que va a llamar una otra metodo `otra_rotear()` si no va a rotear de nuevo pon `self.rotating = False` para que pueda recibir llamado en `piece_clicked()`.
No se si este es optima pero funciona

**Comment by ManuelSIlvaCav** [comment]
vale,  hize algo parecido, segui la logica del if para un booleano que blockiara el contenido de piece_clicked pero con una variable seteada una vez que no se formara nada mas posterior al movimiento
Grax

**Comment by noksenberg** [comment]
@MainScientist Hola, traté con las animaciones desactivadas, y aún se queda pegado.

**Comment by ManuelSIlvaCav** [comment]
a mi me sucedia algo parecido y busque en mi codigo las partes de chequeo, aveces se me quedaba pegado porque se quedaba dando vueltas en dos loops cuando se formaba algo rebuscado y que justo calzaba con dos chequeos y no sabia por cual irse

**Comment by otro-felipe** [comment]
¿El problema es siempre o en ocasiones especiales? Si es en ocasiones especiales te recomiendo chequear lo que dice @ManuelSilvaCav . Trata de ver en que situaciones pasa y de recorrer tu codigo "al ojo". Si tienes pycharm puedes marcar la linea y usar el debugger.

**Comment by noksenberg** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/8571906/14410853/a32883b0-ff0f-11e5-9b6f-61bbcd33cd6b.png)
Esa es una foto de lo que pasa! Por si no se había entendido. Python puede manejar todo el flujo de mi programa, lo que se cae es la interfaz.

**Comment by ManuelSIlvaCav** [comment]
ya eso segun yo... es porque las instrucciones que le tay dando a la gui se estan superponiendo, a mi me pasaba eso mismo cuando me calzaba un cluster normal y armando que se yo una estrella, ve bien el orden y los loops cuando armas combinaciones y el orden de llamados a la gui, porque yo tuve que arreglar los requerimientos y break necesarios en los chequeos para que no pasara eso
Saludos

**Comment by noksenberg** [comment]
Gracias por la ayuda!
