### ISSUE TITLE
Duda python general

### ISSUE THREAD

**Issue by hhase** [IIC2233-2016-1/syllabus#242]
Hola!
tengo dos dudas sobre generales que no tienen que ver mucho con la tarea:

1) En uno de los issues de la tarea 1 fue mencionado que no era bueno tener funciones sueltas en un programa, por lo que era mejor agruparlas en una clase. Estuve leyendo un poco en internet y lo que mas se menciona es justo lo contrario... 
Así que estoy un poco confundido, que es mejor?
Uno de los videos que peor hablan de las clases es: https://www.youtube.com/watch?v=o9pEzgHorH0

2) Por que se dice que python no es buen lenguaje para programación funcional? 
Presentacion relacionada con la pregunta: http://kachayev.github.io/talks/uapycon2012/#/45 

Saludos!

**Comment by otro-felipe** [comment]
La gran gracia de escribir clases es que hace el código mucho más legible y ordenado. Si bien en lenguajes como Python se pueden obviar ciertas clases, necesitas usar clases para **representar entidades en el  código**. Una muy muy muy muy muy muy muy muy mala idea es hacer esto:

``` python
def presentar_animal(animal):
    print("Hola soy {} y soy de color {}".format(animal["nombre"], animal["color"])

ornitorrinco = {"nombre": "Perry", "color": "verde"}
presentar_animal(orintorrinco)
```

Quizás en python sí se puede abusar mucho de las clases, ya que varias veces necesitas clases estáticas que, en python, pueden ser pensadas como un módulo con funciones estrechamente relacionadas. En este caso sí puedes obviar el uso de clases, pero olvidarte de las clases, representar tus entidades como diccionarios y tener métodos sueltos para simular el comportamiento de estas entidades atenta contra la legibilidad, extensibilidad e integridad del código, es decir: va a ser muy dificil de seguir, muy dificil de hacerlo crecer (agregar más funcionalidades) y de debuguear.

Lo que el presentador menciona en el primer video es no usarlas demasiado, porque ciertamente para problemas sencillos, varias veces no necesitas usar clases. Pero para proyectos grandes cuya intención es perdurar por el tiempo, debes usar  clases. Para trabajar en equipo debes usar clases y métodos claros para que tus compañeros sepan que hace tu código. Si quieres hacer una api debes hacer clases y métodos claros para que los usuarios tengan alto control sobre las cosas que hace la api. (Una de las preguntas al final fue respecto a la hora de **sobresimplificar** un código en una api, le quita el control a lo que haces). Al final el uso de clases depende de a quién va dirjido el código y con qué fines. ¿Es un pequeño script? Simplifico. ¿Es una api, alguien mas va a leer mi código, quiero que mi proyecto crezca? Ordeno mi código y lo hago legible.

Para saber más sobre esto te recomiendo el libro Clean Code.
