### ISSUE TITLE
Terminar partida

### ISSUE THREAD

**Issue by ManuelSIlvaCav** [IIC2233-2016-1/syllabus#243]
Hola, cuando la persona gane,pierda o guarde el mapa, existe alguna funcion de la gui para que esta deje de funcionar y se cierre todo? o simplemente imprimo el mensaje en consola de que se acabo el juego...
Gracias

**Comment by otro-felipe** [comment]
Puedes imprimir en consola que se ganó el juego con el puntaje correspondiente y terminarlo todo con un `sys.exit(0)`
