### ISSUE TITLE
[T02] Generando piezas nuevas

### ISSUE THREAD

**Issue by fcorencoret** [IIC2233-2016-1/syllabus#246]
Cuando hago un cluster y se generan piezas nuevas en la parte superior del tablero, se tienen que poder generar piezas normales, con estrellas y bombas cierto? Red, star_red y bomb_red? Con que frecuencia o probabilidad le asigno a cada una de las opciones o esto queda a mi criterio?

**Comment by otro-felipe** [comment]
Queda a tu criterio, siempre y cuando no generes las piezas que se forman al armar estructuras especiales. La cantidad de bombas, piezas con estrellas etc queda a tu criterio y debes espcificarlo en el readme.
