### ISSUE TITLE
Selección y rotación

### ISSUE THREAD

**Issue by bmarinb** [IIC2233-2016-1/syllabus#247]
¿La selección de una pieza se hace mediante un clic, requiriendo en total dos clics para la rotacion?
¿O al pasar el mouse sobre una pieza y sección debe seleccionarse automáticamente, de modo que baste solo un clic para la rotación?

**Comment by otro-felipe** [comment]
Al pasar el mouse sobre una pieza y sección debe seleccionarse automáticamente, de modo que baste solo un click para la rotación.
