### ISSUE TITLE
Falta de nombres en productos.txt Tarea 1

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233-2016-1/syllabus#25]
Estaba revisando el texto "productos.txt" y hay como 12 productos que su nombre es " "
Para términos de comodidad para trabajar todo el código y cuando se muestren los productos, ¿elimino esos productos o les invento un nombre?

**Comment by bamavrakis** [comment]
Hola!
Ignora esos productos :)
Saludos!

**Comment by Hernan4444** [comment]
Gracias por la respuesta

**Comment by bamavrakis** [comment]
Hola! con el cambio de archivos se arreglo este problema.
Saludos!

**Comment by jecastro1** [comment]
FIXED
