### ISSUE TITLE
Método gui.move_piece no actualiza la interfaz

### ISSUE THREAD

**Issue by bmarinb** [IIC2233-2016-1/syllabus#250]
Tengo seleccionadas las 3 piezas que voy a rotar
Las popeo y guardo las piezas en una lista (uso .deleteLater para actualizar la interfaz)
Luego hago move_piece de cada pieza con la posición a la que debería caer y la interfaz no se actualiza, sin embargo si se detecta el cambio de posición (lo corroboré con get_piece)

¿Estoy haciendo algo mal?
¿Cómo muestro la pieza en su nueva posición?

**Comment by negebauer** [comment]
Quieres eliminar las piezas o solo hacerlas rotar? (`.deleteLater` es para **eliminarlas**)
Si es rotar, estas haciendo que de las 3 vueltas y no se anima?

**Comment by bmarinb** [comment]
estoy rotando solo 1 vuelta, tal como deben rotar las estrellas
¿Es que el método solo funciona cuando se da una vuelta completa?

**Comment by negebauer** [comment]
Prueba sin usar `.deleteLater`
Ese método tienes que llamarlo cuando quieras que una pieza desaparezca por completo (destruida)

**Comment by bmarinb** [comment]
Eso era, gracias!

**Comment by negebauer** [comment]
Recuerda cerrar la issue cuando este resuelta 😁
