### ISSUE TITLE
¿Eliminar 4 o 5 piesas?

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#251]
El pdf dice algo sobre eliminar 4 o 5 piesas.
¿A que se refiere esto?
Entiendo eliminar multiplos de 3, con combos, o con piesas espaciales. ¿Pero 4 o 5?
¿Me lo pueden explicar?

**Comment by negebauer** [comment]
Si al hacer una rotación quedan 3 o más piezas del mismo color conectadas se deben eliminar todas
