### ISSUE TITLE
atributo MyList a clase MyInterface

### ISSUE THREAD

**Issue by josetov** [IIC2233-2016-1/syllabus#252]
Hola, cree una clase MyList (lista ligada) y me gustaria que la clase MyInterface al instanciarla recibiera una instancia de la lista ligada como un atributo (ya escribi el contructor **init** para MyInterface() ).
Cuando ejecuto el programa hago lo siguiente:
lista = MyList()
p = MyInterface(lista)

Pasa que me pycharm me arroja el siguiente error:
TypeError: **init**() missing 1 required positional argument: 'lista'

Alguna idea como arreglar esto? Gracias

**Comment by negebauer** [comment]
Pushea lo que llevas para echarle una mirada

**Comment by josetov** [comment]
Ok. El problema aparece en demo.py

**Comment by negebauer** [comment]
Fíjate la línea 66 de tu demo.py
Estas creando un MyInterface ahí también!

**Comment by josetov** [comment]
Gracias! se me paso eso 👍
