### ISSUE TITLE
creación de un nuevo juego

### ISSUE THREAD

**Issue by bmarinb** [IIC2233-2016-1/syllabus#253]
Si creo un nuevo juego, debo impedir que se cree con clusters ya formados?
De lo contrario,¿ en que momento podría eliminar estos clusters?

Si lo elimino al hacer clic en cualquier pieza, podría darse el caso de que al eliminarlo cambie la posición de la pieza, lo que obligaría o a realizar una rotación indeseada o a hacer clics en la pantalla hasta que se limpien todos los clusters

**Comment by tamycova** [comment]
No no debes impedirlo, pueden haber mapas con cluster formados, ya lo habíamos respondido. 

#213
