### ISSUE TITLE
Animaciones y su correcta implementación

### ISSUE THREAD

**Issue by andersskog** [IIC2233-2016-1/syllabus#255]
Tengo mi tablero creado con listas ligadas, que envía todos los cambios al tablero entregado con la tarea. El problema es que al ocurrir cadenas de figuras, estás ocurren correctamente en mi tablero creado, pero visualmente en la interfaz todo ocurre automáticamente y no se puede apreciar nada de lo que esta ocurriendo. ¿Cuál es la forma correcta de realizar estos cambios? ¿Podrían dar algún ejemplo de uso? 

Más específico, al usar piece_clicked, la rotación ocurre correctamente, se identifica todo y se destruyen las figuras correspondientes. En la interfaz todo ocurre inmediatamente.

**Comment by IsaacConDosA** [comment]
Tienes que hacer:
gui.set_animations(True)
antes del run()

**Comment by Zepk** [comment]
Yo tengo el mismo problema, en el fondo, cada vez que se arma un cluster, este "explota", las piezas que están arriba caen para llenar las posiciones vacías, los lugares que quedan vacíos, son rellenados.
Pero cuando se hace click, todo pasa al mismo tiempo, se hace una "super-animacion" donde todas las piezas vuelan directamente de donde parten a la posición final donde deben quedar tras haberse hecho explotar los clusters y las cadenas de clusters.
Y esto hace dificil ver si el programa corre correctamente, porque no hay una pausa entre que animaciones.
Yo intente usar la funcion `time.sleep()`, entre la función que hace desaparecer los cluster, y las que rellenan el tablero con nuevas piezas, pero eso no funciona, porque el `sleep` toma toda la animación, la pausa, y luego hace todo al mismo tiempo

**Comment by rmant** [comment]
A mi también me pasa lo mismo. En el fondo me elimina los clusters antes de que se termine de ejecutar la animacion de la rotacion, por lo que se ve estéticamente feo y no se alcanza a apreciar bien porque se están eliminando las piezas.

**Comment by otro-felipe** [comment]
#227 
#179 
#201 
#210 

Lean esto. Si siguen con la misma duda reabran la issue.
