### ISSUE TITLE
[T02][Inicio Juego]

### ISSUE THREAD

**Issue by vbarros2** [IIC2233-2016-1/syllabus#256]
Cuando inicio el juego tengo que crear una ventana con las opciones juego nuevo y reanudar juego.
O esto puede salir en la ventana de resultados?? En este caso puedo usar Tkinter??

También, hasta cuantos juegos tengo que poder guardar?? Lo decido yo esto??

Muchas Gracias

**Comment by otro-felipe** [comment]
Está explícito en el enunciado que el comienzo del juego debe ser por consola. Si quieres crear una ventana debes hacerlo con `PyQt4` como dice aqui #178 
Tú decides cuantos juegos se deben poder guardar si es que quieres poner algun límite, aunque no no es necesario que lo haya.
