### ISSUE TITLE
problema con piece_section_entered

### ISSUE THREAD

**Issue by cggutierrez** [IIC2233-2016-1/syllabus#257]
cuando uso ese metodo , este me da para trabajar con la Piece y la seccion de la piece en la que tengo el mouse encima, pero me hace falta la posicion en la que esta la Piece y no logro encontrar por ningun lado como obtenerla.

Me he saltado algun metodo para obtener la posicion o algo asi?

**Comment by otro-felipe** [comment]
Puedes usar los parametros `piece.row` y `piece.column` que si bien no están detallados en el enunciado, fueron mencionados en las issues hace un tiempo aquí #219
