### ISSUE TITLE
Problema al castear

### ISSUE THREAD

**Issue by caackermann** [IIC2233-2016-1/syllabus#259]
En mi clase para listas tengo:
`class MyList(self, *args):
      for i in args:
             self.append(i)`
Pero cuando le entrego un metodo que retorna una lista, en especifico `os.listdir(path)`:
`directories = MyList(os.listdir(path)` la lista que se crea tiene un solo elemento, que es justamente la lista que le entregue. Como que en lugar de hacer append de cada elemento lo hace con la lista entera. Hay algo que este haciendo mal?

**Comment by caackermann** [comment]
Cuando hago print de args en el init de MyList imprime algo asi:
`([objeto1, objeto2, objeto3],)`
pero si hago:  `print(os.listdir(path)`
Se imprime
`[objeto1,objeto2,objeto3]`

**Comment by andresfdezc** [comment]
Los elementos de `args` son todos los argumentos que le entregues a tu lista **separados por comas**. Al hacer `MyList(os.listdir(path))` le estás entregando un solo elemento, que es la lista completa. Por ello el `for` que incluiste realiza un solo ciclo (`i = os.listdir(path)`) y hace append de ese único elemento.

**Comment by caackermann** [comment]
No estoy muy seguro de entender. Cual seria la manera correcta de hacerlo entonces?

**Comment by andresfdezc** [comment]
Tienes que pensarlo y programarlo tú en el `__init__` de tu clase.

**Comment by isarovic** [comment]
class MyList(self, *args): for i in args[0]: self.append(i)

en el for solo pon args[0]
