### ISSUE TITLE
Duda sobre método en la solución de la AC4 2015-1

### ISSUE THREAD

**Issue by sormazabal** [IIC2233-2016-1/syllabus#26]
Hola!

Estaba revisando la sulución de la AC4 y me surgió la duda al mirar esta parte dentro de la class HashSoda9001:

" # Opción 1: Usar defaultdict (mejor)

```
        # Función que se llamará en ausencia de una pila
        # para una determinada key (litros)
        def crea_pilas():
            return []

        # Creamos el defaultdict con la función de recién
        pilas = defaultdict(crea_pilas)"
```

¿Por qué se crea un método para crear la pila en lugar de sólo escribir "defaultdict([])"? #

**Comment by aaossa** [comment]
Porque el argumento que recibe `defaultdict` debe ser `callable`, o llamable o invocable, es decir, por ejemplo una función. Mira, me hice un mini código de ejemplo y esto me salió:

![Error esperado](https://cloud.githubusercontent.com/assets/10425834/13793346/3eedec62-ead5-11e5-8df9-64e8914d8304.JPG)

Lo que tu dices (`[]`) no es una función, sino objeto (uno que no es `callable`). Lo que hace `defauldict` es preguntarse: "_¿Existe esta llave? Mmm, no existe, entonces_ **llamo** _(recuerda, `callable`) a la función por defecto (por eso se llama `default`+`dict`). ¿Qué me retorna la función `crea_pilas` que me dieron? Una lista vacía. Entonces, si la llave no existe, es como si el valor para dicha llave fuese una lista vacía_"

**EDIT:** También sale en el material esto de que aceptan una función como argumento. Puedes verlo online [**aquí**](https://htmlpreview.github.io/?https://github.com/IIC2233-2016-1/syllabus/blob/master/Material-de-clases/02-EDD/04-dictionaries.html)

**Comment by sormazabal** [comment]
Muchas gracias! :D
