### ISSUE TITLE
¿Como destruyo piesas?

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#260]
Actualmente estoy tratando de sonseguir que se destruya una piesa, antes deproceder hacer que el resto caiga. Sin embargo, no logro conseguir que una ficha desaparesca del tablero.
¿Como lo hago?
Use el buscador, pero encontre nadie preguntando esto.

**Comment by andresfdezc** [comment]
Lo que preguntas se encuentra en la issue #188.
