### ISSUE TITLE
uso __dict__

### ISSUE THREAD

**Issue by josetov** [IIC2233-2016-1/syllabus#261]
Cree una clase y me gustaria iterar sus atributos. Puedo usar self `__dict__` para eso? (sin los "/ " )
Gracias

**Comment by agmardones** [comment]
No se puede :(, (#65)

**Comment by bamavrakis** [comment]
Hola! 
No, no puedes usarlo para esta tarea.
Saludos!

**Comment by santiagocruzb** [comment]
Pero que pasa si obtengo los atributos de la clase y los casteo? @bamavrakis

**Comment by aaossa** [comment]
No deberías hacer eso de todas formas, es una mala práctica. Si escribiste una clase deberías saber cuales son los atributos que esta tiene, por lo que hacer eso es innecesario.

**Comment by santiagocruzb** [comment]
Hice una clase que funciona como diccionario. Si quiero obtener todos los atributos (keys) de esta clase tengo que usar __ dict__. Podría ir llamándolos 1 a 1 con un **for** y un **try** pero no es tan eficiente. ¿?
