### ISSUE TITLE
El martes a que modulo es la sala de ayuda para la tarea

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#262]
Durante la ayudantia del lunes, dijieron que el martes, en algun modulo, habria una sala de ayuda para la tarea. ¿En que modulo es y en donde?

**Comment by agmardones** [comment]
Ojala el/los módulo/s incluya al 5 <3

**Comment by aaossa** [comment]
@bamavrakis enviará un aviso sobre esto ~~en el transcurso del día~~ antes de las 10, sean pacientes :grin:
