### ISSUE TITLE
Tengo un error raro

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#266]
Me sale este error

```
Traceback (most recent call last):
  File "C:\Users\Pablo\Desktop\Progra avanzada github\perojas3-iic2233-repo\Tareas\T02\gui\piece.py", line 195, in tick
    self.on_move_end()
TypeError: 'int' object is not callable
```

Sin embargo, puedo hacer todo bien. y hasta ahora no me causa otro problema.

**Comment by tamycova** [comment]
No es raro el error, debe haber algún problema en tu código. En algún lugar estas tratando de usar una variable de tipo int como una función, quizás usando el valor de algún return o por error de tipeo (2(6+3) en vez de 2*(6+3)). Necesitas debuggear porque es un error muy puntual.

**Comment by perojas3** [comment]
El error ocurre cuando muevo el mouse por el tablero, mientras se estan reponiendo los hexagonos.
Pero mientras no haga click, no pasa nada negativo.
