### ISSUE TITLE
Pregunta sobre los usuarios baneados

### ISSUE THREAD

**Issue by TristanPouliquen** [IIC2233-2016-1/syllabus#27]
Hola,

En el enuncio de la tarea1, es escrito que debemos recordar los correos de los usuarios baneados para que estos no pueden reinscribirse con este correo. 

Pero, en [banea2.txt](https://github.com/IIC2233-2016-1/syllabus/blob/master/Tareas/T01/Enunciado/banea2.txt), hay solamente el nombre del usuario. 

Debemos solamente considerar el nombre del usuario o agregar el correo para los nuevos usuarios baneados ?

Gracias :smiley:

**Comment by bamavrakis** [comment]
Hola!
Como dice el enunciado, deben considerar el correo del usuario baneado sin modificar el archivo banea2 (eso no implica que no puedan crear otros archivos)
Saludos!

**Comment by bamavrakis** [comment]
Como soy buena persona, añadí los correos a la lista de baneados para que lo modifiquen directamente en banea2.txt :dancer: 
Saludos!

**Comment by TristanPouliquen** [comment]
Gracias ! :)
