### ISSUE TITLE
Forma de entrega

### ISSUE THREAD

**Issue by isipalma** [IIC2233-2016-1/syllabus#270]
Hola,

Queria saber si solamente hay que subir nuestros codigos, o mejor tambien subimos el gui? (yo creo que solamente los codigos pero me aseguro preguntando :3 )

Saludos

**Comment by bamavrakis** [comment]
Hola! Sube todo, nosotros al recolectar nos encargaremos de filtrar los archivos que corregiremos ;)
Saludos!
