### ISSUE TITLE
[T02] Flores

### ISSUE THREAD

**Issue by isarovic** [IIC2233-2016-1/syllabus#271]
Hola! 
Cuando los flores son alternadas, de estrellas o de espejos, ¿Se borran las piezas ? ¿O solamente sucede eso con la flor normal?

Saludos!

**Comment by flobarrios** [comment]
Hola! si, se destruyen las 6 piezas a su alrededor y se genera una especial en el centro dependiendo del tipo de flor (alternada genera un espejo, y las de estrellas y espejos generan un black pearl).

**Comment by isarovic** [comment]
Gracias!
