### ISSUE TITLE
Duda con castear

### ISSUE THREAD

**Issue by JoseDaroch** [IIC2233-2016-1/syllabus#272]
Leí todas las otras issues sobre lo que hablaban de castear pero aun no me queda 100% claro, se que quizá sea muy repetitivo pero ... directamente me gustaría saber si puedo hacer lo siguiente para leer los archivos de las partidas guardadas:
Leer cada linea y separarla por comas y cada uno de los elementos que me entrega ese split llevarlo mediante un for uno a uno a mi lista.
Gracias!

**Comment by agmardones** [comment]
Según yo no puedes, porque estarías usando directamente la lista del split, lo que podrías hacer es implementar el casteo para listas, onda `MyList([1,2,3])` y poder hacer `MyList(line.split(','))`, para hacer esto ve el último comentario de #259. Ojalá te sirva!
