### ISSUE TITLE
Otro error raro

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#273]
Veran,tengo una funcion llamada generador continuo, es un generador que genera de manera aleatoria los tipos de hexagonos. Sin embargo, cuando lo uso para agregar fichas. Me sale este error:

`QPixmap::scaled: Pixmap is a null pixmap`

¿Que hago?

**Comment by Cnmoya** [comment]
Hola,aprovecho de comentar que tengo el mismo problema.
Ademas me aparecen algunas piezas raras
por ejemplo que sean transparentes o con la estrella corrida
![img](https://cloud.githubusercontent.com/assets/17578068/14503334/117160d0-0186-11e6-901d-3b213295a2fd.png)

**Comment by otro-felipe** [comment]
esto pasa alningresar algun tipo de forma incorrecta o al no tener las imagenes guardadas como deberian.
