### ISSUE TITLE
Terminar el Juego

### ISSUE THREAD

**Issue by Zepk** [IIC2233-2016-1/syllabus#275]
En caso de que el jugador haga un cluster de black pearls, o que una bomba explote ¿como se hace para que termine el juego?

¿Tengo algún método que que cierre la ventana o basta con que le diga por consola que gano o perdió, o hay algún método que haga alguna animación bonita de game over?

**Comment by agmardones** [comment]
#243

**Comment by Zepk** [comment]
Gracias! :)
