### ISSUE TITLE
Problema tarea

### ISSUE THREAD

**Issue by matnagra** [IIC2233-2016-1/syllabus#276]
El comando move_piece y add_piece supuestamente pueden recibir una funcion como argumento que sera ejecutada cuando se ejecute la anumacion. Me pasa que la funcion que reciben como argumento se ejecuta antes que la funcion move_piece o add_piece.
No se por que pasa esto y he probado de todo

**Comment by agmardones** [comment]
y se la pasas sin paréntesis?, (`on_move_end=funcion` no `on_move_end=funcion()`)

**Comment by matnagra** [comment]
aun asi no funciona

`def borrar(piece):
    piece.deleteLater()
    return

class MyInterface(gui.GameInterface):

```
def piece_clicked(self, row, column, section, piece):
    gui.move_piece(row, column+1, piece, on_move_ended=borrar(piece))`
```

por ejemplo este codigo. si tengo una pieza en 0,0 me la deberia mover a la columna de al lado y despues borrarla, pero lo que en verdad hace es borrarla y despues me arroja un error al intentar moverla porque dice que no hay nada en ese espacio....

**Comment by otro-felipe** [comment]
Se ha mencionado en repetidas ocasiones que la funcion debe ir sin parentesis y no puede llevar parametros.
