### ISSUE TITLE
Se me olvido poner algo en el readme ¿Que hago?

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#278]
En el readme, se me olvio poner que cuando se mueve el maouse mientras los hexagonos se mueven, se produce un error en la consola. Pero este error no afecta el juego, y se puede ignorar sin problemas.
Pero se me olvio colocar esto en el readme. ¿Puedo hacer algo al respecto?

**Comment by gafigueroa** [comment]
Puedes subir un nuevo readme que lo incluya.

**Comment by negebauer** [comment]
@perojas3 Aprovecho de comentarte que tu readme de la tarea 1 y tarea 2 están malos. Tienes que hacer un archivo README.md en markdown. No un .pdf y cambiarle la extension.
Básicamente, tu README no se ve

**Comment by JoseDaroch** [comment]
Si igual se me olvido poner una cosa lo puedo subir de nuevo? (¿no hay problema con plazos de entrega?)
Ademas igual por apurado lo subí como pdf, podría aprovechar de cambiarlo a .md (en la tarea 1 lo hice bien jaja)

**Comment by flobarrios** [comment]
Hola, si lo puedes modificar (no se descuenta por modificar el README fuera de plazo).

**Comment by perojas3** [comment]
Ok, muchas gracias, los modifico cuando lleque a mi casa en la tarde.

**Comment by perojas3** [comment]
Una cosa más.
¿Podrian dejar claro lo del markdown y el pdf  aquí?
https://github.com/IIC2233-2016-1/syllabus/issues/143
Es para evitar futuros errores

**Comment by negebauer** [comment]
@perojas3 Es muy simple, tienes que crear un archivo .md y escribir ahí. Igual que si fuera un .txt
Fíjate en los README.md que hay en el syllabus
