### ISSUE TITLE
Una duda de decoradores

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#279]
Estoy haciendo la actividad de decoradores del semestre 2015-1. El de las hamburgesas.
Puedo hacer 2 de los 3 ejercicios (el de comparar y el de los precios), pero el de la lista me acompleja bastante, vi la solucion pero no la entendi.
¿Como es eso de tener una clase con un atributo, no una instancia de la clase con el atributo?
¿Como consigue eso de Hamburgesas.instancias?

Lo que hace en la solucion es hacer el decorador que retorne un nuevo init con el comando `clase.instancias.append(self)`
¿Pero a que propiedad corresponde eso? ¿Se puede hacer sin decoradores?
Aparte, ¿Una instancia de una clase puede llamarse a si misma con self de esa forma? ¿Como se deve hacer para evitar que ocurra un error? Se que bajo otras circunstancias el programa se pega.

Eso seria.

**Comment by andresfdezc** [comment]
Para empezar, hay que tener claro que **una clase también es un objeto**. De hecho, es una instancia de alguna metaclase (que predeterminadamente es `type`). Veremos esta materia en la ayudantía del lunes.

Como una clase es un objeto más se le pueden agregar atributos propios. En este caso el decorador `guardar_instancias(clase)` le añade a la clase una lista vacía llamada instancias (al usar `setattr(clase, 'instancias', list())`). Esta lista vacía va a ser sólo de la clase, y **no** de sus instancias, por lo que su referencia será `clase.instancias`.

Aquella lista se puede añadir sin decoradores modificando la clase directamente, escribiendo sus propios atributos fuera de los métodos que contiene:

``` python
def Clase:
    instancias = list()

    def algun_metodo(self, *args, **kwargs):
        pass
```

Por otra parte, una instancia de un objeto se puede referenciar a sí misma dentro de alguno de sus métodos con el nombre del primer argumento, que por convención es `self`. Hacer esto no es un error.

Finalmente, cuando el decorador reemplaza el método `__init__` de la clase, está indicando en el `new_init` que después de que se instancie un objeto, dicho objeto se guarde a sí mismo (_self_ en inglés) dentro de la lista instancias que tiene su clase.

**Comment by perojas3** [comment]
Ok, muchas gracias.
