### ISSUE TITLE
Error en archivo personas.txt

### ISSUE THREAD

**Issue by Mieynaudi** [IIC2233-2016-1/syllabus#28]
Hola!, tengo un problema con el archivo personas.txt, mas especificamente con los usuarios, el enunciado dice que los nombres de usuario son unicos, pero en el archivo existen usuarios repetidos y mi programa utiliza un diccionario donde la 'key' es el usuario, entonces los sobreescribe. Debo cambiar el programa o efectivamente los nombres de usuario no se deberían repetir?

**Comment by bamavrakis** [comment]
Hola!
Se acaban publicar nuevos archivos que solucionan este problema :)
Saludos!

**Comment by jecastro1** [comment]
FIXED
