### ISSUE TITLE
Duda Metaclases

### ISSUE THREAD

**Issue by isipalma** [IIC2233-2016-1/syllabus#281]
Hola, buenas.

Queria saber que diferencia hay entre el overriding de `__init__` y el de `__call__` pues no me quedaron muy claros (se que `__call__` se llama al hacer una instancia de la clase, pero cuando se llama al `__init__`?
Otra duda que tengo es con el `return` de la metaclase, pues en un ejemplo el `return` utilizaba `super()`. mientras que en otro se utilizo `type`. Que diferencia tienen?

Eso seria todo, y gracias por su tiempo ;)

**Comment by otro-felipe** [comment]
Hola! Cuando creas un objeto este tiene varias etapas en las que es procesado para poder terminar convirtiéndose en una instancia de una clase. Además de esto, python también entrega métodos especiales, que son llamados cuando se utilizan los métodos en conjunto con alguna sintáxis de python. Para ser más claro:

#### Instanciación

Cuando creas una instancia esta pasa por una etapa _"pre-instanciación"_ en donde aun la instancia no existe y está a punto de ser creada y otra etapa que ocurre una vez tu clase ya está instanciada y formada como un objeto en python pero "vacía" por decirlo de alguna forma.
- `__new__`: Este método es llamado durante la primera etapa y recibe los mismos parámetros que el `__init__`. En este momento tu instancia aún no ha sido creada, por lo que aun no existe el self. El primer parámetro de esta instancia corresponde a la misma clase del objeto, por eso se prefiere reemplazar el `self` por `cls` como parámetro de este método. Este método retorna la instancia de tu objeto, por eso cada vez que es llamado este método se debe llamar al `super().__new__` que es el que hace toda la pega por detrás para crear la nueva instancia.
- `__init__` : En este método la instancia ya está creada y viene en el parámetro `self`. Aquí viene una instancia _nueva_ lista para ser construida y agregarle todos los atributos que tú quieres que tenga. Este método, como ya debes saber, no retorna nada.

#### Métodos especiales

Son métodos que principalmente hacen _overload_ de operadores. Entre ellos esta el `__eq__`(=), `__gt__`(>), etc. Uno de estos métodos es `__call__` que hace overload de los paréntesis. Es decir, es un método que se ejecutará cada vez que existan paréntesis en frente de una instancia. Por ejemplo:

``` python
class MiClase:

    def __call__(self):
        print("¿Por qué llamas?")

a = MiClase()
a()  # Imprime "¿Por qué llamas?"
```

Como en metaclases, las instancias corresponden a las mismas clases, el call ocurre cuando se llama a `MiClase()` porque **MiClase** es una instancia de la metaclase `type`.

En términos simples el `__new__` y el `__init__` de **MiMetaclase** son llamados al momento de hacer lo siguiente:

``` python
class MiClase(metaclass=MiMetaclase):
...
```

El `__call__` de **MiMetaclase** es llamado a la hora de hacer `MiClase()` y recibe todos los parámetros que puedan ir dentro de los paréntesis, por lo que es ideal que solo uses `args` y `kwargs`.
