### ISSUE TITLE
metaclases

### ISSUE THREAD

**Issue by IsaacConDosA** [IIC2233-2016-1/syllabus#283]
Holaa, tengo una duda con respecto al `__new__` y al `__init__` : 
¿Lo que retorna el `__new__` es lo que recibe como `cls` el `__init__`? por eso se pueden hacer "cambios profundos"?
Saludos y gracias

**Comment by santiagocruzb** [comment]
[AYUDANTIA] Podrían subir la ayudantía que estaba preparada para hoy? Por lo general explican mejor la materia que el html.
Saludos.

**Comment by aaossa** [comment]
@ifcarrera efectivamente es así :+1: . Puedes hacer el siguiente "experimento":
- Guarda lo que vas a retornar en el `__new__` de la metaclase en una variable, imprime su id y luego retornalo.
- Recibe en el `__init__` de la metaclase `cls` y luego imprime su id. Deberían corresponder al mismo identificador y por tanto al mismo objeto.

@santiagocruzb: Ya fué subida, y la subí como Pull Request para que le llegara un correo incluso a quienes tienen **Watch** al repositorio (arriba a la derecha). Te recomiendo "hacer watch" del repositorio para que las futuras notificaciones te lleguen al correo y puedas enterarte de cualquier cambio importante que hagamos :grin:

**Comment by santiagocruzb** [comment]
![image](https://cloud.githubusercontent.com/assets/13748925/14627018/cc10abf0-05c6-11e6-8b92-30b2e074d42b.png)
Jajajajaj dale gracias!
