### ISSUE TITLE
Actividad para la materia  de metaclase

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#286]
Tal y como la semana pasada, desearia conocer cual es la mejor actividad para asegurarnos que entendimos la materia de Metaclase.
Lo deseo saber ahora porque tengo una ventana mañana en el modulo 3, y considero que es el mejor momento para hacerla. Y si no la entiendo, puedo tener preguntas listas para la ayudantia en el modulo 5.

**Comment by tamycova** [comment]
Hola, puedes intentar resolver la actividad 09 y 10 del syllabus del semestre pasado (cuyo link está en el README del syllabus de este año).
