### ISSUE TITLE
Contenidos archivos CSV

### ISSUE THREAD

**Issue by andersskog** [IIC2233-2016-1/syllabus#287]
En el archivo viajes.csv se encuentran las líneas:

27682102,86,
27682102,,86

Podemos asumir que estas líneas están malas? o significa que no existen datos? 

Gracias de antemano!

**Comment by tamycova** [comment]
Hola, significa que los datos no están (las tablas son de la Encuesta Origen Destino del gobierno), puedes ignorar estas líneas (di que lo hiciste en el README).

**Comment by vjmoreno** [comment]
se puede borrar simplemente esa linea?
