### ISSUE TITLE
Tarea 3, RAM, Clases

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233-2016-1/syllabus#289]
Quería saber si era rentable, en términos de ram, si yo logro (de una forma) crear clases de cada documento que me pidan y trabajar con ellos. Por ejemplo en el documento "sexo.csv", crearía 2 clases con 2 atributos cada clase(id y Sex). la primera clase tendría id = 1 y Sex = "Hombre" y la segunda clase tendría id = 2 y Sex = "Mujer"
y así con los demás documentos que me pidan, así podría trabajar casi del mismo modo como fue la actividad 5.
Es posible o mejor veo otro forma?

**Comment by flobarrios** [comment]
Hola !! Recuerda que tiene que ser capaz de leer cualquier base de datos, de cualquier tamaño y tambien puede tener muchos atributos. No creo que sea lo mas conveniente. Saludos!

**Comment by Hernan4444** [comment]
Oka, muchas gracias por la respuesta.
