### ISSUE TITLE
Metaclase 

### ISSUE THREAD

**Issue by IsaacConDosA** [IIC2233-2016-1/syllabus#290]
Hola, aún no me queda claro, ¿ por qué el `__new__` no modifica el `name` y las `bases` que recibe el `__init__` (si estoy retornando la clase con los cambios hechos) pero el diccionario de atributos sí?

**Comment by otro-felipe** [comment]
Debes estar haciendo algo mal, recuerda que el nombre de la clase es almacenado en el parámetro `__name__` y que el parámetro `bases` es una tupla, por lo tanto es inmutable, por eso debes usar otras formas de modificar este parámetro (esta fue la primera forma que se me ocurrió). Intenta usar este código y dime cómo te va :)

``` python
class FakeObject:
    pass


class Meta2(type):

    def __new__(meta, name, bases, attr):
        name += "Meta"
        bases_2 = list(bases)
        bases_2.append(FakeObject)
        return super().__new__(meta, name, tuple(bases_2), attr)


class Innocent(metaclass=Meta2):
    pass


a = Innocent()
print(Innocent.__name__)  # Imprime InnocentMeta
print(isinstance(a, FakeObject))  # Imprime True
```

**Comment by IsaacConDosA** [comment]
@MainScientist No era eso, gracias por esa explicación de todas maneras. 
Quizás me expliqué mal. La pregunta es: ¿por qué después de hacer el `__new__`, cuando se ejecuta el `__init__` de la metaclase, el parámetro "name" y "bases" que recibe el `__init__` no es el que cambié en el `__new___`, sino el mismo que recibió como parámetro el `__new__`?
