### ISSUE TITLE
No coincide la nota del e-mail con el excel

### ISSUE THREAD

**Issue by fnquinteros** [IIC2233-2016-1/syllabus#291]
me mandaron al mail la nota de la recorrección de la AC02. Con esa nota estoy conforme, sin embargo, la nota que aparece en el excel de notas es distinta (menor) y quería saber que debo hacer en este caso, ¿Enviar un mail al coordinador? mi intención no es recorregir, sino que quede bien subida la nota.

**Comment by jecastro1** [comment]
Solved
