### ISSUE TITLE
Tarea 3, RAM, listas

### ISSUE THREAD

**Issue by JoseRomeroi** [IIC2233-2016-1/syllabus#292]
Hola, quería saber si puedo utilizar el comando file.readlines() para leer los archivos .csv, ya que esto me retornaria una lista. Puedo hacerlo, o tengo que leer el archivo necesariamente usando programacion funcional? Es eficiente en terminos de RAM?

**Comment by Nebula2028** [comment]
+1 ya que yo tambien estoy leyendo los archivos asi (al menos despues de la primera linea con los campos, para la que uso file.readline()

**Comment by negebauer** [comment]
Pueden usar `file.readlines()` para leer los archivos pero tomen en cuenta que el programa debe funcionar con archivos grandes, **muy** grandes.
Si cargas todas las líneas se podría quedar sin RAM y morir 😢 
Les recomiendo que desde ya usen `readline()` y vayan leyendo línea a línea para no tener problemas

**Comment by negebauer** [comment]
Recuerden que el programa debe funcionar con archivos grandes, **muy** grandes por lo que cargar todas las líneas podría llenar la RAM y hacer que se caiga 😢
Además no pueden iterar sobre listas como detalla el enunciado.
Les recomiendo que desde ya usen `readline()` y vayan leyendo línea a línea para no tener problemas.

**Comment by negebauer** [comment]
Recuerden que el programa debe funcionar con archivos grandes, **muy** grandes por lo que cargar todas las líneas podría llenar la RAM y hacer que se caiga 😢
Además no pueden iterar sobre listas como detalla el enunciado.
Les recomiendo que desde ya usen `readline()` y vayan leyendo línea a línea para no tener problemas.

**Comment by micostabal** [comment]
Hola! Me gustaría saber qué se entiende por "muy grande", en ordenes de magnitud. ¿Cómo cuánto hace que se llene la RAM y se caiga?

**Comment by otro-felipe** [comment]
Todo va a depender del espacio disponible que tenga la RAM al momento de ejecutar el programa. Por muy grande nos referimos a archivos mas grandes que la RAM disponible.

**Comment by elzambon** [comment]
Hola me gustaría en base a lo mismo del RAM saber si una estructura en particular soportaría lo que piden, la estructura es crear una lista de instancias de una namedtuple para cada archivo que se utilizara para las consultas? o lo único que soportaría lo pedido es trabajar con solo generadores? por ej un generador que dentro tiene las instancias de namedtuple
Saludos

**Comment by andersskog** [comment]
Hola! Ciertas partes de la tarea (Agrupatelos X, Ordenatelos X) requieren de sortear los datos. Para sortear datos es necesario para un computador tener todos los datos de lo que se requiere sortear, por lo tanto, se debe hacer con una estructura que no es un generador. Sorted crea una lista de los datos entregados (incluso si esto es un generador). Dado lo anterior, sería posible que nos den algún hint de como realizar esto asegurando eficiencia en la memoria?

Por el momento, yo estoy filtrando las tablas (ONDE) con generadores y al terminar esto convierto los datos a listas, asumiendo que ya no serán datos muy grandes. Desde la lectura de archivos hasta la finalización del filtro de tablas TODO esta hecho con generadores.
1) Esta bien hacer esto?
2) En caso que no, cual será la penalización?

**Comment by fdoflorenzano** [comment]
@andersskog Es una forma de hacerlo, y en primera instancia **no hay descuentos por eficiencia** mientras se respeten las restricciones de la tarea (fors y whiles). Yo intentaría terminar la tarea y luego ver temas de eficiencia si fuera tu.
