### ISSUE TITLE
Sobre los comandos de la tarea

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#293]
En los ejemplos del pdf, siempre se hace exactamente un solo comando por linea. Y en el ultimo se utiliza un `;`

Eso significa, en consola,esto:
[primera linea] `EMPRESTA edad` [preciono enter]
[Segunda linea] `DE Persona;` [preciono enter]
[Se ejecuta el programa]

¿O me estoy confundiendo?

**Comment by negebauer** [comment]
Para que no tengan que gastar más tiempo en parseo el formato de las consultas será de una consulta completa por línea.

```
EMPRESA edad DE persona;
```

**Comment by perojas3** [comment]
Tampoco importan los espacios. Ejemplo:

```
EMPRESTA                       edad
DE                       persona;
```

**Comment by jtagle2** [comment]
Respecto a los saltos de línea. Se puede asumir que después del ";" no empezará una instrucción en la misma linea? 
Por ejemplo, podemos asumir que
`EMPRESTA edad`
`DE persona; EMPRESTA`
`sexo DE persona;`
No ocurrirá?

**Comment by negebauer** [comment]
@perojas3 @jtagle2 Se reviso este tema, revisen mi comentario actualizado arriba ^

**Comment by perojas3** [comment]
OK, gracias. Entonces supondre que siempre vendra un comando correcto.
