### ISSUE TITLE
No entiendo a lo que se refieren a funcional.

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#294]
En el pdf dicen solo restricciones respecto a whiles y loops.
Pero me deja la duda segun que cosa más se puede hacer.
¿Pueden darme una lista de las cosas que se pueden o que no se pueden hacer?
Es que en este momento siento como si no pudiera hacer nada.

**Comment by flobarrios** [comment]
Hola !! esas son las restriciciones además de que no se puede usar ninguna librería a menos que se encuentre especificado en #284. Respecto a funcional, fíjate en el [material de clases](https://github.com/IIC2233-2016-1/syllabus/tree/master/Material-de-clases/03-FUNCTIONAL)
