### ISSUE TITLE
COMUN CN y SACALE

### ISSUE THREAD

**Issue by andersskog** [IIC2233-2016-1/syllabus#295]
Para estas dos funciones, las consultas comparadas deben tener el mismo número de columnas?
Si no es el caso, como comparo las filas?

Gracias!

**Comment by fdoflorenzano** [comment]
Hola! Funcionan igual que UNETELO CN en ese sentido, él número de columnas en ambas tablas entregadas tiene que coincidir, y los tipos tienen que coincidir en el **orden** que vengan. Es decir, dos resultados de consulta con tipos:
- (int, int, int) UNETELO CN (int, int). **No funciona**, por **número** de columnas.
- (int, str) UNETELO CN (str, int). **No funciona** por **tipos no coincidentes en orden**.
- (int, str) UNETELO CN (int, str) **Funciona** por que coinciden el número de columnas, y los tipos en orden tambíen coinciden.

La misma regla corre para UNETELO CN, UNETELO TODO CN, COMUN CN y SACALE.

Saludos!
