### ISSUE TITLE
Duda con el diccionario attr en Meta (AC10 - 1-2015)

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2233-2016-1/syllabus#296]
Hola!! En la actividad 10 del primer semestre, defino así la clase Meta, pero cuando la hago correr, hay veces que no funciona. La verdad no sabría explicar por qué, pero creo que tiene que ver con el orden que crea attr... cuando intento setear una property, me dice error de llave: __ module __, por ejemplo. Las clases las defini tal como en el enunciado. ¿Qué puede ser? Gracias de antemano!

``` python
class Meta(type):

    def __new__(meta, name, bases, attr):
        atributos_futuros = {}
        metodos_futuros = {}

        for attribute_name in attr:
            debiera_ser_clase = attr[attribute_name]
            if isinstance(debiera_ser_clase, type):
                clase = attr[attribute_name]
                attribute_name = '_' + attribute_name
                atributos_futuros.update({attribute_name: attr[attribute_name[1:]]()})

                def obtenedor(self):
                    print ('obteniendo')
                    return self.__dict__[attribute_name]

                def cambiador(self, otro):
                    if isinstance(self.__dict__[attribute_name], clase):
                        self.__dict__[attribute_name] = otro
                    else:
                        print('ERROR')

                metodos_futuros[attribute_name[1:]] = property(obtenedor, cambiador)


        def inicializar(self):
            self.__dict__.update(atributos_futuros)

        attr['__init__'] = inicializar
        attr.update(metodos_futuros)

        return super().__new__(meta, name, bases, attr)
```

**Comment by otro-felipe** [comment]
No veo el codigo que mencionas en la [solución de la actividad 10 de ese semestre.](https://github.com/IIC2233-2015-1/syllabus/blob/master/Actividades%20en%20Clases/Actividad%2010/Soluci%C3%B3n/solucion.py) ¿Estás seguro que estás viendo la solución que corresponde?

**Comment by AlfonsoIgnacioV** [comment]
sí... esta parte la escribí yo, es la solución que se me ocurrió, pero no sé porqué no funciona
