### ISSUE TITLE
For y whiles en generadores

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#297]
¿Se permite usar for y whiles en generadores?
¿Osea, retornar con un yield?

**Comment by bamavrakis** [comment]
Hola, perdón por la demora. Si se permite utilizarlos en generadores.
Saludos!

**Comment by noksenberg** [comment]
Esto quiere decir que se puede usar for y while dentro de una funcion libremente siempre y cuando se retorne con yield?

**Comment by tamycova** [comment]
Si puedes, pero ojo si quieres imitar operadores funcionales como si fueran for's solamente poniendole un yield en vez de return, porque pierdes el objetivo de la tarea.
