### ISSUE TITLE
Consulta sobre el retorno del metodo __init__ en una metaclase

### ISSUE THREAD

**Issue by iavasquez1** [IIC2233-2016-1/syllabus#298]
Al momento de querer retornar en una metaclase en el metodo `__init__`, pycharm me lanza un error mencionando de que no puedo retornar un valor desde `__init__`, ¿alguien sabe por qué esto ocurre?. Estuve viendo la materia y también se muestra que el `__init__` también retorna a `super().__init__(parametros)`.

**Comment by otro-felipe** [comment]
en #281 hablo un poco del método `__init__`. Este método no debería retornar nada, pero no hay problemas si pones un return, de todas formas el valor de este return es completamente ignorado, por lo que es completamente inocuo ponero o no.
