### ISSUE TITLE
No me llegan pautas al correo

### ISSUE THREAD

**Issue by cggutierrez** [IIC2233-2016-1/syllabus#299]
Según tengo entendido deberían llegarme las pautas de las actividades y tareas al correo, cosa de la que me entere hoy por medio de un amigo dado a que no me ha llegado nada, tengo que configurar algo o tienen mi correo mal? ayuda :C

**Comment by flobarrios** [comment]
Hola !! Estan en tu repositorio privado, como issues. Saludos!

**Comment by negebauer** [comment]
Tienes que ponerle watch a tu repositorio privado para que te lleguen los mails

**Comment by cggutierrez** [comment]
gracias!

**Comment by caackermann** [comment]
Pero en el repositorio privado estan las pautas o el feedback? Yo solo tengo issues con el feedback de las actividades/tareas y la distribucion de puntaje, pero ninguna pauta.

**Comment by negebauer** [comment]
El feedback es la pauta

**Comment by flobarrios** [comment]
Hola ! Para tareas y actividades solo se sube el fedback. Saludos!

**Comment by caackermann** [comment]
Ahh, perfecto. Nunca los van a subir? Como para saber la manera correcta/eficiente de resolverlas?

**Comment by negebauer** [comment]
Te refieres a la solución?
No se tiene planeado subirlas
