### ISSUE TITLE
[TAREA 01][¿Correos electrónicos válidos?]

### ISSUE THREAD

**Issue by cdonoso** [IIC2233-2016-1/syllabus#30]
Estimados tengo una duda:

En la parte de ingreso y registro sale que el sistema debe aceptar nuevos usuarios con un correo electrónico válido. ¿¿¿Que es un correo electrónico válido o que esperan que sea??? :cry: :cry: 
(Creo que no sale en el enunciado)

Saludos!

**Comment by negebauer** [comment]
Un correo electrónico válido es aquel que sigue un formato tipo `usuario@dominio`
Para más información al respecto te dejo [wikipedia](https://en.m.wikipedia.org/wiki/Email_address)

**Comment by cdonoso** [comment]
Muchas gracias @negebauer !!
