### ISSUE TITLE
utilidad metodo __init__

### ISSUE THREAD

**Issue by IsaacConDosA** [IIC2233-2016-1/syllabus#300]
Hola, ¿por qué nos interesa hacer overriding de `__init__`, si en realidad lo que hace "todo" es el `__new__`? saludos y gracias

**Comment by andresfdezc** [comment]
Hola! Recuerda que el `__init__` la clase ya estará creada, mientras que el `__new__` no. Es cierto que casi todo se hace en el `__new__`, pero existirán algunas ocasiones en las que deberás realizar algo sobre la clase cuando esta ya fue creada. En definitiva, todo depende de en qué momento del proceso de creación quieras realizar algo.

**Comment by aaossa** [comment]
Felicitaciones eres la Issue º300 :tada:

**Comment by IsaacConDosA** [comment]
@aaossa :open_mouth: :open_mouth: cuántas décimas de regalo? :O
