### ISSUE TITLE
Consulta en consola

### ISSUE THREAD

**Issue by wayoalamos** [IIC2233-2016-1/syllabus#302]
Al escribir una consulta en consola, esta se debe escribir en consultas.txt?

**Comment by negebauer** [comment]
No es necesario, pero de hacerlo indícalo en el README

**Comment by tamycova** [comment]
No @wayoalamos  no es necesario!! Piensa en tu main como dos partes, primero lee consultas.txt y genera resultados.txt, y después mantiene su ejecución aceptando consultas una a una e imprimiendo resultados en pantalla :dancer:
