### ISSUE TITLE
Duda archivos

### ISSUE THREAD

**Issue by FernandoPieressa** [IIC2233-2016-1/syllabus#303]
Hola, no estoy entendiendo muy bien los archivos a cargar, yo debería poner una opción dentro del programa donde le de la opcion al usuario que archivos cargar? o cargo todo lo que este en la carpeta del main?

**Comment by Geeermy** [comment]
Hola! De partida, revisa #302 para que entiendas la dinámica que pedimos.
Entendido esto, las tablas a cargar son las indicadas al principio del archivo. Recordemos que la estructura es:
Número de archivos a cargar
archivo 1
...
Número de consultas a procesar
consulta 1
... 
Solo debes cargas las que están antes de "Número de consultas a procesar".
Ahora, si quisieras darle al usuario la opción de editar esto desde un menú en consola (añadir o quitar tablas), puedes hacerlo siempre que lo explicites en el READ ME. Pero ten en cuenta que no es un requisito de la tarea.
Espero haber sido claro.
Saludos y éxito! :)

**Comment by vjmoreno** [comment]
@Geeermy y se puede cambiar el formato de las consultas que está en el archivo consultas.txt? , por ejemplo pasar de:

`EMPRESTA Persona,Sex DE personas,sexo ONDE AnoNac=2013 Y Id=Sexo Y Sex="Mujer";`

a tener:

`EMPRESTA: Persona,Sex; DE: personas,sexo; ONDE: AnoNac=2013 Y Id=Sexo Y Sex="Mujer"`

**Comment by Geeermy** [comment]
@vjmoreno No! el formato de las consultas es estándar, **deben** leerlo tal como se los entregamos. Las modificaciones que pueden hacer y explicitar en el READ ME son las del manejo en consola con el usuario para ver si la hacen dinámica, o solo de lectura de archivos, lo demás **no se cambia**.
PD: Lo hacemos así porque es similar a algo que verán en cursos posteriores **(spoilers)**

**Comment by ManuelSIlvaCav** [comment]
Tengo una duda respecto al formato de las consultas, geermy dice que vienen con un formato estandar las consultas, por lo que no se pueden editar como se plantea arriba, pero en #293 , se dice que las consultas podrian venir de cualquier formato con saltos de linea y no necesariamente del formato "estandar" que dicen. Cual es finalmente la forma de leer consultas, para la forma en que vienen los ejemplos o cualquier consulta que llegue con cualquier formato
Gracias

**Comment by Geeermy** [comment]
@ManuelSilvaCav a lo que yo hago referencia es al formato del texto. Si te fijas, en el ejemplo de @vjmoreno se cambia el formato de la escritura añadiendo ":" a cada comando, eso NO va a pasar. Los espacios grandes y saltos de líneas darán lo mismo.
Espero que ahí esté claro :)
Saludos!

**Comment by IsaacConDosA** [comment]
@Geeermy asumimos que siempre habrá el archivo consultas.txt con las tablas a cargar?, es decir, siempre habrán tablas a cargar con el correspondiente archivo existente verdad?
sl2

**Comment by flobarrios** [comment]
@ifcarrera si puedes asumir eso!
