### ISSUE TITLE
¿Qué opción utilizaría menos RAM?

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#304]
¿Tener muchos diccionarios de pequeña extensión dentro de una lista? ¿o que cada valor de una key de un diccionario tenga una extensa lista de valores? ¿o ambos serían igual? La pregunta también va a un sentido más bien en general: ¿cómo respondo ese tipo de preguntas en general?

**Comment by otro-felipe** [comment]
A priori no sabría responderte, claramente va a depender de la extensión de las listas extensas y qué tan muchos sean esos diccionarios. El tema no es trivial [aquí se habla de esto](http://stackoverflow.com/questions/33978/find-out-how-much-memory-is-being-used-by-an-object-in-python). De todas formas puedes usar testearlo usando varios ejemplos con [sys.getsizeof](https://docs.python.org/3/library/sys.html#sys.getsizeof). No sé qué tan preciso sea, pero puede llegar a ser una buena aproximación.

**Comment by MortizDX** [comment]
Muchas gracias por la respuesta, voy a revisar los links y sí tengo alguna duda de lo mismo lo volveré a abrir.
