### ISSUE TITLE
Archivos .csv que deben ser leidos

### ISSUE THREAD

**Issue by vjmoreno** [IIC2233-2016-1/syllabus#305]
Mi programa debe trabajar solo con los archivos que se encuentren detallados dentro de consultas.txt? Por que hasta el momento trabajo con todos los que tengo dentro de cierta carpeta.

**Comment by Geeermy** [comment]
Hola! Sí, solo los detallados (en el ejemplo los dimos todos, pero pudo haber sido diferente).
Si quieres hacer algunas consideraciones con la modalidad del programa, revisa lo expuesto en #302 y #303.
Saludos! :D
