### ISSUE TITLE
Número de tablas en consultas.txt

### ISSUE THREAD

**Issue by santiagocruzb** [IIC2233-2016-1/syllabus#306]
Hola! En el enunciado sale que tiene que salir en el archivo `consultas.txt` arriba debe salir el número (N) de tablas que se le está entregando. Ese N es a lo más 4, no? No me hace sentido que se entreguen tablas que entreguen el mismo tipo de información (ej, `personas1.csv` y `personas2.csv`), ni que se le entreguen tablas que no vienen en el formato que estamos leyendo (ej, `autos.csv`).
Confirmación de esto?
Desde ya muchas gracias!

**Comment by jtagle2** [comment]
Lo que tengo entendido, es que al final lo que tenemos que implementar es el LCJ, y este es independiente de las bases de datos (el único requisito es que esté en formato csv), pero da lo mismo si es con 1 o con 100 bases de dato, el tema es poder interpretar y filtrar cualquier archivo csv. Porque por ejemplo, despues podría haber otra base de datos (precio.csv) que informe precio de los viajes, y en ese caso tendría que leer mas bases
Comento para saber igual

**Comment by Geeermy** [comment]
Hola! Como dice @jtagle2 tiene que ser independiente a los archivos que les damos. Con esto me refiero a que **no se basen únicamente a los archivos dentro de la carpeta de la tarea.** La idea es que si añaden más archivos que cumplan el formato se puedan incluir en LCJ sin problemas, no hay un límite para N.
Con respecto a lo de la información, **la revisión que haremos no incluirá archivos csv que contengan columnas con el mismo nombre entre archivos, aunque sí podrían contener el mismo tipo de datos** (imagínate un csv con alumnos de un colegio, y otro con lo mismo, pero de un colegio diferente). Y por esto mismo, añadir un archivo como "autos.csv" debería funcionar también, ya que tu código debe identificar cualquier tipo de formato (recalcando que no te bases en los archivos de ejemplo).
Espero haber podido aclarar todos tus puntos. Si quedan dudas, no dudes en preguntar de nuevo.
Saludos!
