### ISSUE TITLE
Duda con readlines()

### ISSUE THREAD

**Issue by IsaacConDosA** [IIC2233-2016-1/syllabus#307]
Tengo la siguiente duda; entiendo que no debemos usar readlines() para leer un archivo porque se podría caer para archivos grandes, ¿pero podemos de todas formas crear una lista por compresión recorriendo cada línea? Se caerá de todas formas al hacer eso? 
Recomiendan hacerlo o esperan que lo hagamos de otra forma?
Saludos

**Comment by aaossa** [comment]
Sí, se caería de todas formas porque `readlines()` retorna una lista, el archivo completo. Independiente del procedimiento que hagas sigues usando la misma memoria que hacer `variable = archivo.readlines()`

Hay otras formas de hacer esto con generadores  :grin:

**Comment by santiagocruzb** [comment]
@aaossa y `readline()`?
