### ISSUE TITLE
Nota 7 al pie de página

### ISSUE THREAD

**Issue by bmarinb** [IIC2233-2016-1/syllabus#308]
"Nos interesa que no usen los ciclos for y while en lo que son las funcionalidades logicas del programa. Pueden utilizarlos
para imprimir valores, por ejemplo."

¿Puedo usar for para escribir el archivo resultados?
EDIT: Por ejemplo, hacer un for sobre un map() que me entrega todo lo que debo escribir dada una consulta, e ir escribiendo sobre el archivo resultados

**Comment by rodolfopalma** [comment]
Sí, se puede usar `for` para efectos de escritura de archivos!
