### ISSUE TITLE
Duda con algunas condiciones

### ISSUE THREAD

**Issue by rmant** [IIC2233-2016-1/syllabus#309]
Hola! No me quedó claro como funcionan las condiciones "PARECIO A, ENTRE, EN,
EXISTE", si me podrían dar un ejemplo de cada una feliz. En el enunciado no encontré ninguno. Gracias!

**Comment by aaossa** [comment]
Fusionaré esta issue con #328. Cualquier comentario posterior realizalo en esa issue por favor :grin: Gracias!
