### ISSUE TITLE
[T03] Cantidad de operaciones en consulta

### ISSUE THREAD

**Issue by micostabal** [IIC2233-2016-1/syllabus#311]
No me queda claro leyendo el enunciado de la tarea, qué debe hacer nuestro programa en el caso de que tengamos más de una operación que involucre dos busquedas en la sentencia de consulta. Estas operaciones que involucran de algún modo dos bases de datos serían : UNETELO CN, UNETELO TODO CN, COMUN CN, SACALE. Por ejemplo, podríamos tener algo así como:
(EMPRESTA nombre DE Persona) UNETELO (CN EMPRESTA nombre DE Persona) UNETELO CN (EMPRESTA nombre DE Persona( UNETELO (CN EMPRESTA nombre DE Persona) ...UNETELO CN (EMPRESTA nombre DE Persona), de forma de tener operaciones sucesivas de estas bases de datos.
La pregunta es ¿se puede sumar más de una vez o tener una secuencia de estas operaciones binarias?
En caso de que se pueda, ¿cómo sería la sintaxis para operaciones que no sean necesariamente asociativas? 
En caso de que no se pueda tener más de una de estas operaciones "binarias", ¿podríamos decir que el número de 'Empresta' en cada consulta, puede ser como máximo dos?
¿esta respuesta corre para la cantidad de busquedas anidadas también?

**Comment by tamycova** [comment]
No me queda clara tu pregunta! puedes explicarla más?

**Comment by micostabal** [comment]
Pueden probar nuestro programa con una sentencia en LCJ que contenga más de una de las siguietnes operaciones: UNETELO CN, UNETELO TODO CN, COMUN CN, SACALE?

**Comment by tamycova** [comment]
Si, en consultas anidadas por ejemplo

**Comment by tsuarezsaieh** [comment]
Pero solo en una consulta anidada? 
Se podría algo así?: ((EMPRESTA nombre DE Persona) UNETELO CN (EMPRESTA nombre DE Persona)) UNETELO CN (EMPRESTA nombre DE Persona)

Donde unimos el resultado de una unión con otra sentencia?

**Comment by fdoflorenzano** [comment]
Sí, puede ser algo así. @tsuarezsaieh
