### ISSUE TITLE
archivos

### ISSUE THREAD

**Issue by IsaacConDosA** [IIC2233-2016-1/syllabus#312]
En el caso de que en algunas lineas no aparezca un dato, por ejemplo: en "Comunas.csv", hay una linea que dice comuna NO ESPECIFICA, esto se debería imprimir como resultado si ponen EMPRESTA Comuna?

**Comment by negebauer** [comment]
Si dice NO ESPECIFICA ese es el dato que debes imprimir.
Para datos que no estén (string vacío) fíjate en #287
