### ISSUE TITLE
Problema con recursion

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#313]
Veran, tengo este problema. Estoy haciendo una funcion recursiva que lee e imprime cada linea del .csv.
Pero python no imprime completo, y cuando le quito el `try` y el `exept` me lanza el siguiente error:
`RuntimeError: maximum recursion depth exceeded while calling a Python object`
¿Que me recomiendan hacer?

**Comment by perojas3** [comment]
Ya vi que se podia usar fors para imprimir valores. Esta soucionado

**Comment by jtagle2** [comment]
En todo caso, con funcional se puede hacer algo como:
`list(map(print, iterable))`

**Comment by tamycova** [comment]
@perojas3  si esta solucionado por favor cierra la consulta para que no se acumule!
