### ISSUE TITLE
Pregunta consultas

### ISSUE THREAD

**Issue by noksenberg** [IIC2233-2016-1/syllabus#314]
Al revisar las consultas, nuestro programa debe asegurar que existen ciertos comandos mínimos? Es decir, si una consulta por ejemplo no tiene el comando 'EMPESTA', se debe identificar como un error?

Sí es así, que comandos se consideran como mínimos? y podemos asumir que estos siempre estarán?

Gracias

**Comment by flobarrios** [comment]
Hola ! Los comandos mínimos que debe tener una consulta son EMPRESTA y DE. Sin embargo, para esta tarea, puedes asumir que todas las consultas ingresadas no vendrán con errores y serán válidas.

**Comment by sitoro** [comment]
En el punto 7.3 del enunciado también se nos pide que el programa no se caiga ante errores en las consultas y muestra algunos ejemplos. Entonces ¿Las consultas con las que nos evaluarán serán efectivamente todas válidas?

**Comment by rodolfopalma** [comment]
@sitoro Sí. Revisa el anuncio de #339.
