### ISSUE TITLE
Duda uso de if en Tarea 3

### ISSUE THREAD

**Issue by bvfernandez** [IIC2233-2016-1/syllabus#315]
Hola!! sé que tenemos que ocupar programación funcional pero quería saber si podemos definir alguna función que tenga un if/else (por lo tanto tendría que ocupar return)

**Comment by tamycova** [comment]
Por supuesto que puedes usar return, if, else! La restriccion está en las iteraciones no más no te compliques :)

**Comment by bvfernandez** [comment]
perfecto, gracias!! @tamycova
