### ISSUE TITLE
Uso de for en diccionario por comprensión

### ISSUE THREAD

**Issue by bceppi** [IIC2233-2016-1/syllabus#316]
Tengo una duda respecto al enunciado, en la parte que dice:

> Se permite el uso de loops (for y while) **solo en listas y generadores por comprensión**.

Mi duda es que si se refiere, a que en la estructura de datos **(cual sea)**, sea por comprensión para poder usar _for_ y _while_, o que exclusivamente en listas y generadores (por comprensión) se pueden usar.
Saludos.

**Comment by flobarrios** [comment]
Hola!! se pueden usar exclusivamente en generadores y listas por comprensión. Fíjate igual en lo que dice el enunciado:

_Nos interesa que no usen los ciclos for y while en lo que son las funcionalidades lógicas del programa. Pueden utilizarlos para imprimir valores, por ejemplo._

**Comment by JoseDaroch** [comment]
Y en funciones generadoras?, podemos usar for y whiles? (fuera de las listas por compresion)

**Comment by flobarrios** [comment]
Si!

**Comment by noksenberg** [comment]
Hay alguna manera de formar diccionarios de está forma? (Que requieran iteración para su construcción)
