### ISSUE TITLE
Duda sobre while y funciones

### ISSUE THREAD

**Issue by cggutierrez** [IIC2233-2016-1/syllabus#317]
Como podemos ocupar los  while dentro de generadores? estuve buscando y solo encuentro el while normal y for dentro de iteradores pero hay cosas que creo que necesitare while como por ejemplo en una función generadora Contador, y hablando de funciones, se pueden definir funciones o simplemente tenemos que usar lambda en todo el código?

**Comment by perojas3** [comment]
Yo pregunte lo mismo y todavia no me responden:
https://github.com/IIC2233-2016-1/syllabus/issues/297

**Comment by cggutierrez** [comment]
mi pregunta es distinta

**Comment by tamycova** [comment]
Sí, obvio que puedes definir funciones! Lambda es una forma de definirlas "on the fly", pero es igual de válido que respondas tus propias funciones. La primera parte no la entendí (?) te recomiendo revisar la materia :)

**Comment by cggutierrez** [comment]
la primera parte me referia a que no encuentro como usar un while  en el estilo  (...for i in algo...) o para eso mejor usamos un while de los "normales" en funciones generadoras?

**Comment by tamycova** [comment]
@cggutierrez  para iterar no necesitas usar el while, puedes usar operadores funcionales que iteren como un "for"

**Comment by cggutierrez** [comment]
ah vale, pensaba en el while para tener una condicion en CONTEA pero supongo que debe haber otra forma entonces, gracias :)
