### ISSUE TITLE
Iterar sobre listas

### ISSUE THREAD

**Issue by Zepk** [IIC2233-2016-1/syllabus#320]
# Se permite el uso de loops (for y while) solo en listas y generadores por comprensión

No me queda claro el significado de esto, osea, yo puedo crear una lista por comprensión usando un for, algo del estilo:
`lista = [x for x in cosa]`

Pero luego de eso, una vez creada mi lista por comprensión, puedo usar un for para iterar sobre ella? Es decir algo del estilo:

```
lista = [x for x in cosa]
for cosa in lista:
    print(cosa)
```

(Aqui hasta donde llega mi entendimiento, estoy usando un for en una lista por comprension)

Otra manera de iterar podria ser esta:

```
def leer_archivo(archivo):
    a = iter(archivo)
    while True:
        b = next(a)
        yield b

a = leer_archivo(algo)
for x in a:
    #hacer algo
```

Pero aca tambien esoy usando un for en un generador, y no se si esto es a lo que se referian en el enunciado o no

O tengo que iterar de otra manera?

**Comment by bmarinb** [comment]
@Zepk Estuve un buen rato preguntándome eso. La idea es usar built in functions.

**Comment by fgvenegas** [comment]
La idea es que utilicen programacion funcional y built-ins para, por ejemplo en tu caso, iterar sobre una lista

**Comment by Zepk** [comment]
@fgvenegas Bueno, pero no has respondido mi pregunta, están permitidas o no las cosas que escribí en la pregunta original?

**Comment by tamycova** [comment]
@Zepk 
Esta definitivamente NO:
lista = [x for x in cosa]
for cosa in lista:
    print(cosa)
Y la otra falla por el for que usas, no queremos ver ningún for en la lógica de tu programa a menos que este adentro de una lista por compresión, o los casos que ya se han visto en otras issues.

**Comment by Zepk** [comment]
Gracias por la respuesta! :D

**Comment by caackermann** [comment]
Y al ocupar:
`lista = (x for x in cosa)
for cosa in lista:
    hacer algo`
Tampoco se puede? Ya que ahi estaria iterando sobre un generador y no una lista.

**Comment by rodolfopalma** [comment]
@caackermann hola! la línea que pusiste no parece ser sintaxis válida de Python 3 y no entendí bien a qué te refieres, puedes reformular la pregunta?

**Comment by Zepk** [comment]
Se refiere a lo siguiente:

```
generador = (x for x in cosa)
for cosa in generador:
    #hacer algo
```

Aqui en teoría haces un generador al comienzo, y luego iteras sobre el mismo

**Comment by caackermann** [comment]
A eso me refería!, no aparecieron los saltos de línea. Es válido hacer eso?

**Comment by tamycova** [comment]
@Zepk @caackermann sigue siendo no válido, la iteración puede hacerse con los comandos funcionales o dentro del mismo generador.

**Comment by caackermann** [comment]
Ok.gracias!

**Comment by bvfernandez** [comment]
Una pregunta, en la parte del ejemplo del manejo de errores en el main (que sale en el enunciado) dice:
    for i in consultas:
        try:
            procesar_consulta(i)
Solo para confirmar... se puede ocupar este ejemplo para manejar los errores (por lo mencionado arriba)? Es decir,  puedo por ejemplo, en la otra parte del código, hacer un generador de consultas( o una lista por comprensión) y después iterar sobre el en el programa principal como lo hace el ejemplo?
