### ISSUE TITLE
Iteraciones dobles

### ISSUE THREAD

**Issue by rmant** [IIC2233-2016-1/syllabus#321]
Una pregunta, ya que en la tarea no puedo ocupar loops como fors, como lo puedo hacer para hacer una iteracion doble con un generador?, por ejemplo si quisiera hacer algo como
`for fila in filas:
    for columna in columnas:`
Gracias!

**Comment by IsaacConDosA** [comment]
Tengo la misma duda, me pasa que puedo iterar solo una vez. Porque se acaba el segundo generador y no puedo hacerlo :(

**Comment by ManuelSIlvaCav** [comment]
cps

**Comment by aaossa** [comment]
Evitemos los "cps", suscribanse a las notificaciones de una issue si les interesa. Si les interesa el repo hagan watch (arriba a la derecha):

![image](https://cloud.githubusercontent.com/assets/10425834/14770701/2608a1c2-0a4e-11e6-8378-c58953883176.png)

Tanto en Facebook como aquí, en Github, existen sistemas para evitar las respuestas que no aportan a la discusión y que son solo para marcar seguimiento. Los invitamos a usar Github correctamente :grin:  

@rmant: Tu quieres hacer algo así al parecer

``` python
a = [1, 2, 3]
b = [4, 5, 6]
c = [a, b]

todos = [numero for lista in c for numero in lista]
>> [1, 2, 3, 4, 5, 6]
```

**Comment by IsaacConDosA** [comment]
@aaossa en ese caso son listas, pero cuando los iterables son generadores, eso no se puede creo; porque al iterar completamente el generador que va en el segundo for, se "borra", y ya no se puede volver a iterar sobre ese generador para el segundo elemento del generador que está en el primer for. 
Algo así, creo:
`for i in generador1: for j in generador2`
Cuando i es el segundo elemento del generador1, el generador2 ya no existe.

**Comment by ManuelSIlvaCav** [comment]
sorry lo del cps, pero tomando lo anterior, como se puede aplicar logica a eso, es decir que algun if para que no se genere una lista con todos, por en general los dobles loop son para encontrar coincidencias entre dos listas. 
Y segundo para los generadores, existe alguna forma de que siga existiendo un generador una vez iterado, para iterarlo desde el inicio? o simplemente desaparece de la faz de la tierra y nada que hacer
Saludos

**Comment by rmant** [comment]
@aaossa No es eso lo que busco hacer, sino más bien algo como 
`(elemento for elemento in diccionario for diccionario in lista)`
Encontré que aparentemente se puede hacer algo similar con itertools.chain , pero no me quedó muy claro como aplicarlo. Gracias.

**Comment by wayoalamos** [comment]
@rmant  Existen comandos para solucionar ese mismo problema, hay que buscar en google.
