### ISSUE TITLE
Problema con Ordenalos X y agrupalos X

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#322]
Veran, aquí me pasa esto.
Algo que hay que tomar en cuenta es que hay que evitar que la memoria ram se llene. Y que deve terminarse las consultas en el tiempo adecuado teniendo .csv.
Este es el problema. Ambos comandos piden que se ordenen todos los datos de un .csv. El ordenalos exige que se ordene en orden numerico o alfavetico las lineas segun ese comando. Eso se puede hacer con sort en una lista (cosa que no se puede hacer porque una lista tan larga llenaria la memoria RAM), o con una funcion, pero el problema de eso es que, como el .csv es tan largo, no puedo almacenarlo en una lista por el RAM, ni en una clase por el limite de recurción, e intentar ordenar uno, luego ver el resto otra ves, ordenar el siguiente, ver el resto de nuevo, muy lento, y tardaria mucho con .csv muy largos.
¿Existe una forma de poder ordenar los datos sin tener que revisar todos los .csv, que se suponen que son muy largos?

**Comment by tamycova** [comment]
Hay formas más eficientes de hacer estas consultas, de hecho, es uno de los objetivos de la tarea que las encuentres! Algo que te puede ayudar es saber que los operadores funcionales son de tipo lazy (https://en.wikipedia.org/wiki/Lazy_evaluation), y esto te ayuda bastante en la eficiencia de tu programa. Además saber que los print te quitan mucha eficiencia a tu programa trata de mantenerlos al minimo; si una consulta es muy grande imprime las primeros resultados, y lo demás envialo a un .txt. Existen distintos tipos de algoritmos de ordenación que tu puedes implementar que son más acorde al problema, ya que sabes como tienes la disposición de datos y te puede ayudar =) .

**Comment by perojas3** [comment]
¿Me puedes decir de donde puedo sacar esos algoritmos por favor?

**Comment by fgvenegas** [comment]
Como se les enseño en una de las primeras ayudantías, tienen Google como la mejor herramienta a su disposición, estos algoritmos debes buscarlos y entenderlos por ti mismo ya que es parte de la dificultad de la tarea

**Comment by agmardones** [comment]
No se me ocurre como hacer sort sin almacenar los datos en listas. O no es necesario almacenarlos ni siquiera parcialmente? He googleado harto :(
