### ISSUE TITLE
ONDE "tabla_nombre.col_nombre" o "col_nombre"?

### ISSUE THREAD

**Issue by jonnylee719** [IIC2233-2016-1/syllabus#323]
En los ejemplos de la tarea pdf, tienen:

`EMPRESTA DIVERGENTE nombre, cantidad
DE Cervezas, En-Stock
ONDE En-Stock.nombre-cerveza = Cervezas.nombre
Y Cervezas.nombre PARECIO A "Cristal"
ORDENATELOS X cantidad PA RIBA;`

Segun lo que entiendo es para consultas de >1 tablas que tiene columnas del mismo nombre, e.g. `Cervezas.nombre = Vinos.nombre`. 

Pero en el consultas.txt no es el caso:
`EMPRESTA Persona,Sex DE personas,sexo ONDE AnoNac=2013 Y Id=Sexo Y Sex="Mujer";`

Mi pregunta: cuando la consulta es para >1 tabla, es `tabla_nombre.col_nombre` o `col_nombre`?

**Comment by tamycova** [comment]
Hola @jonnylee719 ! Lo correcto sería tabla.atributo, pero por simiplicidad ustedes pueden asumir que usaremos tablas con columnas sin nombres iguales, osea usaremos solo col_nombre ya que no será ambiguo a que tabla pertenece el atributo.
