### ISSUE TITLE
[T03] comando ONDE

### ISSUE THREAD

**Issue by fcorencoret** [IIC2233-2016-1/syllabus#324]
En el enunciado se ponen dos casos distintos para hacer el comando ONDE y queria saber si el programa tenia que funcionar para ambos o solo para uno. El primer caso solo dicen ONDE columna1 = columna 2, y el segundo caso es ONDE tabla1.columna1 = tabla2.columna2.
Gracias

**Comment by fgvenegas** [comment]
Revisa #323 creo que ahi se responde basicamente lo mismo, si tienes mas dudas puedes volver a preguntar, si quedas conforme cierra el issue :3
