### ISSUE TITLE
ONDE

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233-2016-1/syllabus#327]
Dentro del código nos pondrán ONDE complejos como:
  "x" == algo AND ("y">otro OR "q"!=otra)

¿O serán piadosos y pondrán patrones con puros OR o puros AND si es que la consulta va a usar algunos de esos?

**Comment by ManuelSIlvaCav** [comment]
Tengo la misma duda, sobretodo si los OR van a definir todo lo  que esta antes O todo lo que esta despues del OR, ya que si esta como el ejemplo de Hernan,se complejiza bastante la cosa buscando parentesis y encontrar las condiciones.

**Comment by salangarica** [comment]
idem anteriores D:

**Comment by bamavrakis** [comment]
Hola, para las consultas de este estilo, todos los argumentos del OR y AND correspondiente serán encerrados por paréntesis, como en el siguiente ejemplo: ONDE (((algo1) Y (algo2)) O ((algo3) Y (algo4)))
Como se puede observar, el primer Y está relacionado con algo1 y con algo1, el segundo Y relacionado con algo3 y con algo4, y el O está relacionado con los resultados de ambos Y.

Espero que haya quedado claro,
Saludos!

**Comment by ManuelSIlvaCav** [comment]
Espera... creo que hay un parentesis demas y te refieres a que entonces el O alude a que se cumpla el primer conjunto con 'Y' de algo1 y algo 2 O el segundo 'Y' de algo3 y algo4 ??

**Comment by bamavrakis** [comment]
Sobre lo primero, no se de que estas hablando :x, y sobre lo segundo sí, me refiero a eso.
Saludos!

**Comment by sormazabal** [comment]
Solo para clarificar:
En el archivo de ejemplo y en el PDF las consultas con Y y O salen sin paréntesis. Pero acabas de señalar que estas deberían llevar paréntesis. ¿Con cuál formato nos quedamos? (Pregunto porque justo estaba con problemas para elegir el orden de las condiciones y lo de los paréntesis me facilita harto la pega)

**Comment by flobarrios** [comment]
Hola !! Decidimos que ese tipo de consultas llevará paréntesis como explico @bamavrakis. Saludos!

**Comment by FranciscoRencoret1** [comment]
que pasa si no hay condicion O, hay parentesis igual? Seria asi? ONDE (algo1=algo2 Y algo3=algo4)

**Comment by fcorencoret** [comment]
que pasa si no hay condicion O, hay parentesis igual? Seria asi? ONDE ((algo1=algo2) Y (algo3=algo4))

**Comment by flobarrios** [comment]
Si! De igual forma lleva paréntesis. Saludos!

**Comment by cggutierrez** [comment]
tambien llevara parentesis una sola condicion? ej: ONDE (algo1=algo2)

**Comment by tamycova** [comment]
Sí!

**Comment by joaquinricci** [comment]
Podrian dar un ejemplo con el comand ENTRE, como se escribiria?

**Comment by Hernan4444** [comment]
Se pueden dar condiciones de este modo:
 (algo1=algo2) Y (algo3=algo4) Y  (algo5=algo6)
O siempre van a ser   "(x) operador (y)"
y por lo tanto deberia ser algo asi:
 ((algo1=algo2) Y (algo3=algo4)) Y  (algo5=algo6)

**Comment by tamycova** [comment]
@bamavrakis

**Comment by bamavrakis** [comment]
Hola! Efectivamente como mencionaste las condiciones siempre serán del tipo (x) operación (y) , por lo que el ejemplo que diste quedaría como lo último que planteaste. Saludos!

**Comment by diegosapunar** [comment]
podrian subir ejemplos concretos,ya que encuentro discrepancias entre el ejemplo, issues y enunciado, respecto a este tema (como van a presentarse las consultas). Gracias!

**Comment by rodolfopalma** [comment]
@diegosapunar Revisa #339.
