### ISSUE TITLE
Ejemplos Consultas

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233-2016-1/syllabus#328]
Es posible que suban algunos ejemplos usando los comandos que en el pdf no se usaron (como ENTRE, PARECIO A, etc) y algunas consultas BASTASTE complejas para darnos la idea si nuestros programas logran entender esas consultas o todavía nos falta por mejorar el programa.

No es necesario subir archivos o resultados, solo ejemplos de consulta para guiarnos un poco mas.

Ojala se pueda,Gracias de antemano.

**Comment by bamavrakis** [comment]
Hola! , se subirán en el transcurso del día o a lo más mañana :)
Saludos!

**Comment by Hernan4444** [comment]
Oka, Muchas gracias :)
Saludos!

**Comment by aaossa** [comment]
La dejaré abierta hasta que se suban los ejemplos como recordartorio

**Comment by rodolfopalma** [comment]
#339
