### ISSUE TITLE
Tarea 3: Formato de las consultas

### ISSUE THREAD

**Issue by JoseRomeroi** [IIC2233-2016-1/syllabus#330]
En el archivo consultas.txt aparece:
EMPRESTA Persona,Sex     (sin espacio entre Persona,sex)

En el enunciado de la tarea, en el pdf aparece:
EMPRESTA nombre, nombreProducto     (con espacio entre nombre, nombreProducto)

Nuestro programa debe funcionar para ambos casos? o nos guiamos por el formato que aparece en consultas.txt (sin espacio) y lo especificamos en el Readme

**Comment by bamavrakis** [comment]
Hola! El programa debe funcionar para el segundo caso, es decir, con un espacio entre nombre y nombreProducto.

Saludos!

**Comment by ManuelSIlvaCav** [comment]
Lo del espacio aplica a todos los metodos de la consulta entonces? onda espacio entre operadores =, >, < y espacio entre DE tabla1, tabla2 ??

**Comment by cggutierrez** [comment]
entonces para adecuarnos a este formato modificamos nuestro consultas.txt agregando el espacio para ir probando nuestro codigo?

**Comment by JoseRomeroi** [comment]
@bamavrakis misma pregunta que  @cggutierrez . El archivo consultas.txt está erróneo y debemos añadirle un espacio luego de las comas para poder probar?

**Comment by tamycova** [comment]
@ManuelSIlvaCav , @cggutierrez  hoy vamos a hacer un anuncio para aclarar estas dudas menores de manera transversal!

**EDIT:** #339
