### ISSUE TITLE
Tamaño tablas

### ISSUE THREAD

**Issue by rmant** [IIC2233-2016-1/syllabus#331]
El programa debe soportar cualquier tamaño de tablas sin importar lo grande? Mi pc se queda sin ram al hacer por ejemplo empresta todo de Personas,Viajes; , que seria una tabla de 113592 x 60055 filas. Sin embargo con todas las demas combinaciones de los ejemplos funciona bastante rápido.

**Comment by bjassael** [comment]
Yo computé la tabla y no me quede sin ram, pero se demoró mucho tiempo de la manera que lo hice.  Es posible optimizar para que de la tabla de 113592 x 60055 filas en un tiempo aceptable?

**Comment by micostabal** [comment]
Cómo uno cacha cuándo se queda sin RAM? ¿Cuánto tiempo es el máximo que esperan por cada consulta?

**Comment by tamycova** [comment]
hola! @bjassael , @micostabal , @rmant  vean un issue que vamos hacer dentro de una hora!

**Comment by rmant** [comment]
@tamycova Qué pasó con el Issue? Gracias!

**Comment by diegosapunar** [comment]
me pasa lo mismo que @bjassael

**Comment by tamycova** [comment]
@rmant  al final vamos a hacer un aviso con todo, ejemplos nuevos, etc pq no todos ven las issues! asique estamos en eso

**EDIT:** #339
