### ISSUE TITLE
Duda con uso de lambda

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#332]
Caso: Tengo una función1 que obtiene algunos lambda (lambda1 x: {retorna un bool según algo} y lambda2 x: {retorna un bool según otra cosa}) de otra función2 que lo retorna (según ciertas condiciones) y función1 retorna 'lambda1 and lambda2'.

Duda: Si hago 'nueva_función = función1()' y luego quiero usar nueva_función con ciertos datos ¿por qué solo necesita una variable para ejecutar ambos lambda dentro de ella? ¿No es posible que cada lambda utilice variables independiente entre sí? Mi intención sería que 'nueva_función' entregue el bool si se cumplen ambos lambdas, pero eso no ocurre con 'and'.

**Comment by bamavrakis** [comment]
Hola, no entendí tu pregunta. Formulala de otra forma y te contesto :P.
Saludos!

**Comment by MortizDX** [comment]
``` python
def funcion2(string):
      if 'mayus' in string:
         return lambda x: x.isupper()
     elif 'minus' in string:
        return lambda x: x.islower()

def funcion1(s1,s2):
    return funcion2(s1) and funcion(s2)

a = funcion1("mayus","minus")
print(a("CASA", "casa"))
print(a("casa","mesa"))
```

Mi intención sería que, en el primer caso me tirara true al cumplirse ambas condiciones y un false para el segundo, pero python solo deja poner una variable y trabaja con ella en ambos casos, lo que no es mi idea.
¿Se entiende mejor así?

**Comment by fdoflorenzano** [comment]
Creo haber entendido, el problema está en la forma de funcion1 que debiese retornar una función que evalue con más argumentos, el siguiente código me dio el resultado que quieres:

``` python
def funcion2(string):
    if 'mayus' in string:
        return lambda x: x.isupper()
    elif 'minus' in string:
        return lambda x: x.islower()

def funcion1(s1,s2):
    def funcion3(a,b):
        return funcion2(s1)(a) and funcion2(s2)(b)
    return funcion3

a = funcion1("mayus","minus")
print(a("CASA", "casa"))
print(a("casa","mesa"))
```

**Comment by MortizDX** [comment]
Muchísimas gracias, eso era exactamente lo que quería.

**Comment by MortizDX** [comment]
Experimentando me ha surgido otra duda que deriva de lo mismo. 

Si tengo dentro de una funcion2 (distinta al caso anterior) otra funcion3 como en el caso anterior (es decir, también requiere de dos variables) ¿cómo puedo utilizar args para asignar acordamente las variables que corresponden? 

Lo único que se me ha ocurrido es separar los argumentos con tuplas, de modo que se trabaja como si fuera un árbol binario con parentesis, pero pregunto por si hay otro medio, en especial para casos en que se complica más las combinaciones.
