### ISSUE TITLE
[T03] DIVERGENTE

### ISSUE THREAD

**Issue by fcorencoret** [IIC2233-2016-1/syllabus#334]
Como funciona el comando DIVERGENTE? Si hago DIVERGENTE nombre significa que debo solo retornar las filas donde el nombre sea unico (no repetido en la tabla)? Si tengo fila1 = (pedro , 1, 2) y fila2= (pedro, 3,4) deberia solo retornarme la primera fila? 

O el comando deberia retornar solo las filas enteras que estan duplicadas? Que en ese caso me retornaria ambas filas?

Gracias

**Comment by flobarrios** [comment]
Hola! si seleccionas solo el nombre, debes retornar todos los nombres y sin repeticiones por lo que en este caso sería solo pedro. Ahora si haces algo como EMPRESTA DIVERGENTE nombre, id DE Tabla, en donde el id es la segunda columna, debieses retornar pedro, 1 y pedro, 3 ya que ahora las filas son distintas. Saludos!
