### ISSUE TITLE
[T03][Duda Consultas]

### ISSUE THREAD

**Issue by vbarros2** [IIC2233-2016-1/syllabus#335]
Que pasa si por ejemplo:

EMPRESTA persona
DE Personas,Viajes

Que personas se imprimen, las de personas o viajes?? Esto es un caso particular pero se da mucho ya que persona esta en ambas tablas...

Gracias

**Comment by flobarrios** [comment]
Hola! Recuerda que todas las columnas tendran nombres distintos por lo que se imprimirá las personas de la tabla cuya columna se llame persona. Para que retorne lo de ambas tablas, debe ser algo como EMPRESTA personas, p_viajes DE Personas, Viajes. En donde p_viajes corresponde a la columna de Viajes y personas a la de Personas. Saludos!

**Comment by vbarros2** [comment]
Lo que pasa es que en los del ejemplo se llaman igual pero lo voy a cambiar...

Gracias!

**Comment by flobarrios** [comment]
En #323 se explico eso igual!! Cambia el ejemplo pero igual recuerda que probaremos con tablas distintas.
