### ISSUE TITLE
Error tipeo de la tarea 'Los operadores validos en ONDE son <, >, <=, => !=,'

### ISSUE THREAD

**Issue by wayoalamos** [IIC2233-2016-1/syllabus#336]
Los operadores validos en ONDE son <, >, <=, => !=,.
Solo por aclarar, supongo que en el penúltimo hay un error de tipeo.

**Comment by tamycova** [comment]
porque falta una coma dices tu?

**Comment by joaquinricci** [comment]
es >= no =>, eso @wayoalamos ?

**Comment by tamycova** [comment]
@wayoalamos  te convocamos

**Comment by IsaacConDosA** [comment]
@tamycova Hola, al final en los comandos pondrán "<=" o "=<" ?? o debiera funcionar para ambos casos? 
Saludos y gracias :smile:

**Comment by flobarrios** [comment]
hola!! los comandos correctos son:

```
X < Y (X menor a Y)
X > Y (X mayor a Y)
X <= Y (X menor o igual a Y)
X >= Y (X mayor o igual a Y)
X = Y (X igual a Y)
X != Y (X distinto a Y)
```

Si por alguna razón están usando => en vez de >=, traten de cambiarlo y si ya no pueden, especifiquen en el README para que no afecte en la corrección de su tarea 😄
