### ISSUE TITLE
Consulta ONDE

### ISSUE THREAD

**Issue by diegosapunar** [IIC2233-2016-1/syllabus#337]
En una consulta las condiciones pueden tener O e Y. (con paréntesis)

Por ejemplo: EMPRESTA nombre DE Producto 
ONDE nombre='Taza' Y (precio<10000 O id=0)

**Comment by tamycova** [comment]
@diegosapunar  ONDE ((nombre="Taza") Y ((precio<1000) O (id=0))) , estamos trabajando en el anuncio...

**Comment by rodolfopalma** [comment]
#339
