### ISSUE TITLE
NUEVO EJEMPLO Y ANUNCIO

### ISSUE THREAD

**Issue by tamycova** [IIC2233-2016-1/syllabus#339]
Hola, revisen el anuncio del SIDING pues se aclaran muchas cosas. También subimos un nuevo ejemplo con más consultas como solicitaron, el archivo resultados.txt lo vamos a subir pronto, igual mientras tanto es intuitivo si sus resultados cumplen la consulta o no.

Saludos

**Comment by cggutierrez** [comment]
Como maestro pokemon de hace años, esto me motiva y merecen mis honores, gotta catch'em all <3

**Comment by tamycova** [comment]
gotta EMPREST them all (?)

**Comment by cggutierrez** [comment]
![image](https://cloud.githubusercontent.com/assets/17582367/14874817/7e98502e-0cda-11e6-9208-dbc01d05d635.png)

**Comment by rodolfopalma** [comment]
Hola! Se acaba de subir un archivo llamado `resultados.txt` en la carpeta del ejemplo con lo que se espera retornen las consultas subidas ayer. También se corrigió un pequeño error de tipeo en `consultas.txt`. Pueden revisar los cambios en el [link del commit](https://github.com/IIC2233-2016-1/syllabus/commit/1f83ede00235b970ac464b4913fa133e475fa9a6).

**Comment by diegosapunar** [comment]
Una pregunta, cuando se hacen comparaciones de una columna con un valor; ¿Se mantendra el orden de los ejemplos?
es decir:

1) pokemon_id_especie <= 151
2) 151 >= pokemon_id_especie

Puedo asumir que siemore sera de la forma 1)... o puede presentarse de la forma 2)..

Saludos!

**Comment by fdoflorenzano** [comment]
Puede ser de ambas formas.

**Comment by noksenberg** [comment]
Puede ser que en la consulta 2 falten datos? por ejemplo abomasnow-mega tiene promedio 118.8 y no está

**Comment by fdoflorenzano** [comment]
@noksenberg Seguro? Revisé y su id es 10060, y las estadisticas que tiene son: 30, 90, 105, 105, 132, 132 que promedia  594/6 = 99. Casí Mega Abomasnow :(

**Comment by noksenberg** [comment]
Gracias!
