### ISSUE TITLE
funciones MATS,MIN,CONTEA

### ISSUE THREAD

**Issue by andersskog** [IIC2233-2016-1/syllabus#341]
Las funciones MATS,MIN,CONTEA,PROMDIO pueden aplicarse a más de una columna del EMPRESTA?

 Ej: EMPRESTA edad, max(altura), min(peso) AGRUPATELOS X edad.

Es esto una consulta válida?

**Comment by fdoflorenzano** [comment]
Sí, es valida.

**Comment by diegosapunar** [comment]
¿Estas funciones entregan tablas con  una fila (cuando estan en el empresta)?...

**Comment by fdoflorenzano** [comment]
No son tablas en sí, ya que retornan solo un valor. Puedes verlo como que se agrega como columna.

**Comment by diegosapunar** [comment]
@fdoflorenzano Puede exitir el caso que haya más de un condicion en el TENIENDO.
por ejemplo; 

AGRUPATELOS X pokemon_nombre TENIENDO ((PROMEDIO(poke_estadisticas_base) >= 100) Y (MATS(poke_ataque_ataque) < 100)

**Comment by joaquinricci** [comment]
En el ejemplo de @andersskog entregaria una tabla con tres columnas, la primeras serian las edades agrupadas, la segunda la altura maxima repetida para cada fila y la tercera el peso minimo repetido para cada fila??

**Comment by flobarrios** [comment]
Si, asi quedaría 😬

**Comment by diegosapunar** [comment]
@flobarrios y acerca de mi pregunta??

**Comment by fdoflorenzano** [comment]
@diegosapunar Sí, es posible, nunca se dijo lo contrario. Disculpa la demora.

**Comment by diegosapunar** [comment]
@fdoflorenzano Esta bien.. Gracias. Mi problema es que entre mas condiciones, mas se demora en correr, no se me cae el programa pero si se demora varios minutos..

**Comment by joaquinricci** [comment]
Podria existir la misma consulta ingresada por @andersskog al principio pero sin el AGRUPATELOS X edad??

**Comment by fdoflorenzano** [comment]
Sí, te respondí recién jaja @Jricci1

**Comment by agmardones** [comment]
@fdoflorenzano pero en el enunciado dice que son específicas de agrupatelos, o da igual?

**Comment by fdoflorenzano** [comment]
@agmardones No dicen que sean especificas, pero que se utilizan generalmente con AGRUPATELOS X. La idea es que al no poner ARGRUPATELOS X, todas las filas están en el mismo grupo por defecto. Con la diferencia que en ese caso se imprimen todos los miebros del grupo, en cambio al hacer AGRUPATELOS X solo imprime un representante.
