### ISSUE TITLE
Ayuda con consultas.txt

### ISSUE THREAD

**Issue by vjmoreno** [IIC2233-2016-1/syllabus#342]
Hola, hasta ayer iba bastante bien con el modelamiento de mi tarea, pero luego de los cambios hechos al archivo consultas.txt no se me ocurre una manera optima para trabajar con las consultas. Alguien me puede dar alguna pista de como comenzar a trabajar con las ellas? No se me ocurre nada y los paréntesis me complican demasiado.

Gracias de antemano .

**Comment by fdoflorenzano** [comment]
Pucha, la idea era que esto les facilitara la lectura de condiciones, además de que no deja espacio para condiciones ambiguas. Puedes ver a los paréntesis como una estructura predecible (siempre estará) y que esta te guía para encontrar las condiciones atómicas que deben cumplir las filas que se muestran finalmente. Además como las consultas tienen una estructura fija, hay que analizar caso a caso cuales partes están presenten y que aplicar sobre la consulta. Espero ayude, siento que no jaja Saludos!

**Comment by MortizDX** [comment]
Llevo ya muuuuchas horas dandole vuelta al asunto de los parentesis y en verdad no logro llegar a una solución ¿es posible separar adecuadamente las condiciones atómicas solamente con los built-in functions o acaso alguna librería es necesaria? Seriamente no se me ocurre que hacer con ello y es de las partes más dependientes de la tarea.
