### ISSUE TITLE
AGRUPATELOS X

### ISSUE THREAD

**Issue by andersskog** [IIC2233-2016-1/syllabus#343]
El agrupatelos X puede tener más de 1 columna?

**Comment by fdoflorenzano** [comment]
Como dice el enunciado, en AGRUPATELOS X se señalan **las** columnas por donde agrupar y coincidan los valores. Entonces sí.

**Comment by wayoalamos** [comment]
Pueden explicar bien como funciona el agrupatelos x cuando tienen dos o mas columnas? No entiendo

**Comment by fdoflorenzano** [comment]
Con una columna funciona agrupando todas las filas que coincidan en esa columna no? Si es `AGRUPATELOS X nombre`, todos los 'Fernando' se agrupan juntos. En cambio con 2, agrupa todas las filas que coincidan en **ambas** columnas, `AGRUPATELOS X nombre, edad`, entonces agrupa todos los  'Fernando' , 21. En ese caso, de existir 'Fernando', 18, este queda en otro grupo, al igual que 'Andrés', 21. Y así para cualquier número de columnas... Los grupos se forman al coincidir todas las columnas especificadas simultáneamente.
