### ISSUE TITLE
Uso de for y while

### ISSUE THREAD

**Issue by agmardones** [IIC2233-2016-1/syllabus#344]
Hola, está permitido tener una función que se encargue de enviarle valores a un generador?:

``` python
def enviador(lista, gen):
    gen.send(None)
    for i in lista:
        gen.send(i)

def recibidor():
    numero = yield
    while numero:
        #Hacer cosas con el numero
        numero = yield

a = enviador([1,2,3,4,5], recibidor())
print(a) # Esto imprime None, entonces a es un generador?
```

Gracias!

**Comment by rodolfopalma** [comment]
Está permitido tener una función que le envíe valores a un generador. Para la tarea, los ciclos sólo están permitidos al interior de los generadores y en la escritura de archivos. El `for` de la tercera línea del ejemplo que pones no corresponde a ninguno de los dos casos, por lo que en el contexto de la tarea, tu ejemplo no es válido.

**Comment by agmardones** [comment]
Y, entonces, qué objeto genera enviador al ser calleado :o? Si fuera generador, estaría permitido el uso del for
