### ISSUE TITLE
Sobre el main  

### ISSUE THREAD

**Issue by bvfernandez** [IIC2233-2016-1/syllabus#345]
Una pregunta, en la parte del ejemplo del manejo de errores en el main (que sale en el enunciado) dice:

``` python
for i in consultas:
     try:
           procesar_consulta(i)
```

Solo para confirmar... se podría ocupar este ejemplo para manejar los errores (por lo mencionado en #320 )? Es decir, puedo por ejemplo, en la otra parte del código, hacer un generador de consultas( o una lista por comprensión) y después iterar sobre el en el programa principal como lo hace el ejemplo?

**Comment by rodolfopalma** [comment]
No. El uso de ciclos `for` y `while` está restringido a escritura de archivos y **dentro** de generadores.

**Comment by bvfernandez** [comment]
bueno verificarlo, muchas gracias! @rpalmaotero
