### ISSUE TITLE
Sobre la repeticion.

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#347]
Tengo la siguiente duda. ¿Bajo cuales condiciones se pueden repetir impreciones iguales, y en cuales no?

**Comment by fdoflorenzano** [comment]
Si tiene DIVERGENTE, no deberían repetirse ninguna, pero si no lo tiene y en los resultados hay filas iguales, se repite.
Ej: Tabla Personas con dos columnas: nombre y edad, y dos filas: (Fernando, 21) (Fernando, 24).

```
EMPRESTA nombre DE Personas;
Fernando
Fernando
```

```
EMPRESTA DIVERGENTE nombre de Personas;
Fernando
```
