### ISSUE TITLE
¿Que tanto deve reconocer los Y y los O en los parentesis?

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#349]
Tengo esta dudua. Mi codigo puede leer sin problemas las condiciones cuando hay un solo T o un solo O, pero se confunde cuando hay más de uno de esta forma:
`((dato1 > dato2) O (dato3>dato1)) Y (dato4 = dato5)`
Porque detecta el primero solamente.
¿Deveria cambiarlo, o no nos pediran condiciones tan complejas?

**Comment by fdoflorenzano** [comment]
Debería ser capaz de reconocer condiciones complejas. Pero si tienes una forma de reconocer el primero, reconocer el resto no debería costar tanto más.

**Comment by perojas3** [comment]
El lo que hago es detectar los `) Y (` y `) O (`, hacer split en esos, pero el promea es cuando no es el primer  `) Y (` en el string. ¿Algun consejo para poder separar los parentesis?
