### ISSUE TITLE
[T01][time]

### ISSUE THREAD

**Issue by fcorencoret** [IIC2233-2016-1/syllabus#35]
Hola, una pregunta, se puede importar la libreria time para ver la hora actual? Para asi poder ver que subastas se cierran cuando parto el programa..

**Comment by flobarrios** [comment]
Duplicado: #20 Pero si se puede :)

**Comment by fcorencoret** [comment]
perdon, no me di cuenta de que era la misma libreria pense que eran distitnas. Otra pregunta, en el enunciado dice: 'Al momento de ingresar al sistema se deben ingresar la fecha y hora actuales, para una correcta interaccion con el programa', eso no significa que el usuario tiene que ingresarlas, sino que nosotros la tomamos (con los comandos de time) para efectos del programa cierto?

**Comment by priccis** [comment]
Creo que el usuario debe ingresarlo por motivos de prueba.
Así los correctores pueden publicar un producto con fecha de termino en
2017 y para ver si el sistema funciona luego hacen login con una fecha
futura (2019) y ven si se vencieron o no los artículos.

**Comment by gdburky** [comment]
Si es que se puede ingresar la fecha libremente ej: 2019 , esto quiere decir que se cerraran las subastas que expiren para esa fecha , por lo que se asociaran los productos a los distintos usuarios que los ganaron. Pero luego, si deseo entrar con una fecha anterior a 2019 mi programa debe ser capaz de deshacer todos los cambios que se hicieron cuando entre con el año 2019? Es decir, se deben borrar todos los cambios hechos en los archivos de textos (quitar lo productos ganados, reabrir subastas ya cerradas, etc).

**Comment by fgvenegas** [comment]
@tareos

**Comment by aaossa** [comment]
@IIC2233-2016-1/tareos

**Comment by vbarros2** [comment]
Algo que no entiendo es para que usar la librería time si igual es el usuario el que tiene que ingresar la fecha??. Y lo otro es que si el usuario la elije, tiene que ingresar seg, min, hora, día, año??
Gracias

**Comment by flobarrios** [comment]
Hola! 

@gdburky: queda a tu criterio actualizar/revertir los cambios hechos en los archivos de texto si es que lo consideres necesario siempre y cuando cumplas con lo especificado con el enunciado. O bien, puedes trabajar con fechas crecientes cronológicamente para que no tengas que "volver al pasado". Recuerda especificar en el README como abordaste este tema :smile: 

@vbarros2 : queda a tu criterio si el usuario ingresa la fecha o la obtienes a partir de la librería time una vez que este se logee. Usa la que encuentres mas últil y especificado en el README. Fíjate que los archivos (como subastasfin.txt) tienen un formato de fecha específico (dd/mm/aa/hh:minmin) por lo que si decides ingresarla en otro formato tendrías que ver como transformarla para trabajar con ambas :smile:

**Comment by tmorales1** [comment]
Esto incluye la libreria datetime cierto?

**Comment by flobarrios** [comment]
Si!

**Comment by IsaacConDosA** [comment]
@flobarrios tengo una duda respecto a lo que dijiste más arriba, si alguien al ingresar pone que es el año 2048, tengo que pasar todas las subastas de subastasact.txt a subastasfin.txt. Entonces cuando alguien ingrese posteriormente tengo que devolverlas o sino no habrá nada que comprar o no?

**Comment by flobarrios** [comment]
@ifcarrera efectivamente tendrías que actualizar los archivos, y si el usuario se conecta en una fecha posterior, busca una forma para informarle que no hay subastas vigentes.

**Comment by IsaacConDosA** [comment]
@flobarrios no entendí bien jaja :(. Si un usuario entra una fecha en que ya no quedan subastas, debo trasladar todas las subastas a subastasfin.txt. Pero después cuando alguien entre y ponga la fecha actual, no habrán subastas activas para comprar. ¿Puede pasar eso?

**Comment by flobarrios** [comment]
@ifcarrera fijate en lo que le respondí a @gdburky, si el usuario entra en una fecha anterior a la previamente ingresada, queda a tu criterio actualizar o revertir los cambios. O como dije, pueden suponer que se ingresan las fechas de forma lineal. Pueden hacerlo como quieran (de las 2 formas que dije) pero recuerden especificarlo en el README 😊

**Comment by jecastro1** [comment]
Si tienen una duda distinta de la original, por favor abrir otra issue. Así es más fácil buscar las respuestas para sus compañeros
