### ISSUE TITLE
duda: definir funcion con for, dentro de una funcion generadora

### ISSUE THREAD

**Issue by bvfernandez** [IIC2233-2016-1/syllabus#351]
mi duda está en que si podemos definir funciones (que tengan for o while y que use return ) DENTRO de una función generadora , para así,obviamente aplicarla. gracias :)

**Comment by flobarrios** [comment]
ve lo que dicen en #297

**Comment by bvfernandez** [comment]
Si lo ví 😁, pero me refiería a definir una funcion (que tenga for y que retorne algo) dentro de la funcion generadora. Por ejemplo:

```
Def funcion_generadora():
      Def funcion_interna():
              For i in algo:
                        #aqui hacer algo
              #hacer mas cosaa
              Return (otra cosa)

      For j in algunacosa:
             Yield funcion_interna(j)
```

**Comment by fdoflorenzano** [comment]
Se puede, pero ojo con los Fors internos. Si se pueden reemplazar por uno o más generadores que resulten en lo mismo, deberías hacerlo de esas forma.
