### ISSUE TITLE
Nombres del header

### ISSUE THREAD

**Issue by IsaacConDosA** [IIC2233-2016-1/syllabus#352]
Hola, los nombres de las columnas de los archivos que prueben, pueden estar escritos de cualquier forma? 
Es decir, pueden estar escritos todo con mayúscula, o solo la primera con mayúscula o todo con minúscula?

**Comment by flobarrios** [comment]
hola! si, pueden estar escritos de cualquiera de esas formas pero la consulta será consistente al nombre del header. Ej: si una columna se llama id, en una consulta NO se pedirá por ID. Saludos!
