### ISSUE TITLE
Persona en persona.csv y en viajes.csv

### ISSUE THREAD

**Issue by cggutierrez** [IIC2233-2016-1/syllabus#353]
En ambos archivos se encuentra el parámetro "Persona" el cual supuestamente según enunciado no debería ocurrir (según lo que entendí).  
La pregunta es, ¿ignoro eso y le cambio el nombre a una para trabajar o simplemente yo no he entendido algo y lo que llevo hasta ahora esta malo? ajjaja

**Comment by flobarrios** [comment]
hola!! si, cambia el nombre de de esa columna en alguna de las 2 tablas. Saludos!
