### ISSUE TITLE
Solicitud de cambio de fecha de entrega de tarea 3

### ISSUE THREAD

**Issue by iavasquez1** [IIC2233-2016-1/syllabus#354]
Dado a los cambios realizados en el archivo de consultas.txt, que afecta al trabajo que llevo avanzado, es que solicito si es posible que se realice un cambio de la fecha de entrega de la tarea 3. Agradeciendoles que consideren mi sugerencia ya que la fecha del lunes 2 de mayo no permitiría realizar mas avances.

**Comment by JoseRomeroi** [comment]
Me sumo a mi compañero, creo que debido a las aclaraciones claves echas tan en cima de la fecha de entrega, nos vendría bien un poco mas de plazo

**Comment by vbarros2** [comment]
En mi caso los cambios de enunciado y ejemplo fueron claves para avanzar con mi código, por lo que me sumo a la propuesta.
Gracias

**Comment by aaossa** [comment]
Espero hayan visto el correo, pero si no es así:

> Estimados,
> 
> Hemos decidido correr la fecha de entrega de la Tarea 3 para el Miércoles a las 23:59 horas debido a los cambios realizados la semana pasada.
> 
> Les recuerdo además que habrá ayudantía de simulación mañana Lunes, que será fundamental para la realización de la Tarea 4.
> 
> Saludos, Bastián
