### ISSUE TITLE
Consultas con MIN, MATS..

### ISSUE THREAD

**Issue by joaquinricci** [IIC2233-2016-1/syllabus#355]
Tengo un par de duas con respecto a este tipo de consultas:

1) Para la consulta EMPRESTA x, MATS(y), MIN (z) AGRUPATELOS X x:
cada fila tiene que ser un reultado donde el x no se repita y el y tiene que ser el mayor para ese especifico grupo de x y en caso de empate, se desempata con el menor en z o es el mayor y de todas las tablas el que se repite indefinidamente y el menor z el que se repite indefinidamente por cada dila??

2) Puede existir alguna consulta con EMPRESTA x, MATS(y), MIN (z) y que no posea AGRUPATELOS X?? si es asi, como seria el resultado.

**Comment by fdoflorenzano** [comment]
Hola!:
1) No hay desempates en las consultas, MATS(y) entrega el máximo valor de y en el grupo, si hay 2 valores máximos, entrega ese. MIN(z) entregaría el mínimo del grupo de la misma forma. EJ:

EMPRESTA nombre, MATS(edad), MIN(altura) DE Personas AGRUPATELOS X nombre:
Con filas en persona:
('Fernando', 21, 170)
('Fernando', 20, 170)
('Andrés', 19, 165)
('Andrés', 19, 180)
Resultaría:
Fernando | 21 | 170
Andrés | 19 | 165

2) Sí puede ocurrir, solo que al no especificar AGRUPATELOS X, todos pertenecen al mismo grupo y retornaría una tupla con el **primer x**, el máximo y, y el mínimo z. Para el caso anterior, sería:
Fernando | 21 | 165

**Comment by joaquinricci** [comment]
Muchas gracias! @fdoflorenzano 
para el 2, el resulltado seria
Fernando | 21 | 165, o solo Fernando?

**Comment by fdoflorenzano** [comment]
(Puse enter sin querer y la actualicé unos segundos después, pero sí, eso.)
