### ISSUE TITLE
Duda COMUN CN

### ISSUE THREAD

**Issue by bmarinb** [IIC2233-2016-1/syllabus#356]
Considerando la siguiente consulta
(EMPRESTA pokemon_id DE pokemon ONDE (pokemon_altura > 10)) COMUN CN (EMPRESTA pokemon_id DE pokemon ONDE (pokemon_peso < 200));

¿Es obligatorio que en cada consulta que tenga COMUN CN los empresta de cada subconsulta sean iguales?
- ¿O al menos que las filas emprestadas tengan datos del mismo tipo?

**Comment by fdoflorenzano** [comment]
#295 Se respondió aquí. (Respuesta: No es necesario)
