### ISSUE TITLE
¿Como funciona EXISTE y EN?

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#357]
Tengo una duda preincipalmente en esta. ¿Como funcionan?

**Comment by andersskog** [comment]
1) Si al hacer existe ... y no hay ningún resultado dentro de la consulta anidada, que debe retornar la consulta? un error o simplemente nada? Cual sería la utilidad de este existe?

**Comment by fdoflorenzano** [comment]
@perojas3. EXISTE() es un operador que evalua una consulta y de existir algún resultado en esa consulta, retorna TRUE, si no retorna nada, FALSE. En cambio EN, recibe una columna y una consulta, evalua la consulta y si la columna dicha existe dentro de la consulta, retorna TRUE. 

Ej:

```
EMPRESTA nombre DE Personas ONDE edad EN (EMPRESTA edad DE Personas ONDE nombre = 'Fernando');
```

Aquí, EN recibe la columna edad y la consulta anidada `EMPRESTA edad DE Personas ONDE nombre = 'Fernando'`. Esta última retornará todas las edades de personas llamadas Fernando. Luego para la consulta exterior, esta selecciona todas las filas donde edad está en este resultado, es decir, todas las personas que tengan edad igual a algún Fernando. (Que no necesariamente son solo Fernando's)

```
EMPRESTA nombre DE Personas ONDE EXISTE(EMPRESTA nombre DE Personas ONDE nombre = 'Camilo');
```

Aquí, para cada fila de Personas, la consulta debe evaluar la existencia de algún resultado para la consulta anidada. En este caso, como el resultado siempre es el mismo, entonces si la consulta retorna algo, todas las filas cumplen y por lo tanto debiese entregar todos los nombres, si no hay personas con nombre Camilo, entoces EXISTE retorna FALSE a todas las filas de la consulta externa y no retorna nada. En cambio, si existe algún Camilo, retorna TRUE para todos y retorna toda todo.

@andersskog El operador EXISTE en este contexto tiene poco sentido, originalmente teníamos la intención de pedirles algo extra para esta parte pero fue removido a último momento, lo cual le dejo poco sentido a este operador. Finalmente, retorna TRUE si la consulta anidada tiene algún resultado y FALSE si nada, resultado que seria el mismo para todas las filas de la consulta externa.

Espero se haya entendido!

**Comment by bmarinb** [comment]
Las condiciones del ONDE no deberían ir entre paréntesis?
`EMPRESTA nombre DE Personas ONDE (EXISTE(EMPRESTA nombre DE Personas ONDE nombre = 'Camilo'));
`

**Comment by fdoflorenzano** [comment]
@bmarinb sisi, me faltó ponerlo en los ejemplos jaja

**Comment by andersskog** [comment]
@fdoflorenzano que pasa cuando tenemos:

1) EMPRESTA nombre DE Personas ONDE ((EXISTE(EMPRESTA nombre DE Personas ONDE nombre = 'Camilo')) Y (edad>30));
2) EMPRESTA nombre DE Personas ONDE ((EXISTE(EMPRESTA nombre DE Personas ONDE nombre = 'Camilo')) O (edad>30));

Es decir: existe Y algo mas, existe O algo mas
Gracias!

**Comment by fdoflorenzano** [comment]
@andersskog Buena pregunta, hay 2 casos, que la consulta del Existe retorne algo o no.
- Si existe alguien de nombre Camilo, entonces EXISTE arroja TRUE para todas las filas. Para la primera consulta, como tiene un Y, dependera de la edad de cada fila. En cambio para la segunda, como ya retorna TRUE con un O, todas las filas cumpleen el ONDE y selecciona todas.
- Si no existe alguien de nombre Camilo, entonces EXISTE arroja FALSE y para la primera consulta ninguna fila es seleccionada y para la segunda dependerá de la edad.

**Comment by perojas3** [comment]
Osea printea True o False?

**Comment by fdoflorenzano** [comment]
No lo printea. Eso retorna EN o EXISTE en la valuación de los Y o O. Y dependiendo si para cada fila si cumplen la condición, debiese imprimir la fila.
