### ISSUE TITLE
TENIENDO

### ISSUE THREAD

**Issue by andersskog** [IIC2233-2016-1/syllabus#359]
Puede existir un teniendo sin estar presente el agrupatelos x

Ej:

EMPRESTA Persona, MIN(edad) DE  personas TENIENDO min(edad)>30

Es posible que suban más ejemplos de este operador y una descripción más amplia?

Gracias!

**Comment by sitoro** [comment]
No soy ayudante pero me atrevería a decir que no, pues en ese caso lo correcto sería usar un ONDE

**Comment by fdoflorenzano** [comment]
Tecnicamente se puede ya que la idea de TENIENDO es servir solo para funciones agregadas, pero para efectos de tarea y corrección, pueden asumir que solo aparecerá con AGRUPATELOS X.

**Comment by andersskog** [comment]
Cual será el formato?

TENIENDO ((MIN(edad) Y MATS(altura)) O ...)
o
TENIENDO (MIN(edad)),(MATS(altura))

**Comment by fdoflorenzano** [comment]
@andersskog En el anuncio de la semana pasada se dijo que tiene el mismo formato que las condicones en ONDE. Ojo que ninguna de  las opciones que  me dijiste tienen sentido por que no pones condiciones sobre MIN(edad) o MATS(altura). (Un mayor, un menor, etc...)
