### ISSUE TITLE
[T01] Uso de filter

### ISSUE THREAD

**Issue by Pochoclo** [IIC2233-2016-1/syllabus#36]
Hola, quería saber si se puede usar filter en la tarea para buscar cosas.
saludos

**Comment by mjjunemann** [comment]
Si esta permitido el uso de filter, pero debo recordarte que el uso de eval NO!

Saludos

**Comment by Pochoclo** [comment]
bueena gracias!

**Comment by jecastro1** [comment]
Ver #65
