### ISSUE TITLE
DIVERGENTE con dos columnas

### ISSUE THREAD

**Issue by isipalma** [IIC2233-2016-1/syllabus#360]
Holi
Quería preguntra qué debería entregar un DIVERGENTE que tenga dos o mas columnas? las filas enteras tendrian que ser diferentes? Esq en el pdf aparece una consulta asi, pero no lo que deberia salir

gracias ;)

**Comment by fdoflorenzano** [comment]
Sí, las filas enteras deben ser distintas, pero para eso solo es necesario que una columna sea distinta. Por ejemplo:
EMPRESTA DIVERGENTE nombre, edad DE Personas;
Donde Personas tiene. ('Fernando', 21) ('Fernando ', 22), ('Andrés', 21).
El resultado será:
Fernando | 21
Fernando | 22
Andrés | 21
