### ISSUE TITLE
Más de dos consultas en COMUN CN / SACALE

### ISSUE THREAD

**Issue by agmardones** [IIC2233-2016-1/syllabus#361]
Tiene sentido una consulta así?:

(EMPRESTA a DE b) COMUN CN (EMPRESTA c DE d) COMUN CN (EMPRESTA e DE f)

Mismo caso para SACALE.

**Comment by flobarrios** [comment]
Hola !! COMUN CN retorna la intersección de 2 o más consultas por lo que sí tiene sentido y retornaría la intersección de las 3 consultas.
Para SACALE, esta funciona como la diferencia de conjuntos y también aplica a más de 2 consultas. 
Saludos!

**Comment by andersskog** [comment]
@flobarrios en el ejemplo de @agmardones, sería:

(EMPRESTA a DE b) COMUN CN (EMPRESTA c DE d) COMUN CN (EMPRESTA e DE f)

o

((EMPRESTA a DE b) COMUN CN (EMPRESTA c DE d)) COMUN CN (EMPRESTA e DE f)

La segunda forma sería como en el ONDE  y podría facilitar la tarea un poco :)

**Comment by fdoflorenzano** [comment]
@andersskog Puede asumir la segunda forma para aprovechar código. De todas formas, cualquier cosa de ese estilo que queda poco espeficificada, **SIEMPRE** tomar una posición y colocarlo en el **README**.

**Comment by agmardones** [comment]
Gracias!
