### ISSUE TITLE
Sobre la repeticion en promedio, min y mats.

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#362]
En las consultas de ejemplo, cuando se usan esas 3, se imprime solo 1 vez, en vez de imprimirse la cantidad de veces igual al largo del .cvs. ¿Eso significa, que cuando se aplican alguno de estos 3, de se anula la repeticion, como con DIVERGENTE ó UNETELO CN?

**Comment by flobarrios** [comment]
Hola ! depende de tu consulta. 

Por ejemplo, si tienes esta tabla:

```
'Florencia', 21
'Tamara', 21
'Fernando', 21
'Florencia', 20

```

Si haces algo como:

```
EMPRESTA PROMEDIO(edad) DE personas;
```

Efectivamente estarías retornando una sola tupla, con un solo elemento, con el valor promedio de las edades de la tabla personas (20.75). Sin embargo, una consulta de este tipo:

```
EMPRESTA nombre, PROMEDIO(edad) DE personas  AGRUPATELOS X nombre;
```

Debería retornar 3 tuplas con 2 elementos cada una, el primero correspondiente al grupo con un nombre x  y el segundo el valor promedio de las edades de cada grupo de nombre x.

Retornará algo como:

```
Florencia | 20.5
Tamara | 21
Fernando | 21
```

Si no se agrega AGRUPATELOS X, todos pertenecen al mismo grupo y retornaría una tupla con el primer nombre y el promedio de todas edades. En este caso:

```
EMPRESTA nombre, PROMEDIO(edad) DE personas;
Florencia | 20.75
```

**Comment by Hernan4444** [comment]
@flobarrios Estimada, en el issues [#355](https://github.com/IIC2233-2016-1/syllabus/issues/355), por lo que entendi, se pregunto algo similar y se dijo que si hay un ejemplo:
`EMPRESTA nombre, PROMEDIO(edad) DE personas;`
Se considera toda la lista como un grupo, asi que se mostraria solo el primer elemento de la lista con el promedio y por lo tanto seria:
`Florencia | 21`
¿Con que opcion me quedo?

**Comment by flobarrios** [comment]
@Hernan4444 toda la razón perdón lo lo había visto me falto el  AGRUPATELOS X. Corregí el comentario. Gracias y saludos!!
