### ISSUE TITLE
Diferencia entre teniendo y onde

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#363]
Es el titulo. No entiendo la diferencia entre teniendo y onde. ¿Me aclaran?

**Comment by fdoflorenzano** [comment]
Hola, TENIENDO se reserva a condiciones que se aplican sobre los grupos de AGRUPATELOS X, donde las condiciones aplican sobre funciones MIN, MATS, CONTEA o PROMEDIO. En cambio ONDE aplica sobre filas especificas, no grupos.

**Comment by rmant** [comment]
@fdoflorenzano A mi sigue sin quedarme clara la diferencia. Por ejemplo, en que se diferencia decir 
EMPRESTA pokemon_nombre DE pokemon ONDE (pokemon_altura > 100) AGRUPATELOS X pokemon_id_especie

con decir

EMPRESTA pokemon_nombre DE pokemon AGRUPATELOS X pokemon_id_especie TENIENDO (MIN(pokemon_altura) > 100)

**Comment by fdoflorenzano** [comment]
@rmant Es sutil la diferencia. Tus consultas están bien armadas (en teniendo hay MIN, me refiero). Pero por ejemplo podría haber en Pokemon 2 filas: 'Bastianmon' de altura 90 y 'Mega Bastianmon' de altura 110, ambos con mismo pokemon_id_especie. 
- La primera primero filtra cada fila por altura, es decir, solo Mega Bastianmon pasa, y luego agrupa por especie, entonces queda solo en el grupo y entrega:
  Mega Bastianmon (Entre otros resultados)
- La segunda en cambio primero agrupa, es decir quedan juntos en un grupo Bastianmon y Mega Bastianmon, y luego filtra al grupo ENTERO si el minimo de altura > 100. Como el mínimo es 90, el grupo no cumple a TENIENDO, y no imprimiría Mega Bastianmon como en el primer caso.

Espero se entienda!

**Comment by rmant** [comment]
@fdoflorenzano  Ahí me quedó claro! Gracias!

**Comment by perojas3** [comment]
A mi no, sigo sin entender.

**Comment by fdoflorenzano** [comment]
@perojas3 Dime que no entiendes específicamente para saber como explicarte.

**Comment by IsaacConDosA** [comment]
@fdoflorenzano, no caché qué imprime el segundo caso? , nada ? saludos

**Comment by fdoflorenzano** [comment]
@ifcarrera Si Bastianmon y Mega-Bastianmon son los únicos en la tabla, no imprimiría nada. Si hay más pokemones que cumplan con las condiciones, entonces se imprimen esos.

**Comment by rmant** [comment]
@fdoflorenzano Una pregunta, el operador PARECIO A no se aplica para el teniendo cierto? Y lo otro, el teniendo solo se ocupa con MIN, MATS, o PROMEDIO? Es decir, no puedo decir TENIENDO (Altura >= 90)? Gracias!

**Comment by fdoflorenzano** [comment]
@rmant Exacto
