### ISSUE TITLE
ENTRE

### ISSUE THREAD

**Issue by cggutierrez** [IIC2233-2016-1/syllabus#364]
En el siding publicaron lo siguiente:
El formato de la condición ENTRE será (columna **ENTRE(V1 Y V2)**), lo que equivale a ((columna > V1) Y (columna < V2)).
Pero en el archivo consultas (de pokemon) sale los siguiente:
EMPRESTA DIVERGENTE pokemon_nombre DE pokemon, encuentros ONDE ((encuentro_pokemon_id = pokemon_id) Y (encuentro_min **ENTRE (30 Y 60)**)) ORDENATELOS X pokemon_peso PA BAJO SOLO 10;

Hay un espacio de diferencia, modificamos el archivo para adecuarlo al formato del siding?

**Comment by fdoflorenzano** [comment]
@cggutierrez Sí, acabo de modificar el archivo en el syllabus.
