### ISSUE TITLE
CONTEA

### ISSUE THREAD

**Issue by sitoro** [IIC2233-2016-1/syllabus#365]
Las funciones MATS, MIN y PROMEDIO por protocolo deben ir acompañadas de la columna sobre la que actúan (ej: PROMEDIO(Estatura), etc.).
En el enunciado de la tarea 3 y en el foro siempre se refieren a CONTEA como si fuera otra función que trabaja igual que las otras 3 (solo que esta cuenta los datos).
Por lo tanto siguiendo el mismo protocolo al pedir contea tambien debe hacerse del modo "CONTEA(columna)" (solo para que sea igual que las otras 3 funciones porque independiente de la columna entregada siempre retornará la cantidad de filas) O se le debe llamar solo a ella sola ej TENIENDO (CONTEA > 10) ???? 
Cual de estas dos formas es la que debe entender nuestro programa (CONTEA o CONTEA(columna)) ???

**Comment by fdoflorenzano** [comment]
@sitoro Como mismo dijiste, CONTEA también recibe una columna a contar como en el ejemplo del enunciado. Entonces debiese ser CONTEA(columna). Para efectos de la tarea, finalmente da lo mismo a que columna se refiera, por que siempre contara filas. (Originalmente tenía más especificaciones, pero por simplificación de tarea se dejó como te la explico)

**Comment by sitoro** [comment]
Ok comprendo. Gracias
