### ISSUE TITLE
[T03][Ayuda Problema]

### ISSUE THREAD

**Issue by vbarros2** [IIC2233-2016-1/syllabus#366]
Tengo un problema que necesito resolver y no he podido.
Tengo una lista:
lista = [(1, 2), (1, 10), (1, 40), (2, 2), (2,35).....]
Tengo que agrupar las tuplas en las que tengan igual primer valor, es decir:
lista1 = [[(1, 2), (1, 10), (1, 40)], [(2, 2), (2,35)].....]

Si alguien me puede ayudar con alguna idea se agradecería mucho ya que llevo mucho tiempo tratando de solucionarlo pero realmente no puedo sin usar for.
Gracias!

**Comment by rmant** [comment]
Busca en la libreria itertools un método que se llama groupby!

**Comment by vbarros2** [comment]
Gracias! Me sirvio
