### ISSUE TITLE
[Otros][Ayuda con PyCharm]

### ISSUE THREAD

**Issue by cdonoso** [IIC2233-2016-1/syllabus#37]
Por alguna extraña razón PyCharm no me está funcionando, me sale que se están escaneando unos archivos pero lleva como 2 horas en eso y no me deja correrlo (creo que no me deja correrlo por eso). Saben como solucionarlo :cry: o de la existencia de algún otro interprete igual de bueno y cómodo que PyCharm. 
Agradezco cualquier ayuda.

Saludos!

**Comment by fgvenegas** [comment]
Si lo cerraste asumo que lo pudiste solucionar ? :(

**Comment by cdonoso** [comment]
Si y no jajajaja no pude arreglar pycharm, pero encontré otro intérprete (eclipse)

**Comment by cdonoso** [comment]
@fgvenegas

**Comment by fgvenegas** [comment]
Vale, sino Sublime apaña harto tambien!

**Comment by flobarrios** [comment]
@cdonoso si quieres sube una foto del error para cachar mejor lo que te esta pasando y ver como lo podemos solucionar (por si en algún momento quieres volver a usar PyCharm) :smile:
