### ISSUE TITLE
Problema con codigo de la tarea

### ISSUE THREAD

**Issue by cggutierrez** [IIC2233-2016-1/syllabus#370]
Cada vez que quiero realizar una consulta, abro los archivos y al finalizarla los cierro, pero cuando tengo consultas anidadas o alguna funcion que "sea mas de una consulta a la vez" los archivos me quedan en blanco dado a que aun no termino de revisar la consulta para que esten disponibles en las demas consultas, que puedo hacer para solucionar esto? algún consejo o alguna forma de iterar un generador sin perderlo? seria de mucha ayuda!

**Comment by fdoflorenzano** [comment]
@cggutierrez Pueden haber muchas formas de acercarse a este problema. Una es procurar leer y cerrar inmediatamente archivos. Otra es crear archivos auxiliares temporales para el funcionamiento de estas partes especificas. De nuevo, hay muchas formas, y las que mencioné no son las únicas... Saludos!

**Comment by cggutierrez** [comment]
Gracias, me estaba complicando por el uso de generadores, que no me permitían cerrar un archivo antes de iterar el generador pero lo solucione usando listas luego de resolver las consultas, gracias!
