### ISSUE TITLE
¿Qué es mejor: definir funciones dentro de métodos o solo métodos por si solos?

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#371]
Mi consulta es la del título, ya que si bien la segunda opción me da la sensación que hace el código más ordenado, la primera impide que se hagan llamados a funciones que no debiesen ser llamadas por si cuenta. ¿qué es preferible generalmente?

**Comment by aaossa** [comment]
Puedes verlo desde el lado del modelamiento: 
- Si tu función interna corresponde a algo que tu clase debería hacer, es decir, si está bien modelarlo como método de una clase, entonces déjala como método. 
- Si tu función es mas que nada de apoyo y no tiene relevancia como método en el modelo puedes dejarla anidada. 

Pero ojo con esta opción. Esta es la que yo esperaría que usaran:

**Te recomiendo dejarla como método privado, ¿por qué?, porque así puedes testearla, si algún otro método requiere usarla no duplicas código y además porque así no es accesible desde afuera.**

**PS:** Muy buena pregunta :+1:

**Comment by MortizDX** [comment]
Ooh, claro, no consideré testearla más adelante con unnitest. Bueno, lo tendré en cuenta para la próxima tarea, ya que no queda mucho tiempo para esta n.nU

Gracias por la respuesta!
