### ISSUE TITLE
Que se puede hacer despues de la fecha de entrega de la tarea

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#372]
Tengo entendido que puedo modificar el readme depues de la fecha de la tarea. Comprendo eso
Pero una cosa que hago es escribir comentarios en el codigo para hacer más facil la correccion. ¿Puedo añadir estos despues de la fecha de entrega?

**Comment by kcsss** [comment]
![lie_down__try_not_to_cry__cry_a_lot_combo_by_badflippy-d5t596e-630x322](https://cloud.githubusercontent.com/assets/15813877/15003094/7357aa22-117e-11e6-8430-f84b556682d8.jpg)

**Comment by perojas3** [comment]
¿Eso que significa?

**Comment by cggutierrez** [comment]
Supongo que tus archivos .py si o si los tienes que agregar antes de la fecha limite por cosas del ultimo commit que hiciste y no modificarlos (segun lo que he visto).
Por lo demás también me gustaría saber si puedo subir el README fuera de la fecha limite.

**Comment by perojas3** [comment]
Sí se puede, ya me han confirmado lo del README, pero no si puedo agregar comentarios al .py

**Comment by bamavrakis** [comment]
Hola!
No puedes agregar comentarios al código luego de la fecha de entrega. Pero puedes hacer un README bien bonito con todo lo que creas necesario que el ayudante sepa :D

**Comment by cggutierrez** [comment]
Vi tu pregunta sobre el README de la tarea 2, pero era sobre modificarlo y quisas directamente subirlo despues de la fecha limite sea cosa distinta

**Comment by perojas3** [comment]
OK, pero ahora lo sé. ¿El sabado esta bien como para gregarle el readme y los comentarios?

**Comment by bamavrakis** [comment]
Si, está bien :)
