### ISSUE TITLE
[T03] DIVERGENTE

### ISSUE THREAD

**Issue by fcorencoret** [IIC2233-2016-1/syllabus#373]
Me gustaria saber bien como funciona este comando. Si vemos la tercera consulta del ejemplo 2, : 

EMPRESTA DIVERGENTE pokemon_nombre DE pokemon, encuentros ONDE ((encuentro_pokemon_id = pokemon_id) Y (encuentro_min ENTRE (30 Y 60))) ORDENATELOS X pokemon_peso PA BAJO SOLO 10

Ejecutando la consulta pero sin el divergente, me doy cuenta de que 'metagross' (el primer resultado) aparece primero en mis resultados con 12 filas iguales pero que solo varian en encuentro_id. Aplicando la logica que dijieron anteriormente, el DIVERGENTE elimina las filas que son identicas, pero estas filas no lo son por lo que el resultado deberia ser 'metagross' 10 veces... 

No sera que el divergente se refiere a que esa columna especificada por el DIVERGENTE (en este caso pokemon_nombre) no se pueda repetir en todas las filas? Ahi haria sentido la respuesta entregada, pero esto no fue lo que nos habian dicho del comando. Porfavor explicar bien.

**Comment by fdoflorenzano** [comment]
Efectivamente es como dices, el divergente actúa sobre las columnas especificadas, no las filas completas. Se hace referencia a este funcionamiento en #347, #360 y en enunciado dice que al usarlo "retorne solo los valores diferentes de la consulta", que retorna la consulta? Las columnas especificadas en EMPRESTA, o sea que sean diferentes en las columnas en EMPRESTA.
