### ISSUE TITLE
UNETELO CN

### ISSUE THREAD

**Issue by cggutierrez** [IIC2233-2016-1/syllabus#374]
me podrían dar un ejemplo de como funciona? no entiendo bien desde el enunciado

**Comment by fdoflorenzano** [comment]
Es simplemente la unión de los resultados de 2 consultas. Junta los resultados de las dos consultas que se le enteguen. En el ejemplo del enunciado, una consulta retorna los nombres de Personas y la segunda retorna los nombres de los Productos y finalmente, la consulta total retorna todos esos nombres como resultado. Ojo que en ese ejemplo faltán los parentesis alrededor de las consultas que se especificó en el anuncio de la semana pasada, es decir:
(consulta1...) UNETELO CN (consulta2...)

**Comment by bmarinb** [comment]
En el enunciado dice que ambas consultas deben tener las mismas columnas:
¿Se refiere al número de columnas, al número y que sean del mismo tipo, o que sean exactamente las mismas columnas?

**Comment by cggutierrez** [comment]
vale gracias, no me di cuenta del ejemplo del enunciado!
