### ISSUE TITLE
[T01] [Duda sobre clases]

### ISSUE THREAD

**Issue by vbarros2** [IIC2233-2016-1/syllabus#38]
Si tengo una clase con muchas instancias ya ingresadas, como puedo recorrer un atributo de la clase?? Es para filtrar que no se repitan usuarios en la Tares

Gracias!

**Comment by mjjunemann** [comment]
Estas preguntando algo muy directo con la tarea y no podemos darte una respuesta :). Te invito a usar la guía de cómo buscar en google que les mostraron en la ayudantía, te va a ser útil y además comienzas a desarrollar la habilidad de buscar en google desde temprano en el ramo (que te va a ser útil a largo plazo).

**Comment by vbarros2** [comment]
Ok Gracias!
