### ISSUE TITLE
Fecha entrega Tarea 4

### ISSUE THREAD

**Issue by isipalma** [IIC2233-2016-1/syllabus#381]
Hola, queria preguntar sobre la fecha de entrega que aparece en el enunciado de la Tarea 4. Es esa la fecha real (16 de mayo)? o el plazo de entrega sera en 2 semanas como en todas las tareas? 

Gracias y saludos.

**Comment by fdoflorenzano** [comment]
@isipalma  Hola, toda la razón, está mal. Esa era la fecha antes del plazo extendido de la T3. Ya fue actualizado el enunciado.
