### ISSUE TITLE
Pregunta Safe Zones

### ISSUE THREAD

**Issue by Meaylwin** [IIC2233-2016-1/syllabus#382]
Segun el enunciado, los edificios Gun Shops al acabarse las municiones se eliminan, pero, cuando un grupo o individuo entra a un edificio Safe Zone y se les agota el tiempo, ¿se elimina el lugar, o sigue existiendo?
Suponiendo que sigue existiendo, ¿puede entrar el mismo grupo al mismo edificio al pasar X tiempo?, o ¿no pueden volver a entrar a un edificio que el grupo o el individuo ya entro?

**Comment by flobarrios** [comment]
Hola ! se subió una nueva versión del enunciado. En #384 se explican los cambios. Espero que eso clarifique tus dudas. Saludos!

**Comment by Manuel-uc** [comment]
Del mismo enunciado me quedo una duda en cuanto a la oersonalidad

**Comment by Manuel-uc** [comment]
Del enunciado me quedaron un par de dudas mas:
-Por lo que entendí existen solo 4 tipos de objetos, armas larga distancia, corta distancia,  botiquín y munición. 
¿No existe el agua o la comida? 
¿Lo que implica que solo pueden morir en interacción con zombis o por enfermedad? 
¿Cuando se enferma cada persona, es un porcentaje de ocurrencia entregado por nosotros y especificado en el README?  
Si la personalidad Racional puede compartir munición, ¿también puede compartir botiquines? 
¿Lo que significa que cada persona tiene un espacio ilimitado de municiones, armas y botiquines?
