### ISSUE TITLE
Dudas sobre las estadísticas

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2233-2016-1/syllabus#383]
Hola! Tengo algunas dudas:
1. En las estadísticas están consideradas que muera una persona, que muera un zombie y que una persona pase a ser zombie. Sin embargo, ¿no sería lo mismo en la práctica que una persona muera a que se convierta en zombie? Lo digo porque el enunciado dice que si una persona llega a tener vida cero, se convierte en zombie. 
2. ¿A qué se refiere exactamente la estadística de tasa de muertes y tasa de zombies? ¿Hay que decir cuántas conversiones y cuántas muertes han habido en promedio, por cada unidad de tiempo de la simulación?

Muchas gracias
Saludos

**Comment by flobarrios** [comment]
Hola ! se subió una nueva versión del enunciado. En #384 se explican los cambios. Espero que eso clarifique tus dudas. Saludos!
