### ISSUE TITLE
Quitarle un archivo a la tarea 3

### ISSUE THREAD

**Issue by jneyzaguirre** [IIC2233-2016-1/syllabus#385]
Como dice el titulo, quiero quitarle un archivo, ya que no se esta usando, pero siempre que me dejen. Esto debido a que en su momento lo use, pero después no me gusto como estaba quedando y simplemente hice otro, pero no lo borre. Más que nada es para que no gasten tiempo en  revisar el archivo.

**Comment by negebauer** [comment]
Puedes actualizar tu README especificando que ese archivo no sirve de nada
