### ISSUE TITLE
Tamaño del tablero / Choque de unidades 

### ISSUE THREAD

**Issue by vlcastillo** [IIC2233-2016-1/syllabus#386]
Jugando con la interfaz gráfica me di cuenta que esta es infinita, pero se muestra solo una parte de ella. ¿La simulación debe estar restringida al cuadrado visible o se debe hacer en un plano infinito?

Por otro lado, ¿debe existir choque entre unidades? ¿o pueden estar dos en una misma posición?

**Comment by rodolfopalma** [comment]
Acota la simulación al espacio de la interfaz. Además, la simulación debe ser capaz de detectar colisiones.

**Comment by Zepk** [comment]
Y el tamaño del tablero, cual seria el tamaño del tablero, va desde el (0, 0), pero cual es la cota superior?

**Comment by MortizDX** [comment]
Al momento de crearse los zombies y personas ¿estas no pueden "surgir" en el misma cordinada ni sobreponerse, verdad? De ser así, no significa que hay un tope "máximo" de entidades que puede haber en pantalla? ¿Que debemos hacer si el usuario introduce más de lo que puede aguantar el tablero? (lo mismo con las tasas de llegadas de entidades)
