### ISSUE TITLE
Dudas T4

### ISSUE THREAD

**Issue by ManuelSIlvaCav** [IIC2233-2016-1/syllabus#387]
una duda, la idea de la simulacion es que desde la funcion que llama gui.run se ejecute todo?

y lo otro, para ls simulacion las entidades tienen que estar moviendose y cuando se encuentren se hace el evento? o definimos los eventos con probabilidades por ejemplo de que el zombie1 ataque al humano3 y lo mostramos en la gui.

Gracias!

**Comment by otro-felipe** [comment]
La idea de esta funcion es que sea como una especie de tick de la simulacion sincrona y en el hagan todo lo que deben hacer para simular una pequeña fraccion de tiempo de la simulacion completa.
