### ISSUE TITLE
Pauta Tarea

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233-2016-1/syllabus#388]
¿Es posible subir antes la pauta con los puntajes que tendrán las tareas? Así uno puede saber en que enfocarse si es que el tiempo no le da para hacer todo.

**Comment by mjjunemann** [comment]
No se subiran pautas de las tareas antes de las entregas, tienes que lograr desprender lo fundamental de la tarea. 

El enunciado se encuentra dividido en secciones, y luego estas en subsecciones, en general si la seccion tiene muchas subsecciones significa que cada subseccion tiene una porción del puntaje total de la sección (no necesariamente divido en partes iguales, hay cosas que al leerlas se nota que son más importantes que otras). 

Luego tu tienes que evaluar la importancia de cada sección y con eso puedes estimar cuanto puntaje podria tener cada subsección.

**Comment by Hernan4444** [comment]
Oka, muchas gracias :+1:
