### ISSUE TITLE
No tengo feedback T02

### ISSUE THREAD

**Issue by ManuelSIlvaCav** [IIC2233-2016-1/syllabus#389]
Creo que mi caso fue particular, ya que no tengo feedback de mi tarea2 y un 1.0 en la planilla de notas, lo que me hace pensar que no la corrigieron, mas o menos para cuando estará la nota lista si es que la están revisando ahora? de lo contrario pueden ver que onda mi tarea y su status xd
Gracias!

**Comment by flobarrios** [comment]
Hola!! Tu tarea si fue corregida y no es un 1. Se va a solucionar lo antes posible!

**Comment by aaossa** [comment]
La dejaré abierta hasta que efectivamente se solucione :ok_hand:

**Comment by otro-felipe** [comment]
Acabo de subir tu feedback! Perdón por la demora.

**Comment by ManuelSIlvaCav** [comment]
Gracias!

**Comment by ManuelSIlvaCav** [comment]
Se me olvidaba!, si puedes actualizar la nota del excel te pasarias! para no estar pidiendo despues jajaj c:

**Comment by mjjunemann** [comment]
Tu tranquilo, en nuestras notas tu ya no sales con la nota anterior, y al final del semestre copiamos lo que tenemos para calcular la nota final, por lo menos.

**Comment by spiza** [comment]
Yo tampoco tengo feedback!! Quisiera ver el desglose! :)

**Comment by mjjunemann** [comment]
Hubo un error de script que recopilaba los feedback en tu tarea , ya que no
estaba dentro de T02 directamente, si no en T02/Enunciado , ya te lo subí a
tu issue de T02

**Comment by aaossa** [comment]
@ManuelSIlvaCav cerraré la issue porque acabo de subir tu feedback como corresponde. Tu nota aparecerá mas adelante en el excel público, pero como dijo @mjjunemann tenemos tu nota correcta
