### ISSUE TITLE
Hackeo

### ISSUE THREAD

**Issue by Iruretagoyena** [IIC2233-2016-1/syllabus#39]
Hola !
Con el tema del hackeo; podemos poner las funcionalidades adentro del programa y hacer que solo nuestro usuario tenga acceso a ellas, o debe ser un código totalmente distinto?
Gracias

**Comment by Geeermy** [comment]
Hola!
Como dice en la parte del Hackeo: "decides crear un programa a parte del solicitado por la empresa (es decir, en otro archivo)". Con otro archivo nos referimos a un archivo .py. (Y es lo más lógico, queremos hackear a la empresa, no le podemos pasar en el código principal lo que usaremos para arruinarlos D: ! )
Espero que ahora haya quedado claro. Saludos! :)
