### ISSUE TITLE
Tablero Tarea 04

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233-2016-1/syllabus#390]
Hay forma de tener acceso a los elementos del tablero, por ejemplo si pusiera Tablero[0][1], me dice None si no hay nada pero si hay un zombie, me devuelve algo en relación a ese zombie, por ejemplo el objeto. ¿Hay algo así? o ¿es nuestro trabajo ver como analizar eso?

**Comment by otro-felipe** [comment]
Es su trabajo ver como trabajar en el tablero, para esto todas las entidades y sus atributos (menos los que tienen _ o que son relativos a la interfaz grafica) estan a su disposicion. Principalmente `entity.cord_x`, `entity.cord_y`, `entity.height()` y `entity.width()` son los que podrian servirte para verificar si en algun (x,y) hay una entidad.

**Comment by flobarrios** [comment]
Hola !! La idea de esta tarea es que generes la simulacion fuera de la interfaz y que esta sea simplemente una forma de visualizarla. De esta forma, tienes que trabajar con tu propio tablero y a partir de este, pasarselo a la gui para que se visualize.

**Comment by Hernan4444** [comment]
Ok, muchas gracias. Aprovechando el issues
si  entity.cord_x = 500 y entity.height() = 20 y entity.width() = 20

se supone que la entidad ocupa en el eje X desde el pixel 490 a 510 y en el eje Y desde el pixel 490 a 510??

**Comment by otro-felipe** [comment]
No, significa que ocupa del 500 al 520 y en el eje Y, desde cord_y hasta cord_y + 20. (En el enunciado se detalla que las coordenadas corresponden a la esquina superior izquierda de la entidad)(en la gui el eje Y crece hacia abajo, por lo que la esquina superior izquierda es el pixel 0,0)

**Comment by Hernan4444** [comment]
Gracias, no me percate de ese detalle en el enunciado
