### ISSUE TITLE
Duda tarea 4 

### ISSUE THREAD

**Issue by camiolguin** [IIC2233-2016-1/syllabus#391]
En las instrucciones de la tarea dice que las clases extra que agreguemos tienen que heredar de las ya creadas (human, zombie, etc si las queremos extender) o de entity, pero por ejemplo si quiero crear una clase Grupo que contenga como atributo a los humanos (instanciados) que lo forman, necesariamente debe heredar de entity??

Gracias!!

**Comment by otro-felipe** [comment]
Para nada, esto en el enunciado es una recomendacion para que la interaccion con la interfaz grafica sea lo minimo posible (solo cambiar el `cord_x`, `cord_y` o `angle` actualiza la gui). Si quieres crear tu propia clase `Human` que tiene por composicion un atributo de tipo `gui.entities.Human` eres libre de hacerlo. De la misma forma las clases que no representan ningun elemento en la gui no necesitan heredar de `Entity`.

**Comment by camiolguin** [comment]
ok! graciass

**Comment by negebauer** [comment]
Recuerda cerrar el issue si quedaste conforme
