### ISSUE TITLE
Nota diferente en el feedback y en el excel (T02)

### ISSUE THREAD

**Issue by egvillalobos** [IIC2233-2016-1/syllabus#394]
En el feedback sale como nota un 1.0 con nota 0 en cada item, sin embargo en el desglose de puntaje sí salen puntajes y en excel sale el puntaje correcto (sumando todos los puntos del desglose). Puedo suponer que eso fue solo un error del feedback y me quedo tranquilo sabiendo que el excel esta bien?

**Comment by mjjunemann** [comment]
En tu feedback, no estan la suma de los puntajes pero si miras los subitems estan los puntajes, solo falto poner la suma.

**Comment by egvillalobos** [comment]
Yaya gracias, solo quería confirmar que faltó sumar la suma nomas
