### ISSUE TITLE
Mapa T04

### ISSUE THREAD

**Issue by vjmoreno** [IIC2233-2016-1/syllabus#395]
El enunciado de la tarea dice que se los entregará un archivo mapa.cvs, pero al parecer aún no está disponible.

**Comment by Zepk** [comment]
Me cuelgo de esta duda para preguntar cual es el tamaño del mapa, necesito saber cuales son los limites para evitar que las personas y combines salgan del mapa

**Comment by vjmoreno** [comment]
Ademas me gustaría saber el largo y ancho en pixeles de las diferentes entidades, porque al parecer los tamaños son escalados.

**Comment by santiagocruzb** [comment]
Hola! Se puede usar la librería csv?
Saludos

**Comment by Zepk** [comment]
@vjmoreno para el alto y largo de las entidades se puede usar self.width() y self.height()

**Comment by vjmoreno** [comment]
@Zepk  verdad jaja! gracias!

**Comment by negebauer** [comment]
@santiagocruzb #399

**Comment by negebauer** [comment]
Tamaño del mapa en #401
