### ISSUE TITLE
Personalidades

### ISSUE THREAD

**Issue by bmarinb** [IIC2233-2016-1/syllabus#396]
¿Las personas deben tener un número determinado de personalidades compatibles?
(Si es que deben tener al menos 1, si es que deben tener 1 de cada par o si queda a mi criterio)

**Comment by negebauer** [comment]
Al menos 1

**Comment by diegosapunar** [comment]
@negebauer En el caso de que tengan mas de 1 personalidad. De que color deben ir en la Interfaz... Saludos

**Comment by flobarrios** [comment]
Hola! Deben tener el color de la personalidad que predomine (debe predominar 1)

**Comment by vjmoreno** [comment]
Hola! En mi caso todos los humanos cuentan con 3 personalidades ( no opuestas) y el color se escoge aleatoriamente entre una de esas 3 personalidades. Puede ser así? O necesariamente tiene que predominar el color de una personalidad?

**Comment by flobarrios** [comment]
Hola! Queda a tu criterio. Por ejemplo, si en tu caso las 3 personalidades tienen el mismo porcentaje, tiene lógica que sea aleatorio (aun cuando esto no es valido ya que en el enunciado se especifica que debes elegir un criterio para ver que personalidad prima). Sin embargo, si una predomina quizas es mejor que tenga ese color ya que para efectos visuales se podrá entender mejor el comportamiento de este (dada su personalidad). Esto es solo una recomendación y queda a tu criterio. Recuerda especificarlo en el README!

**Comment by flobarrios** [comment]
Hola! Queda a tu criterio. Por ejemplo, si en tu caso las 3 personalidades tienen el mismo porcentaje, tiene lógica que sea aleatorio. Sin embargo, si una predomina quizas es mejor que tenga ese color ya que para efectos visuales se podrá entender mejor el comportamiento de este (dada su personalidad). Esto es solo una recomendación y queda a tu criterio. Recuerda especificarlo en el README!

**Comment by bmarinb** [comment]
¿Existe algún tipo de penalización si solo entrego 1 personalidad a cada persona?

Porque me parece que añadir más personalidades solo agrega dificultad a la tarea, pero como no se indica nada acerca de como debiéramos decidir cuando agregar más personalidades, somos nosotros los que elegimos que tanta dificultad se nos agrega. Quizás debieran dar alguna restricción respecto a las múltiples personalidades.

**Comment by cggutierrez** [comment]
tengola misma duda que @bmarinb

**Comment by negebauer** [comment]
Su tarea tiene que ser capaz de asignar más de una personalidad a cada persona
Si tú modelamiento o funcionamiento se basa en 1 persona => 1 personalidad tendrán una penalización

Es su decisión ver cómo asignar las personalidades (aleatorias, cierto porcentaje de cada una, etc)

Pero su tarea **debe** estar hecha para más de una personalidad en cada persona
Y que estas no sean contrarias también (inteligente y estupido no pueden estar en la misma persona)

**Comment by tsuarezsaieh** [comment]
@negebauer Si hacemos que cada personalidad contraria sea el porcentaje complementario de su par esta bien? Por ejemplo: Tiene 80% de probabilidades de actuar como Racional y 20% de actuar como estúpido.

**Comment by leylayunis** [comment]
@negebauer en ninguna parte dice que cada persona **debe** tener más de una personalidad, y que se penalizará por asignar una personalidad por persona. El enunciado dice claramente "al menos una" así que no veo problema al asignarle una personalidad por persona. Yo llevo toda mi tarea con el supuesto de que cada persona tendrá solo una personalidad, y que recién ahora digan que por modelarlo así se penalizará hace que tenga que cambiar gran parte de mi tarea ...

**Comment by Geeermy** [comment]
@tsuarezsaieh ¡Sí! Recuerda que las partes referidas a probabilidades quedan a tu criterio :) especifícalo en tu README y ningún problema ;)
@leylayunis En el enunciado tampoco dice que cada persona tiene **solo** una personalidad. Citando al mismo:
_"Personalidad: Las personalidades de una persona determinan su actuar ante las distintas situaciones
que enfrentará en el apocalipsis. Estas son detalladas en la sección 4.1.1. Una persona puede tener más de una de estas personalidades, pero no tendrá personalidades contrapuestas (como valiente y cobarde)."_
_"Como podrás notar, algunas personalidades pueden generar un conflicto. Por ejemplo, un cobarde inteligente podría escapar o no al verse en un grupo grande contra un grupo pequeño de zombies. La personalidad que prima sobre las demás queda a su criterio. Deben especificar este criterio en su README."_
De estas dos citas se desprende que, efectivamente, debían considerar múltiples personalidades. Está bien que hagan personas con una sola personalidad, pero esto no implica que **no pudieran existir personas con más de una**. Si tenías la duda, debiste haberlo preguntado por acá antes de modelarlo de esa forma :/. Por otra parte, más que ser una penalización, básicamente no tendrían todo el puntaje en la sección de personalidades (penalización suena feo jaja).
Mi recomendación: Termina de hacer el resto de tu tarea (para así completar más items), y luego de eso, si te da el tiempo, implementa mezclas de personalidades (no debiese ser más complicado que cambiar el tipo de atributo que le pusiste a tu clase y cambiar las condiciones de acción frente a los eventos vistos).
¡Saludos y éxito! Aun hay tiempo :).
