### ISSUE TITLE
¿Puedo preguntar fisicamente a un ayudante?

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#397]
El jueves le envie un mail a este mail bamavrakis@uc.cl para pedir si podia hablar con un ayudante de sobre la tarea. Especialmente porque quiero mostrar cosas de mi codigo, y no puedo poner codigo aquí. Pero todavia no me responde, por eso quiero preguntar aquí porque estoy desesperado. ¿Puedo hablar mañana en el modulo 3 o 5 sobre la tarea con un ayudante de tarea?

**Comment by bamavrakis** [comment]
Hola! perdón por lo del correo, mañana yo puedo juntarme al quinto módulo en la sala de las pizarras para resolver dudas sobre la tarea :). Saludos!

**Comment by IsaacConDosA** [comment]
@bamavrakis Hola, cuál es esa sala? La SAI o na que ver? saludos

**Comment by aaossa** [comment]
La SAI no tiene que ver con nosotros. La sala será la "sala de las pizarras" (no recuerdo el nombre :cry:) en el DCC. 

**EDIT:** No había leído el mensaje de Bastian, perdón. En el DCC (piso 4, edificio San Agustín) puedes preguntarle a la Sole como llegar y listo, es mas simple que tratar de dar instrucciones jaja

**Comment by Hernan4444** [comment]
No sera la sala de Alvaro campos??

**Comment by fvr1** [comment]
Esa misma

**Comment by aaossa** [comment]
Efectivamente, esa es la sala

**Comment by perojas3** [comment]
OK, mi principal problema es con la interfaz grafica.
