### ISSUE TITLE
Tablero, ancho y altura pixeles Tarea 04

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233-2016-1/syllabus#398]
si yo realizo una matriz para ahí trabajar todos las entidades de la simulación, tengo que considerar el ancho y altura de los pixeles, por ejemplo si tengo un zombie de ancho 2 y largo 2 en la posicion 5,0.
Lo ideal seria que en la matriz la posición 5,0 - 5,1 - 6,0 y 6,1 este marcado por mi entidad o para mejor comodidad, solo la posición 5,0??

**Comment by otro-felipe** [comment]
Esta decisión queda completamente a tu criterio y a lo que tú pienses que es más conveniente para tu modelación.

**Comment by Hernan4444** [comment]
Ok, muchas gracias :+1:
