### ISSUE TITLE
Problema alumno sin repositorio

### ISSUE THREAD

**Issue by msbobadilla** [IIC2233-2016-1/syllabus#4]
Estimados profesores y/o ayudantes

Ya inscribí una cuenta en github, pero no me inscribí en el formulario del siding con plazo hasta el domingo por que estaba fuera de Chile. Estoy preguntando para tener un repositorio lo antes posible. Pido disculpas respectivas.

Usuario: msbobadilla
Manuel Bobadilla  
N°13638823

**Comment by aaossa** [comment]
Si ya pudiste acceder a tu repo avisa por aquí y cierra la issue :+1:
