### ISSUE TITLE
Tarea1 Tiempo transcurrido desde log-in

### ISSUE THREAD

**Issue by tmorales1** [IIC2233-2016-1/syllabus#40]
Lo que tenemos que hacer es que cuando el usuario entre se le pida una fecha. Luego para cualquier consulta que haga el usuario se usa esta fecha y hora o se debe implementar alguna forma de que el tiempo este actualizado? O sea que le sume a la hora que se ingreso en un principio el tiempo transcurrido desde entonces.

**Comment by negebauer** [comment]
No.
Para simplificarte la vida asume que el tiempo no transcurre desde que ingresa al sistema.
