### ISSUE TITLE
¿Como se logra cambiar el movimiento?

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#400]
Estoy viendo el codigo, pero todavia no tengo idea de como lograr cambiar el movimieno de algun humano o zombie depues de que se alla empezado a mover.

**Comment by otro-felipe** [comment]
Si ves el ejemplo, para mover una entidad se hace `entity.cord_x += 5`. Esto hace que dicha entidad se mueva 5 pixeles constantemente, si quieres que se mueva una cantidad que tu definas puedes escribir `entity.cord_x += var` en donde `var` es una variable que tu defines y trabajas en base al estado actual de la simulación.
