### ISSUE TITLE
Eliminar Entidad

### ISSUE THREAD

**Issue by Zepk** [IIC2233-2016-1/syllabus#401]
En caso de que un humano se convierta en zombie, necesito eliminarlo de la interfaz, y reemplazarlo por un zombie, pero en el enunciado no pude encontrar ninguna función que permita eliminar una entidad de la interfaz ¿Existe un método que permita hacer esto?

Y, lo he preguntado en otras issues, pero no me han respondido, así que aprovechando que tengo otra pregunta ¿cual es el tamaño del mapa en pixeles? Esto es necesario para evitar que los personajes salgan del mapa, de momento solo puedo hacer una aproximación al ojo, por lo que no se esta utilizando la totalidad del mapa

**Comment by otro-felipe** [comment]
El tamaño del mapa está es de 1024x800 pixeles. Puedes ocultar una entidad con `entity.hide ()` (Método que sale en el enunciado). Si quieres que esta se elimine y no se vuelva a usar puedes usar el método `entity.deleteLater()` (Método no mencionado en el enunciado, pero que para efectos prácticos hace lo mismo que el método `hide()`).

**Comment by bmarinb** [comment]
El mapa es realmente de ese tamaño? Porque si pongo un zombie en una posición -4,-4 sigue viéndose completamente

**Comment by Zepk** [comment]
Gracias!

El método `entity.hide` lo vi en el enunciado, pero asumí que no era lo mismo que eliminarla, ya que en teoría, la entidad seguiría existiendo, entonces, si la simulación durara demasiado, terminaría con una simulación con miles de entidades, de las cuales muy pocas son efectivamente parte de la simulación, por eso la pregunta, pero si es equivalente nevermind.

En todo caso, nunca fui capaz de encontrar el tamaño del mapa en el enunciado.

@bmarinb Eso puede ser porque la coordenada del zombie se concidera a partir de la esquina superior izquierda del mismo (pero la imagen del zombie es solo una parte de la imagen real que es cuadrada) por lo que si lo pones en esa posición la parte de la imagen que queda fuera no contiene al zombie, de la misma manera, si lo pusieras en la posición 1024, 800, solo el pixel superior izquierdo de la imagen se vería, y parecería que el zombie está fueraa del mapa

**Comment by otro-felipe** [comment]
Podría ser que el método `entity.hide()` haga que al final de la simulación tengas muchas entidades que no están realmente ahí, por lo que si puedes prefiere `deleteLater()` por sobre `hide()`.
