### ISSUE TITLE
Posicion inicial de las entidades

### ISSUE THREAD

**Issue by bmarinb** [IIC2233-2016-1/syllabus#402]
¿Cómo puedo saber la dimensión del mapa para saber donde posicionar a las entidades (humanos, personas) creadas?
¿Debo posicionarlas de forma aleatoria?

**Comment by negebauer** [comment]
El tamaño del mapa se menciona en #401

**Comment by bmarinb** [comment]
Lo preguntaba ya que en mi caso no se me ve cuando uso 1024x800, y como en mi código uso 800x600, me gustaría  tener una variable que guarde estas dimensiones. Pero la clase en la que están es difícil de acceder
