### ISSUE TITLE
Puntaje Tarea2 

### ISSUE THREAD

**Issue by jpdattas** [IIC2233-2016-1/syllabus#403]
En la corrección de la Tarea2, en la parte de Estructura de datos se asigna puntaje (0,8 pts) por
"Item 2: Se implementa de forma correcta la Mega Estructura (Grafo)"
pero ni en el enunciado ni siquiera en los issues (por lo menos no que haya visto) sale que hay que usar grafos.

Me imagino que la idea de esto era hacer que al caer piezas al tablero, estas caigan a cada columna hasta que esta se llenara y que "la estructura de los grafos misma se encargara de llenar las columnas". Sin embargo, si mi estructura funciona,  si funciona bien la caida de piezas y si no se pidió una estructura específica, no veo por que no tendría esas 8 décimas (o por que se asignan de esa forma).

A continuación cito la única parte del enunciado que se refiere a las estructuras:

"8. Developer
Para poder triplicar tus ingresos con la venta del juego y asegurarte una gran reputacion en la industria,
decides demostrarle al mundo que eres capaz de implementarlo SIN USAR LAS ESTRUCTURAS
DADAS POR PYTHON (listas, diccionarios, sets, etc). Debes detallar en el README las
especicaciones de como implementaste cada una de las estructuras utilizadas."

**Comment by vjmoreno** [comment]
Opino lo mismo, iba a mandar a recorregir mi tarea por el mismo tema.

**Comment by jpdattas** [comment]
@negebauer es tarea 2 eso si, no 4 :smile:

**Comment by Geeermy** [comment]
¡Hola!
Hubo un mal entendido con esa parte durante las correcciones. Los que sientan que les hayan bajado en ese item habiendo implementado la mega estructura correctamente (sin ser un grafo necesariamente) manden a recorregir, el problema será solucionado, así que no se preocupen.
¡Perdón por las molestias! 
Saludos :)
PD: No cierren el issue por ahora, en caso de que haya más gente con un problema similar.

**Comment by jpdattas** [comment]
ok, muchas gracias! :smile:

**Comment by fdoflorenzano** [comment]
Pero para aclarar, se esperaba de la tarea que implementaran una estructura de datos orientada al problema. Como dice Germy, no necesariamente un grafo, pero sí una mega estructura que facilitara como hacer los giros, buscar clusters, etc... Si aplicaron una lista de listas para el problema, esto no cuenta como estructura orientada al problema. Esto claramente no se pone explicito en el enunciado, por que sería dar la respuesta. Lo digo para que tengan esto en consideración a la hora de recorregir, sí tienen una lista de listas para manejar las piezas, no cumplieron con lo esperado. En caso contrario, sientanse libres de recorregir! Saludos!

**Comment by fnquinteros** [comment]
Me parece un poco contraproducente el hecho de decir "hagan una estructura ustedes mismos" y luego descontar puntos si la estructura que hicimos no es como ustedes esperaban... si la estructura funciona bien, ¿cuál es el problema con que sea una lista de listas? Cumple su función para la tarea y, como ustedes mismos dicen, si no aparece en el enunciado, tenemos total libertad de hacer lo que nos parezca conveniente y especificarlo en el README o no?
Saludos!!

**Comment by mjjunemann** [comment]
@fnquinteros
Primeras lineas de la T02 

```
Objetivos: 
Aplicar conceptos y nociones de estructuras de datos para el correcto modelamiento del problema
```

 Si implementaste una estructura de listas de listas, esta funciona bien, para una instancia **pequeña del juego**, que consistía en ~ 8x8, pero si cambiamos la instancia a 15x15 , 20x20 ... y así cada vez que tu estructura hace cálculos son más lentos, se les pidió implementar una estructura para el correcto modelamiento del problema, y en el material de clases se explicaban variadas estructuras de datos, entre ellas **Grafos** , pero para optar a puntaje dentro de mega estructura no neceseriamente se necesitaba este grafo, si no cualquier estructura acorde al problema, que ayudara a la eficiencia del problema.

Modelar el problema con listas de listas no esta mal del todo, pero por eso esta dividido el puntaje de la estructura en dos. Este approach (más simplista) al problema contiene errores de modelación y eficiencia (como por ejemplo la inexistencia de conexiones diagonales, que llevan inevitablemente al "harcodeo" y operaciones extra). El material daba las herramientas necesarias para poder modelar el problema de mejor manera.

**Comment by vjmoreno** [comment]
@mjjunemann 
Está más que claro que implementar listas de listas no es la mejor opción si se piensa en instancias más grandes del juego, pero en la tarea se pedía resolver una instancia de 8x8, no de 15x15 o 20x20.  Además, tal como dices, en el enunciado decía: "Aplicar conceptos y nociones de estructuras de datos para el correcto modelamiento del problema" y al aplicar listas de listas ligadas, si se están aplicando conceptos y nociones de estructuras y se puede llegar a un correcto funcionamiento del problema, pese a que no sea lo más adecuado. Por otra parte teníamos plena libertad para escoger la estructura que quisiéramos puesto que en el enunciado no aparece ninguna limitación.

Me gustaría que en los puntos importantes de la tarea se fuera más explicito o que se restringa ciertas prácticas, para así posteriormente, evitar problemas con el puntaje.

**Comment by gafigueroa** [comment]
@vjmoreno
La primera linea del material de clases de EDD dice "Se entiende por estructura de datos a una forma especializada para agrupar y almacenar la información, de tal modo que esta pueda ser utiliza eficientemente.".
El objetivo dice **correcto modelamiento**, que funcione no hace que el modelamiento sea correcto, un correcto modelamiento implica almacenar la información de tal manera que esta sea eficiente y utilizar lista de listas no es para nada eficiente para la instancia de este problema, pues era una grilla hexagonal.

**Comment by sitoro** [comment]
@mjjunemann
Hola vengo desde el futuro a resaltar que al menos en el material de clases casi nada se dice sobre grafos, la única mención a la palabra "grafo" en todo el material se encuentra en el HTML de árboles en donde al explicar el "Bread-First Search (BFS)" menciona que: 

> En estructuras jerárquicas más complejas que los árboles, como por ejemplo un **grafo** no dirijido, es necesario también mantener un listado de los nodos que han sido visitados y de esta forma evitar que existan loops infinitos entre nodos.

Y eso, y nada mas que eso, es TODO lo que se dice sobre Grafos en el material de clases O.o
Saludos ;)

**Comment by fgvenegas** [comment]
Se realizo una ayudantía (en especifico la [Ayudantia 3](https://github.com/IIC2233-2016-1/syllabus/blob/master/Ayudantias/AY03%20-%20Estructuras%20de%20Datos/Ayudant%C3%ADa%203.pdf) ) donde se hablo sobre estructuras de datos como Listas Ligadas y Gráfos, se explico como funcionaban y otro tipo de cosas sobre ellos. Este tipo de ayudantías se utiliza para explicar cosas mas especificas sobre la materia pensando que les pueden ser útiles en el desarrollo de sus tareas, es por eso que si hubo gente que los utilizó en su tarea (quizás también investigaron por su cuenta) salu2 ;)
