### ISSUE TITLE
Porte Edificios

### ISSUE THREAD

**Issue by santiagocruzb** [IIC2233-2016-1/syllabus#404]
Hola! Con tal de poder hacer un poco más fácil la simulación, se puede cambiar el porte de los edificios a 73x73 (que es el mismo porte de los zombies y de los humanos)
Saludos!

@bamavrakis

**Comment by flobarrios** [comment]
Hola!! dado que estarías modificando **soló las imágenes** puedes hacerlo ya que el objetivo de esta tarea no es evaluar interfaces gráficas (y por eso se da el bonus en caso de que quieran hacer más real la simulación visual). Sin embargo, para que quede claro, no es válido modificar métodos ni atributos de la gui. Saludos!!

**Comment by otro-felipe** [comment]
Ojo! No puedes asumir que el tamaño siempre va a ser de 73x73! el tamaño de las entidades puede variar, para eso estan los metodos height y width.
