### ISSUE TITLE
Duda run

### ISSUE THREAD

**Issue by isipalma** [IIC2233-2016-1/syllabus#405]
holi,
mas que todo queria preguntar si es que en el gui.run lo debemos hacer en 50 al igual que en el demo?
y tambien: por donde tienen que entrar las personas en la tienda de armas o en un edificio, o solo tienen que tocar alguna pared de la estructura?
y por ultimo: como recogen botiquines o municion? o parten con algun suministro y los demas los pueden robar y/o compartir?
gracias ;)

**Comment by isipalma** [comment]
olviden la segunda pregunta ;)

**Comment by otro-felipe** [comment]
Respecto a tu primera pregunta: No es necesario que sea siempre 50, lo puedes poner más lento para ver tu simulación el cámara lenta y ver detalles que se te podrían pasar. De todas formas a la hora de corregir la tarea se podria poner cualquier intervalo que no sea más rápido que el tiempo que te demoras en calcular un tick.

**Comment by isipalma** [comment]
pero entonces tendria un problema si ponen un tick ams lento, porq yo calcule, en caso de los edificios, que las personas recibian un tiempo 5 \* tiempo_edificio \* 1200 ya que cada 1200 tick era un edificio y el 5\* tiempo_edificio son los minutos que tienen que pasar antes de que la persona que salio del edificio vuelva a entrar. O hay que tomar que cada tick equivale a un minuto? o hay que hacerlo a tiempo real?

**Comment by MortizDX** [comment]
¿hay alguna forma de obtener el valor que le ingresa uno al tick?
