### ISSUE TITLE
Agragar nuevos zombies

### ISSUE THREAD

**Issue by Zepk** [IIC2233-2016-1/syllabus#406]
Bueno, tengo un problema intentando agregar nuevos zombies después de que uno muerde exitosamente a un humano, intente tanto importando directamente gui en el modulo que contiene la información de mis zombies como haciendo a la gui un atributo de mis zombies, pero ninguna de las dos alternativas crea efectivamente un nuevo zombie en la interfaz gráfica.

Mi código es algo asi:

```
def morder(self, humanos, zombies):
    if achunto_la_mordida:
        if no_la_esquivan:
            zombie = ZombieReal(self.gui, cord_x=una_coordenada, cord_y=otra_coordenada)
            zombies.append(zombie)
            self.gui.add_entity(zombie)
```

¿Como puedo hacer para agregar un nuevo zombie luego de que un humano es mordido?

**Comment by Hernan4444** [comment]
no soy ayudante pero por experiencia, prueba con zombie.show()

**Comment by Zepk** [comment]
@Hernan4444 Mil gracias, eso era :tada:
