### ISSUE TITLE
Enfermos y compartir objetos

### ISSUE THREAD

**Issue by Meaylwin** [IIC2233-2016-1/syllabus#407]
Del enunciado me quedaron un par de dudas:
¿Cuando se enferma cada persona, es un porcentaje de ocurrencia entregado por nosotros y especificado en el README?
Si la personalidad Racional puede compartir munición, ¿también puede compartir botiquines? 
¿Cada persona tiene un espacio ilimitado de municiones, armas y botiquines?

**Comment by santiagocruzb** [comment]
Me sumo. Qué botiquines?

**Comment by Meaylwin** [comment]
Aparece en el enunciado 4.1, pero no se vuelve a hacer referencia de botiquines o enfermedades en el resto del enunciado.
**Enfermedad**: Una persona enferma tendrá una limitación de sus habilidades, lo que reducirá sus posibilidades de sobrevivir. Cuanto más grave sea la enfermedad, peor será el efecto sobre las habilidades de la persona, pudiendo incluso reducir su velocidad a cero. La enfermedad puede ir empeorando o mejorando dependiendo de la gravedad y del uso de objetos, como un botiquín.

**Comment by santiagocruzb** [comment]
@Manuel-uc lo vi, pero claro: no dice de donde salen ni nada más.
