### ISSUE TITLE
Código "no responde" en python shell, pero si en atom

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#41]
Hola, he estado probando código de la tarea 1, y todo me ha corrido bien en atom, pero cuando he querido probar ciertas cosas con la python shell (ya que no me permite input() atom), el código nunca corre y tengo que forzar un cierre del programa. ¿alguna idea al respecto?

Mi otra duda que surge con esto es sobre que pasa si el código me corre normalmente pero ocurre un problema durante la revisión ¿de qué manera evito un caso así?

**Comment by aaossa** [comment]
Preguntas: ¿Imprimes algo antes del `input()`? ¿Se imprime eso? Quizás se queda esperando a que escribas y por eso **parece** que se queda pegado. Si no es esto, ¿puedes correr otros programas `*.py`?

**Comment by aaossa** [comment]
Sobre tu segunda duda: Si lo programas bien no debería pasar eso

**Comment by MortizDX** [comment]
No, no había un input() en el caso concreto. No lo he vuelto a probar en el shell de python pero estoy probando mi código ahora en pycharm y no me ha dado ningún problema ¿a lo mejor es un problema con la cantidad de operaciones que está haciendo? Que yo al hacer click en la shell se quedaba pegada y "no responde" aparecía.
