### ISSUE TITLE
Sobre la deteccion de como moverse

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#411]
Tengo entendio que para cada tick, se deve revisar el comportamiento de cada individuo de el sistema ante cada otro miembro del sistema.
Pero eso tiene un big'O Notation de n^2
¿Eso es correcto, esta bien?

**Comment by otro-felipe** [comment]
Todo depende de cómo hayas pensado tu algoritmo y las cosas que hayas dejado a tu criterio. Si para cada individuo debes revisar a todos los demás individuos, entonces **ese** algoritmo seria O(n<sup>2</sup>).
