### ISSUE TITLE
Grupos tarea 4 en la gui

### ISSUE THREAD

**Issue by mandrade2** [IIC2233-2016-1/syllabus#415]
Hola. Me gustaría saber si puedo asignarle un icono predeterminado a los grupos. Como por ejemplo una imagen con cuatro humanos para diferenciarlos de las personas individuales y así tratarlos como una sola entidad. Esto solo sería para simplificar un poco los grupos en la gui.

**Comment by flobarrios** [comment]
Hola !! Si puedes. Ojo igual si el grupo se separa y cosas de ese estilo. Saludos!

**Comment by mandrade2** [comment]
Muchas gracias!
