### ISSUE TITLE
Relacion personalidades y habilidades

### ISSUE THREAD

**Issue by rmant** [IIC2233-2016-1/syllabus#416]
Hay alguna relacion entre las personalidades y las habilidades ? Por ejemplo una persona valiente debería tener una mejor habilidad de combate? O esto es algo totalmente aleatorio? Y otra cosa, las habilidades son fijas o pueden ir mejorando con el tiempo? Gracias!

**Comment by negebauer** [comment]
Esto queda a tu criterio
Recuerda especificar en el README como lo abordaste

**Comment by tamycova** [comment]
@rmant lo ideal es que sean lógicas! como dices, que una persona valiente debería tener una mejor habilidad de combate sería una buena especificación.
