### ISSUE TITLE
Botiquin/Parche

### ISSUE THREAD

**Issue by FernandoPieressa** [IIC2233-2016-1/syllabus#418]
En partes del enunciado sale que un Humano se puede curar usando parches o sanar de enfermedades con botiquines, sin embargo, no hay ninguna imagen de botiquín para usar dentro del gui, ni especificaciones de donde conseguirlos. Que hacemos con ellos?

**Comment by rodolfopalma** [comment]
Queda a tu criterio si agregas una imagen para representar botiquines fuera de los edificios. Lo importante que se defina un criterio razonable de aparición de los botiquines.
