### ISSUE TITLE
¿Como detengo la simulacion?

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#419]
Comprendo el sistema de ticks. Que el programa los ejecuta y todo eso. ¿Pero que hago despues, como hago que deje de ejecutarlos?

**Comment by otro-felipe** [comment]
En el tick principal puedes poner un `if` de forna que tu codigo solo se ejecute dadas ciertas condiciones.

**Comment by perojas3** [comment]
Sí,eso lo entiendo, pero cual es el comando para detener la simulacion. Le doy un tiempo t
`t-=1

...

if t==0:

  deterner_simulacion`
¿Cual es ese detener simuacion?

**Comment by isipalma** [comment]
No se si ya respondieron en otra parte, pero lo que podrias hacer es poner una condicion de que cuando el tiempo termine guardas las estadisticas en un archivo y cuando haya terminao luego haces sys.exit() (por lo menos a mi me funciono)
