### ISSUE TITLE
Tarea 1 Email Validator

### ISSUE THREAD

**Issue by vicentemartintarud** [IIC2233-2016-1/syllabus#42]
Podemos ocupar el modulo email_validator, para validar los emails que se ingresen al registrar?

**Comment by fgvenegas** [comment]
Nop, la idea es que ustedes creen su propio algoritmo validador :)

**Comment by spiza** [comment]
Y tiene que ser un email?? Podemos simplemente verificar que lo que ingrese la persona no sea un email que ya existe??

**Comment by negebauer** [comment]
Si tiene que ser un email

**Comment by noksenberg** [comment]
se puede usar el modulo re para chequear el email?

**Comment by negebauer** [comment]
@noksenberg Podrías usarlo mientras trabajas para ir viendo que haces bien las validaciones, pero no puede estar en tu entrega

**Comment by jecastro1** [comment]
Ver #65
