### ISSUE TITLE
Se puede cambiar self.setFixedSize(1024, 800) ?

### ISSUE THREAD

**Issue by Nebula2028** [IIC2233-2016-1/syllabus#420]
Busque en issues abiertas y cerradas y a pesar que en varias partes hablan del tamaño del mapa (que ya se que es de 1024x800) en ninguna parte dicen si esta permitido cambiarlo para poder verlo bien en los notebooks ~~normales~~ chicos.

Entonces se puede cambiar ese atributo de la clase MainWidget(QWidget)? O afecta en algo más? Porque revisando los modulos que trae la gui asi al ojo no veo que pueda haber mayor conflicto (dado que usan _SCALE para escalar casi todo).

**Comment by otro-felipe** [comment]
#423
