### ISSUE TITLE
Cerrar GUI programáticamente por eficiencia en los tests unitarios. 

### ISSUE THREAD

**Issue by dtfuller** [IIC2233-2016-1/syllabus#421]
En mi clase que interactúa con la interfaz, estoy tratando crear un método que cierre la GUI. Esto, para poder llamarlo desde el tearDown() de mi TestCase, y así testear de manera eficiente sin tener que cerrar a mano cada instancia de la vista que se me abre. 

Busqué pero nada me ha servido. Hasta ahora he tratado: 

gui.MainWidget.close()
gui.MainWidget.hide()
gui.MainWidget.destroy()
gui.QApplication.closeAllWindows()
gui.QApplication.exit()

Saludos y gracias de antemano.

**Comment by otro-felipe** [comment]
No es necesario tener que cerrar la gui programaticamente si nunca llamas a `gui.run` dentro del testeo (no es necesario llamar este metodo dentro del testeo, solo `gui.init()`).

**Comment by dtfuller** [comment]
Ok, muchas gracias :+1:
