### ISSUE TITLE
Trayectoria Bala

### ISSUE THREAD

**Issue by ManuelSIlvaCav** [IIC2233-2016-1/syllabus#422]
Para los humanos que disparen, la bala tiene que ser realista y seguir una trayectoria recta desde donde se disparo (por lo que puede fallar al objetivo si se moviera) o puede mágicamente seguir al objetivo que se tenia y siempre lastimarlo, pero con menos daño.

Gracias!

**Comment by otro-felipe** [comment]
Esto queda a tu criterio y debes especificarlo en el readme.
