### ISSUE TITLE
Resolución interfaz

### ISSUE THREAD

**Issue by otro-felipe** [IIC2233-2016-1/syllabus#423]
Aquellos que tengan problemas con el tamaño de la pantalla pueden cambiar **solo esta linea de codigo** de la interfaz:

``` python
self.setFixedSIze(Ancho, Alto)
```

En el archivo `gui.main_widget`. Tengan en consideración que tampoco pueden dejarla muy pequeña y recuerden que deben usar siempre los métodos `entity.height()` y `entity.width()` ya que los tamaños de las entidades pueden cambiar.

Los cambios de resolución que hagan deben especificarlos debidamente en el archivo readme.

**Comment by perojas3** [comment]
¿Esto solo cambia el tamaño de como se ve la simulacion? ¿O cambia efectivamente el largo y el ancho? ¿Deja de ser 1200x800?
Sí es asi, sobre los bordes, ¿Como puedo obtener el largo y ancho de la simulacion para dejar el limite de los bordes en funcion de estos?
