### ISSUE TITLE
Movimiento grupos

### ISSUE THREAD

**Issue by rmant** [IIC2233-2016-1/syllabus#424]
En un grupo de personas como funciona el movimiento para que se mantengan juntos? Todos los integrantes se mueven de la misma manera o el movimiento es aleatorio? Además, si los integrantes tienen distintas velocidades de movimiento como evito que ciertos humanos no se queden atrás?
Gracias!

**Comment by negebauer** [comment]
Esto queda a tu criterio y debe ser especificado en el README
La idea es que sea una implementación razonable
Por ejemplo, que los integrantes de un grupo se muevan todos aleatoriamente no es razonable
Tiene que haber alguna relación con el movimiento como grupo

**Comment by fcorencoret** [comment]
Que pasa cuando un zombie se acerca a un grupo? en cada tick ese zombie trata de atacar a cada uno de los integrantes del grupo siempre y cuando esten en el rango que yo defina para atacar?

**Comment by negebauer** [comment]
@FranciscoRencoret1 lo mismo, a tu criterio
Recuerda especificar
Y que tenga sentido
