### ISSUE TITLE
crear entidades ya ejecutado el run

### ISSUE THREAD

**Issue by mhaacke** [IIC2233-2016-1/syllabus#425]
estaba tratando de generar las balas como una entidad propia pero por lo que me di cuenta se necesita que todos las entities estén inicializadas antes del run , me gustaría saber si esto es efectivamente así o si ahi alguna forma de crear entidades ya ejecutado el run .

**Comment by santiagocruzb** [comment]
Agrégalas en el "tick" y acuérdate de poner `entity.show()`

**Comment by mhaacke** [comment]
gracias me sirvió :D

**Comment by camiolguin** [comment]
Cuando se agregan entidades si aparecen con entity.show() pero si agrego alguna decoracion en el tick() no se ven a menos que las ponga antes del run
