### ISSUE TITLE
Actividades

### ISSUE THREAD

**Issue by vbarros2** [IIC2233-2016-1/syllabus#426]
Podrían subir las soluciones de las actividades pasadas para estudiar para el midterm?

Gracias!

**Comment by aaossa** [comment]
Hola, pueden estudiar actividades pasadas y sus respectivas soluciones en el repositorio del curso del semestre 2015-1. El repo, y usuario de entonces, es [IIC2233-2015-1/syllabus](https://github.com/IIC2233-2015-1/syllabus).

**Comment by ManuelSIlvaCav** [comment]
Hola pero podrian subir las actividades con peor rendimiento (yo por ejemplo no entendi 100% metaclases ni la de funcional) y encuentro que las actividades de ese semestre igual son distintas a las de nosotros (algunas no todas)
Saludos!

**Comment by vbarros2** [comment]
Si, me paso lo mismo que a @ManuelSIlvaCav, hay varias actividades con otro enfoque que son bien diferentes a las de este semestre.
Gracias!

**Comment by jecastro1** [comment]
En la prueba se evaluarán habilidades, los contenidos del curso y las lecturas.

Habiendo analizado el asunto con el equipo docente, **no se subirán las soluciones**. 

En el repositorio del 2015-1 hay actividades con solución si quieren verlas.
