### ISSUE TITLE
Unidad de tiempo de SafeZones y de input para tiempo de simulación

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#429]
¿En qué unidad de tiempo se encuentran esos dos elementos? En el caso del tiempo que ingresa el usuario suposé que era en milisegundos, pero para las SafeZones la duda me surge por el valor ingresado en el mapa.csv, ya que pone 0.5 ¿se consideran en milisegundos, en minutos u otro?

**Comment by flobarrios** [comment]
Hola! todo en minutos. Si te fijas, en el csv se especifica que el tiempo de las Safe Zones es en min. Y por si quedan dudas, la tasa de zombies y humanos también es entidades por minutos (está en el enunciado). Saludos!!

**Comment by MortizDX** [comment]
Puff, se me había ido el principio del archivo, jaja, gracias. El tiempo que establece el usuario al principio ¿es en minutos igual entonces?

**Comment by flobarrios** [comment]
Si!! Y para la parte de estadisticas el tiempo también en minutos

**Comment by MortizDX** [comment]
Ok, muchas gracias!
