### ISSUE TITLE
[T01] [Duda]

### ISSUE THREAD

**Issue by vbarros2** [IIC2233-2016-1/syllabus#43]
![capture1](https://cloud.githubusercontent.com/assets/17580808/13863474/cef098ba-ec78-11e5-92d6-a1775404000b.JPG)

Alguna idea de como hacer que funcione esto... me tira error por el código parte1.caso1 ya que parte1 no esta definido,

Gracias!

`

**Comment by aaossa** [comment]
Porque no existe en ninguna parte la variable `parte1`. Si te fijas bien, en ninguna parte escribiste algo como `parte1 = ...`.

Para hacerlo funcionar... así directamente (tal como lo pides) está complicado. Pero si quieres usar los "nombres" en la lista `lista` puedes crear un diccionario y acceder con esos "nombres" como llaves al valor (que sería el objeto de la clase `prueba`)

Un ejemplo:

``` python
class Prueba:

    def __init__(self, caso1, caso2):
        self.caso1 = caso1
        self.caso2 = caso2

if __name__ == '__main__':
    diccionario = {}
    lista = ["P1", "P2"]

    for i in range(2):
        diccionario[lista[i]] = Prueba("caso" + str(i), "caso" + str(i))

    print(diccionario["P1"].caso1)
    print(diccionario["P2"].caso1)
```

PD: **PEP8!!**

**Comment by vbarros2** [comment]
Perfecto, Muchas Gracias!!
