### ISSUE TITLE
Tick

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233-2016-1/syllabus#430]
Para comodidad de uno puede considerar cada tick como 1 segundo y por ello si en el tiempo de simulación me dicen 20 minutos tendrían que ser 1200, obviamente especificando eso en el Readme, u de forma obligatoria consideramos cada tick como 1 minuto?

**Comment by ManuelSIlvaCav** [comment]
Yo igual tengo esa duda, porque 1 tick igual a 1 minuto el arribo de zombies, personas y permanencia en edificios seria muy corta y un poco caotico para la gui. Yo tambien tenia 1 tick 1 segundo btw

**Comment by flobarrios** [comment]
Hola! El tiempo de simulación (en min) no tiene que tener la misma magnitud que el tiempo entre cada tick ya que no es lógico que cada tick sea equivalente a un minuto en la simulación. El usuario ingresa el tiempo en minutos y ahi ustedes ven como transformarlo al tiempo que ustedes definieron para los ticks. Saludos!

**Comment by negebauer** [comment]
Recuerden especificarlo en el README!

**Comment by Hernan4444** [comment]
Ok muchas gracias :+1:  Saludos!!!
