### ISSUE TITLE
Espacio que ocupan las entidades en la Interfaz

### ISSUE THREAD

**Issue by diegosapunar** [IIC2233-2016-1/syllabus#432]
¿Cuantos pixeles usan los edificios, personas y zombies?

Con el fin de que no caigan Zombies arriba de Personas o Edificios.. y cosas por el estilo.

Saludos

**Comment by Phytonia-Master** [comment]
Tengo la misma duda, puedes reabrir la issue @diegosapunar  o responderla si ya la aclaraste porfa?
Salu3
