### ISSUE TITLE
Duda sobre interfaz nueva

### ISSUE THREAD

**Issue by cggutierrez** [IIC2233-2016-1/syllabus#434]
para usarla tal como estabamos usando la anterior, copiamos los archivos y los reemplazamos por los de la carpeta gui y todo funcionaria igual con los problemas solucionados (ademas de no nesesitar entity.show() )??

**Comment by otro-felipe** [comment]
Si, no deberia haber ninguna incompatibilidad.

**Comment by cggutierrez** [comment]
Gracias!
