### ISSUE TITLE
Agregar nuevos entities con su png y clase

### ISSUE THREAD

**Issue by mfuenzalida1** [IIC2233-2016-1/syllabus#435]
Hola!
Tengo una duda; se pueden agregar entities nuevas? como por ejemplo si quiero hacer que cada vez que una persona reciba daño salga sangre, puedo crear la clase en entities.py con su png correspondiente? o esta prohibido modificar ese archivo?

Sorry si ya preguntaron lo mismo, busque y no pude encontrar algo parecido.

**Comment by otro-felipe** [comment]
Puedes crear tu propia clase que herede de `Entity` en tu propio archivo con tus entidades, no hay necesidad de modificar los archivos de la gui. Si quieres ensangrentar por encima a las entidades y que esta imagen las siga puedes usar `add_decoration`.

**Comment by negebauer** [comment]
@mfuenzalida1 Recuerda cerrar el issue si responde tu pregunta
