### ISSUE TITLE
Los objetos seres son solidos?

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#436]
Mipregunta viene a esto. Si 2 zombies se jutan. ¿Estos deven colisionar o se pueden atravezar?

**Comment by sitoro** [comment]
No soy ayudante pero
En #386 dijeron que el tablero debe ser capaz de detectar colisiones ;)

**Comment by perojas3** [comment]
Sí, pero entre las paredes, no 2 seres distintos.
