### ISSUE TITLE
Problema nueva gui

### ISSUE THREAD

**Issue by rmant** [IIC2233-2016-1/syllabus#437]
Cuando cambio de la gui original a la nueva gui no se ve nada, sólo blanco, y se imprime constantemente en la terminal 

> QPixmap::scaled: Pixmap is a null pixmap

Porqué podrá ser? Gracias!

**Comment by Hernan4444** [comment]
A mi me aparecio eso, es porque en algun parte le estas entregando un nombre equivocado como imagen. por ejemplo si el arma se llama "short" talves es estas entregando la primera letra "s". Al menos eso me pasaba a mi cuando me apareció ese error

**Comment by jpdattas** [comment]
como se arregla? tengo el mismo error. incluso usando el archivo demo.py me pasa eso

**Comment by Hernan4444** [comment]
a otro amigo le paso xD el error es que no encuentra las imagenes, alguna entidad esta abriendo alguna imagen que no existe en assets

**Comment by rmant** [comment]
La carpeta gui2 no viene con los assets, había que copiar manualmente la carpeta desde gui a gui2

**Comment by jpdattas** [comment]
jaja eso era. muchas gracias!
