### ISSUE TITLE
Que objetos existen y de donde se obtienen?

### ISSUE THREAD

**Issue by rmant** [IIC2233-2016-1/syllabus#438]
No me queda claro que objetos existen aparte de las armas, sólo los botiquines? Y de donde se obtienen estos? Salen de la nada? Gracias!

**Comment by iavasquez1** [comment]
Yo también tengo esta duda porfavor aclárenla

**Comment by cggutierrez** [comment]
tengo la misma duda de los botiquines!

**Comment by rmant** [comment]
Cabros, en buena, pero como quieren que teniendo midterm el martes, termine la tarea para el miércoles si hay algo que no está ni cercano a estar claro en el enunciado, y a pesar de haber hecho un issue el viernes, hoy día lunes todavía nadie se pronuncia al respecto. No es con la primera tarea que me pasa. Entiendo que los ayudantes tienen otras cosas que hacer y no están todo el día respondiendo dudas, pero en ese caso, al menos hagan enunciados claros. Por favor no respondan "Queda a tu criterio, especifícalo en el README". Gracias!

**Comment by fcorencoret** [comment]
Estoy muy de acuerdo. Los enunciados estan siempre incompletos y no basta con el 'que quede a tu critero, especifica en el README'  porque siempre quedan cosas demasiado abiertas como para ser especificadas por nosotros. Seria filete si pudieran hacerlo mas especificados. Gracias!

**Comment by mandrade2** [comment]
Yo creo que darnos la flexibilidad de hacer un programa con nuestros criterios es algo que nos beneficia a todos  y nos da espacio para hacer un programa menos pauteado en algunos aspectos. Yo apoyo el "que quede a tu criterio" de los ayudantes ya que basta con tomar una decisión y ponerla en el README. Saludos!

**Comment by flobarrios** [comment]
Hola! hace un tiempo en #418 se respondió algo similar. Efectivamente aparte de las de las armas solo existen los botiquines. Donde "aparecen" o se obtienen queda a tu criterio pero te voy a dar algunos ejemplos:
- Puedes hacer que cada cierto tiempo y probabilidad a algún humano random le llege de "regalo" un botiquín aumentando sus vidas.
- Algo similar pero que tenga quizás un poco más de lógica y le llege al humano más damnificado.
- Podría aparecer una imagen de un botiquín en alguna parte de la ventana de la simulación que dure cierto tiempo en pantalla y si algún humano lo intercepta entonces aumenta su vida.

Les dejo una imagen de un botiquín por si no saben de donde obtenerla ![medkit2](https://cloud.githubusercontent.com/assets/11543803/15300348/8839201a-1b7e-11e6-813b-608da60663f9.png) y un ejemplo para representarlo gráficamente:
- Una vez que el humano recibe o intercepta un botiquín, se le agregue a esta entity una decoración de la imagen que les adjunté u otra a elección por algunos segundos para saber que sus vidas han aumentado.

**NOTA:** estos son simplemente ejemplos que pueden utilizar por si les estaba costando el "queda a tu criterio" pero efectivamente ustedes pueden elegir libremente como abordar este problema. Lo único importante es que sea razonable y que por ejemplo, una persona no este recibiendo botiquines constantemente con el fin de que nunca muera ya que esto no es real. 

Cuando les decimos "queda a tu criterio" aprovechen que no tienen que hacer algo textual de un enunciado y atrévanse a tomar una decisión al respecto. Espero que haya quedado más claro y perdón por la demora. Saludos!

**Comment by rmant** [comment]
@flobarrios Ahí me quedó claro. Muchas gracias!
