### ISSUE TITLE
Problema Zombies

### ISSUE THREAD

**Issue by noksenberg** [IIC2233-2016-1/syllabus#440]
Hola, 

Despues de aplicarle la funcion show() a una entidad Zombie se me cambia automaticamente el width() a 120, cuando debería ser 36. Que puedo hacer para solucionarlo?

Gracias.

**Comment by otro-felipe** [comment]
En qué contexto usas esa función? Estás agregando alguna decoración?

**Comment by noksenberg** [comment]
Es para agregar zombies una vez que ya se comenzó a correr el run

**Comment by otro-felipe** [comment]
Probaste con la nueva gui? En ella ya no debes hacer `show()`. ¿Estabas haciendo `entity.show()`?

**Comment by noksenberg** [comment]
Si, que debo hacer en lugar de show()?

**Comment by negebauer** [comment]
@noksenberg Solo el `add_entity`

**Comment by noksenberg** [comment]
Al usar solo add_entity de la nueva gui las cosas me empiezan a aparecer así:

![image](https://cloud.githubusercontent.com/assets/8571906/15275688/b65973f4-1aa8-11e6-8a14-38c506fc365e.png)

**Comment by otro-felipe** [comment]
Tienes que usar la nueva gui. Reemplazar los archivos dentro de gui2 por los archivos donde tu tienes la gui se tu tarea.

**Comment by noksenberg** [comment]
Ok, gracias!
En la nueva gui tambien funcionan hide y add_decoration?

**Comment by noksenberg** [comment]
Gracias!

**Comment by otro-felipe** [comment]
Creo que lo dije al reves jajaja lo que queria decir era: mover los archivos dentro de gui2 a la carpeta donde tienes tu gui n.n
