### ISSUE TITLE
Importancia eficiencia Tarea4

### ISSUE THREAD

**Issue by jpdattas** [IIC2233-2016-1/syllabus#441]
Hola, que tanto se espera del punto de vista de la eficiencia del código? osea cuantos recursos consume o que tan lento sea?

A veces me debato entre hacer un comportamiento más sofisticado que consumiría más recursos o uno más simplista. Que recomendarían?

**Comment by Geeermy** [comment]
¡Hola!
Aquí no buscamos la solución perfecta, nos preocupa más que la simulación y los eventos de ella se hagan de forma correcta.
No obstante, tampoco es la idea que los movimientos de tus personajes cambien una vez por hora. Trata de que tu solución sea lo suficientemente buena para que el programa se vea relativamente fluido :).
Si crees que tu programa va muy lento con tus soluciones, puedes buscar formas más efectivas de resolver los problemas (por ejemplo, con estructuras de datos más sofisticadas y aplicadas).
¡Éxito con la tarea! :)
