### ISSUE TITLE
Dudas con la muerte

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#442]
Tengo unas dudas de que devo hacer cunado se muere un personaje se muere, osea cuando su vida baja a 0.
¿Que pasa cuando un humano se muere? ¿Se convierte en un zombie? ¿O solo se combierte si es mordido?
¿Cuando un ser muere definitvamente, como lo quito del sistema?¿Cual comando debo usar? ¿En que momento debo usarlos?
Eso seria, espero su respuesta, porque las nesesito para continuar.

**Comment by flobarrios** [comment]
Hola! un **humano** muere cuando es atacado por un zombie (no si es mordido) u otro humano y en este caso, debes eliminarlo de tu simulación, guardando el registro para las estadísticas. Como lo quitas del sistema depende de como hayas modelado el problema pero por ejemplo si es un objeto, puedes hacerlo [así](http://stackoverflow.com/questions/16686788/python-how-to-kill-a-class-instance-object). El momento en para usarlo depende de ti (obviamente siempre después de que haya muerto) ya que debes pensar en como calcular las estadísticas. 

PD: Si es mordido por un zombie se convierte automáticamente en uno de estos y si después de esto es atacado y muere, **muere como zombie y no como humano** y aplica lo mismo que te dije antes para quitarlo de la simulación.

Saludos!

**Comment by perojas3** [comment]
Me refiero a como puedo quitar de la interfaz grafica al humano, y como puedo "borrarlo" para que deje de consumir ram.

**Comment by rmant** [comment]
@flobarrios  Y como se elimina al humano o zombie de la GUI? Me pasa que cuando mueren siguen apareciendo en la interfaz. La GUI solo tiene el metodo de add_entitiy, pero no encuentro uno para eliminarlo. Gracias.

**Comment by Hernan4444** [comment]
@flobarrios  aprovechando el issues, si tengo en una variable un objeto (ej x = objeto_1) y luego sobreescribo la variable (x = objeto_2) que pasa con el objeto_1, se elimina??

**Comment by Hernan4444** [comment]
@rmant por lo que vi, si haces zombie.deleteLater() te lo elimina, es el mismo comando que se usaba para la tarea 2

**Comment by rmant** [comment]
No me funciona con deleteLater()

**Comment by gantunesr** [comment]
@rmant ¿zombie._base_label.hide()?

**Comment by otro-felipe** [comment]
Acceder a atributos protegidos de las clases es una mala práctica, con `entity.hide()` o `entity.deleteLater()` debería bastar.

**Comment by bmarinb** [comment]
No existe deletelater()

**Comment by negebauer** [comment]
@Hernan444
El objeto 1 va a ser eliminado por el recolector de basura de Python.
Esto siempre y cuando la variable x haya sido la única referencia al objeto 1

**Comment by Hernan4444** [comment]
@negebauer Muchas gracias :+1:  justo eso necesitaba leer c:

**Comment by otro-felipe** [comment]
@bmarinb ojo que la L es mayuscula. delete**L**ater().

**Comment by rmant** [comment]
@negebauer No entendí lo que dijiste, podríai explicarme porfa? Si simplemente hago "del instancia" no se me elimina de la gui. Gracias!

**Comment by flobarrios** [comment]
@rmant antes de hacer del instancia debes hacer instancia.deleteLater()

**Comment by negebauer** [comment]
@rmant 

``` python3
x = objeto_1     ## hago una referencia a objeto_1
x = objeto_2     ## elimino la única referencia al objeto_1, el objeto_1 va a ser eliminado
```

``` python3
x = objeto_1     ## agrego una referencia al objeto_1
y = objeto_1     ## otra referencia al objeto_1
x = objeto_2     ## elimino una referencia al objeto_1,
                 ## pero sigue teniendo la referencia 'y' por lo que no se elimina
```

En el caso de la `gui` no basta con que eliminen su objeto, también tienen que eliminarlo de la `fui` misma, como dice @flobarrios

**Comment by gebalassa** [comment]
Qué hace .deleteLater y por qué no basta la eliminación de la instancia de donde esté guardado (ej: Una lista)?

**Comment by negebauer** [comment]
Al agregar la entidad a la gui está también guarda una referencia a ella
Por eso hay que usar deleteLater para que elimine esa referencia también
