### ISSUE TITLE
Cargar mapa en dimensiones distintas

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#443]
Si modificamos las dimensiones de la simulación, y en el archivo mapa que nos dan hay coordenadas fueran de las nuevas dimensiones y/o las dimensiones del mismo edificio no caben/no se ven completamente (debido a su ubicación indicada) ¿qué se debe hacer? ¿se cargan tal cual como indica el archivo, se ubican en otro lado o no se cargan?

**Comment by otro-felipe** [comment]
No debes preocuparte por esto. Como te habrás fijado, al cambiar la resolución en la nueva gui cambias la escala de las entidades también, por lo que de tener problemas de espacio podríamos escalar dichos mapas. Sin embargo, debes tener consideración de no escoger un tamaño demasiado pequeño, debes ser criterioso en este aspecto también.
