### ISSUE TITLE
Convertir a Zombie

### ISSUE THREAD

**Issue by cggutierrez** [IIC2233-2016-1/syllabus#444]
Cuando un humano se convierte a zombie por mordedura, el nuevo zombie tendrá la misma vida que tenia el humano (es lo mas lógico que pienso)?, se inicia simplemente un nuevo zombie con toda la vida o simplemente queda a mi criterio? (pregunto por si es que es requisito algo)

**Comment by flobarrios** [comment]
Hola ! Queda a tu criterio. Especificalo en tu README!

**Comment by cggutierrez** [comment]
Gracias!
