### ISSUE TITLE
Problema con un tipo de teletransportacion

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#445]
No me respondieron esto, https://github.com/IIC2233-2016-1/syllabus/issues/436
Por lo que programe un tipo de coliccion entre zombies y personas. Pero en ocaciones ocurre una teletransportacion. Como si u zombie se meuve unos cuantos especios cuando otro zombie se meve cerca de él.
¿Esto importa o no?

**Comment by otro-felipe** [comment]
Si hay bugs en la simulacion entonces ~~hay tabla~~ es motivo de descuentos. Las simulaciones deben ser muy fieles a las realidades de manera de tener resultados correctos, la idea es que las entidades no se muevan en direcciones ni en cantidades que no les corresponde.

**Comment by perojas3** [comment]
Es que estos problemas me recuerdan a los videojuegos tanto actuales como antiguos.
Si hasta en niveles profecionales tienen problemas con las coliciones. ¿Es posible para nosotros poder programarlas sin esos errores?

**Comment by Geeermy** [comment]
Claro, pero considera que en esos juegos tienen equipos de **más** programadores, muchos encargados de diferentes cosas que deben ser compartidas en conjunto para un programa común posteriormente. Con tantas líneas de código de distintas personas, es más "perdonable" que se les pase algo (aunque muchas veces igual deben subir actualizaciones arreglando esos problemas). En lo que te pedimos nosotros, no debiese ser tan difícil encontrar ese pequeño bug :) así que anímate y revisa tu código.
¡Suerte! :)

**Comment by perojas3** [comment]
Requiero ayuda fisica para esto. Puedo hablar con un ayudante el lunes o el martes?

**Comment by fgvenegas** [comment]
Mientras te responden aprovecho de spamear invitandolos a la Programaton del dia miercoles donde habrá ayudantes del ramo para resolver sus dudas :)
