### ISSUE TITLE
Límite de entidades en mapa

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#446]
Al momento de crearse los zombies y personas ¿estas no pueden "surgir" en el misma cordinada ni sobreponerse, verdad? De ser así, no significa que hay un tope "máximo" de entidades que puede haber en pantalla? ¿Que debemos hacer si el usuario introduce más de lo que puede aguantar el tablero? (lo mismo con las tasas de llegadas de entidades)

**Comment by otro-felipe** [comment]
Pueden asumir que no vamos a ingresar una cantidad exagerada de manera que no quepan en el mapa. Si quieres puedes calcular el area que usaran las entidades y el area disponibles y ver si caben o no y en base a eso hacer algo.
