### ISSUE TITLE
¿Como agrego entidades al mapa cuando ya esta corriendo?

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#447]
Tengo la siguiente duda.
Cuando ya esta corriendo la simulacion, y quiero agregar un nuevo zombie o humano a esta, o tranformar un humano en un zombie. Como hago para que esta entidad aparezca en la interfaz grafica.
Ya intente con gui.add entity, pero eso solo me funciona cuando estoy agregando entidades antes de empezar la simulacion, no despues.  Sospecho que es con add_decoration(path), pero no entiendo como hacerla funcionar.
¿Me podrian explicar?

**Comment by otro-felipe** [comment]
Estas usando la nueva gui?

**Comment by perojas3** [comment]
Sí

**Comment by perojas3** [comment]
La decargue pero no estoy seguro si la estoy usando o no. Simplemente la baje con git, y la deje en la carpeta donde estoy trabajando. ¿Hay que hacer algo más?

**Comment by VNicholls** [comment]
Fijate que el nombre de la carpeta sea el mismo al que llamas (la nueva se llama gui2). Además la gui2 viene sin la carpeta assets con las imágenes! :+1:

**Comment by gantunesr** [comment]
me paso lo mismo, en el archivo **init**.py de la gui anterior no tiene una línea. En la gui2 esta solucionado.
Antigua gui:

![screen shot 2016-05-14 at 11 21 26 pm](https://cloud.githubusercontent.com/assets/17601467/15271659/69465a56-1a2a-11e6-8d89-6fa77c33eb2f.png)

gui2:

![screen shot 2016-05-14 at 11 21 33 pm](https://cloud.githubusercontent.com/assets/17601467/15271660/6b78a32e-1a2a-11e6-969f-fd3110c2a925.png)

**Comment by gebalassa** [comment]
3 horas en esto :-/

gracias gg

**Comment by negebauer** [comment]
#440 
#437
