### ISSUE TITLE
Capacidad GunShops

### ISSUE THREAD

**Issue by Zepk** [IIC2233-2016-1/syllabus#448]
En el enunciado se menciona que las GunShops tienen un stock de armas y una capacidad para albergar gente, pero para que sirve la capacidad de estas tiendas?
Hasta donde entiendo estas no funcionan como safe-zones, si una persona entra a esta, obtiene sus armas y sale inmediatamente por lo que no tiene mucho sentido que estos edificios tengan entonces un atributo de capacidad, sobre todo porque si se acaban las armas que tiene, este desaparece.

**Comment by ManuelSIlvaCav** [comment]
Tengo la misma duda! y ademas, las gunshops cuando se les acaba el stock, hacemos desaparece el edificio de la gui, o simplemente lo dejamos y que las personas no vayan ya que no les sirve.

Ultima cosa, las municiones para cada tipo de arma son distintas xd? o son compartidas para no hacer mas codigo y dejar solo 1 tipo de municion

Salu2

**Comment by agmardones** [comment]
No soy ayudante, pero en el enunciado sale que los edificios en general dan un tiempo zombie-free. Al menos yo, hice que las tiendas tuviesen un tiempo de atención, onda para que pueda llegar otra persona y ponerse en la cola de espera (y aquí supongo que hace sentido la capacidad y que funcione como safezone)

**Comment by Zepk** [comment]
@ManuelSIlvaCav Al menos yo entendi que las armas de corto alcance eran armas de combate cuerpo a cuerpo, como cuchillos, hachas, ese tipo de cosas, porque en el enunciado solo se hablaba de balas para las armas de largo alcance, en cambio para las de corte se hacia referencia a los "golpes"

@agmardones Gracias por esa respuesta, yo de momento estoy haciendo lo mismo :)

**Comment by ManuelSIlvaCav** [comment]
D: me deje llevar entonces por las fotos que ocuapn en la gui de una pistola y una aka :(, vale por la aclaracion

**Comment by negebauer** [comment]
Lo ideal es hacer algo como lo mencionado por @agmardones 
Las personas hacen fila en la tienda de armas y mientras están en la fila están seguros

**Comment by negebauer** [comment]
Sobre las armas vean #457
