### ISSUE TITLE
Espacios ocupados en el mapa 

### ISSUE THREAD

**Issue by lampuerov** [IIC2233-2016-1/syllabus#449]
Hola, tengo dudas respecto al espacio ocupado por los entities:
1. ¿De qué forma puedo saber si un espacio del mapa está ocupado o no?
2.  Si debo definirlo yo, ¿Cuál es la forma más eficiente de hacerlo?

Salu3

**Comment by otro-felipe** [comment]
Debes definirlo tú e identificar la forma de hacerlo es parte de la tarea, la idea no es tener el algoritmo más eficiente de todos, pero tampoco puede demorarse en exceso.
