### ISSUE TITLE
Duda acerca de los correos utilizados

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2233-2016-1/syllabus#45]
Hola. Mi duda es esta, el enunciado dice primero, con respecto al correo del nuevo usuario:
 "...y ademas un nombre de usuario y correo que no hayan sido utilizados previamente"
Luego, en la parte del baneo, dice que: 
"Ademas, debe restringirse la creacion de nuevos usuarios que utilicen el correo electronico del baneado (así evitamos que vuelva a ingresar al sistema... con el mismo correo al menos)."

¿No es redundante esto? Tengo la impresión que no cambia en nada esto respecto a si el usuario no estuviera baneado, porque incluso si no estuviera baneado, no podría crearse un usuario nuevo con su mismo mail, ¿se entiende mi duda?
Lo de embargarle sus productos sí está claro, pero este aspecto creo que no haría diferencia.
Gracias!
Saludos.

**Comment by Geeermy** [comment]
Hola!
Sí, se entiende tu inquietud, y sí, es algo redundante, pero en las páginas de ventas normales funciona de esa forma... si te banean en MercadoLibre, por ejemplo, no es nada difícil crear otro mail para poder usar una cuenta nueva. Ahora, la diferencia radica en que ahí también ingresas información financiera (como tarjetas de crédito, por ejemplo), lo que hace más complicado volver a ingresar al sistema... como estamos en una versión simplificada, obviamente será más fácil ingresar nuevamente al sitio usando solo otro mail. Y bueno, en este tipo de páginas tampoco te dejan asociar más de un usuario a un mismo mail, nada que hacer con eso.
La idea es que antes de crear un usuario, definitivamente deberás verificar que el mail no sea de un usuario baneado, y además, que no sea de un usuario ya creado, tienes que hacer ambas verificaciones antes de permitir la creación (y revisar que sea un mail válido, además).
Espero haber aclarado tu inquietud :) saludos y suerte!
