### ISSUE TITLE
Representacion de grupos de personas

### ISSUE THREAD

**Issue by cggutierrez** [IIC2233-2016-1/syllabus#450]
Como represento un grupo de personas en la gui? solo como varias personas juntas caminando en la misma dirección ? (asumiendo que no serán grupos tan grandes como para que se superpongan con lo demas de la gui o al chocar una parte del grupo esta se separe por cambiar de direccion), como una sola persona que funciona como varias a la vez?  o tenemos que hacer nuestra propia imagen para un grupo? (si es que tenemos que hacerla, como se hacen?)

**Comment by Geeermy** [comment]
¡Hola!
Esto queda a tu criterio, pero debes especificarlo en tu README, y que ojalá sea entendible/intuitivo. Por ejemplo, si decides poner una sola persona, que en alguna parte yo sepa la cantidad de integrantes que abarca. Por otra parte, recuerda que un grupo de personas sí o sí ocupa más espacio que un solo individuo (puedes asumir que se reunen en un círculo completo, por ejemplo... pero nuevamente, a criterio), así que debes buscar una forma de mostrar eso en tu interfaz.
Si quieres hacer tu propia imagen, te recomiendo Photoshop :) o bien Paint y después buscas programas online para hacer el fondo transparente jaja (para todo este tipo de cosas, te recomiendo **google**, te ayudará más que yo).
Si finalmente decides guiarte por la primera opción (todos juntos caminando en la misma dirección), también está bien.
¡Saludos y éxito! :)

**Comment by cggutierrez** [comment]
Gracias! :dancers:
