### ISSUE TITLE
Duda con el estúpido

### ISSUE THREAD

**Issue by IsaacConDosA** [IIC2233-2016-1/syllabus#451]
Hola! 
¿El estúpido no es tan estúpido como para quedarse si no tiene balas, verdad?
O sí alcanza ese nivel y es una muerte segura?
Salu3

**Comment by Geeermy** [comment]
¡Hola!
Esto queda a criterio tuyo, pero si es "estúpido", no sería raro pensar que cometería semejante imbecilidad. Pero recuerda que otras personalidades podrían predominar ahí, si es estúpido y cobarde, podría hacer otra cosa. Pero como dije antes, la manera en la que cambian esas decisiones queda a tu propio criterio.
Salu24500-03
