### ISSUE TITLE
Pixeles que ocupa el zombie

### ISSUE THREAD

**Issue by lampuerov** [IIC2233-2016-1/syllabus#452]
Tengo un problema con el ancho de los zombies, pues van variando con cada tick. 
¿Cómo arreglo esto?

**Comment by fnquinteros** [comment]
Yo hice algo que no sé que tan legal sea, que sería copiar un método de Human que aparece en entities llamado updatePixmap, lo arreglas un poquito porque tienes que importar un par de métodos de gui.entities para que funcione. Aprovecho para preguntar si es legal o no lo que hice jeje...

**Comment by otro-felipe** [comment]
@fnquinteros Si tuviste que hacer eso, sospecho que hardcodeaste de alguna manera el ancho y eso no está bien. La idea es que no te preocupes cuál es el numero exacto del ancho de las entidades. Cada vez que las necesites debes usar `entity.width()` o `entity.height()`, si cambian o no cambian no debería hacer ninguna diferencia en sus tareas.

**Comment by MortizDX** [comment]
Estaba viendo lo de las colisiones, y me surgió esa duda con los zombies ¿por qué ocurre eso? ¿que hace el "rotar" a las imágenes que cambian las dimensiones de los zombies pero no la de los humanos? Sé que la esquina superior izquierda no cambia al rotar, pero me confunde lo del resto de la imagen.

EDIT: Experimentando, si roto 2 edificios pegados entre sí, estos se sobrelapan en ocasiones, mientras que con las personas/zombies no pasa ¿así tiene que ocurrir?

**Comment by Nebula2028** [comment]
mm yo no soy ayudante pero al menos para solucionar ese molesto cambio de tamaño al rotar los zombies tuve que crear una clase MiEntidad que heredara de Entity y luego MiZombie hereda de MiEntidad. La gracia es que MiEntidad haga overriding al metodo updatePixmap() de Entity tal cual solo que sin la última línea del metodo original (self.setFixedSize(self.__pixmap.width(), self.__pixmap.height()))

Al menos asi dejan de cambiarse de tamaño los zombies al rotarse.

Saludos

**Comment by jpdattas** [comment]
@MainScientist me surgio este mismo problema al querer trabajar con las cordenadas del centro de las imágenes en vez de las de la esquina. Lo hice para que se viera mejor, especificamente para la visión de las entidades. trabaje con width y height y no entendía por que se comportaba raro hasta notar que estos cambiaban de tamaño. creo que si no uso distancia fija no se consideraría hardcodeo o si ?. 
Como sea, se puede hacer overriding de cosas de la gui en este caso?
