### ISSUE TITLE
Con respecto al manejo de excepciones

### ISSUE THREAD

**Issue by fnquinteros** [IIC2233-2016-1/syllabus#453]
En el pdf de la tarea sale explícito una sección sobre el correcto manejo de excepciones en el programa... esto me hace pensar que habrá puntaje de la tarea por manejo de excepciones. El tema es: ¿Qué pasa si mi programa no arroja ninguna excepción? ¿Me dan menos puntaje por no usar manejo de excepciones? en ese caso, ¿conviene hacer el programa de manera que se generen errores de forma consciente para poder usar manejo de excepciones? Salu3!

**Comment by Hernan4444** [comment]
Estoy con las mismas dudas, con suerte hice una excepción para sentir que use algo de esa materia pero todo lo demás lo intente preveer con condiciones y cosas por el estilo. ¿hay tabla por no usar excepciones?

**Comment by Geeermy** [comment]
¡Hola!
Obviamente, la idea es que implementen excepciones que tengan **sentido**.
Probablemente, dentro de la simulación, como ustedes hacen el manejo nunca se enfrenten a esa situación, pero ¿qué hay del input del usuario para la simulación?, ¿qué hay de la lectura de mapas?
Recuerden que hay más cosas a parte de la simulación que hay que tener muy en cuenta, ya que no tendrán el control solamente ustedes como programadores (los correctores, como usuarios de la simulación, pueden jugar también...).
¡Saludos! :)
