### ISSUE TITLE
Tiempo de simulacion en ticks

### ISSUE THREAD

**Issue by cggutierrez** [IIC2233-2016-1/syllabus#454]
como interpretamos el tiempo de simulación que recibirá nuestro programa, cada tick es un segundo o un minuto?
Ademas de eso, es necesario ajustar el delay del gui.run para que corra a tiempo real o da igual el tiempo en que corra?

**Comment by negebauer** [comment]
#430

**Comment by cggutierrez** [comment]
Gracias, busque pero no lo vi!

**Comment by negebauer** [comment]
Recuerda cerrar el issue cuando estés conforme :)
