### ISSUE TITLE
Manejo de excepciones

### ISSUE THREAD

**Issue by JoseDaroch** [IIC2233-2016-1/syllabus#455]
Hola, 
Hay algo que no entiendo respecto al manejo de excepciones. Llevándolo un poco a la tarea, por manejo de excepciones que se entiende?, por ejemplo si el usuario que pondrá a correr nuestra simulación ingresa una letra para el numero de zombies (se genera un error), tengo que imprimir los mensajes correspondientes en un except y luego el programa termina? o tengo que seguirle pidiendo valores?, en el ultimo caso no seria mejor meter la respuesta de numero de zombies en un while "respuesta no sea un numero", y preguntar hasta el infinito?
Eso, gracias

**Comment by flobarrios** [comment]
Hola!! tu programa debe manejar las excepciones con el fin que que este no termine por estos motivos. No es necesario que imprimas el error en consola y para la última pregunta, piensa que una mejor implementación podría ser que ese while contenga un try/except. Obviamente (fuera de esta tarea) también podrías hacerlo como tu dices y funcionaría pero la idea de esta tarea es que aprendas una nueva forma de manejar posibles errores a través de exceptions y por ende, te recomiendo fuertemente manejar los inputs de esta forma para que tengas todo el puntaje en ese item!

Fijate en este codigo de [stackoverflow](http://stackoverflow.com/questions/11758029/try-block-inside-while-statement)

Espero que haya quedado mas claro. Saludos!!

**Comment by otro-felipe** [comment]
Para ampliar un poco la respuesta de @flobarrios , la idea del manejo de excepciones es hacer tu código como si todo estuviese bien y "rodear" ese código dentro del bloque try/except. De esta forma el código se ve como: `try {Hago como que todo esta bien}si falla por ValueError{Hacer esto cuando encuentre un inesperado}`. Varias veces es más sencillo o intuitivo pensar en que poner un if es más que suficiente, pero cuando te enfrentas a lenguajes de más bajo nivel, puedes definir tus propias excepciones las cuales deben estar definidas junto con la funcion. Por ejemplo:

``` java
public class UC{

public static AlumnoUC login(String username, String password) throws LoginException{
    // blablabla
    return new AlumnoUC(username, password);
    }
}
```

Este es un método en java, en este se declara la clase UC con un método estático `login` y una keyword `throws`. La gracia de esto es que java no te va a dejar usar este método a menos de que escribas el try/catch para manejar la excepción. De esta forma, otras personas usando este método pueden manejar mejor los problemas que puede suponer un login fallido, además dentro de la excepción puedes agregar un código de error, de esta forma, puedes separar el flujo ideal de la función de el flujo a seguir en caso de error de manera más intuitiva y legible.

**Comment by JoseDaroch** [comment]
Muchas gracias! @flobarrios @MainScientist
