### ISSUE TITLE
Resultado tasas

### ISSUE THREAD

**Issue by isipalma** [IIC2233-2016-1/syllabus#456]
Holi

Me surgio la siguiente duda: Cuando dice Tasa de muertes en la parte de estadisticas a cuales muertes se refiere? solamente a la de las personas o tambien a la de los zombies (pregunto por si acaso)
Tambien queria saber si la tasa de conversion es numero de convertidos total partido por el tiempo de la simulacion en minutos

Saludos y gracias de antemano ;)

**Comment by flobarrios** [comment]
Hola!! dado que se pide el numero de muertes tanto de humanos como de zombies, **la tasa de muerte la debes calcular para ambos por separado.** La tasa de conversión si se calcula como tu dices. Por ejemplo, imagina que el total de humanos convertidos fue 20 y el tiempo de simulación fueron 10 minutos. La tasa de conversión sería 20/10 = 2 (Se convierten 2 humanos en  zombie por minuto). Saludos!

**Comment by isipalma** [comment]
Muchas gracias! eso si dos dudas mas :3 : mi tasa de muertos de humanos es por heridas, disparos o por ataque por garras o pelea con otra persona, pero no cuento por convertido, esta correcto esto?
y deberia detener la simulacion si se acaban todos los humanos en cierto tiempo? ya que puede ser que en el ultimo segundo de la simulacion, cuando ya todos los humanos estaban muertos justo llega un humano por tanto no hay apocalipsis, entonces es medio injusto

**Comment by flobarrios** [comment]
Exacto! No tienes que contar los convertidos. Lo segundo queda a tu criterio pero si existe la posibilidad de llegue otro humano quizas los correcto no es detener la simulación ya que existe al menos un sobreviviente.

**Comment by isipalma** [comment]
gracias!

**Comment by flobarrios** [comment]
@isipalma porfavor cierra la issue cuando ya este resuelta. Saludos!
