### ISSUE TITLE
Armas de corto alcance: ¿combate cuerpo a cuerpo o pistolas con "corto alcance"?

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#457]
Había estado trabajando con la idea de que se refería a lo segundo, debido a la imagen que se encontraba los assets del gui, pero tras leer #448, prefiero preguntar directamente a que se referie con eso para estar seguro.

**Comment by IsaacConDosA** [comment]
Yo tambien lo estoy haciendo como pistolas de corto alcance. Supuse que las de largo alcance eran rifles y cosas así.

**Comment by negebauer** [comment]
Sobre las armas, es como menciona @Zepk en #448, tomen como que todas las armas de corto alcance funcionan igual. Dan golpes al estar cerca y no tienen munición.

**Comment by MortizDX** [comment]
Oh, ok, significa que tras conseguir una de corto alcance, nunca debería perderla ¿verdad?

**Comment by negebauer** [comment]
@MortizDX Eso no esta especificado en el enunciado por lo que queda a tu criterio (Hint: que no la pierda es un buen criterio)
Recuerda especificarlo en el README

**Comment by MortizDX** [comment]
Eso pensaba hacer, muchas gracias!
