### ISSUE TITLE
Problema con quitar decoración ( add_decoration() o (None) )

### ISSUE THREAD

**Issue by Nebula2028** [IIC2233-2016-1/syllabus#458]
Hola, estoy intentando quitar la decoración de una entidad una vez iniciada la simulación, y según lo que entiendo el metodo add_decoration(self, path) viene con un if que si path es None hace algo como "quitar la decoración", pero en la práctica esto no me funciona porque:
1.- si hago self.add_decoration() me tira TypeError por que falta 1 positional argument (path)
2.- si hago self.add_decoration(None) me tira AttributeError: 'NoneType' object has no attribute 'deleteLater'

Como lo hago? (por mientras estoy reemplazando la decoración por otra, pero me gustaría volver al estado sin decoración de alguna forma)

**Comment by Nebula2028** [comment]
alguien alguna idea ?

**Comment by otro-felipe** [comment]
Esto pasa cuando haces `add_decoration(None)` a una entidad que ya no tenia ninguna decoración.

**Comment by Nebula2028** [comment]
mmmm pero estoy seguro que le estoy haciendo self.add_decoration(None) a cosas que si tienen decoración, y no funciona. De hecho si uno hace: 
self.add_decoration(imagen1)
self.add_decoration(None)
self.add_decoration(imagen2)

El resultado es que queda con ambas decoraciones, una puesta encima de la otra. Aun no logro hacer que algo vuelva a no tener decoración.

**Comment by Nebula2028** [comment]
creo que lo solucioné. Hay que hacer self.updatePixmap() despues de cada cambio de la decoracion. Al menos asi me resulto el "des-decorar". No se si esto es lo esperado... pero es la unica forma que me resulta

**Comment by otro-felipe** [comment]
No debería pasar así, quizás estás escribiendo mal algún path, si tienes pusheado el código en tu repo podría echarle un ojo. No accedes a ningún parámetro protegido dentro de tu código cierto? No has modificado nada de la interfaz?
