### ISSUE TITLE
¿Chequear si un rango de números intersecta o está dentro de otro rango de números?

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#460]
¿Es posible hacer eso en python? Se me ocurre si ambos rangos son solo con enteros, tendría que recorrer cada valor del primer rango y compararlo con los extremos del segundo, ¿pero si fuera con dominio en los reales?

**Comment by tamycova** [comment]
Hola @MortizDX ! dale una segunda vuelta, que este en los reales no hace una diferencia mayor en el algoritmo :)

**Comment by gebalassa** [comment]
Si es para las colisiones, ¿No resultaría mejor usar desigualdades? ("<", ">", ">=", "<=")

**Comment by MortizDX** [comment]
@tamycova Puff, se me ocurrió algo recién y que no era tan distinto a lo que ya tenía, jaja ^^u Gracias por la respuesta de todas formas!
@gebalassa Eso hacía, pero no sé como se fue no ampliarlo a más dimensiones, jeje.
