### ISSUE TITLE
Decorar

### ISSUE THREAD

**Issue by jtagle2** [IIC2233-2016-1/syllabus#462]
Al momento de decorar, me tira una especie de advertencia (creo que no es una excepción, porque no me tira a ninguna línea específica). Me dice:
QPixmap::scaled: Pixmap is a null pixmap
Saben que puede ser? Estoy seguro que el path entregado es correcto y la foto existe. De hecho, puedo ver que la entidad está decorada, porque veo un cuadradito en la esquina superior izquierda, pero no se ve la imagen. Y cuando deja de estar decorada, el cuadradito desaparece.

**Comment by otro-felipe** [comment]
Probablemente estés escribiendo mal el path. Si no se ve la imagen es porque no la encuentra.

**Comment by jtagle2** [comment]
Efectivamente era eso. Tenía otra extensión la imagen, no me había dado cuenta. Gracias!
