### ISSUE TITLE
Un par de días más de plazo para la Tarea 4 ? Pls ?

### ISSUE THREAD

**Issue by Nebula2028** [IIC2233-2016-1/syllabus#463]
Se que esto no corresponde mucho acá, pero como en pedir no hay engaño, prefiero ponerlo para recibir (el ojala masivo) apoyo del resto del curso.

Sería posible que dieran un poco más de plazo para entregar la T04 ? Justificando que con el midterm hemos estado más ocupados estudiando para la prueba en estos últimos días.

Hasta el jueves o viernes no más, creo que significaría una gran diferencia para muchos.

Saludos y repito, no se pierde nada con preguntar T_T

**Comment by JoseDaroch** [comment]
Lo apoyo, considerando que ademas tenemos el midterm un día antes de la entrega (aparte del resto de cosas que pueda tener cada uno), creo que a muchos se nos complica bastante terminar la tarea relativamente "bien" :(

**Comment by Hernan4444** [comment]
También creo que dar un poco mas de tiempo seria bien significativo para muchos

**Comment by IsaacConDosA** [comment]
Tienen mi completo apoyo

**Comment by rmant** [comment]
Más allá del midterm, encuentro que hay ciertos puntos en los que fueron poco claros del enunciado y fueron aclarados hace poco. Además surgió el problema que algunos tenían con la gui, y esperar a la versión dos también retrasó el trabajo. Entiendo que en la tarea pasada ya se dió más plazo y no debe ser una práctica que se haga recurrente, pero encuentro que para que nosotros cumplamos con las dos semanas de plazo, debemos contar con claridad sobre lo que debemos hacer desde el día uno.

**Comment by Nebula2028** [comment]
igual mi objetivo no era bajo ningún caso alegar sobre problemas que puedan haber surgido con respecto a enunciado/librerias de apoyo. Eso siempre puede suceder, e igual tuvimos dos semanas... pero con el midterm (y otras cosas) se hizo difícil. Apelemos a la benevolencia y piedad, no a "reclamar un justo derecho".

 Al menos hasta el jueves 23:59 ya serían 24 hrs más que serían una gran diferencia para mi y se agradecería caleta. Con respecto a las tareas anteriores, esta quizá no está tan difícil, pero si bastante más larga. Piedad por favor !

**Comment by isipalma** [comment]
Yo apoyo la iniciativa ya que ademas del midterm tambien esta la actividad del jueves y como se dijo en otro comentario tambien hay que sumarle todas las actividades extras de cada uno, entonces la verdad no ha habido el debido tiempo para trabajar en la tarea. Y ademas como la programaton es mañana, si uno esta trabajando en la tarea y en la programaton aprende a hacer algo nuevo para la tarea estara muy encima para alcanzar a implementarlo bien, y no creo que sea bueno implementar cosas nuevas de forma tan apresurada

**Comment by joaquincastillo** [comment]
Me sumo a la solicitud!

**Comment by bvfernandez** [comment]
Me sumoooo! Porfavoooor!! Para así poder entregar algo "aceptable"

**Comment by Nebula2028** [comment]
importante lo que dice @isipalma ya que la idea es que la programatón sea provechosa para todos... y claramente el mismo día de la entrega será muy poco provechosa.

Aprovecho de mencionar que para la programatón pasada, fui al domo y estuve ahi como 4 horas programando solo (forever alone) y no interactué con ningún ayudante. No se si yo soy muy autista, tuve mala cuea, o la idea es "perseguir/hinchar" a los ayudantes para que te vengan a "ayudar", pero la verdad no me fue muy útil. Fue lo mismo que ir a programar solo a la biblioteca solo que con más ruido  (también escuche ese día algo de unas pizzas, que tampoco nunca vi xD).

Algo similar me paso el día de la ayudantía que fue no presencial y al final fue presencial en la sala del DCC. Fui el día y hora correspondiente a la sala alvaro campos y fue denuevo lo mismo (programar solo sin interactuar nada con nadie). Despues de varios dias supe que habian decidido cambiar la sala de esa ayudantía a otra del final del pasillo (imposible saberlo, no habia niun cartel ni nada). Nuevamente no se si soy yo el pollo o que xD

**Comment by IsaacConDosA** [comment]
Personalmente, me sirvió mucho la programatón pasada, le pregunté a algunos ayudantes :smile: 
Por lo que creo que es una instancia muy necesaria. La idea sería consultar todo el día miércoles para tener tiempo y programarlo decentemente. Si se entrega el mismo miércoles, se formaría una ansiedad dentro de los domos durante la programatón.

**Comment by fgvenegas** [comment]
La idea es que en la programaton vayan y le pregunten a los ayudantes las dudas que tienen, no es que ellos vayan puesto por puesto ayudando, ustesdes tienen que acercarse, siempre es bueno sentarte en una mesa con gente que caches que estan en las mismas y trabajar con ellos y si tienes dudas ir donde estan los ayudantes y la solucionas altiro. Los mismo ayudantes estan preguntandole a ayudantes de otros ramos de sus cosas  jaja. Y por lo de la ayudantia disculpas por no avisar pero la Alvaro Campos estaba super llena y tuvimos que improvisar :( habiamos dejado a alguien que redirigiera a las personas pero al parecer no funciono xd. Disculpas de nuevo por eso. Vayan a la programaton ! es una buena instancia para compartir con sus compañero y ayudantes ;)

**Comment by tamycova** [comment]
@Nebula2028 es valida tu pregunta! se esta evaluando tu propuesta pero no asuman que pasará (de hecho es probable que no).
Respecto a los otros argumentos planteados:
1. El programa del curso fue entregado al inicio, tener o no tener el midterm (o actividad el jueves...) no debe afectar en su planificación para ejecutar la tarea. 
2. Respecto a puntos pocos claros en el enunciado, no ha habido una diferencia significativa en relación a las otras tareas (de hecho mucha de las aclaraciones han sido acerca de preguntas que estaban a su criterio, o hints de cosas que se espera que se les ocurra a uds). 
3. Respecto a las actividades extras de cada uno, esto definitivamente no es un problema que los organizadores de este curso deban considerar al planificar el ramo. Se espera que si deciden tomar un curso puedan dedicarle las horas necesarias. 
4. Respecto a la programatón, esta es una actividad EXTERNA. La invitación fue extendida por parte del capítulo, los mismos ayudantes vamos a ir probablemente a trabajar en nuestros proyectos de otros ramos lo que no impide que colaboremos si nos piden ayuda, pero definitivamente esta actividad no tiene ninguna implicancia en la organización del curso. @Nebula2028 nadie te va a ir a ayudar si no lo pides! yo hablé con varios alumnos de este ramo en la última programatón, pero también trabajé en mis cosas.

**Comment by Nebula2028** [comment]
Estoy de acuerdo con los puntos 1 2 y 3. Por eso partí diciendo que solo apelo a la piedad del cuerpo docente.

respecto al punto 4, quizás es error mio y tengo que ser más preguntón. Tampoco esperaba que me viniera alguien del cielo a sentarse al lado y ayudarme, pero a los pocos ayudantes que identifiqué ese día todos se veían bien ocupados y yo tampoco tenia muchas dudas concretas que hacer. A veces más que una duda especifica y concreta uno esperaría poder recibir cierto feedback de lo que ha hecho hasta el momento (modelación y forma de hacer las cosas) o simplemente preguntar por hints o consejos de como abordar el problema. 
Siento que pasa que a veces los ayudantes por no querer "ayudar de más" (entregarte info que ayuda demasiado a hacer la tarea) al final se limitan a sólo contestar dudas especificas y dar algunas pistas esperando que a uno se le ocurra solo el camino (cosa que muchas veces no pasa nunca, o demora muchas horas/días en ocurrir). Quizá por esto hay gente que recurre a gente externa (que no sean ayudantes, o a veces ni siquiera de la universidad) para recibir ayuda más robusta. Yo no creo tener a nadie por fuera que me pueda dar ese tipo de ayuda :( (pq no estoy considerando la opción ilegal de pagarle a alguien para que me haga una tarea completa por ej)

En fin, doy mi opinión no con ánimo de criticar sino solo de dar feedback como un alumno que le está costando caleta y que piensa que quizá se le podría sacar más el jugo a estas instancias extras de ayuda (como por ejemplo la programatón de mañana).
Saludos!

**Comment by gebalassa** [comment]
**+10000000**

Encuentro feo poner **Tarea + Midterm + Actividad** para una misma semana, ni siquiera en los ramos matemáticos hacen eso :laughing: . La Programatón va a estar _heavy_ ajajajajajajajaj gg.

P.D.: Se ruega mayor precisión con enunciados futuros plz :confused: 

```
        @@@@@@           @@@@@@
      @@@@@@@@@@       @@@@@@@@@@
    @@@@@@@@@@@@@@   @@@@@@@@@@@@@@
  @@@@@@@@@@@@@@@@@ @@@@@@@@@@@@@@@@@
 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
   @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
      @@@@@@@@@@@@@@@@@@@@@@@@@@@
        @@@@@@@@@@@@@@@@@@@@@@@
          @@@@@@@@@@@@@@@@@@@
            @@@@@@@@@@@@@@@
              @@@@@@@@@@@
                @@@@@@@
                  @@@
                   @


```

**Comment by iavasquez1** [comment]
Apoyo la solicitud del cambio de fecha de entrega de la tarea 4

**Comment by flobarrios** [comment]
Estimados, se subió un anuncio al Siding. Quedó para el viernes a las 23:59. Saludos y aprovechen estos días extra!!

**Comment by Hernan4444** [comment]
@iavasquez1 ya dieron el anuncio y lo cambiaron para el viernes
