### ISSUE TITLE
[Github] Commits

### ISSUE THREAD

**Issue by santiagocruzb** [IIC2233-2016-1/syllabus#464]
Hola!
Como puedo fijar un commit antiguo para trabajar de ahora en adelante en ese? (los commits hechos entre el actual y ese antiguo me dan lo mismo)
Saludos!

@jecastro1

**Comment by flobarrios** [comment]
Hola! [acá](http://stackoverflow.com/questions/4114095/revert-git-repo-to-a-previous-commit) resuelven lo que estas preguntando. Saludos!
