### ISSUE TITLE
PyQt4 - Qt designer

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233-2016-1/syllabus#465]
Como el titulo indica, podemos tener instalado Qt designer para apoyarnos durante el trabajo con la interfaz grafica?? o debemos usar solo codigos en python para implementar todo?

**Comment by aaossa** [comment]
Deben tener QtDesigner instalado. Pero para la AC de esta semana solamente tienen que usar código, no pueden usar Designer.

**Comment by Hernan4444** [comment]
oka, muchas gracias :+1:
