### ISSUE TITLE
decoraciones

### ISSUE THREAD

**Issue by JoseDaroch** [IIC2233-2016-1/syllabus#466]
Hola, tengo una duda respecto a las decoraciones del mapa, si creo una clase que herede de entity y la hago aparecer en el mapa (sangre por ejemplo) como hago para que mis zombies y humanos pasen por arriba y no la sangre por arriba de ellos?
Gracias!

**Comment by otro-felipe** [comment]
Con los métodos en el enunciado esto no se puede ahcer, por lo que mientras salga da igual si pasan por arriba. Ahora si quieres realmente hacerlo puedes usar el método `entity.raise_()`.
