### ISSUE TITLE
ImportError: cannot import name 'QtGui'

### ISSUE THREAD

**Issue by Meaylwin** [IIC2233-2016-1/syllabus#467]
Intentanto ejecutar el material de clases me aparece este error:
`ImportError: cannot import name 'QtGui'`
Claramente tengo instalado PyQt4 porque lo he utilizado para las tareas, además, he intentado desisntalar y volver a instalar diferentes versiones de PyQt4 que encontre en 
https://www.riverbankcomputing.com/software/pyqt/download
Mi OS es Windows 64-bits
Agradezco cualquier tipo de ayuda

**Comment by aaossa** [comment]
¿Te funcionan, por separado, los siguientes códigos?

``` python
import PyQt4
```

``` python
from PyQt4 import QtGui
```

**Comment by Meaylwin** [comment]
El primero funciona, el segundo no :/

**Comment by aaossa** [comment]
Te pasa tanto por consola como en el editor de texto que usas? Solo has instalado las versiones de 64-bits cierto?

**Comment by Meaylwin** [comment]
En consola no tengo error.
En mis intentos desesperados de arreglar el problema instale uno de 32-bits, pero al darme cuenta lo desistale y volvi a instalar el de 64, actualmente puedo correr la tarea 4, pero `from PyQt4 import QtGui` sigue dando problemas en consola.

**Comment by aaossa** [comment]
Prueba a descargar de [esta página](http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyqt4) la versión de PyQt4 que te sirva. En tu caso, debería ser **`PyQt4-4.11.4-cp34-none-win_amd64.whl`**. Una vez que la descargas ponla en cualquier carpeta, abres la consola en la misma y usas `pip install PyQt4-4.11.4-cp34-none-win_amd64.whl` (si le pusiste otro nombre deberás cambiarlo también, la forma correcta es `pip install <path_al_whl>`.

Después de esto cierra todas las sesiones de consola y de tus editores de texto, para trabajar con la "nueva versión" (supongo que ya lo hacías, pero por si acaso)

**Comment by Meaylwin** [comment]
Después de mucho intentar:

```
C:\>C:\Python34\scripts\pip install Python34\PyQt4-4.11.4-cp34-none-win_amd64.whl
Processing c:\python34\pyqt4-4.11.4-cp34-none-win_amd64.whl
Installing collected packages: PyQt4
  Found existing installation: PyQt4 4.11.3
    Uninstalling PyQt4-4.11.3:
      Successfully uninstalled PyQt4-4.11.3
Successfully installed PyQt4-4.11.4
```

Cierro la consola y los editores, intento correr de nuevo `from PyQt4 import QtGui
` y continua diciendo `ImportError: cannot import name 'QtGui'
`

**Comment by Meaylwin** [comment]
Sigo sin poder solucionar el problema, ¿podría juntarme con alguien para encontrar una solución?

**Comment by aaossa** [comment]
Si puedes usar `import PyQt4` puedes usar algo de `PyQt4.QtGui`? Si no puedes, antes de la clase lo puedes ver con un ayudante. Si puedes, deberías poder realizar la actividad así y después de la clase le buscamos solución.

**Comment by Meaylwin** [comment]
Si uso import PyQt4.QtGui me aparece el siguiente error:  ImportError: No module name 'PyQt4.QtGui' ; 'PyQt4'  is not a package.

**Comment by Meaylwin** [comment]
Podría juntarme con un ayudante antes de la clase? :(

**Comment by aaossa** [comment]
Creo que te falta un archivo en la carpeta de PyQt. ¿Puedes importar de la siguiente forma?

``` python
from PyQt4.QtGui import QWidget, QLabel, QPixmap
```

Si puedes usar la interfaz de la tarea eso debería funcionarte.

**Comment by Meaylwin** [comment]
`ImportError: No module named 'PyQt4.QtGui'; 'PyQt4' is not a package`

**Comment by aaossa** [comment]
Puedes ver si tienes `PyQt4` en `site-packages`? La ruta debería ser algo como: 

```
C:\Python34\Lib\site-packages\PyQt4
```

**Comment by Meaylwin** [comment]
Si esta

**Comment by aaossa** [comment]
Tienes `QtGui.pyd` en la carpeta?

**Comment by Meaylwin** [comment]
Si

**Comment by fgvenegas** [comment]
que seccion eres?

**Comment by Meaylwin** [comment]
1
