### ISSUE TITLE
Acerca de susbastasfin.txt

### ISSUE THREAD

**Issue by jfcumsille** [IIC2233-2016-1/syllabus#47]
Tengo una duda sobre las subastas en subastasfin.txt. Se supone que estas ya están actualizadas en los otros archivos de texto, o tenemos que actualizarlas apenas se ingrese la hora? Lo pregunto porque en la primera subasta del archivo sale que "naraya" compro el producto "31134115378" que vendia "bnavarrete11", pero al buscar en usuarios.txt este producto no lo tiene "naraya" ni "bnavarrete11", sino que "acortes11" quien ni siquiera participo de la subasta jaja por lo que si deben ser actualizadas tendria que quitarle el producto a "acortes11" y darselo a "naraya" mientras que el dinero va para "bnavarrete11" o lo dejo tal cual y solo actualizo los datos de las subastas que se cierran de subastasact.txt ?

Espero que se entienda jaja
Muchas gracias.

**Comment by bamavrakis** [comment]
Hola!!
El archivo de subastas finalizadas ya están actualizadas y no deberías hacer nada con su información (ya que ya están finalizadas) (si te hace sentir mejor, imagina que naraya le regaló su producto a acortes11 ya que son buenos amigos :smiley: ). El archivo de subastas activas debes trabajarlo de la manera que tu dices, ya que deberás finalizar subastas en la que la fecha de término es menor a la fecha que ingresar al entrar al sistema (finalizar una subasta implica todo lo que comentaste). 

Saludos!

**Comment by arturodelreal** [comment]
En el archivo de las subastas activas hay productos que aparecen en mas de una subasta, que se supone que debemos hacer con eso?
