### ISSUE TITLE
¿Responden preguntas durante las activdades?

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#470]
Es que en este instante estamos en la activadad 11.
Y me preguntaba si se respondian dudas durante la actividad por el sylabus.

**Comment by aaossa** [comment]
Hola, la respuesta es "No". Los ayudantes están en la sala precisamente para responder. Además, es mucho mejor para todos si nos dicen la duda, vemos código y comentamos presencialmente que vía issues.

**Comment by perojas3** [comment]
Gracias.
