### ISSUE TITLE
Interfaz Tarea 4

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233-2016-1/syllabus#471]
Como forma de estudiar para la actividad de hoy había desarrollado una mini ventana que solicitara los input de la tarea 4 (tasas de llegada, números iniciales, etc.), 

¿puedo mantenerla al momento de entregar la tarea?

Creo que se ve mas fácil para entregar los datos que usar la consola con los tradicionales input.

**Comment by bamavrakis** [comment]
Hola!, Si, no hay ningún problema con eso :D.
Saludos!

**Comment by Hernan4444** [comment]
Muchas Gracias :+1:  :D
