### ISSUE TITLE
Problema interfaz tarea 4 

### ISSUE THREAD

**Issue by camiolguin** [IIC2233-2016-1/syllabus#472]
Hola! Para usar el gui.run() uso una funcion creada en mi clase Simulación. El problema es que el programa se ejecuta y muy pocas veces termina simulación porque la interfaz se queda pegada. Usando otra funcion Simulación (no una clase, y que no tiene los atributos que guardo para las estadisticas) el programa si me corre correctamente y me muestra la interfaz.

**Comment by Nebula2028** [comment]
me quiero colgar para preguntar algo en la misma linea. Es necesario que se haga una clase Simulación ? Hasta el momento yo solo hago gui.run(tick, 50) en donde cada iteración de la función tick sería como una "unidad de tiempo" de la simulación (como venia en el demo.py).

Básicamente en cada ejecución de tick se hace una variable tiempo += 1 y cuando llega al tpomax termina. Esto está bien o se espera que se haga una clase aparte para la simulación como en el material de clases de simulación ??

gracias

**Comment by otro-felipe** [comment]
Lo que pasa es que el método que pones en gui run se repite por defecto, por lo que no es necesario que vaya un while (de hecho el método se está repitiendo en exceso). Debes cambiar el while por una condición solamente.

**Comment by camiolguin** [comment]
Ahi si! graciaasss
