### ISSUE TITLE
Problema Testing

### ISSUE THREAD

**Issue by IsaacConDosA** [IIC2233-2016-1/syllabus#476]
Hola, estoy haciendo el testeo del programa, pero siempre me aparece el siguiente error:

.QWidget: Must construct a QApplication before a QPaintDevice

y no se ejecuta ningún test. 
¿Qué puede ser? 
Saludos

**Comment by camiolguin** [comment]
Me aparece el mismo error, me sumo a la pregunta

**Comment by ManuelSIlvaCav** [comment]
Me paso lo mismo, y el problema era que llamaba dos veces a gui.init() en el testing y en el modulo que estaba testeando (Y)

**Comment by isarovic** [comment]
¿Cómo se hace un testing en nuestro programa si depende de otro (gui)? No estoy entendiendo mucho donde poner el gui.run() o cómo hacer que se haga un test en particular, o me tira QWidget: Must construct a QApplication before a QPaintDevice o el test dice que no hay test. ¿Algun sabio con tiempo que me pueda explicar un poco cómo hacer el testing?

**Comment by otro-felipe** [comment]
debes importar la gui en tu archivo para testear y luego, al iniciar el set de tets debes inicializarla, pero no correrla (llamar `gui.init` y no `gui.run`). Luego de eso puedes instanciar los objetos sin necesidad de mostrarlos en la gui (no es necesario que se vea la gui para el testeo, ya que la idea es que solo testees la lógica de tu programa).

**Comment by IsaacConDosA** [comment]
@MainScientist haciendo eso me tira el error que puse :cry:

**Comment by FernandoPieressa** [comment]
@MainScientist Al llamar gui.init solo me funciona 1 funcion del test, si pongo mas de 1 me vuelve a tirar el error, aunque por separado poniendo solo 1 test funcione cualquiera

**Comment by MortizDX** [comment]
Tratando de correr el test desde la línea de comando me tira el error que ya han mencionado varias veces, y cuando lo trato de correr desde pycharm, me ocurre algo parecido a lo que dice @FernandoPieressa , solo que no tira error a veces pero solo considera un test.

Estoy confuso @_@

**Comment by otro-felipe** [comment]
Lo que tienen que hacer es **no llamar al método al principio de la clase** sino llamarlo en en setUp del testing.

``` python
def setUp(self):
    gui.init()
```

**Comment by FernandoPieressa** [comment]
Ya lo arregle, sin embargo llamarlo en el SetUp era donde lo tenia y me tiraba error, lo solucione poniendo el gui.init() afuera de la clase Test al principio del modulo testing

**Comment by MortizDX** [comment]
Me funciona con lo que dice @FernandoPieressa, había estado antes poniéndolo como lo dices @MainScientist , pero nada :s

**Comment by IsaacConDosA** [comment]
@MainScientist si lo hago como dices tú me tira el error. Lo solucioné haciendo gui.init() antes de definir la clase del testeo, en el main. No sé si estará bien

**Comment by otro-felipe** [comment]
Que raro, deberia funcionarles tambien con el setUp. Si les funciona de esa forma entonces no deberia haber problema, de todas formas me intriga saber por qué no funciona en el setUp.
