### ISSUE TITLE
Problema con importar un clase desde otra clas que a su vez importa a la primera

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#477]
Tengo este problema.
Tengo la clase zombie y humanos, y cada uno tiene su comportamiento detectando la clase de los seres cercanos usando `isinstance`.
Pero para conseguir eso deben importarse las clases mutuamente, y python no lo permite ¿Que puedo hacer?

**Comment by ivaniadg** [comment]
Hola @perojas3 

El intérprete de Python va a ejecutar el módulo 1 pero necesita importar el módulo 2, que a su vez necesita importar el 1.  Esto claramente te entrega un error.

Para solucionarlo debes poner las dos clases en el mismo módulo. Esto además tiene sentido porque un módulo debe poder tener acceso todo lo que necesita para ejecutarse de forma "independiente" y claramente las clases `Zombie` y `Humanos` se necesitan la una a la otra.
