### ISSUE TITLE
Problema extraño con Interfaz gráfica

### ISSUE THREAD

**Issue by fnquinteros** [IIC2233-2016-1/syllabus#478]
Tengo un problema rarísimo que no se si afectará mi nota. Resulta que al crear humanos al principio de la simulación anda todo perfecto, pero a medida que ingresan a la simulación según la tasa de llegada, algunos aparecen como ventanas nuevas sobre la ventana de la simulación, las ventanas incluso se mueven solas a lo largo de la pantalla. :expressionless: No se que onda! Aqui dejo una imagen del problema:

![asd](https://cloud.githubusercontent.com/assets/10425834/15445355/2fd19c1a-1ed3-11e6-9e95-92c146956594.png)

**EDIT @aaossa:** Puedes subir directamente la foto a Github. No hace falta usar otras cosas :+1:

**Comment by Zepk** [comment]
A mi me paso lo mismo, para arreglarlo me asegure de hacer: 
`self.gui.add_entity(humano)`
 justo en la linea de abajo de la linea en la que cree al humano, y con eso se me arreglo, espero te ayude
