### ISSUE TITLE
Duda unittest

### ISSUE THREAD

**Issue by jpdattas** [IIC2233-2016-1/syllabus#479]
Hola, me surgió una duda. Cual es la gracia de unittest si puedo verificar las mismas cosas y hacer cosas más personalizadas con una clase propia? Me surgió la duda porque para la tarea el unittest me tiraba error e hice un archivo donde probaba cosas donde no me daba el error (aunque tenía lo mismo).
La duda es en general más que sobre la tarea

**Comment by rodolfopalma** [comment]
Tienes razón en que uno podría hacer lo mismo que `unittest` con clases y métodos propios. De hecho, podrías emular casi toda la librería estándar de Python con clases y métodos propios que tu escribas! Sin embargo, estarías reinventando la rueda, y a no ser que sea con fines pedagógicos esto una muy mala idea. 

Al usar los módulos y librerías estándar (no solo de Python, de cualquier otro lenguaje en general) te aseguras de usar código que ha sido extensamente probado, debuggeado y optimizado. Con tus propias implementaciones, no.

**Comment by jpdattas** [comment]
ok. pero según entiendo unittest sería como hacer distintos if condicion: print(error).
Mi pregunta iva mas a si es solo eso (sea optimizado, mas corto, etc) o si hay algo más especial que hace que no este viendo. De todas maneras gracias por la respuesta
