### ISSUE TITLE
Actualizacion de datos

### ISSUE THREAD

**Issue by santiagocruzb** [IIC2233-2016-1/syllabus#48]
Hola!
Con tal que la próxima vez que se corra el programa estén los datos actualizados, importa la forma cómo se guarden?

**Comment by gafigueroa** [comment]
Si, debes guardarlo de tal manera en que puedas leerlo después

**Comment by santiagocruzb** [comment]
Obvio que tengo que leerlos después, pero puedo guardarlos de alguna forma que no sea necesariamente en el mismo .txt que se pasaron?

**Comment by Geeermy** [comment]
Hola! 
La idea es que vayas reescribiendo la información en los .txt que te pasamos inicialmente. Pero solo para saber, ¿para qué querrías hacer más archivos?

**Comment by santiagocruzb** [comment]
@Geeermy se pueden reescribir (desde cero) los txt que pasan por archivos que sean mas ""fáciles"" de leer y escribir que los actuales JSON. El numero de archivos seria constante.

**Comment by Geeermy** [comment]
Ahhh no, lo lamento :( la idea es que tu programa sea capaz de leer los archivos y guardarlos en el mismo formato en que te los entregamos. Por eso mismo los dejamos así en un comienzo. 
Para las próximas tareas les entregaremos más herramientas para que no sea tan tedioso el trabajo con archivos :) pero ahora queremos evaluar su manejo en este tipo de cosas.
Saludos y ánimo!
