### ISSUE TITLE
Duda modelamiento

### ISSUE THREAD

**Issue by jpdattas** [IIC2233-2016-1/syllabus#481]
Hola. En la ayudantía pasada dijeron que no estaba bien hacer referencias circulares. Pero no entiendo como modelar sin esto. Hasta ahora, siempre las he usado y no me imagino como hacer interacciones sin estas

**Comment by tamycova** [comment]
hola @jpdattas !! no entiendo a qué te refieres, podrías quizás explicarlo mejor o darme un ejemplo?

**Comment by Nebula2028** [comment]
me imagino que se refiere a importar modulos o clases de forma bidireccional. por ej:
Sistema.py
import Unidades

Unidades.py
import Sistema

**Comment by tamycova** [comment]
@Nebula2028 peroo según yo python se queja al hacer eso (osea tira error), se debe estar refiriendo a algo mas!

**Comment by ivaniadg** [comment]
Hola @jpdattas 

En el caso típico de modelos circulares tenemos una clase que _organiza/es dueña de_ los otros objetos, y estos objetos necesitan conocer el estado de la organización para poder realizar acciones. 

La solución típica (y errónea) es la siguiente

``` python
class Organizador:
    def __init__(self, num_elementos):
        self.listo = True
        self.elementos = [Elemento(self) for _ in range(num_elementos)]

class Elemento:
    def __init__(self, organizador):
        self.organizador = organizador

    def realizar_accion(self):
        if self.organizador.listo:
            print("Me puedo mover!!! :D")
        else:
            print("Mi jefe dice que no me puedo mover :'(")
```

La modelación es circular porque un `Elemento` puede acceder a **todos** los atributos de `Organizador` y modificarlos si quisiera. En la vida real esta situación casi no ocurre, por ejemplo:
- Los alumnos pueden hacer preguntas en el syllabus de github, pero no pueden modificar las actividades
- Los clientes pueden saber cuántos productos hay en vitrina de un supermercado, pero no conocen sus facturas, ni su sistema de logística

Por esto es que esta modelación **no se aproxima a la realidad**. Distintos lenguajes de programación ofrecen herramientas para lograr una modelación más precisa (Java tiene las interfaces, por ejemplo). Para modelar esto en Python se usa el hecho de que las funciones son objetos, que podemos decorar funciones y pasarlas como parámetros. El siguiente código es una forma de arreglar el código de arriba.

``` python
class Organizador:
    def __init__(self, num_elementos):
        self.listo = True
        self.elementos = [Elemento(self.esta_listo()) for _ in range(num_elementos)]

    def esta_listo(self):
        def _esta_listo():
            return self.listo
        return _esta_listo

class Elemento:
    def __init__(self, puedo_realizar_accion):
        self.puedo_realizar_accion = puedo_realizar_accion

    def realizar_accion(self):
        if self.puedo_realizar_accion():
            print("Me puedo mover!!! :D")
        else:
            print("Mi jefe dice que no me puedo mover :'(")
```

Aquí usamos los decoradores para crear la función `_estoy_listo` que retorna el valor del atributo `listo` de `Organizador`. Luego `Elemento` usa esta función misma función guardada en la variable `puedo_realizar_accion` para _"hacerle una pregunta"_ a `Organizador`.

**Comment by jpdattas** [comment]
Excelente la explicación! Muchas gracias, me quedó muy claro!

**Comment by MortizDX** [comment]
Una pregunta sobre el ejemplo dado, ¿sería válido que en vez de utilizar un decorador, que el mismo `Organizador` le entregará su atributo `listo` al `Elemento` cada vez que que quiera utilizar `realizar_accion`? ¿o eso no es correcto en cuanto a modelación?

Por ejemplo:

``` python
class Organizador:
    def __init__(self, num_elementos):
        self.listo = True
        self.elementos = [Elemento(self.esta_listo()) for _ in range(num_elementos)]

    def esta_listo(self):
        def _esta_listo():
            return self.listo
        return _esta_listo

    def correr(self):
        for i in self.elementos:
            i.realizar_accion(self.listo)
            self.listo = not self.listo


class Elemento:
    def __init__(self, puedo_realizar_accion):
        self.puedo_realizar_accion = puedo_realizar_accion

    def realizar_accion(self, puedo):
        if puedo:
            print("Me puedo mover!!! :D")
        else:
            print("Mi jefe dice que no me puedo mover :'(")

a = Organizador(5)
a.correr() 
```

**Comment by ivaniadg** [comment]
Hola @MortizDX, 
Eso es correcto, no hay problemas de modelación, pero no logras tener el mismo comportamiento. Piensa en la actividad de [threads](https://github.com/IIC2233-2016-1/syllabus/blob/master/Actividades/AC10/Actividad%2010.pdf). La acción que realizaba cada soldado dependía del estado del equipo contrario y de las torres, pero su equipo no decidía cuando debía atacar, solo le decía si las condiciones para atacar se cumplían.

**Comment by MortizDX** [comment]
Mm, cierto. Y entregarle directamente su atributo al momento de ser creado dificultaría en algo la modelación? Es que me cuesta entender la necesidad de entregar ese atributo mediante un constructor :/

**Comment by ivaniadg** [comment]
El problema es que el parámetro que quieres entregar puede ser inmutable y solo tendrás el valor que tenía la variable cuando la pasaste como parámetro. Me explico:

Si el tipo del parámetro que entregamos es mutable (`bytearray`, `list`, `dict`, `set`, user defined), entonces el `Organizador` lo puede modificar y el `Elemento` tendrá siempre una versión actualizada.

``` python
class Organizador:
    def __init__(self, num_elementos):
        self.listo = [True]
        self.elementos = [Elemento(self.listo) for _ in range(num_elementos)]

class Elemento:
    def __init__(self, puedo_realizar_accion):
        self.puedo_realizar_accion = puedo_realizar_accion

    def realizar_accion(self):
        if self.puedo_realizar_accion[0]:
            print("Me puedo mover!!! :D")
        else:
            print("Mi jefe dice que no me puedo mover :'(")

if __name__ == '__main__':
    org = Organizador(5)
    for i, e in enumerate(org.elementos):
        if i % 2 == 0:
            org.listo[0] = not org.listo[0]
        e.realizar_accion()
        print(org.listo)
```

OUTPUT

```
Mi jefe dice que no me puedo mover :'(
[False]
Mi jefe dice que no me puedo mover :'(
[False]
Me puedo mover!!! :D
[True]
Me puedo mover!!! :D
[True]
Mi jefe dice que no me puedo mover :'(
[False]

```

Esto tiene el comportamiento que esperamos, pero es extraño el uso de la variable listo. Ten en consideración que esto funciona porque **modifiqué** la variable `org.listo` y no creé una nueva lista para la variable como en este ejemplo:

``` python
class Organizador:
    def __init__(self, num_elementos):
        self.listo = [True]
        self.elementos = [Elemento(self.listo) for _ in range(num_elementos)]

class Elemento:
    def __init__(self, puedo_realizar_accion):
        self.puedo_realizar_accion = puedo_realizar_accion

    def realizar_accion(self):
        if self.puedo_realizar_accion[0]:
            print("Me puedo mover!!! :D")
        else:
            print("Mi jefe dice que no me puedo mover :'(")

if __name__ == '__main__':
    org = Organizador(5)
    for i, e in enumerate(org.elementos):
        if i % 2 == 0:
            org.listo = [not org.listo[0]]
        e.realizar_accion()
        print(org.listo)
```

OUTPUT

```
Me puedo mover!!! :D
[False]
Me puedo mover!!! :D
[False]
Me puedo mover!!! :D
[True]
Me puedo mover!!! :D
[True]
Me puedo mover!!! :D
[False]
```

Ahora, si el tipo es inmutable (`int`, `float`, `str`, `tuple`, `bytes`, ...), la única opción que te queda es usar un decorador para consultar el valor de la variable. Esto ocurre porque una vez que cambias el valor de la variable se crea un nuevo espacio de memoria y por lo tanto una nueva referencia.

``` python
class Organizador:
    def __init__(self, num_elementos):
        self.listo = True
        self.elementos = [Elemento(self.listo) for _ in range(num_elementos)]

class Elemento:
    def __init__(self, puedo_realizar_accion):
        self.puedo_realizar_accion = puedo_realizar_accion

    def realizar_accion(self):
        if self.puedo_realizar_accion:
            print("Me puedo mover!!! :D")
        else:
            print("Mi jefe dice que no me puedo mover :'(")

if __name__ == '__main__':
    org = Organizador(5)
    for i, e in enumerate(org.elementos):
        if i % 2 == 0:
            org.listo = not org.listo
        e.realizar_accion()
        print(org.listo)
```

OUTPUT

```
Me puedo mover!!! :D
False
Me puedo mover!!! :D
False
Me puedo mover!!! :D
True
Me puedo mover!!! :D
True
Me puedo mover!!! :D
False
```

Por todo esto, usar decoradores es una forma de asegurarse de obtener el comportamiento esperado de una forma clara.

**Comment by MortizDX** [comment]
Oh, ya veo, eso explica muchísimo o: Y me da una mayor apreciación por los decoradores XDD ¡Muchas gracias por explicación! :D

**Comment by jpdattas** [comment]
Y si el organizador es quien quiere que una instancia evento "realice la acción"  según cierta condición, está bien que acceda directamente al método haciendo por ejemplo "self.elementos[5].realizar_accion"? o debiese llamar (o preguntar) al elemento para que la realice? claramente lo primero es más rápido por lo que es tentador hacerlo de esa forma pero no se si sea lo correcto.

**Comment by ivaniadg** [comment]
Depende. En este caso los `Elemento`s componen a `Organizador` así que no tiene sentido hacer una interfaz nueva para su comunicación. Si tuvieses dos clases que se comunican entre sí entonces tiene sentido. Por ejemplo:

``` python
class Alumno:
    def __init__(self, profesor, responde):
        self.companeros = None
        self.profesor = profesor
        self.puede_responder = responde

    def conocer_companeros(self, companeros):
        self.companeros = companeros

    def resolver_duda(self):
        for c in self.companeros:
            if c():
                print("Mi compañero está libre :D y ha resuelto mi duda")
                return
        if self.profesor():
            print("El profe ha respondido :D")
        else:
            print("Todavía tengo dudas")

    def responder(self):
        def _responder():
            return self.puede_responder
        return _responder


class Profesor:
    def __init__(self, responde):
        self.puede_responder = responde

    def responder(self):
        def _responder():
            return self.puede_responder
        return _responder


if __name__ == "__main__":
    profesor = Profesor(True)
    alumnos = [Alumno(profesor.responder(), False),
               Alumno(profesor.responder(), False),
               Alumno(profesor.responder(), True)]

    for a in alumnos:
        companeros = alumnos.copy()
        companeros.remove(a)
        companeros = [c.responder() for c in companeros]
        a.conocer_companeros(companeros)

    for i, a in enumerate(alumnos):
        print('Alumno ' + str(i))
        a.resolver_duda()

```

Aquí los `Alumno`s solo se hacen consultas entre sí, por eso tiene sentido. El usar o no este enfoque de interfaz depende de lo que se esté modelando. En este caso tiene sentido, en el del `Organizador` tiene más sentido hacer lo primero.

**Comment by jpdattas** [comment]
Ok, muchas gracias!!
