### ISSUE TITLE
Algun consejo para la tarea 5

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#482]
Estoy haciendo la tarea 5 y desearía que me dieran un consejo respecto a la forma de enfrentar los problemas. Digo, tengo entendido que las interfaces gráficas funcionan más o menos distinto. ¿Como debería razonar los problemas con las interfaces gráficas en mente?

**Comment by ivaniadg** [comment]
Hola @perojas3 !
1. No entiendo a qué te refieres con 

> las interfaces graficas funcionan más o menos distinto
1. Para trabajar con interfaces gráficas debes entender bien el concepto de _backend_ y _frontend_. De estos se habló en la ayudantía de hoy. Tienes alguna duda en específico?
