### ISSUE TITLE
¿Librerias permitidas?

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#483]
Normalmente esta habierto donde dice las librerias permitidas de la tarea. Pero esta vez no lo encuentro.
¿Donde se ven las librerias permitidas para esta tarea?
¿Se permite usar PyQt?
En el caso de que no se permita ¿Que ibreria se deveria usar para la interfaz grafica?

**Comment by fgvenegas** [comment]
Si, puedes utilizar PyQt, ese es el framework que utilizamos en el ramo para el desarrollo de interfaces gráficas (también puedes usar QtDesigner que es una herramienta de PyQt que sera evaluada en la próxima actividad). 
Respecto a la issue con las librerías permitidas los @IIC2233-2016-1/tareos deberían crearla pronto

**Comment by negebauer** [comment]
Fue creado el issue #485
