### ISSUE TITLE
Pëqueño error interfaz

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233-2016-1/syllabus#484]
buenas, estaba intentando abrir las imagenes dentro de la interfaz y cada vez que traigo una pelota con la imagen me aparece este error:
`libpng warning: iCCP: known incorrect sRGB profile`

En verdad no afecta en nada el trabajo, pero sigue siendo un error que molesta. Alguna idea??

**Comment by Hernan4444** [comment]
Ya me dieron la solución, hay que convertir las imágenes porque están mal en el formato de colores.
Con esta pagina se puede:
[http://imagen.online-convert.com/es/convertir-a-png](url)

**Comment by flobarrios** [comment]
Hola!! justo estaba en eso. Voy a volver a subir la carpeta assets con el perfil correcto. Saludos!
