### ISSUE TITLE
Disminuir espacio entre botones

### ISSUE THREAD

**Issue by spiza** [IIC2233-2016-1/syllabus#487]
Hola!

Mi duda es muy simple.. Para trabajar (T5) usaré PyQt4, y por un tema netamente de diseño es que quiero que dentro de un Layout (Horizontal o Vertical), la separación de los botones se disminuya, pero la verdad no encuentro nada de eso en internet, y por ende recurro a ustedes.. se puede hacer? así como para saber si lo dejo así nomá

Gracias!

**Comment by spiza** [comment]
Comento información que puede ser útil.. me interesa disminuir tanto el tamaño de los botones (hacerlos lo más chico posible), así como también la distancia entre los botones.

Gracias

**Comment by fgvenegas** [comment]
Tal vez te puede ser útil para eso QtDesigner donde puedes modelar más fácil ciertos elementos de una interfaz como tamaño de botones o ventanas. Esto es precisamente lo que se evaluará el jueves en la actividad y lo que se vio en la ayudantía de hoy.
