### ISSUE TITLE
[T05][Duda PyQt]

### ISSUE THREAD

**Issue by vbarros2** [IIC2233-2016-1/syllabus#489]
Se pueden tener dos archivos .py con diferentes códigos en PyQt y correrlos en la misma ventana.
Es decir podría tener dos archivos como el de la ayudantia de pelotas que rebotan con diferentes ecuaciones y correrlos en una misma ventana??

Estoy tratando de tener una clase pelotas y otra para el mono que se mueve, puedo juntar las imagenes y el mono si lo puedo mover pero las pelotas no empiezan a moverse.... en resumen no se ejecuta la funcion run(self) de mi clase pelotas

Gracias!

**Comment by santiagocruzb** [comment]
Tienes que hacer toda la interfaz gráfica en una sola clase, y usar triggers para avisar de los cambios que quieras desde otras clases (pelotas y monos) hacia la clase de la interfaz.

**Comment by vbarros2** [comment]
Perfecto,

Gracias
