### ISSUE TITLE
[T01][Subastas Finalizadas y Subastas Activas]

### ISSUE THREAD

**Issue by vbarros2** [IIC2233-2016-1/syllabus#49]
No entiendo porque el comprador fmedina gana la subasta por 37422 que es un peso mas de lo que aposto ileiva. Pasa lo mismo en las subastas activas, que el precio actual es un peso mas de de lo que aposto el penultimo postor

```
"fecha_termino": "2016-03-06 09:35:59",
    "id": 27562972793,
    "fecha_inicio": "2015-08-15 19:28:40",
    "comprador": "fmedina",
    "precio": 37422,
    "vendedor": "elopez11",
    "productos": [
      87170832346
    ],
    "historial": [
      [
        "asanhueza1111",
        22790
      ],
      [
        "mcarvajal1111",
        23128
      ],
      [
        "xpatel",
        23521
      ],
      [
        "cmoreno111",
        24163
      ],
      [
        "lruiz11",
        26337
      ],
      [
        "athompson",
        27564
      ],
      [
        "mvidal11",
        31643
      ],
      [
        "jdonoso11",
        33868
      ],
      [
        "sbravo",
        35368
      ],
      [
        "lleiva",
        37421
      ],
      [
        "fmedina",
        44476
```

**Comment by negebauer** [comment]
Sobre porque fmedina gana esa subasta echa una mirada a lo que dijo @bamavrakis en #47

**Comment by bamavrakis** [comment]
Hola!! 
En la sección 5 del enunciado sale súper bien explicada esta parte :D (por si te quedan dudas con mi explicación) , pero como soy amoroso te explicaré de nuevo:

Cuando uno apuesta, está apostando la cantidad máxima que esta dispuesto a pagar (pongamosle x), pero si la apuesta mayor antes de que uno apueste (pongamosle y) es menor que lo que deseas apostar, es decir, x>y, entonces el precio actual de la subasta será un peso mayor a la apuesta mayor anterior, es decir, y+1. Ahora si viene un tercer individuo que desea apostar (llamemosle z) más del precio actual en la subasta (y+1), pero menos de lo máximo que está dispuesto a apostar la segunda persona, es decir, y+1 < z < x, entonces el precio actual será un peso mayor a z, es decir, z+1, y el individuo "x" seguirá liderando la subasta hasta que llegue un cuarto individuo (ehh se me terminó el alfabeto, w?) tal que lo máximo que está dispuesto a apostar sea mayor a x. En este caso el precio actual de la subasta será de x+1 y "w" será el ganador actual de esta, y así hasta que termine la subasta.

Espero haya quedado claro,
Saludos!!

**Comment by vbarros2** [comment]
Perfecto....
Muchas Gracias!

**Comment by bamavrakis** [comment]
La voy a dejar abierta un rato más para que el resto pueda ver mi respuesta más facilmente

**Comment by jfcumsille** [comment]
Me quedo una duda, al finalizar la subasta el precio que se debe pagar por el producto es el que estaba dispuesto a pagar el ganador o el precio actual, es decir, el que el resto de los usuarios pueden ver? Tomando tu ejemplo suponiendo que finaliza la subasta con w como ganador, este deberia pagar w o x+1?

**Comment by Geeermy** [comment]
Hola! Siguiendo el ejemplo de mi compañero, al final el total a pagar sería x+1, ya que es el precio con el que queda la subasta. Si es justo igual al máximo... mala suerte para ellos jajaj.
Saludos! :)

**Comment by agmardones** [comment]
No debería ser w?, si no, uno podría apostar infinita plata sin tener miedo a pagarla al ganar la subasta.

**Comment by bamavrakis** [comment]
Hola!
Si uno apuesta "infinito" y al finalizar la subasta no tiene la cantidad acordada (x+1), se va multado, por lo que no le convendría hacer eso.
Saludos!

**Comment by agmardones** [comment]
Claro, estaba suponiendo que el que apostaba tenía la cantidad pactada. Entiendo que el ganador es quien apuesta el máximo (sin necesariamente tener el dinero que apuesta), entonces, podría apostar mucha plata en una subasta (un monto excesivo para ganarla si o sí) y sólo pagar el precio en el que quedará la subasta después de todas las apuestas (más allá de si salga ganando/quede multado o no).

**Comment by jpdattas** [comment]
Hola. En el enunciado dice "En caso de que ambos apuesten el mismo máximo, el precio actual será ese mismo, pero el primer postor será considerado el ganador actual". Entonces habría que necesitar algún otro dato (tiempo)? O se podría asumir que "historial" siempre está ordenado y que el último usuario en la lista es el que se queda con el producto, según el precio que el penúltimo usuario de la lista aposto?
