### ISSUE TITLE
Error resources - Duda consola

### ISSUE THREAD

**Issue by bmarinb** [IIC2233-2016-1/syllabus#492]
Al utilizar resources en el QtDesigner me salta un error al ejecutar mi código
 `ImportError: No module named resource_rc`
Después de divagar por internet encontré la solución:
https://pythontips.com/2014/03/08/importerror-no-module-named-resource_rc/#more-465
En que básicamente hay que compilar el resource.qrc  en .py
Sin embargo mis pobres conocimientos en consola me están fallando. ¿En qué carpeta debo utilizar el comando? ¿Como debo cambiar los parámetros para poder aplicarlos a mi caso? (uso windows, digamos que mi recurso se llama imagenes.qrc)

**Comment by stephichau** [comment]
@bmarinb a mi me paso algo parecido y lo pude solucionar usando las rutas directas (sin ocupar resources) :)

**Comment by bmarinb** [comment]
@stephichau ¿te refieres a agregar las rutas en el código cierto? Eso hice yo
Dejo abierto el thread un par de días por si aparece alguien que sepa usar resources

**Comment by stephichau** [comment]
@bmarinb 
esto: 
<img width="483" alt="screen shot 2016-05-27 at 7 02 02 pm" src="https://cloud.githubusercontent.com/assets/16126322/15623875/1c51fb0c-2451-11e6-8605-c89e6191b7d4.png">

**Comment by bmarinb** [comment]
@stephichau  Gracias ! No lo había visto
