### ISSUE TITLE
Problema con las burbujas

### ISSUE THREAD

**Issue by fnquinteros** [IIC2233-2016-1/syllabus#493]
Hola!
Mi problema es el siguiente: Al crear 15 burbujas el programa anda perfecto. La 16ava burbuja que creo anda más lento que las demás creadas antes (no se pega el programa, este anda a velocidad normal, solo las burbujas añadidas desde la 16ava en adelante se hacen lentas). Mis burbujas son QTimers y se crean todas por igual y con las mismas características. No tengo idea que está pasando y me gustaría saber si a alguien le pasa algo parecido o sabe una solución :disappointed: Gracias!

**Comment by fnquinteros** [comment]
Resulta que a veces las que se echan a perder son de la 17ava en adelante y a veces de la 16ava en adelante. Ojalá me contesten luego >.<

**Comment by rodolfopalma** [comment]
Podrías detallar un poco más tu implementación con los QTimers? Has probado modelando las burbujas como QThreads?

**Comment by fnquinteros** [comment]
No he probado modelarlas como QThreads... Las burbujas tienen un movimiento parabólico (definí y en función de t y tengo una variable x que crece en magnitud si la burbuja se aleja del punto en el cual surgió. Al rebotar multiplico la coordenada t por -1 y eso es todo el run de las burbujas... Y por mientras las creo presionando una tecla (para poder ver como funciona sin haber implementado los niveles) Y se crean a la izquierda o derecha de la pantalla según las creo con movimiento hacia derecha o izquierda (depende de un choice). Y todas las burbujas se guardan en una lista en la clase Game. Al crearlas, se les hace start (una sola vez. No usé ningún for ni while para el método start, por lo que no veo porqué se retarda el movimiento de estas...). Si les facilita ver mi problema, haré un push de mi Tarea...

**Comment by fnquinteros** [comment]
Sigo esperando respuesta o cierro la issue? :sweat_smile:

**Comment by fnquinteros** [comment]
nada aún? :sweat:

**Comment by mjjunemann** [comment]
Usas time.sleep?

**Comment by fnquinteros** [comment]
no

**Comment by fnquinteros** [comment]
si hiciera eso se detendrían totalmente todas las burbujas...
