### ISSUE TITLE
2 Preguntas: Menu y Murallas

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233-2016-1/syllabus#494]
hola, la primera pregunta es: Puedo hacer el menú en una interfaz distinta y cuando se escogen las opciones, se cierra y se abre la otra interfaz con el juego?? o es necesario que estén en la misma interfaz??

Segundo: Para los niveles 7 y 8 que hay murallas, cuando se pasa una sección se abre una pedazo de la muralla abajo o podemos eliminar toda la muralla??

**Comment by rodolfopalma** [comment]
Hola, disculpa la demora! Se tiene que borrar completa.

EDIT: Se me olvidó responder la primera pregunta. No es necesario que esté todo dentro de la misma interfaz.

**Comment by Hernan4444** [comment]
Gracias :D
