### ISSUE TITLE
Ejemplo funcionando de la Tarea 3

### ISSUE THREAD

**Issue by hhase** [IIC2233-2016-1/syllabus#495]
Hola!

Dado que el promedio de la tarea 3 ha sido el mas bajo de las tareas, quería preguntar si era posible que subieran una "pauta" o algo equivalente a lo que hubiese sido un 7, para saber como se hacia. 

Hay varias cosas, como por ejemplo el tema de la lectura recursiva de instrucciones que simplemente no se como hacerlas y un ejemplo de la tarea funcionando sería muy útil para poder aprender de mis errores de mi orgulloso 2.2.

Saludos!

**Comment by Nebula2028** [comment]
me sumo totalmente. Hice una petición similar en el readme, pero obviamente tiene más posibilidades de ser escuchada por aqui.

Me parece que la programación funcional es de las cosas más difíciles pero tb más utiles de dominar. Yo tengo un (no tan orgulloso) 1,8 y la verdad si le dedique muchas horas a la tarea.. pero muy poco productivamente (me quedaba pegado constantemente).

Una pauta de esta tarea realmente sería un feedback importante para el aprendizaje de esa unidad de materia, asi que como caso excepcional podrían considerarlo.

Saludos

**Comment by aaossa** [comment]
Hola, pueden encontrar una solución de la tarea 3 [en la carpeta de la misma](https://github.com/IIC2233-2016-1/syllabus/tree/master/Tareas/T03/Solucion). Ojalá les sirva para su aprendizaje :grin:
