### ISSUE TITLE
Omisión de archivo .ui en Actividad 12

### ISSUE THREAD

**Issue by jneyzaguirre** [IIC2233-2016-1/syllabus#496]
Mirando el commit a revisar de la actividad 12, me di cuenta que no subí el archivo ".ui" . Realmente me acabo de dar cuenta, y quería pedirles el permiso para subirlo, ya que por culpa mía estoy afectando a mi compañera. Ojala se pueda hacer algo, el archivo sigue con su ultima fecha de modificación ayer a las 4:51 pm. Se que debí haberlo subido a la hora, pero simplemente se me paso por el apuro de hacer la mayor cantidad de funcionalidades. Me gustaría enfatizar que estoy afectando a mi compañera.

Desde luego, muchas gracias por su comprensión.
José Antonio Eyzaguirre

**Comment by agmardones** [comment]
Me pasó lo mismo. En mi caso, hice todo en una carpeta distinta y al momento de copiar en el repo, se me olvidó pasar el .ui (la costumbre de dejar sólo el .py). La subí apenas llegué a la casa junto a un README [disculpas a mi compañero :( jaja]

**Comment by aaossa** [comment]
Hola, cada vez que tengan una situación particular relacionada con notas o entregas tienen que mandar un mail avisando, no publicarlo aquí. Manden un mail a @jecastro1 (pueden encontrarlo en el [README](https://github.com/IIC2233-2016-1/syllabus#ayudantes-jefes)) para ver sus casos por separado
