### ISSUE TITLE
Ejemplo PyQt4 ayudantía 11 no me funciona

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#497]
Se lo mencioné a uno de los ayudantes al final de la actividad 12, pero me dijo que debería estar funcionando correctamente. El ejemplo siempre se queda pegado al rebotar la primera pelota y en la terminal sale el error "QThread: Destroyed while thread is still running" (que según entendí, es por intentar crear threads dentro de un thread? si estoy equivocado por favor diganme). Si lo trato de correr desde pycharm, además de ocurrir lo anterior y salir ese error, también aparece "QAbstractEventDispatcher: An event dispatcher has already been created for this thread" ¿alguna idea?

EDIT: Ok, probandolo más veces... a veces sí corre, y otras me da ese error. En verdad no entiendo qué pasa :/

**Comment by IsaacConDosA** [comment]
Me sumo a la pregunta. Me ocurre exactamente lo mismo. No deja de salirme ese error :(

**Comment by andresfdezc** [comment]
Primero, disculpen la demora.

Segundo, hemos notado que en Windows el _garbage collector_ de Python elimina los QThreads mientras todavía se están ejecutando, ya que no queda ninguna referencia a ellos (variable o estructura donde estén almacenados). Para solucionar esto se puede simplemente guardar cada instancia de Character en alguna estructura de datos (por ejemplo, una lista) mientras se esté ejecutando.

Para su tarea, les recomendamos guardar todos las instancias que hereden de QThread en al menos una lista, para que no les pase lo mismo.

Subiremos en un rato una versión nueva de la ayudantía que soluciona ese error.
