### ISSUE TITLE
Usar archivos .ui o convertirlos?

### ISSUE THREAD

**Issue by caackermann** [IIC2233-2016-1/syllabus#498]
Investigando en internet encontré una pagina donde hablaban que en lugar de trabajar con archivos .ui directamente en python, se podian convertir a archivos .py usando el comando `pyuc4` desde el terminal. Queria saber que tan util o valido es hacer esto y cual seria la diferencia?
Dejo el link por si sirve de algo:
https://nikolak.com/pyqt-qt-designer-getting-started/
Gracias!

**Comment by aaossa** [comment]
Hola, ambas formas son válidas, correctas y funcionan bien. Yo diría que la diferencia está en que el formato `*.ui` te permite editar las interfaces en QtDesigner de una forma más sencilla y rápida que trabajar la interfaz en código, no creo que vaya mucho más allá que eso. Recuerda que puedes hacer la misma interfaz en código y en QtDesigner :grin:
