### ISSUE TITLE
Duda acerca de super()

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2233-2016-1/syllabus#5]
Hola, mi duda es la siguiente. Cuando utilizo `super().__init__(**kwargs)` en el `__init__` de otra clase, me tira error:

> TypeError: super() takes at least 1 argument (0 given)

Si la clase que se esté definiendo es _Clase_, por ejemplo, y pongo `super(Clase).__init__(**kwargs)`, me tira este otro error:

> TypeError: must be type, not classobj

Lo mismo pasa si pongo `super(Clase, self)__init__(**kwargs)`

No entiendo qué es lo que en realidad hace `super()` y de qué forma usarlo para obtener el resultado de los apuntes. Según lo que busqué debería funcionar alguna de las formas de arriba, pero todas me tiran error.

Gracias!

**Comment by fgvenegas** [comment]
Por como entiendo tu pregunta ve si lo que escribiste es como esto porque asi me funciona bien;

``` python
class Clase:

    def __init__(self, **kwargs):
        super().__init__(**kwargs)


clase = Clase()
```

**Comment by fgvenegas** [comment]
Cuando creas una clase simple no es necesario usar super(), aunque como dice @MainScientist  algunos consideran que es buena practica porque igual hereda de Object (esto se ve mas adelante), pero principalmente usas super cuando quieres hacer herencia y evitar problemas como el del diamente que se produce en la multiherencia

**Comment by otro-felipe** [comment]
Cuando programas bajo el paradigma de orientacion a objetos es importante tener en cuenta que las clases pueden ser heredadas, por lo tanto es importante que las clases "hijas" tengan una referencia hacia sus "padres". El super es esta referencia. De manera mas concreta:

``` python
class Animal:
    def __init__(self, filo, clase, orden, familia):
        self.filo = filo
        self.clase = clase
        self.orden = orden
        self.familia = familia

class Perro(Animal):
    def __init__(self, raza):
        super().__init__("Chordata", "Mammalia", "Carnivora", "Canidae")  # Aqui llamas al init de Animal
        self.raza = raza
```

Esta referencia puede ser bastante util a la hora de extender ciertos metodos de clases ya hechas y tambien para no repetir el codigo del init de animal. (en vez de copiar self.clase = ...... por cada clase que herede de animal simplemente llamas al init que hace todo por ti).

**Comment by AlfonsoIgnacioV** [comment]
Ya lo resolví, era un problema de versión solamente, me estaba tomando una versión anterior. Gracias :)
