### ISSUE TITLE
Se pude usar la libreria Sys

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#50]
Deseo usar la libreria sys parapoder importar agunos archivs python que en una subcarpeta
¿Esta permitido?

**Comment by aaossa** [comment]
No es necesario :grin:, puedes hacer esto:

## Opción 1

Puedes importar las funciones en los archivos de la subcarpeta así:

``` python
from subcarpeta.modulo import funcion

funcion()
```

## Opción 2

Puedes crear un archivo `__init__.py` dentro de la subcarpeta e importar todo el modulo así:

``` python
from subcarpeta import modulo

modulo.funcion()
```

**Comment by perojas3** [comment]
Y para clases?

**Comment by aaossa** [comment]
En lugar de función, usa el nombre de la clase

**Comment by fgvenegas** [comment]
Esta en el material de la ayudantia del lunes pasado como importar modulos

**Comment by perojas3** [comment]
Sí, pero esta muy confuso. Muestra que hay que hacer, pero no los detalles más menores. ¿Alguno conoce un ejemplo concreto?

**Comment by andresfdezc** [comment]
[Aquí](https://github.com/IIC2233-2015-2/syllabus/tree/master/Ayudant%C3%ADas/AY02/modelacion-zoo) hay un ejemplo de modularización de la ayudantía 2 del semestre pasado.

**Comment by agmardones** [comment]
Hola!
Y  si uno quisiera implementar en el menú un método para salir con sys.exit(0), estaría permitido?

**Comment by fgvenegas** [comment]
si :)

**Comment by jecastro1** [comment]
Ver #65
