### ISSUE TITLE
Problema "QUIT GAME" y "PAUSE"

### ISSUE THREAD

**Issue by Zepk** [IIC2233-2016-1/syllabus#501]
Bueno, resulta que tengo el siguiente problema, acabo de agregar las opciones para pausar el juego y cerrar la aplicación con un push button, pero resulta que si estoy jugando en el modo de 1 jugador, y presiono el boton con el mouse, el boton queda "marcado", y luego si despauso el juego, y presiono las teclas lo que pasa es que se cambia del boton de QUIT GAME al boton PAUSE,, asi que el personaje no puede vovler a moverse nunca mas.
Alguna sugerencia para evitar este problema?

Una foto de lo que pasa, por si no me explique muy claramente
[http://prntscr.com/b9nykz](url)

**Comment by Zepk** [comment]
Nevermind, recien hace 1 minuto explicaron como hacer eso en la issue #499

**Comment by aaossa** [comment]
:grin: :ok_hand:
