### ISSUE TITLE
Back-end y Front-end

### ISSUE THREAD

**Issue by JoseDaroch** [IIC2233-2016-1/syllabus#502]
Buenas,
Se que durante la ayudantia se vio más menos en que consistían estos conceptos, pero no me quedo muy claro. Busque y aun no entiendo mucho el como hacer para separarlos o que involucra cada uno específicamente.
Por eso agradecería si alguien pudiera explicármelo un poco mejor.

**Comment by ivaniadg** [comment]
Hola @JoseDaroch,

El modelo de _backend - frontend_ es básicamente una abstracción. Separas la parte de presentación e interacción de la parte de procesamiento. De esta manera si debes cambiar la forma en que se procesan los datos, solo debes modificar el backend y si debes cambiar la forma en que se interactua con el usuario solo cambias el frontend. Para trabajar con este modelo siempre hay que definir muy bien la forma de comunicación entre ambas partes.

Por ejemplo: digamos tengo una clase `Calculadora` que puede sumar dos números y restar dos números. En la interfaz quiero poder ingresar dos números, seleccionar una operación y que al hacer click esta se ejecute y el resultado aparezca. El código del frontend se vería más o menos así.

``` python
class Ventana(calc_ui[0], calc_ui[1]):

    def __init__(self):
        super().__init__()
        self.setupUi(self)

        self.calculadora = Calculadora()
        for operacion in self.calculadora.operaciones.keys():
            self.operaciones.addItem(operacion)

        self.calcular.clicked.connect(self.ejecutar_operacion)

    def ejecutar_operacion(self):
        operacion = self.calculadora.operaciones[self.operaciones.currentText()]
        self.resultado.setText(str(
            operacion(int(self.operando_1.text()),
                      int(self.operando_2.text()))))
```

Si te fijas, la interfaz no sabe cómo se suma ni como se resta. Solo sabe que `calculadora` sabe hacer eso, y que necesita los valores de `operando_1`y `operando_2`. El frontend simplemente hace un **mapping entre las acciones que realiza el usuario y la respuesta del programa a esas acciones**.  

La gracia de usar este enfoque es que cada parte por separado es **reutilizable**: si ya no me gusta la interfaz puedo programar una nueva o si creo que el programa es incompleto, puedo agregarle más operaciones sin tener que modificar toda la interfaz, solo agrego lo que sea necesario.

**Comment by JoseDaroch** [comment]
Gracias, muchísimo más claro, te pasaste! :D
