### ISSUE TITLE
Duda sobre disparo en la tarea

### ISSUE THREAD

**Issue by cggutierrez** [IIC2233-2016-1/syllabus#503]
Jugué el Bouble Trouble que esta enlazado en el pdf pero creo que me confundí. En el juego cada vez que se dispara queda una cuerda que también revienta las burbujas, pero según entendí del enunciado eso es lo que debería hacer el power-up de alambre de púas, entonces, nuestro disparo normal no lleva una cuerda, y esta cuerda solo es cuando hay power up de alambre de púas?
Lo otro, no entiendo bien como funciona el disparo doble en el sentido de que se debería ver en la interfaz al disparar con este power up.
gracias!

**Comment by negebauer** [comment]
El disparo normal es una cuerda que sube y al impactar con una burbuja o con el techo desaparece
El alambre de púas hace que al chocar con el techo la cuerda no desaparezca, solo desaparece cuando la toca una burbuja
El jugador normalmente solo puede disparar una cuerda y no volver a disparar hasta que esa desaparezca. Con el disparo doble puede disparar hasta dos cuerdas y no puede volver a disparar hasta que desaparezca al menos una.

**Comment by MortizDX** [comment]
¿También tenemos que considerar la cuerda normal en el juego? Que en el enunciado mismo no se indica concretamente para la bala normal, solo con el alambre (y como el enunciado dice enfocarse más en lo escrito que en el juego de ejemplo, consideré que no era necesario).

**Comment by negebauer** [comment]
Si, la idea es que hagan la cuerda normal @MortizDX 😓

**Comment by MortizDX** [comment]
Ya veo n.nU Gracias por la aclaración.

**Comment by negebauer** [comment]
Vamos que aún hay tiempo 💪 @MortizDX

**Comment by vjmoreno** [comment]
Tengo una duda con el disparo doble, en el enunciado dice: Si este dispara dos veces, podrá volver a hacerlo luego de que la primera bala haya tocado el techo, o bien cuando haya reventado una burbuja. Entonces cuando desaparezca una de las dos balas puede volver a disparar doble o solo puede disparar 1 vez más?

**Comment by negebauer** [comment]
Solo pueden haber dos disparos activos en un momento dado con el power up de disparo doble

**Comment by vjmoreno** [comment]
@negebauer gracias!

**Comment by negebauer** [comment]
@vjmoreno de nada!

@cggutierrez Recuerda cerrar el issue si estás satisfecho con la respuesta 😁
