### ISSUE TITLE
Sobre los creditos.

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#504]
Obiamente tendre que usar sprites y fondos de otra parte.
¿Como tengo que dar los creditos?

**Comment by fgvenegas** [comment]
A que te refieres con dar los créditos ?

**Comment by fgvenegas** [comment]
Asumiendo que te refieres a mencionar quien es el creador de la imagen, puedes agregar en el README el link de donde las sacaste o su autor, eso queda libre a tu decision y no habrán descuentos si no lo haces, aunque es bueno acostumbrarse a referenciar algo que sacaste de internet para el futuro ;)
