### ISSUE TITLE
División burbujas

### ISSUE THREAD

**Issue by camiolguin** [IIC2233-2016-1/syllabus#505]
Durante la ejecución del main quiero agregar nuevas burbujas del tipo QtCore.QThread pero me aparece el error
QThread: Destroyed while thread is still running

Como las puedo agregar a la interfaz luego de haberla ejecutado?
Gracias!

**Comment by fgvenegas** [comment]
Puedes hacer push de tu tarea para revisar como las estas agregando porfa? y te respondo en base a eso ;)

Edit: si puedes comentar tu OS tambien seria de ayuda

**Comment by camiolguin** [comment]
lo acabo de subir! graciass

**Comment by fgvenegas** [comment]
Cual es tu sistema operativo?

**Comment by camiolguin** [comment]
mac os x

**Comment by fgvenegas** [comment]
En #497 se dio una respuesta ya que al parecer era un error generalizado, ojala te sirva!

**Comment by camiolguin** [comment]
gracias!
