### ISSUE TITLE
Problema PyQt4

### ISSUE THREAD

**Issue by bregonesi** [IIC2233-2016-1/syllabus#506]
Hola.
Tengo un problema con las pelotas o mas bien con la PyQt4. El programa se cae cuando hay muchos movimientos por segundo.
He intentado hacer el movimiento de las pelotas con la librería _threading_ y también con _QThread_, pero en ambos casos se cae.
Con o sin locks también se cae. He intentado también en windows y osx.
En internet no he contrado nada.
Estos son los errores que me tira.

En mac: (se cierra la interfaz y tira esto en consola)
<img width="1109" alt="screen shot 2016-05-29 at 14 07 53" src="https://cloud.githubusercontent.com/assets/14252577/15635316/5ab3ad9c-25a9-11e6-9c48-877597079605.png">
En windows: (no hay errores en consola)
<img width="282" alt="screen shot 2016-05-29 at 14 07 02" src="https://cloud.githubusercontent.com/assets/14252577/15635317/5afae7de-25a9-11e6-8266-5d8034da7710.png">
A alguien mas le pasa?

PS: Con un simple código como este se cae siempre y cuando hayan hartas pelotas. Con una pelota en pantalla funciona bien.

``` python
def movimiento(pelota):
  pelota.x += 1
  pelota.y += 1
  pelota.mover()
```

**Comment by fgvenegas** [comment]
Especulando solamente, asumo que el `run` de tu Qthread tiene un while adentro que ejecuta el movimiento, estas haciendo `sleep()` dentro de ese while? Puede ser por eso porque sino lo pones todos los Qthreads ejecutandose sin detener terminan por colapsar la interfaz. Tambien es util utilizar Qtimers ya que les entregas como parametro cada cuanto se deben ejecutar

**Comment by bregonesi** [comment]
Exacto, tengo un `while` y `sleep`. Voy a intentar usar `Qtimers`.
Gracias!

**Comment by JoseDaroch** [comment]
Mas o menos que son los Qtimers?, no encontré nada muy claro

**Comment by bregonesi** [comment]
@fgvenegas Lo implemente usando `Qtimer`, pero en osx funciona lento. No hay otra forma de implementarlo?
El código es mas o menos así.

``` python
self.timer = QTimer(self)
self.timer.timeout.connect(self.movimiento)
self.timer.start(1)
```

**Comment by fgvenegas** [comment]
@bregonesi Para que utilizas `timeout`? Es solo una conjetura pero puede tener que ver con eso por lo que vi a la rapida en internet, hasta donde yo recuerdo basta con hacer `self.timer.start(1)` para que el Qtimer ejecute su función, que en este caso seria moverse si no me equivoco

**Comment by fgvenegas** [comment]
Me parece raro que ande lento solo en OSX, yo recuerdo que cuando los use en mi tarea los implementaba de esta manera

``` python
class Personaje(QtCore.QObject):

    def __init__(self):
        super().__init__()
        self.timer = QtCore.QTimer()
        self.timer.connect(self.timer, QtCore.SIGNAL("timeout()",), self.run)
        # Aca iban mas cosas del init

    def run(self):
          # Funciones que se ejecutan cuando haga self.timer.start(1)


```

No te aseguro nada la verdad porque me parece que el tema de la velocidad no debería verse afectada por eso, pero quizas pueda servirte

**Comment by bregonesi** [comment]
Hice un contador de tiempo entre cada vez que se mueve una pelota.
Para una pelota en pantalla:
<img width="327" alt="screen shot 2016-05-29 at 16 00 48" src="https://cloud.githubusercontent.com/assets/14252577/15635790/c333d376-25b6-11e6-9e34-472c52f1332c.png">
Para 10 pelotas:
<img width="306" alt="screen shot 2016-05-29 at 16 01 13" src="https://cloud.githubusercontent.com/assets/14252577/15635791/cc3cc996-25b6-11e6-9c68-d10354f28e22.png">
Para 100 pelotas:
<img width="296" alt="screen shot 2016-05-29 at 16 01 52" src="https://cloud.githubusercontent.com/assets/14252577/15635792/d41d1e72-25b6-11e6-9ee7-5f6e6e2220da.png">

Me di cuenta que si esta minimizada la gui funciona mas rápido.

**Comment by fgvenegas** [comment]
@JoseDaroch Los Qtimers permiten que tu le des un metodo `run` que debe ejecutar cada cierta cantidad que tiempo, que se la das como parametro cuando haces `start,` asi evitas tener un `while` con `sleep()` como generalmente se hace con Qthreads, ademas con Qtimers puedes hacerle `stop()` cuando quieras.

@bregonesi Se te cae el programa en algun momento? Y de casualidad no tienes muchos procesos corriendo en tu notebook que puedan relentizar el juego?

**Comment by otro-felipe** [comment]
quizas al hacer `timer.start(1)` estas ejecutando codigo mas rapido de lo que la interfaz lo procesa, intenta hacerlo con 25 o con 50ms.

**Comment by fgvenegas** [comment]
En efecto como dice @MainScientist el parametro que le entregas al hacer `start()` esta en milisegundos

**Comment by bregonesi** [comment]
No es un problema de CPU, esta usando no mas de 50% de un procesador. y con `timer.start(25)` o 50ms anda igual.
Probe con 100 pelotas en windows maquina virtual y anda perfecto. Por el momento estaré usando maquina virtual para correr el programa.

**Comment by fcorencoret** [comment]
Yo llevo todo el findesemana en el mismo error, pero se me acaba de arreglar porque le puse un time.sleep() mayor y movi el objeto por una mayor cantidad. Antes tenia, time.sleep(0.002) y que se moviera 1 pixel, y ahora tengo time.sleep(0.05) y se mueve 10 pixeles. Con eso funciona bien.
Exigo mis dos dias perdidos de vuelta! jaja

**Comment by jpdattas** [comment]
Al usar timers las imagenes me aparecen medias cortadas derepente, cosa que no pasaba con QTreads (aunque tenian los errores). Hay alguna forma de evitar eso? o da lo mismo?
