### ISSUE TITLE
[OffTopic] Ordenar Codigo

### ISSUE THREAD

**Issue by santiagocruzb** [IIC2233-2016-1/syllabus#507]
Hola! Pycharm tiene la opción de mostrar los atributos y métodos que tiene una clase (ordenados, o por como aparecen). 
![screen shot 2016-05-30 at 12 02 42 pm](https://cloud.githubusercontent.com/assets/13748925/15653993/88adcb6e-265e-11e6-8844-08217a281ced.png)
Es posible ordenar los métodos alfabéticamente, como sale en la foto?
Saludos

**Comment by ivaniadg** [comment]
el primer botón ordena los métodos de forma alfabética (a->z)

**Comment by santiagocruzb** [comment]
Los ordena para verlos visualmente, pero no me reestructura el codigo

**Comment by ivaniadg** [comment]
JetBrains tiene la característica pero para otros lenguajes :disappointed: . Se accede por Code/Rearrange Code.
