### ISSUE TITLE
Rebote burbuja

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#509]
El requerimiento de que la trayectoria de la burbuja sea continua ¿no considera el rebote, verdad? Que cuando la burbuja choca con un elemento (pared, personaje o burbujas), se va a producir una discontinuidad allí ¿o acaso la burbaja debe "predecir" su ambiente para que TODA su trayectoria no tenga discontinuidades?

**Comment by rodolfopalma** [comment]
Efectivamente, no considera el rebote.

**Comment by cataschaufler** [comment]
se incluye dentro del rebote el rebote con el suelo cierto? si es que yo decidi hacer que rebotara con este

**Comment by rodolfopalma** [comment]
Sí, se incluye dentro del rebote el rebote del suelo.
