### ISSUE TITLE
Alguna forma de poder extraer un fragmento de un string entre 2 caracteres

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#51]
¿Desearia saber, existe la forma de extraer un pedaso de string entre 2 caracteres?
Como por ejemplo, que le diga a python que me extraiga lo que hay entre 2 "g" de un string.

**Comment by otro-felipe** [comment]
Eso es un poco complicado, ya que tienes strings en los que hay mas de dos gs `"ggabghg"` en los que el problema se vuelve ambiguo.
 En particular lo que yo te recomendaria es que definas bien que caracteres son los que quieres encontrar y encuentres sus indices usando [index](http://www.tutorialspoint.com/python/string_index.htm) y [rindex](http://www.tutorialspoint.com/python/string_rindex.htm). 
Con estos indices puedas sacar el substring que necesitas. 

``` python
s = "ggabghg"
if s.count("g") >= 2:    # verificar que tienes dos gs o mas
    index1 = s.index("g")  # indice de la primera g
    index2 = s.rindex("g")    # indice de la ultima g
    print(s[index1+1:index2])    # aqui tienes todo lo que hay entre la primera y ultima g del string
```
