### ISSUE TITLE
Constantes

### ISSUE THREAD

**Issue by isipalma** [IIC2233-2016-1/syllabus#510]
Holi

Tengo una duda con respecto al archivo de las constantes, exactamente cuales serian? Pues si tenemos que poner todas las constantes que no se especificarlos entonces serian demasiados y muchos serian innecesarios segun yo (como el puntaje que dan las monedas y los billetes, o la probabilidad con que salgan los bonus)
Esta bien si solamente le pongo el scale y la altura maxima de cada pelotita? o faltaria otra constante?

saludos y gracias de antemano ;)

**Comment by flobarrios** [comment]
Hola ! Es necesario que pongas todas las constantes como las probabilidades de powerups y el puntaje de monedas y billetes. Esto esta enfocado en la corrección, para que podamos chequear si al variar las probabilidades y puntajes, ocurre el cambio esperado en el juego. Saludos!
