### ISSUE TITLE
keyPressEvent

### ISSUE THREAD

**Issue by jtagle2** [IIC2233-2016-1/syllabus#511]
Tengo un problema al momento de detectar las teclas. Cuando apreto las letras o los numeros del teclado, me anda bien. Pero cuando quiero usar las flechas, el keyPressEvent no se llama cuando apreto las flechas del teclado. pero el keyReleaseEvent si

```
def keyPressEvent(self, key):
    print(key.key())

def keyReleaseEvent(self, key):
    print(key.key())
```

Con ese código, si apreto y luego suelto A, me imprime el numero asociado a A 2 veces (una del press, otra del release), pero si apreto cualquiera de las flechas, me imprime solo 1 vez el numero (que me lo llama desde el release). Que puede ser? Estuve buscando en internet y no encontré nada.

Saludos, y gracias

**Comment by aaossa** [comment]
Hola, creo que se soluciona exactamente como #499. Acabo de usar el mismo código adaptado con tus métodos y funciona:

``` python
import sys
from PyQt4 import QtCore, QtGui


class MyWindow(QtGui.QMainWindow):

    def __init__(self):
        super(MyWindow, self).__init__()
        self.initUI()

    def initUI(self):
        self.mywidget = MyWidget(self)
        self.setCentralWidget(self.mywidget)
        btn = QtGui.QPushButton("Window button", self)
        btn.move(50, 150)
        self.statusbar1 = self.statusBar()
        self.statusbar2 = self.statusBar()
        self.mywidget.msg2statusbar[str].connect(self.statusbar1.showMessage)
        self.resize(200, 200)
        self.show()


class MyWidget(QtGui.QWidget):

    msg2statusbar = QtCore.pyqtSignal(str)

    def __init__(self, parent):
        super(MyWidget, self).__init__(parent)
        self.initWidget()

    def initWidget(self):
        btn = QtGui.QPushButton("Widget button", self)
        btn.move(50, 50)
        self.setFocusPolicy(QtCore.Qt.StrongFocus)

    def keyPressEvent(self, event):
        key = event.key()
        self.msg2statusbar.emit("Press {}".format(key))

    def keyReleaseEvent(self, event):
        key = event.key()
        self.msg2statusbar.emit("Release {}".format(key))


def main():
    app = QtGui.QApplication([])
    window = MyWindow()
    sys.exit(app.exec_())

if __name__ == '__main__':
    main()
```

Seguramente, al igual que la _Key_Space_ al usar las flechas cambias el foco.

**Comment by jtagle2** [comment]
Gracias!

**Comment by santiagocruzb** [comment]
@aaossa Una pregunta, por qué los eventos de teclados relacionados a las flechas los asocias al widget y no a la interfaz misma? El código que pusiste funcionaría igual si los eventos van en la interfaz?
Saludos
