### ISSUE TITLE
Respecto a manejar un archivo de audio

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2233-2016-1/syllabus#513]
Hola! Cuando abro un archivo con la extensión .wav, en modo de bytes, se puede ver que los primeros bytes que imprime los muestra así:
b'\n\n\n\n<!DOCTYPE html>\n<html lang="en" class=" is-copy-enabled is-u2f-enabled">\n'
habiendo tomado un número de bytes arbitrario. 

¿De qué manera se obtienen entonces las secciones señaladas? Por ejemplo, la sección RIFF correspondería a '\n\n\n\n' y no a la palabra 'RIFF'. De hecho, pude darme cuenta que lo que devuelve es algo que se puede leer como un archivo parecido a un html. 
Espero haberme explicado
Muchas gracias
Saludos!

**Comment by robocop6** [comment]
Hola!
En ocasiones, los archivos guardados con extensión .wav no siguen el formato wave en forma estricta. El reproductor se encarga de leer los primeros bytes para saber cómo decodificar la información (aunque debo reconocer que nunca me ha pasado esto de que se parezca a un html ._.). Seguramente está ocurriendo algo así.

Además, los archivos pueden estar comprimidos. Para hacer pruebas, puedes probar descargar archivos de [freewavesamples](http://freewavesamples.com/). Los que he descargado de ahí no me han dado ese tipo de problemas.
