### ISSUE TITLE
[T05][KeyPressEvent]

### ISSUE THREAD

**Issue by vbarros2** [IIC2233-2016-1/syllabus#514]
Estoy tratando de realizar el multiplayer pero no puedo mover los dos monos a la vez ya que están en la misma clase de KeyPressEvent. No lo pude solucionar creando otra clase, ni probando otras maneras.

Alguna idea?

Gracias!

**Comment by spiza** [comment]
Keyreleaseevent?

Enviado desde mi iPhone

**Comment by vbarros2** [comment]
No me funciona con KeyReleaseEvent, debiera de funcionar?

**Comment by gdburky** [comment]
[aca (stackoverflow)](http://stackoverflow.com/questions/7176951/how-to-get-multiple-key-presses-in-single-event) hay un ejemplo de como funciona

**Comment by rmant** [comment]
Tengo el mismo problema, y la solucion del link que postearon mas arriba no me funciona, me dice "AttributeError: 'MainMenu' object has no attribute 'keylist'" . Alguna idea de como solucionarlo? Gracias!

**Comment by JoseDaroch** [comment]
Si no me equivoco tienes que crear la lista keylist en tu 'menu'

**Comment by bmarinb** [comment]
Creo que no funciona para el caso en el que mientras mantengo un botón, apreto otro. Después de apretar el segundo se deja de considerar que el primero está apretado. ¿Alguien logro resolver esto?

**Comment by agmardones** [comment]
@bmarinb Lo lograste solucionar? tengo el mismo problema :(

**Comment by bmarinb** [comment]
@agmardones  ya dejé de intentarlo D:

**Comment by vjmoreno** [comment]
A mi me funciono mas o menos con ese código, igual los personajes dejan de moverse por un tiempo corto, para luego moverse. Lo que hice fue hacer la keylist y  el firstrelease = False en el init, y luego todo el código que tenía en el keyPressEvent lo pasé al método processmultikeys e iteré sobre la lista que me entregaba.
