### ISSUE TITLE
Imagenes

### ISSUE THREAD

**Issue by cataschaufler** [IIC2233-2016-1/syllabus#515]
podemos usar otras fotos para las pelotas? o necesariamente tenemos que usar las de la carpeta assets

**Comment by aaossa** [comment]
Hola, puedes usar otras imágenes, los tareos las hicieron con amor y se sentirán mal :cry: pero usa otras no más

**Comment by negebauer** [comment]
Por que harías eso? 😞

**Comment by flobarrios** [comment]
Hola! puedes pero siempre y cuando tus burbujas tengan una jerarquía (como la de boss - mentor - tpd) y no simplemente que se vayan haciendo mas pequeñas. Además, debes implementar más de un color. De otra forma serás penalizada. Saludos!
