### ISSUE TITLE
Duda modelamiento Tarea

### ISSUE THREAD

**Issue by vjmoreno** [IIC2233-2016-1/syllabus#516]
Hola, quisiera saber que es más eficiente, tener un thread que me controle a todas las burbujas o tener uno por cada burbuja. Pregunto porque hasta el momento tengo un thread para todas las burbujas, otro para todos los disparos y otro para el personaje.

**Comment by rodolfopalma** [comment]
<img width="556" alt="screen shot 2016-05-31 at 6 25 21 pm" src="https://cloud.githubusercontent.com/assets/6728087/15692563/308924ba-275d-11e6-8ae7-8f9a84346b5d.png">

Mientras usas tu computador hay miles de threads andando simultáneamente. A la escala de esta tarea no te preocupes de que un par de threads más puedan hacer lento el juego. A mi por lo menos me hace más sentido un thread una burbuja, pero eso no significa que sea la única modelación posible.
