### ISSUE TITLE
Problema botones y Keypressevent

### ISSUE THREAD

**Issue by rmant** [IIC2233-2016-1/syllabus#517]
Tengo un problema que al agregar pushButtons (para elegir modo singleplay o multiplayer) mi gui deja de recibir las señales de keypressevent. Pero extrañamente, sin estos botones, o haciendoles hide a estos desde el init, todo funciona perfecto. (Si hago el hide luego de una señal ya no sirve)

Alguna idea de porqué puede estar pasando esto? No encontré nada en internet. Muchas gracias!

**Comment by aaossa** [comment]
Quizás #499 y #511 pueden servirte
