### ISSUE TITLE
Botones y teclas

### ISSUE THREAD

**Issue by isipalma** [IIC2233-2016-1/syllabus#518]
Holi

Tengo el siguiente problema: cuando intento mover a mi personaje usando las teclas se me seleccionan tambien los botones de salida y de pausa, segun el lado que presione. Entonces cuando uso la barra espaciadora se apretan estos botones en vez de hacerse el disparo
Trate mucho rato buscando que metodo o atributo de los botones cambia eso pero no he podido encontrar :( (en otras palabras quiero que mis botones solamente se puedan apretar con el click y no con enter ni la barra espaciadora que al parecer los tiene por default)

saludos y gracias ;)

**Comment by aaossa** [comment]
#517, #499 y #511

**Comment by bregonesi** [comment]
Creo que te refieres a esto. En el designer -> propiedades del botón hay una opción para hacer que los botones no se seleccionen (focusPolicy). Yo la deje como "NoFocus" y me funciono.
<img width="282" alt="screen shot 2016-06-01 at 18 25 11" src="https://cloud.githubusercontent.com/assets/14252577/15727716/65389500-2826-11e6-88cb-0cae3e043334.png">
