### ISSUE TITLE
Archivos con constantes

### ISSUE THREAD

**Issue by jtagle2** [IIC2233-2016-1/syllabus#519]
Para la tarea, lo que hago es que los parámetros utilizados (radios de las pelotas, del jugador, etc), los tengo en variables estáticas de la clase. Puedo especificar en el README para que es cada parámetro, y que para cambiarlo hay que cambiar el parámetro en la variable de la clase.
Para los radios de las pelotas por ejemplo, tengo un diccionario que se llama: Radios, y es de la forma {nombre_pelota: valor_radio}. Y el programa se ajusta según el valor de ese radio, para esa pelota.
Saludos

**Comment by rodolfopalma** [comment]
Hola, en el punto 4 del enunciado se indica que todas las constantes utilizadas deben ir en un archivo `constantes.{txt, py, csv, ...}` separado de tus clases y lógica del juego. Ver #510 también.
