### ISSUE TITLE
Variables "nombre" y "apellido" en la entidad Usuario

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#52]
Una pequeña duda que me acaba de surgir leyendo los archivos con python, pero que prefiero preguntar antes de actuar por mi cuenta ¿es necesario que la entidad "Usuario" tenga el nombre y apellido de la persona "x" por separado o puede contar todo con una variable "nombre"? Es algo súper menor, lo sé, pero recién noté que hay usuarios con el nombre "Ana Paula" y otros con el apellido (creo lo puedo considerar así) "San Martín" (no me he fijado si hay otros casos similares) y no se me ha ocurrido que hacer en esos casos.

**Comment by tamycova** [comment]
Puedes hacerlo de ambas formas, pero justifícalo en el README. Creo que para efectos de modelación es más correcto tener el atributo nombre separado del apellido, podrías hacerlo con los usuarios nuevos y elegir un criterio arbitrario que separe los nombres de los apellidos en la base de datos.

**Comment by perojas3** [comment]
En el archivo usuarios.txt el nombre y apellido va en la misma variable.

**Comment by MortizDX** [comment]
Ok, muchas gracias por la respuesta!
