### ISSUE TITLE
Colores

### ISSUE THREAD

**Issue by IsaacConDosA** [IIC2233-2016-1/syllabus#520]
Hola, no comprendo bien el sistema de las burbujas. 
1- Si revientan una azul, deben aparecer dos azules o no?
2- Si una burbuja es nivel 20, yo elijo cuantas veces de la Boss saldrán Boss o es un número fijo?

Salu123

**Comment by flobarrios** [comment]
Hola ! Si revientas una azul y esta tiene mas de un nivel efectivamente deben aparecer 2 azules. Respecto a la jerarquía, si el nivel es mayor o igual a 3, tu decides cuantas veces se repite cada tipo, manteniendo la jerarquia (boss --> mentor --> tpd) por ejemplo, para el caso de 20 niveles puede ser:
1. 18 boss, 1 mentor, 1tpd
2. 10 boss, 5 mentor, 5 tpd
3. 1 boss, 18 mentor, 1 tpd
3. 1 boss, 1 mentor, 18 tpd
etc...
Espero que haya quedado mas claro. Saludos!

**Comment by IsaacConDosA** [comment]
Muchas gracias :smile:
