### ISSUE TITLE
Tipo y Jerarquias

### ISSUE THREAD

**Issue by cataschaufler** [IIC2233-2016-1/syllabus#521]
No entiendo bien el enunciado, por que lo que entendi es que el tipo de bubujas son apartes de el nivel y que por ejemplo pordria pasar que una boss de nivel 3 se divida en  una boss de nivel 2 y esta en una boss de nivel 1 pero mas adelante dice que siempre la minima unidad debe ser tdp y tambien dice que una boss no se puede dividir en tdp entonces que sucede en este caso? o significa que la burbuja  boss solo se puede dividir en boss nuevamente si es de nivel 4?

**Comment by flobarrios** [comment]
Hola ! Mira lo que respondi en #520. Si no te queda claro avísame pero ve los ejemplos que estan en el enunciado. Efectivamente, una boss solo se podra volver a dividir en boss si es de nivel 4 ya que obligatoriamente deben estar los 3 tipos (boss, mentor, tpd) si es de nivel mayor o igual a 3, 2 tipos (mentor y tpd) si es de nivel 2 y un tipo (tpd) si es de nivel 1. Saludos!
