### ISSUE TITLE
Bordes de Objetos

### ISSUE THREAD

**Issue by caackermann** [IIC2233-2016-1/syllabus#522]
Hola, queria saber si en pyqt4 existe algo, como en la Tarea 4, para poder ver los bordes o marcos de las entidades?

**Comment by isipalma** [comment]
sip, tienes que poner esto en el archivo donde estan tu clase ventana
_debugging = True
y dentro del init de la ventana poner: if _debugging:
                                                                            self.setStyleSheet("border: 1px solid black")

**Comment by caackermann** [comment]
Gracias!!
