### ISSUE TITLE
Problema con sprite

### ISSUE THREAD

**Issue by cggutierrez** [IIC2233-2016-1/syllabus#523]
al sacarle el fondo a la imagen y dejarla como png, no me aparece en la interfaz, pero al sacarle el fondo y dejarla como jpg si aparece (pero obviamente con fondo)

alguien sabe que puede estar pasando o le paso en algún momento?

**Comment by flobarrios** [comment]
Hola ! Te aparece alguna advertencia al agregar la imagen en png? Verificaste si le estas entregando el nombre correcto? Quizas sea por eso! Avisame y vemos que puede ser!

**Comment by cggutierrez** [comment]
al tratar de sacar cada pixmap del spritesheet me tira index out of range, y al tratar de meterla sin sacar cada pixmap  (la imagen entera) simplemente no sale, mientras que sin editar en ambos casos sale sin problemas :/

**Comment by flobarrios** [comment]
Haz un push a tu codigo para revisarlo y dime en que parte esta!

**Comment by cggutierrez** [comment]
ahi hice el push, es en el metodo init del modulo Player, al usar la imagen sprite6.png no funciona 

edit: si lo corres, tienes que correr el modulo Juego!

**Comment by flobarrios** [comment]
lo reviso altiro !

**Comment by flobarrios** [comment]
Resuelto!
