### ISSUE TITLE
Velocidad Interfaz

### ISSUE THREAD

**Issue by caackermann** [IIC2233-2016-1/syllabus#524]
Hola, queria saber si habra algun problema en el modelamiento de mi programa ya que se pone extremadamente lageado (con una sola burbuja) cuando ocurre lo siguiente:
- Al tratar de moverse muy rapido mientras la pelota se esta moviendo
- Al disparar mientras la pelota se esta moviendo
- Cuando el personaje dispara y luego se mueve

Cada objeto (personaje, disparo, burbuja) son QThreads. Todas estas se instancian y guardan dentro de la ventana principal (QWidget). Lo unico que se me ocurre es que en realidad deben ser muchas signals al mismo tiempo, ya que cada movimiento de cada objeto manda una signal a la ventana principal para que se mueva la imagen asociada. Cual puede ser el problema?
Gracias!

**Comment by jtagle2** [comment]
Yo había empezado la mía con Qthreads, haciendo el típico sleep() al final del while, y también me funcionaba lento. Lo cambié a Qtimers, y ahora anda perfecto. No se por qué, pero funciona (Por si te sirve)

**Comment by fgvenegas** [comment]
En cierto modo cuando utilizamos Qthreads con un `while` y un `sleep()` estamos forzando un proceso que no es natural para un Thread, el deberia realizar un proceso y morir, en cambio aca pedimos que se repita constantemente con este 'truco', en cambio un Qtimer esta diseñado para que tu al hacer `start(x)`, le digas "quiero que me hagas este proceso cada x milisegundos", sin necesidad de incorporar un `while` o `sleep`, es algo natural del Qtimer, es por esto que en la ayudantia se menciono que no era buena idea utilizar Qthreads y en varias issues ya se ha tocado el mismo tema

**Comment by caackermann** [comment]
Cambie todos los threads a timers y ahora funciona perfecto! Gracias!!
Otra pregunta:
En terminos de modelacion o eficiencia, que seria mas correcto al mover una imagen:
- que cada clase realize el movimiento, es decir, dentro de la clase un metodo hace image.move(x,y)
- que la ventana principal realize el movimiento con una signal enviada desde la clase (como en la ayudantia)

**Comment by isipalma** [comment]
segun yo lo segundo es mejor ya que se crea una cola segura, es decir, que como la interfaz hace todo solamente le llegan las señales y hace como una fila y las va ejecutandos egun orden de llegada, asi que no puede suceder cosas como modificar informacion que otro thread esta usando

Yo tengo un problema con que a veces se me queda pegado el programa, y no se a que se debe :(

**Comment by isipalma** [comment]
No se laguea pero a veces cuando paso una etapa queda parado

**Comment by fgvenegas** [comment]
@caackermann en efecto como dice Isidora es lo mas correcto como se vio en la ayudantia ;)

@isipalma puedes hacer push de tu codigo para revisarlo ?

**Comment by isipalma** [comment]
jijiji ya lo resolvi XD estaba borrando algo desde un thread y no desde la interfaz. se me escapo :P
pero gracias ;)

**Comment by fgvenegas** [comment]
Recuerden cerrar la issue cuando este todo ok :)
