### ISSUE TITLE
Github 

### ISSUE THREAD

**Issue by santiagocruzb** [IIC2233-2016-1/syllabus#525]
Estimados.
Hice checkout comit para volver hacia un comit mas viejo.
Despues de varios intentos de solucionar la cosa, me queda lo siguiente (queriendo dejar el commit "burbujas encontrándose con balas" como actual):
![screen shot 2016-06-01 at 9 02 15 pm](https://cloud.githubusercontent.com/assets/13748925/15730612/2a02bec8-283c-11e6-8391-65bbaab7c462.png)

Al momento de hacer push me tira el siguiente error:
![screen shot 2016-06-01 at 6 58 28 pm](https://cloud.githubusercontent.com/assets/13748925/15728552/27c7f99a-282b-11e6-9dfe-b0a4be9e4d9b.png)

Ayuda! muchas gracias!

**Comment by lopezjurip** [comment]
Veo que ya seteaste ese commit como tu `HEAD`, ahora no puedes hacer push porque tu repositorio local está 'detrás' de la nube.

Si quieres sobrescribir lo que tienes en la nube con lo que tienes en tu pc:

``` sh
git push --force
```

Cuidado que esta operación es peligrosa

**Comment by ivaniadg** [comment]
Haz una copia del repo antes. Por si acaso

**Comment by lopezjurip** [comment]
Yo aquí infiltrado :shipit:

**Comment by santiagocruzb** [comment]
`Protected branch update failed for refs/heads/master`
`master branch hook declined`

#VuelveMrPatiwi

**Comment by lopezjurip** [comment]
Culpen a @jecastro1 porque quizás protegió las branches

> https://help.github.com/articles/about-protected-branches/

**Comment by santiagocruzb** [comment]
(para cuando se solucione)
Pato cuales vendrían siendo los comandos para empezar a hacer commits seteando como checkout otro commit mas antiguo y que no me pase esto? (habia hecho checkout commit al antiguo, y ahí partió todo)

**Comment by lopezjurip** [comment]
Es que checkout sirve para moverse entre _puntos_ que pueden ser commits, tags, branches, etc.
El último commit de una branch (el más nuevo) se llama HEAD.

Ahora, **_git no olvida ni perdona_**, entonces no puedes deshacer algo pusheado (a menos que hagas un `--force`).

Lo que puedes hacer es un `git revert <COMMIT>` para revertir algo y seguir en la HEAD sin problemas. Aunque deja "sucia" la historia de git.

Si todavía no está pusheado, puedes hacer `git reset <COMMIT>`. Puedes agregarles las opciones `--soft` para conservar los archivos o `--hard` para borrar lo actual y quedarte con los de ese commit.

**Comment by santiagocruzb** [comment]
Es que nada esta pusheado, porque desde que tuve el problema no me ha dejado pushear nada. 
Siempre tuve estos problemas:
`remote: error: Cannot force-push to a protected branch` o
`hint: Updates were rejected because the tip of your current branch is behind`

**Comment by mjjunemann** [comment]
No se si esto te resulte pero luego de buscar tu problema : older commit to head git , el segundo link arroja algunas cosas utiles a tu problema: 

http://stackoverflow.com/questions/13956207/how-can-i-make-an-older-commit-head-in-git

Ojala te sirva
Siempre respalda antes de hacer cosas de este estilo, no quieres borrar y perder todo.

**Comment by santiagocruzb** [comment]
Había intentando lo que dice ahí, de todas maneras muchas gracias Matías y Pato.
Tuve que volver a bajarme el repositorio entero no más.
