### ISSUE TITLE
Error: KeyPressEvent no detecta arrow keys

### ISSUE THREAD

**Issue by vicentemartintarud** [IIC2233-2016-1/syllabus#526]
De un momento a otro el keyPressEvent dejó de detectar mis arrow keys.
Ayuda por favor!

**Comment by aaossa** [comment]
Primero, debes averiguar en que momento dejan de detectarse. Ocurre cuando presionas la barra espaciadora? Después de usar un botón? Funciona normalmente y sin apretar otra tecla de repente falla? Funciona nunca y hace unos commits funcionaba? 

Revisa eso, es la forma de detectar donde se produce el comportamiento inesperado. Lo que escribiste es demasiado amplio y no podemos ayudarte con algo así sin mas información :(. Cuando descubras en que momento dejan de detectarse los eventos, pregunta aquí :grin:

**Comment by vicentemartintarud** [comment]
Funciona nunca, estoy revisando los commits. Pero pensé que quizás alguien podría saber por qué pasaba. Gracias.

**Comment by aaossa** [comment]
Puede ser que el focus se está pasando a algún widget distinto de donde tienes definido el keyPressEvent. Por ejemplo, puede ser que el focus esté en un botón, donde no tienes definido el evento, entonces nunca sabrás qué está haciendo el usuario :worried: Hay una par de issues con soluciones posibles a esto. Si no pillas el commit en el que te funcionaba trata de implementar lo de esas issues

**Comment by aaossa** [comment]
Revise tu código. Si te fijas bien, cuando apretas "Iniciar" y usas las flechas, se mueve el foco sobre los botones. Tus opciones son:
- que el foco se mantenga solo en donde quieres (ve las otras issues), ó
- que una vez que presiones un botón, el foco vuelva al widget que quieres. 

Espero que esto te sriva :grin:

**Comment by vicentemartintarud** [comment]
Estaba leyendo las otras issues y me sirvieron.
Muchas gracias!
