### ISSUE TITLE
malloc error [T05]

### ISSUE THREAD

**Issue by fcorencoret** [IIC2233-2016-1/syllabus#527]
Para mover las burbujas, uso un while con un time.sleep de 0.05 y luego muevo las burbujas, lo cual me corre bien pero las burbujas se mueven lento. Si achico el time.sleep efectivamente se mueven mas rapido , pero me salen estos errores. Que deberia hacer? Alguien sabe como solucionar esto?

<img width="768" alt="screen shot 2016-06-01 at 11 05 36 pm" src="https://cloud.githubusercontent.com/assets/17628128/15732733/00a6bc18-2856-11e6-9dd0-25f116f88af3.png">

<img width="602" alt="screen shot 2016-06-01 at 11 09 35 pm" src="https://cloud.githubusercontent.com/assets/17628128/15732761/47173fd8-2856-11e6-9e75-c80ce377ded2.png">

<img width="1099" alt="screen shot 2016-06-01 at 11 08 18 pm" src="https://cloud.githubusercontent.com/assets/17628128/15732789/6d5a5586-2856-11e6-8b2d-a3d8b49da6ea.png">

**Comment by mjjunemann** [comment]
En vez de un sleep, puedes disminuir lo que se mueve en x e y aka la velocidad o aumentar si es necesario

**Comment by bjassael** [comment]
Tenía este mismo error, y era porque estaba moviendo la labels al nivel del thread.  Ahora las muevo en el gui mandando una señal desde el thread para moverlas. Con esto se arreglo.

**Comment by caackermann** [comment]
Tus clases son QThreads? Yo tenia ese error y se soluciono al cambiar los QThreads por Timers como indican en #506. Asi no tienes que ocupar sleep ni while y funciona mucho mejor.

**Comment by aaossa** [comment]
Todos esos errores se relacionan con el manejo de memoria que hace Python de los objetos de PyQt y el manejo que hace C++ por debajo. PyQt está construido encima de Qt, de forma que cada clase en C++ de Qt tiene una clase wrapper en Python con la que tu trabajas, pero por debajo esta clase está llamando a un objeto en C++. Los errores que tienes se pueden producir porque creas objetos en Qt que Python borra (por ejemplo, creando un QWidget en una variable que será borrada) o porque accedes a un objeto que está en otro thread (lo que dice @bjassael ), es lo que se me ocurre. Revisa bien tu código, quizás estás haciendo una de esas dos cosas.

Lectura sobre esto: [**PyQt. How to shoot yourself in the foot**](http://enki-editor.org/2014/08/23/Pyqt_mem_mgmt.html)

**PD:** Con esto se relaciona el error que a algunos les ocurría en #497

**Comment by FranciscoRencoret1** [comment]
@caackermann perfecto, pero como identificas esa burbuja en el main ? pq segun yo no se puede enviar un parametro en una señal cierto?

**Comment by fcorencoret** [comment]
@aaossa lo hize ahora como muestran en la ayudantia, hize exactamente el mismo codigo pero ahora se me ve todo laggeado...

**Comment by aaossa** [comment]
Podrías probar con QTimers, como sugieren en #524

**Comment by aaossa** [comment]
@FranciscoRencoret1  Pudiste resolver esto? Hiciste algún cambio? Quizás puede servir para #541

**Comment by bregonesi** [comment]
@FranciscoRencoret1 usas osx? Me paso lo mismo (#506) y en clases pregunte por que se ve lageado con QTimers y osx, pero nadie sabe. No soy el único, en clases había otra persona con osx y con el mismo problema, pero también tengo amigos que le funciona bien. Al parecer es un problema de osx 10.11 nomas.
Lo que yo hice fue instalar windows como maquina virtual y hacer ahi la tarea. El mismo código funciona perfecto en windows pero lagueado en osx.
