### ISSUE TITLE
[ADMINISTRATIVO] Feedback AC09

### ISSUE THREAD

**Issue by dtfuller** [IIC2233-2016-1/syllabus#528]
Hola! 

Estaba revisando si tengo algo que recorrejir, y me di cuenta de que no tengo el feedback de la AC09. Si me lo pueden subir sería espectacular. 

Gracias de antemano y saludos!

**Comment by Hernan4444** [comment]
Aprovecha la issues para comentar lo mismo, tampoco tengo feedback de dicha actividad.

Gracias de antemano!!

**Comment by aaossa** [comment]
Voy en camino!

**Comment by aaossa** [comment]
Listo @dtfuller y @Hernan4444 :grin:

**Comment by Hernan4444** [comment]
Gracias :+1:

**Comment by jneyzaguirre** [comment]
a mi tampoco me llego!

**Comment by perojas3** [comment]
A mi no me habia llegado hasta ayer, pero lo comente en mi repositorio y en 3 horas me entregaron mi feedback. Tal  vez deberian comentaro en sus respectivos repositorios.

**Comment by dtfuller** [comment]
Muchas Gracias :+1: 

P.S.: Lo puse acá porque (como Jaime Castro me comentó en su momento) en general los ayudantese no revisan los issues de los repos de los alumnos.

**Comment by aaossa** [comment]
Para comodidad de todos, **lo mejor es que hagan una issue acá**, por si hay más casos como ahora, **o que manden un mail con copia a los jefes (a todos)**. Para nosotros, cualquier método es preferible por sobre enviar un mensaje personal a algún jefe sin copia a los demás, por un tema de transparencia y coordinación entre nosotros, o responder/abrir issues en sus repos privados (**NO se revisan las issues de sus repos**)

**PS:** Listo @jneyzaguirre

**Comment by jneyzaguirre** [comment]
gracias antonio!
