### ISSUE TITLE
Problema al leer subastasfin y subastasact

### ISSUE THREAD

**Issue by cdonoso** [IIC2233-2016-1/syllabus#53]
Estimados tengo un pequeño problema al leer esos 2 archivos. Cuando quiero extraer los productos y el historial solamente me lee como:
"productos" :[
"historial" :[
y no entiendo porque no toma los otros valores (los productos y el historial) siendo que estos también forman parte de i.

Saludos!

**Comment by ifcarrera** [comment]
Hola!, por la forma en que está escrito el archivo .txt, parece que no forman parte de i

**Comment by otro-felipe** [comment]
Primero que todo **NO PONGAS CODIGO DE TU TAREA EN LA ISSUE.**

Segundo, y con respecto a tu duda, esto pasa por la forma en la que esta escrito el archivo. Al leer el archivo linea a linea, la primera linea de productos es `"productos" :[` y lo que sigue despues se encuentra en las siguentes lineas.

Tercero, como recomendacion: nunca empieces los nombres de variables con mayuscula (esto reservalo solo para las clases). Es una convencion que hace que tu codigo sea mas legible y bonítido. Para saber mas sobre las convenciones que se usan en python puedes ver [pep8](https://www.python.org/dev/peps/pep-0008/).
