### ISSUE TITLE
Instalar PyQt4 en mac 

### ISSUE THREAD

**Issue by Pochoclo** [IIC2233-2016-1/syllabus#530]
Hola, tuve un problema con mi pc y lo mande al servicio tecnico, y me consegui otro (mac), estoy intentanto instalar PyQt4 pero no me da resultado, estoy tratando de instalar brew y se demora infinito, necesito que alguien me de algunos tips para instalarlo, estoy en los domos de enfermería por si hay algún alma cerca que me pueda ayudar por favor!

**Comment by santiagocruzb** [comment]
Esto me funcionó perfecto
https://github.com/IIC2233-2015-2/syllabus/wiki/Mac-OSX

**Comment by Pochoclo** [comment]
gracias, ya lo pudimos resolver, parece que el problema era la conexión a internet jajajaj :smile:
