### ISSUE TITLE
Mágica desaparición de Burbujas D:

### ISSUE THREAD

**Issue by fnquinteros** [IIC2233-2016-1/syllabus#532]
Hola!
Me está pasando con las burbujas que al rebotar justo en la esquina de la pantalla, esta ignora completamente su rebote y se va al infinito... Al principio tenía modelado el movimiento de las burbujas de manera que si se tocaban con una linea en la parte baja de la pantalla, rebotaban, así que pensé que ese era el problema... Pero resulta que me di cuenta que ahora lo tengo modelado distinto y las burbujas cambian el sentido de su movimiento una vez que uno de sus atributos adquiere un valor definido por mi (es decir, ya no tiene nada que ver con la linea de abajo de la pantalla), así que ya no se que puede estar ocurriendo... :sweat:

**Comment by aaossa** [comment]
Quizás tienes mal una condición simplemente. Trata de ver qué pasa con los valores de las coordenadas y de los factores que usas en tus cálculos. 

**PS:** Traté de ver tu código, pero tu último commit es de hace 3 días y no creo que sea el mismo código que tienes hoy

**Comment by fnquinteros** [comment]
actualicé el código. En todo caso creo haber resuelto el problema así que cierro la issue

**Comment by fnquinteros** [comment]
Actualicé el código. En todo caso si fuese un problema con una condición desaparecerían en cualquier circunstancia, pero solo desaparecen al rebotar justo en las esquinas inferiores de la pantalla
