### ISSUE TITLE
Sobre las conecciones

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#534]
Tengo problemas sobre como conectar el precionar una tecla con(en el frontend) con el backend. Cada vez que se lo pregunto a alguien del curso me dice que tengo que hacer una coneccion o signal, o lago haci. Pero no entiendo a lo que se refieren.
Me dijieron que hast hubo una ayudantia de eso, pero no lo recuerdo, o estoy totalmente perdido.

Lo he buscado en google, pero tal parece que eso se puede referir a muchas cosas. Así que no se a cual de esas es.
¿A que se refieren con eso de las conecciones.?

**Comment by santiagocruzb** [comment]
Para el tema de apretar teclas no es necesario hacer conecciones. Solo definir los pasos a ejecutar dentro del keyPressEvent

``` python
import sys
from PyQt4 import QtGui, QtCore

class Example(QtGui.QWidget):

    def __init__(self):
        super(Example, self).__init__()

        self.initUI()

    def initUI(self):

        self.setGeometry(300,300,250,150)
        self.setWindowTitle('Event handler')
        self.show()

    def keyPressEvent(self, e):

        if e.key() == QtCore.Qt.Key_Escape:
            self.close()
        elif e.key() == QtCore.Qt.Key_A:
            #ejecutar alguna accion del backend
            print('apretando a')

def main():

    app = QtGui.QApplication(sys.argv)
    ex = Example()
    sys.exit(app.exec_())

if __name__ == '__main__':
    main()
```

**Comment by perojas3** [comment]
Ok gracias.

**Comment by cggutierrez** [comment]
me pasa que si intento (siguiendo con el ejemplo) `e.key == QtCore.Qt.Key_Down` o cualquier otra de las flechas no me las reconoce
Es problema de mi computador o sospechan que me falta algo o hay algo mal? las demás si me las reconoce :/

**Comment by aaossa** [comment]
Quizás el ejemplo de #499 pueda servirte, ahí se usan señales :+1:
