### ISSUE TITLE
Mostrar cambios en QLabel.setPixmap

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#535]
Cuando se presiona la tecla para disparar (por ejemplo), me gustaría que el personaje hiciera una animación de 2 frames de esa acción. Para eso, mi intención era setear QLabel con setPixmap con el path de la imagen a cargar. El problema es que, si bien parece que hace el cambio, la interfaz solo termina mostrando la última imagen solamente, pasando por alto la intermedia ¿alguien que haya logrado hacer esto para el movimiento, por ejemplo, que me diga como lo abarcó? Llevo dandole vueltas al asunto por varias horas pero no se me ocurre cuál es el problema. Al principio hacia que el personaje mismo hiciera el cambio, y luego lo cambié para que la interfaz hiciera el cambio, pero ambas resultan en los mismos

**Comment by JoseRomeroi** [comment]
tengo exactamente el mismo problema, y no se como solucionarlo

**Comment by santiagocruzb** [comment]
A mi me resultó haciendo un thread que fuera el disparo, y cada tiempo iba cambiando el porte del QLabel (a la larga iba siendo un rectángulo que iba agrandándose hacia arriba y mi pixmap era un cuadro rojo). El tema del pixmap, tuve que ir actualizando el QLabel con triggers en el frontend porque me tiraba el error típico manejos fuera de la interfaz

**Comment by MortizDX** [comment]
O sea, que algo en el back-end le manda una señal al front-end o al revés te refieres?

**Comment by santiagocruzb** [comment]
Claro. En el backend tengo todo el juego y a través de triggers mando las señales para hacer los cambios visuales en el frontend.

**Comment by MortizDX** [comment]
Es que implementé el mismo código del ejemplo de la ayudantía para actualizar la posición de los labels y en eso todo bien.

Para actualizar la imagen, seguí la misma idea, solo que en vez de usar "move" (para mover el label en el front ese caso), puse el setPixamp allí, pero pasa lo que mencioné al principio ¿hiciste algo diferente?

**Comment by santiagocruzb** [comment]
Es casi lo mismo. Solo que tienes que pasarle ademas el pixmap.
Pero puede ser que si estas haciendo eso bien, tengas problemas de dejar corriendo el thread?

**Comment by JoseRomeroi** [comment]
@MortizDX Pudiste solucionarlo?

**Comment by MortizDX** [comment]
@santiagocruzb Eso he hecho, sigue saltando directamente a la última imagen en una trancisión. Y no sé si sea por eso, a menos que pase lo mismo en QTimers.

@JoseRomeroi No, que además me quedan varias cosas que hacer de la tarea así que lo deje de lado, ¿y tú?  :/

**Comment by santiagocruzb** [comment]
También hice que en cada iteración del thread, mi disparo se mueve una cantidad de espacios. Después de cada movida, actualizo el label y cuando llega al techo, para.
