### ISSUE TITLE
Error al crear burbujas después de matar una

### ISSUE THREAD

**Issue by jneyzaguirre** [IIC2233-2016-1/syllabus#536]
Como sabemos, al "matar" una burbuja, deberían aparecer dos más de menor rango. Mis burbujas son QThread, y al achuntarle a una, lo que intento hacer es enviar una señal a otra clase para poder crear estas burbujas. El error que me tira es el siguiente:

QObject::setParent: Cannot set parent, new parent is in a different thread
QPixmap: It is not safe to use pixmaps outside the GUI thread

Lo busque, y lo que dice principalmente es que no puedo crear un thread afuera del principal. Lo que pensé hacer es que la señal que la burbuja envíe al morir llegue a mi ventana principal y ahí se creen las otras dos burbujas. El problema es que para hacer esto necesito importar el modulo de la "ventana principal" en el modulo de los "personajes"; y para crear las burbujas necesito importar el modulo de los "personajes" a la "ventana principal", lo que tira error al cerrarse en un circulo.
Una solución que pensé, pero me pareció un poco chanta (y no creo que sea la idea) es que todas las burbujas estén creadas desde el principio, pero en la medida que mueren unas, aparecen las otras.

Saludos, y desde ya gracias

**Comment by santiagocruzb** [comment]
```
# importar el backend suponiendo que las clases están en módulos distintos
class Frontend:
    def __init__(self):
        self.numero = 4
        self.backend = Backend(self)

class Backend:
    def __init__(self,frontend):
        self.frontend = frontend
        print(frontend.numero)

Frontend()
```

De esta manera puedes tener guardado el frontend en el backend, sin necesidad de importarlo directamente. Al momento de instanciar las burbujas, vas a tener el parámetro para anidarla en el frontend.

**Comment by jneyzaguirre** [comment]
Ahí lo solucione, era un problema al definir el trigger finalmente.

Gracias igual!
