### ISSUE TITLE
Botón exit

### ISSUE THREAD

**Issue by JoseDaroch** [IIC2233-2016-1/syllabus#539]
Buenas,
hasta hace poco me funcionaba perfecto el botón de exit, pero hice algunos cambios (varios) y no lo probé hasta ahora. Funciona correcto con el mouse, pero con el teclado corre hasta que pongo sys.exit(), de hecho justo ahí no ejecuta el sys.exit(), es la única parte a la que no llega el programa.
Alguna idea? 
Gracias!

**Comment by flobarrios** [comment]
Hola ! Haz un push a tu repo y dime en que parte se esta generando el problema para revisarlo!

**Comment by JoseDaroch** [comment]
@flobarrios listo, es en el main, en salir_juego(), que esta conectada con el boton y ademas se activa cuando apreto g, se ejecuta exactamente hasta la parte de sys.exit(), donde entra en una especie de loop (el 'chao' si corre)

**Comment by flobarrios** [comment]
Ok lo veo ahora!

**Comment by flobarrios** [comment]
Hola! cambia el `sys.exit()` por `os._exit(0)` y debería funcionar. Lo encontré [acá](https://bytes.com/topic/python/answers/156121-os-_exit-vs-sys-exit). Saludos!

**Comment by JoseDaroch** [comment]
Sii! ahí si, había buscado pero parece que no se buscar jaja :(, gracias
