### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by jtagle2** [IIC2233-2016-1/syllabus#540]
Hay alguna forma de desactivar solo algunos errores del PEP8? Por ejemplo, que me pida que un método sea estático, o que sea en lowercase. Que para esta tarea, solo molestan, porque lo que interpreta como un método estático, es en ralidad un método que se llama en una señal, y si lo hago estático no funciona.
Si no se puede, da lo mismo, era por comodidad nomás.
Saludos

**Comment by cggutierrez** [comment]
una vez pille eso googleando "pep8 pycharm" fue un googleo muy ligero asi que lo pillaras de una
(se que es poco util mi comentario, pero si no lo haz hecho te puede servir mientras no te conteste alguien que sepa directamente :D)

**Comment by aaossa** [comment]
Esto es... PyCharm? Y te recomiendo no usar `ñ` en Python, puede que no funcione en otros pcs.

**Comment by cggutierrez** [comment]
@aaossa googlie con pycharm porque queria ver si habia una opcion para que pycharm corrigiera pep8 automaticamente (soñar es gratis)

**Comment by ivaniadg** [comment]
@cggutierrez pycharm lo hace. Yo formateo mi código de esa forma. En Pycharm lo puedes activar o desactivar (incluso por partes). Debes ir a settings, code style.
