### ISSUE TITLE
Error cuando tengo 2 burbujas

### ISSUE THREAD

**Issue by tsuarezsaieh** [IIC2233-2016-1/syllabus#541]
Todo funciona bien hasta que se cae el programa y me dice: "Python(9274,0x700001cb5000) malloc: **\* error for object 0x7f86167e5290: pointer being realloc'd was not allocated
**\* set a breakpoint in malloc_error_break to debug"

**Comment by aaossa** [comment]
Quizás te sirva #527

**Comment by tsuarezsaieh** [comment]
No entiendo como usar QTimer! Ahora estando QThread.msleep() me deja hacer lo con dos bubujas pero cuando agrego un elemento extra muere con el mismo error! Ayuuuuuudaaaa!!

**Comment by aaossa** [comment]
Asegurate de estar agregando ese elemento extra desde el thread principal y que la referencia a ese widget no se pierda. Cosas con malloc pasan cuando se pierden cosas en memoria o cuando el thread no ve lo que se supone que existe
