### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233-2016-1/syllabus#542]
Cuando se juega de a 2, si uno muere tiene que esperar a que el otro muera para que ambos revivan con el nivel desde el inicio o le doy un tiempo de muerte y si después de ese tiempo su compañero sigue vivo, el personaje revive (con una vida menos obviamente). y con eso no se repetiría el nivel

**Comment by aaossa** [comment]
Creo que enunciado no especifica un comportamiento específico para esto, así que puedes decidir tú y recuerda justificar esta decisión

**Comment by Hernan4444** [comment]
OK gracias :)
