### ISSUE TITLE
No puedo agregar objetos nuevos a una ventana

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#543]
Tengo el sigiente problema.
No puedo agregar nuevos widget a una ventana ya creada. Solo los que tenia al principio.
Hasta ahora no me afectaba porque en cada nivel definia los objetos al principio, los escondia y los mostraba al final.
Pero mi problema viene ahora que estoy tratando de unir los niveles.
Por ejemplo, no puedo hacer que se pase del nivel 1 al nivel 2 dentro de una misma pantalla, pero puedo programarlo por separado.

**Comment by fgvenegas** [comment]
Te recomiendo que tengas una MainWindow que controle los niveles y a través del método `setCentralWidget()` ir cambiando entre ellos

**Comment by perojas3** [comment]
Lo veo dificil. Lo programe muy parecido a la tarea 2, tengo una ventana principal, y a esta le agrego los widget hijos. Pero a estas alturas no alcanzo ha hacer los cambios.
