### ISSUE TITLE
Vidas compartidas

### ISSUE THREAD

**Issue by fnquinteros** [IIC2233-2016-1/syllabus#544]
Se puede hacer que los jugadores tengan numero de vidas compartidas y que si llega a cero, se pierde la partida? De ese modo si un jugador muere se le resta 1 al numero de vidas y revive pasado unos segundos, a menos que las vidas lleguen a 0.

**Comment by aaossa** [comment]
Del enunciado:

> Notar que si uno de los jugadores pierde **sus vidas** antes que el otro, el que aun tenga vidas deberá seguir jugando solo
