### ISSUE TITLE
Duda pendiente actividad Qt Designer

### ISSUE THREAD

**Issue by bmarinb** [IIC2233-2016-1/syllabus#545]
El día que hicimos esa actividad hubo un problema generalizado, que consiste en que si queríamos crear una nueva ventana para el pago en efectivo, no podíamos crearla, sino que teníamos que tenerla creada desde un comienzo pero escondida, ya que de lo contrario al crearla se cerraba instantáneamente.

Ahora para la tarea sigo con el mismo problema, quisiera encontrar una forma de poder crear un nuevo widget dentro de la ejecución del uno anterior, sin tener que tenerlo creado desde el principio y luego solo mostrarlo.

**Comment by aaossa** [comment]
Hola, lo siento, me perdí un poco en tu pregunta. Quieres crear un widget en la misma ventana o crear una nueva ventana? Si quieres agregar un widget al layout principal puedes guardar el layout y a este agregarle el nuevo widget.

**Comment by bmarinb** [comment]
Crear una nueva ventana

**Comment by ivaniadg** [comment]
Encontré una solución [aquí](http://stackoverflow.com/questions/16069713/pyqt-window-closes-immediately-after-opening).

Avisa si esto resuelve tu problema  😄

**Comment by bmarinb** [comment]
@indonoso La solución no resuelve mi problema :(  Al ejecutarla abre dos ventanas, la que yo creé (myWindow) y una que se titula python, sin embargo no tengo la menor idea de como acceder a ella.
Al parecer no se entendió bien, pero mi problema es teniendo un widget abierto, abrir otro en otra ventana en respuesta a alguna acción del primero.

**Comment by bmarinb** [comment]
Ya lo comprendí, era un error conceptual mío ya que el widget en sí es una ventana.
