### ISSUE TITLE
Problema al actualizar imagen

### ISSUE THREAD

**Issue by caackermann** [IIC2233-2016-1/syllabus#546]
Cuando mi personaje principal es golpeado por una pelota, deberia cambiar la imagen antes de reiniciar el nivel. Sin embargo, el cambio no alcanza a actualizarse en la interfaz (supongo) ya que si pongo un print despues del set pixmap si lo imprime, pero el cambio no se ve reflejado. Cuando por algun error la etapa no se reinicia correctamente, el cambio del pixmap si se alcanza a ver. Cual podra ser el error?

**Comment by aaossa** [comment]
Quizás el cambio al nuevo mapa ocurre muy rápido, por lo que no alcanzas a ver la imagen que quieres antes de pasar a la nueva etapa. Quizás dejando que la etapa parta un(os) segundo(s) después podrías ver el cambio y luego empezar otra vez.

**Comment by caackermann** [comment]
Le puse un sleep despues de la colision y antes de que se inicie la nueva etapa, lo unico que pasa es que se queda pegado hasta que pasa el tiempo (sin actualizar imagen)

**Comment by caackermann** [comment]
Lo logre solucionar, el problema era que cuando se fuerza un exit, la GUI no alcanza a procesar los cambios de imagenes y por lo tanto no se muestran. Lo solucione pasandole 'app' a la widget y usando app.processEvents() antes de forzar el exit.
