### ISSUE TITLE
Multa y Subasta

### ISSUE THREAD

**Issue by matnagra** [IIC2233-2016-1/syllabus#55]
En el punto 4.1 de la tarea donde salen las estructuras de multas y subastas.
Mi duda es:  ¿Se pueden trabajar las multas y las subastas durante el programa como diccionarios o es obligación tener que incorporarlos en clases?

**Comment by bamavrakis** [comment]
Hola! La tarea evalúa modelamiento orientado a objetos, por lo que debes implementar el sistema y trabajar TODAS las entidades como clases.
Saludos!
