### ISSUE TITLE
Material para la T06

### ISSUE THREAD

**Issue by IsaacConDosA** [IIC2233-2016-1/syllabus#551]
Hola, cuando se subirá la materia de la próxima actividad?
Tengo entendido que la tarea 6 es sobre esa materia, no sé si se puede empezar sin ella.
Saludos

**Comment by RodrigoBocazG** [comment]
Revisa los repositorios de los semestres pasados, [2015-1](https://github.com/IIC2233-2015-1/syllabus) y [2015-2](https://github.com/IIC2233-2015-2/syllabus), ahí ya está el material. Por lo menos hasta que los suban. Suerte!
