### ISSUE TITLE
¿Hay que hacer un chat online?

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#552]
Sobre la tarea 6. No la entendi muy bien.
¿Hay que crear un verdadero chat online?
¿Que se conecta a un servidor y todo?
Es que me confunde eso de TCP/IP.

**Comment by rodolfopalma** [comment]
Exacto, debes crear un programa con arquitectura modelo/servidor que tenga todas las características que salen en el enunciado, una de ellas es la capacidad de crear chats entre amigos.

**Comment by perojas3** [comment]
¿Como?
No entiendo la forma en que desean que lo hagamos.

**Comment by fgvenegas** [comment]
La materia de networking está en el syllabus, con eso y revisando las actividades de los semestres pasados te puedes hacer una idea de cómo debería funcionar el chat que te piden en la tarea, aún así esta materia será evaluada la próxima semana y el próximo lunes habrá ayudantía de esto
