### ISSUE TITLE
Imagenes Blinks filtros.

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233-2016-1/syllabus#554]
En el pdf se explica como trabajar con las imágenes de type color 0 y 2 (blanco y negro y RGB respectivamente), pero muchos imágenes png de Internet están en type color 6 (RGB and alpha) y por ende el procedimiento para aplicar filtros parece que es distinto, porque las imágenes no me quedan iguales que cuando analizo las RGB tradicionales.

Mi pregunta es, ¿Estudiamos por nuestra cuenta e incorporamos un filtro para imágenes de type color 6 o trabajos con puros png type color 2 y 0?

**Comment by flobarrios** [comment]
Hola! Queda a tu criterio pero especificalo en el README. Saludos!

**Comment by Hernan4444** [comment]
ok, muchas gracias :+1:
