### ISSUE TITLE
Cliente / Servidor

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233-2016-1/syllabus#556]
Para esta parte, nuestro servidor debe soportar mas de un cliente conectado a la vez o solo uno que hace todo lo que quiera (mandar mensaje, fotos, publicar en su perfil) y luego otro se desconecta para que entre otro???

**Comment by rodolfopalma** [comment]
Más de un cliente a la vez.

**Comment by Hernan4444** [comment]
Oka, muchas gracias c:
