### ISSUE TITLE
Duda respecto a los filtros

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#557]
En la tarea detallan como funciona el formato png.
Dicen como funciona el chunck de IHDR y el IEND. (Con esos es basicamente copiar y pegar)
Sin embargo, respecto a los IDAT no explica de manera clara como trabajar con ellos.
¿De que manera devo tomar la informacion de los IDAT para poder recivir la cantidad de rojo, azul y verde de un pixel?
¿Y como deberia escribirlo despues para poder dejar los pixeles en blanco y negro, como escribo el promedio? ¿Y que, desde entonces, que cada pixel solo utilize 1 byte para el color, significa que debemos cambiar el tamaño de chunk?

**Comment by aaossa** [comment]
@IIC2233-2016-1/tareos
