### ISSUE TITLE
Problema con serializar

### ISSUE THREAD

**Issue by gantunesr** [IIC2233-2016-1/syllabus#559]
Hola, cuando ejecuto este código:

```
import pickle

image = open('pokeball.png', 'rb')
b = image.read()
print(b)
image.close()
```

Me retorna esto:

![captura de pantalla 2016-06-07 a las 17 33 55](https://cloud.githubusercontent.com/assets/17601467/15875528/b175daa6-2cde-11e6-89bd-7e06ed9f3042.png)

Y me debería salir en este formato (aqui solo muestro los primeros 8 bytes): b'\xff\xd8\xff\xe0\x00\x10JF'

¿Como lo puedo solucionar?

**Comment by aaossa** [comment]
¿Por qué dices que te debería salir el segundo formato? Acabo de tomar una imagen random (internet) y me imprime los bytes: `[137, 80, 78, 71, 13, 10, 26, 10]`

**Comment by gantunesr** [comment]
@aaossa ¿Como lo hiciste? Obtuve el segundo formato al compararlo con otra persona

**Comment by aaossa** [comment]
Hice lo mismo que tu, básicamente:

``` python
with open('pokeball.png', 'rb') as image:
    print(list(image.read(8)))
>> [137, 80, 78, 71, 13, 10, 26, 10]
```

Y si lo imprimo como string:

``` python
with open('pokeball.png', 'rb') as image:
    print(image.read(8))
>> b'\x89PNG\r\n\x1a\n'
```

**Comment by gantunesr** [comment]
Gracias @aaossa, el problema era que cambie de computador en los ultimos dias y el pycharm que estaba usando tenia como interpreter a python2. Estoy viendo para cambiarlo a python3.
