### ISSUE TITLE
El formato de los txt

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#56]
En el enunciado dice que van a probar el codigo con otros txt, pero mi codigo esta hecho para extraer informacion de los txt basado en si encuentra un string(ej: usuario), y luego extrae la informacion basado en la posicion. Por lo que si me evaluan con txt que no tenga exactamente el mismo formato, aunque sea solo un espacio de más, mi programa no podra leerlo adecuadamente.
¿El txt con lo que nos lo evaluan, tiene exactamente el mismo formato?

**Comment by IsaacConDosA** [comment]
Me sumo a la pregunta!! Gracias

**Comment by aaossa** [comment]
Piensa que es un json con el mismo formato. Las llaves deberían llamarse igual, pero los valores serian distintos. Al igual con las listas, los valores serán del mismo tipo pero variara la cantidad de elementos (todos seguirán la misma estructura).

PS: Si esto no es así, que un tareo me corrija :grin:

**Comment by otro-felipe** [comment]
@aaossa yo creo que la pregunta apunta mas a cambiar

```
"usuario": "user"
```

por 

```
"usuario":             "user"
```

Si es asi, el parser debe funcionar sin importar si el json viene incluso escrito en una sola linea para obtener todo el puntaje.
Si es por el tema del nombre de las llaves, estas siempre van a tener los mismos nombres (y los valores van a ser siempre del mismo tipo).

**Comment by MortizDX** [comment]
¿Entonces el espaciado puede variar? Por ejemplo:

`{"fecha_termino":"2016-04-28 18:21:28","id":40136789224,"fecha_inicio":"2016-02-21 20:07:17","precio":177226,"vendedor":"inavarro","productos":[59400132773],"historial":[["salvarado",61759],["zvidal",65217],["iescobar11",73180],["lruiz11",73673],["ataylor11111111",75499]]},{ otro ejemplo similar}, ...`

¿ese ejemplo también cuenta como un json? (sin espacio después del `:`) ¿siempre las las llaves tendrán comillas?

**Comment by otro-felipe** [comment]
Si, eso cuenta como un json. Las llaves siempre tendran comillas, lo unico que puede variar son los espacios en blanco (espacios entre elementos de una lista, entre la llave y el `:`, etc...).
[En este post explican mejor como es la sintaxis en json.](http://code.tutsplus.com/tutorials/understanding-json--active-8817)

**Comment by IsaacConDosA** [comment]
@MainScientist Hola, puede cambiar el orden de las variables?, es decir, que en un lado primero salga "fecha_termino" y después "id", pero que en otra llave aparezca primero "id" y luego "fecha_termino". 
Gracias

**Comment by otro-felipe** [comment]
Si, el orden puede ser completamente arbitrario.
