### ISSUE TITLE
Ejemplos material de clases

### ISSUE THREAD

**Issue by IsaacConDosA** [IIC2233-2016-1/syllabus#560]
Hola, estoy leyendo el material de networking, pero no me funcionan los ejemplos, como que en la parte de sockets, por ejemplo, el código se queda detenido eternamente en socket.accept(). Y así me pasa con diferentes ejemplos, ¿qué estoy haciendo mal?
:cry:

**Comment by fgvenegas** [comment]
Para correr ese ejemplo necesitas trabajar con 2 archivos python y 2 consolas al mismo tiempo ! 

**server.py**

``` python
import socket

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)#esto crea un socket para una conexión TCP con IPv4
host = socket.gethostname()                           
port = 1234 
s.bind((host,port))     # este método "enlaza" el socket a un puerto dado, en este caso el puerto 80
s.listen(5)             #aquí le pedimos al sistema operativo que empiece a escuchar por potenciales conexiones al socket, el argumento 
                        #corresponde al número máximo de conexiones pendientes permitidas

cont = 0
while True:
    #aquí establecemos la conexión
    socket_cliente, address = s.accept()      
    print("Obtuvimos una conexión desde %s" % str(address))
    socket_cliente.send("{}. Hola nuevo amigo!\n".format(cont).encode("ascii"))
    socket_cliente.close()
    cont += 1
```

**client.py**

``` python
import socket
s_cliente = socket.socket(socket.AF_INET, socket.SOCK_STREAM)#esto crea un socket para una conexión TCP con IPv4
host = socket.gethostname()#obtiene el nombre de la máquina local
port = 1234
s_cliente.connect((host,port))
data = s_cliente.recv(1024)
print(data.decode('ascii'))
s_cliente.close() 
```

(Le cambie el puerto comparado con el ejemplo)

Luego en una consola corres **server.py** y en otra **client.py** y veras la magia 1313 (tiene que ser en ese orden)

Avisame si te funciona!

**Comment by ifcarrera** [comment]
Ahhh supuse que era algo así. Respecto a eso tengo dos dudas más (perdón):
- _"este método "enlaza" el socket a un puerto dado, en este caso el puerto 80"_, ¿por qué dice el puerto 80 si en realidad es el puerto que tú definas?

- y segundo, me apareció el siguiente error cuando intenté ejecutar client.py:
![error server](https://cloud.githubusercontent.com/assets/17582083/15882408/96a2642a-2d14-11e6-92d1-fca9946c4ceb.png)

**Comment by IsaacConDosA** [comment]
Ahhh supuse que era algo así. Respecto a eso tengo dos dudas más (perdón):
- "este método "enlaza" el socket a un puerto dado, en este caso el puerto 80", ¿por qué dice el puerto 80 si en realidad es el puerto que tú definas?

En realidad era solo una jaja

**Comment by aaossa** [comment]
Sobre tu error, seguramente en algún momento corriste el server y cerraste mal el proceso, por lo que Windows ve que aún está el servidor en el puerto. Asegúrate de cerrar todos los procesos de Python y de cerrar debidamente los programas que corras.

**Comment by IsaacConDosA** [comment]
@aaossa  sí sí, ya arreglé eso, me funciona el ejemplo. Muchas gracias :smile:

**Comment by fgvenegas** [comment]
Sobre el puerto, si, existen un numero de puertos (que no recuerdo pero son muchos) libres para que tu puedas utilizar y otros que se encuentran restringidos, deberia salir mas detallado en el material eso.

**Comment by IsaacConDosA** [comment]
Pero el puerto 80 que aparece ahí comentado, está mal eso? por que en el material lo intentan con el puerto 10001

**Comment by fgvenegas** [comment]
Es probable que el 80 sea un error en el material nomas, deberia decir 10001

**Comment by IsaacConDosA** [comment]
Perfecto, muchas gracias :smile_cat:

**Comment by aaossa** [comment]
Si quieres comprobar que en verdad hay una conexión esperando en el puerto que le digas puedes usar:

```
$ netstat -a | grep <puerto>
```

Como podrás notar, cuando el server está escuchando debería decir algo como:

```
 TCP     <ip_local>:<puerto>   <direccion_remota>    LISTENING
```

que son el protocolo, la dirección local, la dirección remota y el estado de la conexión encontrada. Si tu server no está funcionando, es posible que el output sea ninguno

**Comment by mandrade2** [comment]
Hola al tratar de usar este ejemplo obtengo el siguiente error.

[WinError 10061] No connection could be made because the target machine actively refused it

Creo que es por algo del firewall de windows pero ni si quiera apagandolo me funciona. Esto es cuando ejecuto al cliente , el server si me funciona en otro computador. Que estoy haciendo mal? Saludos

**Comment by aaossa** [comment]
Prueba ambos códigos en el mismo computador. También podrías usar otro puerto, quizás está siendo usado para otra cosa

**Comment by tblatrille** [comment]
Me falla al probarlo con el wifi de la U,  me da:
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
pero con el 3G del celuar o el wifi de mi casa si funciona, podrá ser?

**Comment by fgvenegas** [comment]
si haces 

``` python
host = "127.0.0.1"
```

en vez de 

``` python
host = socket.gethostname()  
```

cambia?

**Comment by mandrade2** [comment]
me funciono haciendo 

`s.bind(("",port))`

en el server. Gracias!
