### ISSUE TITLE
Consultas sobre material de sincronización.

### ISSUE THREAD

**Issue by iavasquez1** [IIC2233-2016-1/syllabus#561]
En el material de sincronización me quedaron dudas respecto a lo siguiente:

``` python
json_string = '{"nombre":"Jorge","edad":34,"estado_civil": "casado", "puntaje" : 90.5}'
print(json.loads(json_string,parse_int=float)) 
```

Cuando hacen `parse_int` ¿cómo el programa sabe que se le tiene que aplicar al objeto json_string?. 

Además tengo una duda respecto a otro código de la guía:

``` python
json_string = '{"nombre":"Jorge","edad":34,"estado_civil": "casado", "puntaje" : 90.5}'
datos = json.loads(json_string, object_hook = lambda dict_obj: [tuple((i,j)) for i,j in dict_obj.items()])
print(datos)
```

¿Cómo el programa en la función lambda sabe que se refiere al `json_string` mencionado sobre la variable datos?.

**Comment by aaossa** [comment]
De la [documentación de Python](https://docs.python.org/3.4/library/json.html#json.loads):

> **`json.loads(s, encoding=None, cls=None, object_hook=None, parse_float=None, parse_int=None, parse_constant=None, object_pairs_hook=None, **kw)`**
> Deserialize `s` (a str instance containing a JSON document) to a Python object using this [conversion table](https://docs.python.org/3.4/library/json.html#json-to-py-table).
> 
> The other arguments have the same meaning as in load(), except encoding which is ignored and deprecated.
> 
> If the data being deserialized is not a valid JSON document, a ValueError will be raised.

En el primer caso sabe porque el primer parámetro de la función es un string que efectivamente contiene un JSON válido. 

Siempre es interesante y una buena idea [ir a ver el código de Python](https://hg.python.org/cpython/file/default/Lib/json):
- `json.loads(json_string, object_hook = lambda dict_obj: [tuple((i,j)) for i,j in dict_obj.items()])`, llama a `json.loads()`, que se encuentra en la librería de [json.py](https://hg.python.org/cpython/file/default/Lib/json/__init__.py#l271) de Python.
- Puedes ver en el código [lo que retorna](https://hg.python.org/cpython/file/default/Lib/json/__init__.py#l332), `return cls(**kw).decode(s)`, que corresponde al método `decode()` de la clase `JSONDecoder`. 
- Vamos a [`JSONDecoder`](https://hg.python.org/cpython/file/default/Lib/json/decoder.py#l253), donde en el método `decode()` se llama a `raw_decode()`: `obj, end = self.raw_decode(s, idx=_w(s, 0).end())`. 
- Vamos a [ `raw_decode()`](https://hg.python.org/cpython/file/default/Lib/json/decoder.py#l345), donce se usa `obj, end = self.scan_once(s, idx)`, correspondiente al módulo [scanner.py](https://hg.python.org/cpython/file/default/Lib/json/scanner.py).
- La función lambda que le das es llamada [aquí](https://hg.python.org/cpython/file/default/Lib/json/scanner.py#l37): `return parse_object((string, idx + 1), strict, _scan_once,`**`object_hook`**`, object_pairs_hook, memo)`.
- [Notemos](https://hg.python.org/cpython/file/default/Lib/json/decoder.py#l327) que `parse_object` corresponde a un [`JSONObject`](https://hg.python.org/cpython/file/default/Lib/json/decoder.py#l1), el cual parsea el string.
- Una vez que genera el diccionario a partir del string, simplemente hace:

``` python
pairs = dict(pairs)
if object_hook is not None:
    pairs = object_hook(pairs)
return pairs, end
```

por lo que la función es aplicada sobre el diccionario que se hizo a partir del string.

Volviendo a `parse_int`. Podrás ver que [aquí](https://hg.python.org/cpython/file/default/Lib/json/decoder.py#l323) y luego [aquí](https://hg.python.org/cpython/file/default/Lib/json/scanner.py#l48) se decide cómo parsear los valores.
