### ISSUE TITLE
Duda Sal

### ISSUE THREAD

**Issue by Meaylwin** [IIC2233-2016-1/syllabus#562]
En la tarea 6, al encriptar una contraseña de un usuario que se quiere registrar se debe concatenar con una sal generada, en mi caso con urandom(), y luego para iniciar sesion, se debe concatenar la sal utilizada al encriptar la contraseña con  la contraseña no encriptada ingresada por el usuario que quiere iniciar sesion. Supongo que esta sal debe guardarse en el archivo .json para luego poder compararse, pero .json no permite escribir bytes.
¿Cual es la mejor forma para guardar los bytes generados en el archivo y despues utilizar la sal como byte para concatenar con la contraseña ingresada al intentar iniciar sesion?
Lo que yo hice fue guardarlo como str en el archivo, pero despues no se como volver a utilizarlos como bytes y poder concatenar.

**Comment by Meaylwin** [comment]
Despues de buscar mucho encontre una solución, la dejare por aqui por si a alguien mas le pasa
http://www.diveintopython3.net/serializing.html
Pero con la solucion me surge una duda, en el archivo {usuarioschats}.json, actualmente guardo las contraseñas y los sal como bytesarray, ¿no hay problema con eso?

**Comment by rodolfopalma** [comment]
Nosotros te pasamos dos archivos en formato json para poblar inicialmente el sistema. Eso no implica que para implementar la persistencia tu también debas hacerlo de esa forma, de hecho queda a tu criterio como hacerlo (no te sientas amarrado a usar json). Una forma de hacerlo es a través de `pickle` como se explica en el link que mandaste. Si es que quieres usar `json` podrías serializar los bytes (datos binarios) con `base64`.

**Comment by cggutierrez** [comment]
Aun tengo dudas con el encriptado de la contraseña!
Según entendí, hay que  crear un urandom en el servidor y comparar las contraseñas encriptadas que tiene el servidor con las que manda el usuario usando la sal que contiene el servidor, pero entre mas leo los issues mas me confundo
 Podrían aclararme profavor? Gracias!!

**Comment by rodolfopalma** [comment]
@cggutierrez todas las verificaciones son en el lado del servidor, el usuario no conoce su sal.

**Comment by cggutierrez** [comment]
Eso lo tengo claro, el problema es que no entiendo bien como funciona el sistema de encriptado, por si me podrias explicar las etapas del log in un poco mas allá de lo que esta en el enunciado o que es lo que entiendo mal de mi comentario anterior porfavor :cry:

**Comment by spiza** [comment]
Permiso..

La cosa es así. El usuario accede a blink, y al momento de registrarse se guarda en el lado del servidor, toda su información más su sal, y su contraseña encriptada, tal como indica el enunciado. Luego cuando el usuario quiere ingresar, pone su username y su pass, y esos dos se envían al server. 

En el server se verifica si existe ese username, y si este existe, entonces se saca la pass encriptada, y también la sal. Con la contraseña que envió el usuario, esta se encodea, y se le suma la sal, para posteriormente pasarla por la misma función de hash. Por último, se compara el resultado obtenido, con la pass encriptada. Todo esto del lado del servidor.

Se entiende?

Enviado desde mi iPhone

**Comment by cggutierrez** [comment]
Si, perfecto. Entonces para los usuarios que nos dieron a poblar tenemos que darles una sal por nuestra cuenta y luego guardarlos en el mismo formato que los recién registrados para luego al volver a abrir el programa saber la sal de cada usuario?

**Comment by spiza** [comment]
Eso es lo que yo creo! Lo que puedes hacer, es que al momento de ejecutar el server, ver si existen o no los usuarios en la base de datos del server. Si existen entonces copi, y si no existen, entonces como dices tú.

**Comment by cggutierrez** [comment]
Buena! Muchas gracias! No esta muy especificado en el enunciado por eso mis dudas, si algún ayudante puede confirmar esto para todos estaría mas que feliz ajajaj

**Comment by rodolfopalma** [comment]
Es como @spiza dijo, gracias!

**Comment by JoseRomeroi** [comment]
@rpalmaotero me quedo una duda, quise mantener mi base de datos en formato json, pero al serializar la contraseña encriptada con base64.b64encode me tira el siguiente error:

TypeError: '_hashlib.HASH' does not support the buffer interface

**Comment by rodolfopalma** [comment]
@JoseRomeroi `b64encode` recibe un string de bytes, asegúrate de estar pasándole ese tipo de dato.
