### ISSUE TITLE
MidTerm

### ISSUE THREAD

**Issue by jtagle2** [IIC2233-2016-1/syllabus#564]
Será posible que suban la prueba a alguna parte (las preguntas)? Que ya no recuerdo bien que preguntaban, y no se si tengo que recorregir algo. Por favor :)

**Comment by andresfdezc** [comment]
Hola! Pronto subiremos la pauta de la prueba que incluye el enunciado, una posible solución y la distribución de puntaje por cada pregunta.

**Comment by camiolguin** [comment]
hasta cuando se puede recorregir?

**Comment by aaossa** [comment]
El plazo no 100% oficial es **hasta el viernes**. Se les enviará un aviso pronto confirmando esto o con la nueva fecha en caso de cambiar

**EDIT:** Ahora es 100%. Hasta el viernes a las 17:00

**Comment by perojas3** [comment]
El viernes 17?

**Comment by andresfdezc** [comment]
@perojas3 Sí

**Comment by perojas3** [comment]
Una cosa más ¿Como devo abrir los archivos Ipynb?

**Comment by fgvenegas** [comment]
Los puedes ver directos desde el [syllabus](https://github.com/IIC2233-2016-1/syllabus/tree/master/Interrogaciones)
