### ISSUE TITLE
Duda método hashlib.sha256

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2233-2016-1/syllabus#565]
Hola! Mi duda es la siguiente: probando el método, me di cuenta que podía aplicar el mismo método sobre la misma secuencia y no obtener el mismo resultado dos veces (de la forma que dice el enunciado y también con la misma cadena), porque de hecho, cuando hago la comparación, me aparece que no son iguales. También cuando imprimo los objetos hash, tienen un tamaño distinto. ¿A qué puede deberse?
Muchas gracias
Saludos!

**Comment by IsaacConDosA** [comment]
estas aplicando la misma "sal" en la comparacion?

**Comment by AlfonsoIgnacioV** [comment]
Sí, la misma...

**Comment by aaossa** [comment]
Revisa bien lo que le das. Si estas aplicando la misma función, con el mismo string, debería darte el mismo resultado.

**Comment by AlfonsoIgnacioV** [comment]
Lo vi un par de veces, es lo mismo. Es un código de prueba (no es parte de la tarea), lo dejo:

``` python
string = 'soy_un_string'
string = string.encode('latin-1')
print(string)

sal = os.urandom(10)
salstring = sal + string

print(hashlib.sha256(salstring) == hashlib.sha256(sal + string))
```

**Comment by aaossa** [comment]
Bueno, si imprimes la representación de cada objeto veras que son distintos, pero si imprimes `hexdigest()` de cada uno veras que son iguales.

Ademas, para comparar estos hashes la forma segura es comparar los hexdigest mediante el método de hmac `hmac.compare_digest(a, b)`

**Comment by JoseDaroch** [comment]
@aaossa Una duda, por que cuando intento guardar una diccionario con pickle.dump(usuario_x) en que el usuario tiene la contraseña encriptada con el hash pero sin aplicarle hexdigest(), y luego intento hacerle pickle.load a ese diccionario guardado, me tira el siguiente error:
NEWOBJ class argument has NULL tp_new error

Funciona perfecto si guardo la contraseña encriptada con el hexdigest(), pero aun así quede con la duda de por que el error
