### ISSUE TITLE
duda P3.b Midterm

### ISSUE THREAD

**Issue by IsaacConDosA** [IIC2233-2016-1/syllabus#567]
Hola, tengo una duda respecto a la pregunta 3.b del midterm. 
¿Por qué es necesario ocupar zip o min para el largo de la lista? 
Si la funcion map, cuando recibe dos iterables, por defecto aplica la función tantas veces como sea el largo de la lista más chica. O no?
Saludos

**Comment by bmarinb** [comment]
map rellena la más chica con Nones

**Comment by IsaacConDosA** [comment]
En la documentacion de Python dice: 

>  With multiple iterables, the iterator stops when the shortest iterable is exhausted. 

Si rellenara con None, tiraría error si quiero multiplicar los elementos de dos listas, estaría multiplicando int*None, pero no es así

**Comment by bmarinb** [comment]
Tienes razón, en Python 2.7 es como dije. En el 3.5 termina con la más corta.

**Comment by andresfdezc** [comment]
Hola! Tienes razón, no es necesario en Python3. Puedes enviar a recorregir tu midterm si lo deseas y revisaremos tu respuesta en particular.
