### ISSUE TITLE
Servidor y Cliente

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233-2016-1/syllabus#568]
Viendo actividades de otros semestre me di cuenta que el servidor era al mismo tiempo una persona que se conectaba como cliente, para esta tarea ¿también tiene que ser así?, o podemos aislar al servidor en un modulo python que solo actúa como servidor y si esa persona quiere acceder desde el mismo pc tendrá que abrir otro python que es el cliente?

**Comment by rodolfopalma** [comment]
La idea es hacerlo de la última forma: que sean dos programas que corran por separado.

**Comment by Hernan4444** [comment]
Wena gracias :+1:
