### ISSUE TITLE
Dudas sobre la lectura de imágenes.

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2233-2016-1/syllabus#569]
Hola! 
1. En los archivos de imagen muchas vecs aparecen más chunks de los que aparecen en el enunciado, por ejemplo uno que se llama gAMA tEXt, etc. ¿Esos los ignoramos?
1. Además, no sé cómo obtener los tamaños de cada uno de los chunks. Se supone que todos ellos traen la info del tamaño en cuatro bytes, pero lo cierto es que a veces la información, de los cuatro  bytes está en una sola (por ejemplo, en un archivo si leía los bytes del tamaño, ABCD, me daba un número del orden de los cien millones), en cambio leyendo sólo D me daba 13 para el IDHR, que es el correcto. ¿Cómo se sabe si el tamaño vendrá en el último byte solamente o vendrá en 2 o más de ellos?

**Comment by Hernan4444** [comment]
Hola, no soy ayudante pero ese problema yo lo tuve y me di cuenta del error.
No puedes leer los bytes del tamaño ABCD asi nomas, tienes que hacer 

```
a  = ABCD
a.to_bytes(4, byteorder="big")

```

Ahi te aparecera el numero correcto, generalmente cuando es pequeño, los 3 primeros bytes son ceros y el siguiente es el tamaño, justo como te dio a ti con el 13 en el byte D. Pero cuando el numero sea mas grande utilizara los otros bytes, asi que mejor usar siempre el metodo que escribi antes. Por lo menos asi se me soluciono todo.

**Comment by AlfonsoIgnacioV** [comment]
Ok, muchísimas gracias! :)

**Comment by IsaacConDosA** [comment]
@AlfonsoIgnacioV pudiste solucionar lo de los gAMA?? También me aparecen :/
