### ISSUE TITLE
login chekeado en el cliente?

### ISSUE THREAD

**Issue by mhaacke** [IIC2233-2016-1/syllabus#570]
por lo que lei en el enunciado se da a entender que la verificación del login se hace por el lado del cliente y no por el lado del server, quiero verificar si esto es así ??

**Comment by mjjunemann** [comment]
No, la verificacion del usuario debe hacerse en el servidor!

El usuario manda su contraseña al servidor y este verifica, luego manda un mensaje al cliente con la respuesta de que es incorrecta o correcta y actua según esto.
