### ISSUE TITLE
duda con la pregunta 4a

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#571]
En la pregunta 4a del midterm preguntan la analogía entre la asincronía del ultimo texto, con el multi-threading.

El problema que tengo es que en la pauta dice debimos haber explicado la relación entre el rendevouz con el join y el arbiter con el lock, pero en el enunciado no se pide explicitamente hacerlo, lo que me confunde. Yo pensé en poner lo del arbiter con el lock, pero lo considere innecesario porque no me lo pedían.

Esta pregunta es para el examen. ¿Hasta que punto tenemos que detallar lo que nos preguntan en una pregunta de redacción escrita? ¿Cuánto es demasiado?. En este ejemplo, ¿cómo se suponía que debía saber que debí responder con el arbiter-lock también?

Tengo entendido que poner cosas de más se puede interpretar como si estuviéramos adivinando, lo que se debería puntuar como incorrecto. Y es esto lo que me acompleja.

**Comment by fgvenegas** [comment]
Hola, en la pregunta se pide relacionar ideas del texto con conceptos de multithreading, lo que se esperaba al leer el texto era que entendieran los 2 mecanismos de los que se habla y como estos están relacionados con conceptos como Join y Lock, no es que sea demasiado o innecesario esto sino que era a lo que iba enfocado el texto y por ende la pregunta, por lo tanto era lo preciso para tener buena la pregunta. En general no es que una pregunta este buena o mala por escribir más o menos, lo importante es responder lo que se te está preguntando

**Comment by IsaacConDosA** [comment]
Ya pero aun así la pregunta pudo estar un poco ambigua; personalmente escribí una plana completa, y solo tuve 3 puntos, realmente escribí respondiendo a lo que preguntaban según mi interpretación.

**Comment by fgvenegas** [comment]
Como dije anteriormente, el escribir mas o menos no era un factor en la cantidad de puntaje, yo corregí la pregunta y habían alumnos que en respuestas breves mencionaban los conceptos y los explicaban correctamente, insisto, si leían el texto y lo entendían deberían haber sido capaces de relacionar los mecanismos con la materia que habían visto.
