### ISSUE TITLE
Descomprimir IDAT

### ISSUE THREAD

**Issue by jtagle2** [IIC2233-2016-1/syllabus#572]
Una pregunta, que quizás es muy básica.
Al leer un idat (el de la imagen de mickey mouse) me da un bytearray de 15000 bytes, y al descomprimirlo me dan 799528 bytes. Supongo que está mal, si cada pixel es de 3 bytes (RGB) y tengo 479x556 pixeles (o sea, 798972 bytes supongo). Tengo 2 preguntas.
1.- Si tengo una imagen de 10x10 pixeles, debería esperar tener 300 bytes al descomprimir? (para dar un ejemplo mas simple jajajaja)
2.- Si es así, como hago para descomprimirlo bien? Estoy haciendo zlib.decompress(idat), y me da un numero erroneo de bytes
Saludos

**Comment by vjmoreno** [comment]
Hola, yo también tengo una pregunta, ¿Podemos asumir que las imágenes que se utilizarán tendrán solo 1 chunk IDAT? Lo pregunto porque una vez que comprimo los chunks IDAT no vuelven a tener el mismo tamaño inicial, por lo que no sé como volver a armar los chunks con los nuevos bytes.

**Comment by rodolfopalma** [comment]
@jtagle2 Cada fila del IDAT parte con un byte adicional que corresponde al filtro usado en esa línea (más información aquí: https://www.w3.org/TR/PNG/#4Concepts.EncodingScanlineAbs), por lo tanto el número de bytes que debería tener los bytes descomprimidos de un IDAT son `alto * (ancho * 3 + 1)`.

@vjmoreno Citando la especificación de PNG (https://www.w3.org/TR/PNG-Chunks.html)

> There can be multiple IDAT chunks; if so, they must appear consecutively with no other intervening chunks. The compressed datastream is then the concatenation of the contents of all the IDAT chunks.

No entendí bien qué es lo que te complica, dime si algo no quedó claro.

**Comment by vjmoreno** [comment]
@rpalmaotero , mi problema es el siguiente:

Para las imágenes con más de 1 chunk IDAT lo que estoy haciendo básicamente es:

1) Concatenar las secciones de información de los chunks IDAT.
2) Descomprimir.
3) Editar.
4) Volver a comprimir.

Pero el tamaño 4) es diferente al de 1), por lo que no se como volver a armar los distintos chunks IDAT.

**Comment by jtagle2** [comment]
Gracias!
No cierro la issue porque hay otra persona preguntando.
Saludos

**Comment by IsaacConDosA** [comment]
@rpalmaotero  holaa, me pasa lo mismo que @vjmoreno, cuando vuelvo a comprimir una imagen ya editada, el tamaño de cada chunk cambia considerablemente, entonces hay un error cuando creo los bloques completos

**Comment by rodolfopalma** [comment]
@vjmoreno @ifcarrera si escriben un chunk `IDAT` siguiendo la misma estructura de siempre (`largo + "IDAT" + bytes_comprimidos + CRC`)?

**Comment by IsaacConDosA** [comment]
@rpalmaotero Sí, estoy haciendo eso mismo, aunque tengo dudas con el CRC, se calcula con crc32 usando solo el data??

**Comment by IsaacConDosA** [comment]
@rpalmaotero específicamente lo que me cambia es el largo de los `bytes_comprimidos`, antes de formar el bloque completo ya me cambió el tamaño de los bytes

**Comment by rodolfopalma** [comment]
@ifcarrera en #555 se habló sobre el cálculo del CRC

**Comment by bmarinb** [comment]
@rpalmaotero Cuando intento filtrar una imagen con varios IDAT, después de que hago todo lo relacionado al filtro ¿Puedo meter toda la información en un solo IDAT?
Estoy haciendo eso y si bien puedo abrir la imagen los resultados son absurdos, entonces no sé si tendrá un error mi código o si tengo que reescribir la imagen con el mismo número de IDATs
PD: Me funciona bien para las imágenes de 1 IDAT

![piano](https://cloud.githubusercontent.com/assets/17581426/16173759/393e023c-3582-11e6-8253-907cb0f0a887.png)
![piano grises](https://cloud.githubusercontent.com/assets/17581426/16173761/3fcf0416-3582-11e6-89f0-bb09f40ab321.png)

**Comment by FernandoPieressa** [comment]
Yo tengo un problema no se porque el comando no me esta funcionando bien de descomprimir, si tengo el idat de la imagen de la tarea y hago esto:

``` python
idat = data
print(len(idat))
a = decompress(idat)
print(len(a))
b = compress(a)
print(len(b))
```

El output me sale:

```
18264
799528
12379
```

No entiendo como me puede bajar tanta la cantidad al comprimir nuevamente

Edit: Aunque baje la candidad igual se puede ver la imagen bien que se crea, pero al agregar el filtro el compress baja aun mas a menos de 2500, y ahi entrega una imagen destruida que pesa 1/5 de lo que pesaba antes, no se cual es el problema

**Comment by cataschaufler** [comment]
Hola! Al usar decompress y compress de la idat de la imagen (sin aplicar ningun filtro) la imagen se guarda pero totalmente destruida... funciona para Mushroom.png pero al hacerlo con MickeyMouse.png no pasa nada y solamente leo la informacion y la escribo nuevamente haciendo decompress(idat) y luego compress sin aplicar filtros. Alguien tuvo este problema con decompress y compress? Gracias
