### ISSUE TITLE
Dudas con configuración de firewall para python

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#573]
He intentado durante varias horas hacer funcionar los ejemplos de TCP de networking del material de clases y también del código dado en #560, y ninguno me ha funcionado, dandome generalmente el "WinError 10061" por el lado del cliente. Así que me puse a configurar el firewall para permitir a python. El problema es que al principio me aparecía 2 veces en la lista de programas, ambos deseleccionados pero con una red habilitada en cada caso. 

Así que seleccioní ambos en cada caso (en ambos computadores) y corrí de nuevo los programas, dandome "TimeoutError: WinError 10061" generalmente en el cliente. Reviso de nuevo los firewalls... pero ahora me aparece 4 veces python en el computador que hace de servidor, y los 2 nuevos aparecen tal como indiqué anteriormente.

¿Me pueden explicar qué está pasando? ¿O qué debo configurar para hacer que funcionen las conexiones?
![firewall_1](https://cloud.githubusercontent.com/assets/14007315/15994811/7f19d3a8-30dc-11e6-99f5-6b7645b6c7a8.png)

**Comment by aaossa** [comment]
Estas iniciando el servidor antes que el cliente?

**Comment by MortizDX** [comment]
Sip, cada vez que lo he probado con cada código.

**Comment by aaossa** [comment]
Te pasa con exactamente el mismo código? Logro reproducir el error solo si el servidor no está corriendo. El programa del servidor se mantiene ejecutándose?

**Comment by MortizDX** [comment]
He estado probando con el ejemplo de envío de datos json del material, sólo cambinado:
`server_host = "" #poner aquí la dirección ip del servidor` de la parte del cliente, pero ahora no estoy seguro si solo eso debo modificar :/

**Comment by aaossa** [comment]
Si no lo modificas te funciona?

**Comment by MortizDX** [comment]
Si no modifico nada (corro ambos códigos tal cuál aparecen en el material), me sale en el cliente que "Error: no pudo conectarse". Quitando el try y su excepción, veo que el error es "OSError: [WinError 10049] La dirección solicitada no es válida en este contexto"

**Comment by mjjunemann** [comment]
No has logrado correr ninguna vez el ejemplo?, o puedes correrlo una vez y luego deja de funcionar?, se me ocurre que tus procesos de python no se cierran correctamente.

La dirección del host para efectos de prueba no deberia cambiar, dejala en 127.0.0.1, y lo que deberia cambiar es el PORT, elige 8000, y si no funciona anda cambiando.

**Comment by MortizDX** [comment]
Hice correr los ejemplos de la ayudantía en un solo PC y corren bien. Aún no lo he probado en 2 computadores y ese era mi problema.

Lo de la dirección del host me confunde bastante: pensaba que había que poner el IP de uno allí para crear el servidor ¿no es así? ¿de dónde sale el 127.0.0.1?

**Comment by fgvenegas** [comment]
Si quieres conectarte entre distintos Pc's debes hacer que el cliente se conecte a la IP del pc que tiene al servidor. 
127.0.0.1 hace referencia al localhost, es como una manera de decir "este computador" ~~ste men~~ y en general es la direccion que se usa siempre por defecto cuando estas corriendo cosas en tu mismo pc
