### ISSUE TITLE
¿En que consiste la historia?

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#574]
El chat dice algo de la historia de los binks.  Y luego autodestruirlos. Eso no lo entiendo. ¿Que tiene que hacer un usuario para agregar un bink a la historia, y autodestruirlo?

**Comment by Hernan4444** [comment]
No soy ayudantes pero por lo que se entiende son dos cosas distintas. Una cosa es enviar un blink al estilo snapchat, es decir le envias la imagen a alguien (de forma privada) y le das un tiempo. Esa persona solo podrá ver la imagen durante ese tiempo y luego se elimina todo dato de esa imagen.

Otra cosa es la historia de los blink que se puede entender como tu "muro de facebook" ahí publicas tus fotos las cuales siempre quedaran ahí.

Si estoy mal, que un ayudante me corriga para cambiar la modelacion a tiempo.
