### ISSUE TITLE
Filtros funcionan solo con algunas Imagenes

### ISSUE THREAD

**Issue by Zanfor** [IIC2233-2016-1/syllabus#575]
Hola, mis filtros (casi todos pero en particular byn y sepia), funcionan solo con algunas imágenes png, no con todas. De hecho algunas las transforma en unas rayas raras. Por ejemplo con el toad sale bonito pero con la imágen de naruto queda la escoba. Qué podrá ser? 
![no entiendo](https://cloud.githubusercontent.com/assets/17620265/15995103/7f602894-30eb-11e6-9c41-ee56791dd0f8.png)

**Comment by Hernan4444** [comment]
En este issues #555 se publico una foto que explica que los png pueden estar en diferentes colores, puede ser que esa imagen esta en otro formato dentro de png que el algoritmo que usamos no funciona.

**Comment by Zanfor** [comment]
ok gracias
