### ISSUE TITLE
Tipos de bloques

### ISSUE THREAD

**Issue by IsaacConDosA** [IIC2233-2016-1/syllabus#576]
Hola, leí una imagen `png` (mushroom del semestre pasado), pero hay algunos bloques que no son `IHDR` o `IDAT.` En particular son `gAMA` o `cHRM.` Creo que estoy leyendolos bien. 
En otra issue a alguien también le pasa. ¿Qué hay que hacer con esos bloques? Saludos

**Comment by rodolfopalma** [comment]
Puedes ignorarlos! Mientras manejes bien `IHDR`, los `IDAT` e `IEND` no deberías tener problemas.
