### ISSUE TITLE
soporte para emojis, como implementarlo?

### ISSUE THREAD

**Issue by mhaacke** [IIC2233-2016-1/syllabus#577]
como se debe implementar los emojis? 
vi que en los semestres pasados ocuparon rich text con html pero intente replicarlo y al parecer no quiere funcionar  y en el mismo post del semestre pasado dice que al parecer no funciona en mac aunque no queda claro ya que no lo responden directamente dejo el link por si acaso 
https://github.com/IIC2233-2015-2/syllabus/issues/504
gracias de antemano :d

**Comment by perojas3** [comment]
En la tarea 2 hacemos algo similar con labels. Puedes usar eso con labels de imagenes en vez de textos.
