### ISSUE TITLE
Lectura y modificacion de imagenes

### ISSUE THREAD

**Issue by JoseDaroch** [IIC2233-2016-1/syllabus#578]
Hola,
He estado hace un buen rato tratando de leer las imágenes png y modificaralas según se pide en la tarea. Intente con la actividad del semestre pasado pero se me complico más de la cuenta con el tema de que aparecen más chunks, no se obtener bien los datos y tampoco capto bien como ordenarlos después en caso de lograr modificarlos. Busque harto pero solo encontré información en donde trabajaban siempre con librerías que al parecer no podemos usar.
Por eso ahora pregunto por acá a ver si alguien podría darme algún indicio? :(
Gracias!

**Comment by santiagocruzb** [comment]
https://github.com/IIC2233-2016-1/syllabus/issues/555 Ahí sale más o menos lo que se tiene que hacer (los chunks extras no sirven, y la actividad del semestre pasado es clave: es donde más información sale)

**Comment by JoseDaroch** [comment]
Gracias, creo que ahí logre hacerlo, pero por casualidad se te demora años? :/

**Comment by santiagocruzb** [comment]
Nada, itero no mas de 4 veces una lista y eso seria
