### ISSUE TITLE
Acerca de condiciones de la Tarea 7

### ISSUE THREAD

**Issue by dtfuller** [IIC2233-2016-1/syllabus#579]
Hola! Con respecto al anuncio de la inscripción de la tarea 7, se que en algún momento se comentó al respecto, pero me surgen nuevas dudas. 
- ¿Cuál va a ser el plazo para hacerla? 
- ¿En términos de dificultad, es la misma que las tareas normales?
- ¿Si nos inscribimos, estamos obligados a hacerla? 
- ¿Van a liberar el enunciado justo desúes de la T06 (como han venido haciéndolo todo el semestre)?

Saludos y gracias de antemano!

**Comment by negebauer** [comment]
Te adelanto una respuesta

> ¿Si nos inscribimos, estamos obligados a hacerla?

**Si**

**Comment by FernandoPieressa** [comment]
Sumo una pregunta:

De que materia seria? ya no queda mas según los contenidos del curso que sale en el git

**Comment by bamavrakis** [comment]
Hola! 
- La tarea se publicará el Viernes 17, y el plazo será hasta el Jueves 23.
- Si se inscriben están obligados a realizarla. Considerar que esta nota reemplazará su peor nota, independiente si es peor que su peor nota (por ejemplo, si mi peor nota es un 3, y en la Tarea 7 me saco un 2, se reemplaza el 3 por el 2)
- La materia que se evaluará será Web Services. Durante el transcurso del día se publicará el material de clases respectivo.

Saludos!

**Comment by dasotosilva19** [comment]
añado otra pregunta: Como se si quedo inscrito en la tarea ? , porque me metí al cuestionario, y sale que en la encuesta vigente (la de la tarea 7) no tiene preguntas, entonces, no sabre si queda marcada mi opción de hacer la tarea o no.

**Comment by agmardones** [comment]
Para cuántos días está pensada que deberíamos hacer la tarea? O en su defecto, cuántos días han dado en semestres anteriores?

**Comment by FernandoPieressa** [comment]
me sumo a la duda de @dasotosilva19 

seguramente es un error y se olvidaron de poner el cuestionario?

**Comment by bamavrakis** [comment]
Hola! Ya fue agregada la pregunta en el cuestionario.
Saludos!

**Comment by dtfuller** [comment]
Muchas gracias, me quedó claro :+1:
