### ISSUE TITLE
Nombre de usuarios 

### ISSUE THREAD

**Issue by IsaacConDosA** [IIC2233-2016-1/syllabus#58]
Hola, en el archivo usuarios.txt, hay personas que puedan tener el mismo nombre? (Obviamente con usuarios y mails diferentes?saludos

**Comment by Geeermy** [comment]
Hola!
Sí, no es raro pensar que dos personas puedan tener mismo nombre y apellido :) por eso mismo se diferencian en el username. Así que sí, se puede (no sé si en el .txt que les pasamos se da ese caso, pero asume que se puede). 
Saludos!
