### ISSUE TITLE
Problema usando QFileDialog

### ISSUE THREAD

**Issue by diegosapunar** [IIC2233-2016-1/syllabus#581]
Uso QFIleDialog para poder abrir un pop-up y seleccionar el archivo .png. (con esto obtengo el path del archivo que selecciona el usuario -- > QFileDialog.getOpenFileName )

Me retorna bien el string con el path, pero ademas me tira los siguientes errores que no entiendo y tras mucho buscar no los he podido solucionar:
1. Qt: Untested Windows version 6.2 detected!
2. log4cplus : E R R O R   N o   a p p e n d e r s   c o u l d   b e   f o u n d   f o r   l o g g e r   ( A d S y n c N a m e s p a c e ) . 
   1. l o g 4 c p l u s : E R R O R   P l e a s e   i n i t i a l i z e   t h e   l o g 4 c p l u s   s y s t e m   p r o p e r l y .

**Comment by aaossa** [comment]
Probé tu código y no me aparece ningún error ni warning. Estás seguro de que son errores o simplemente son warnings? De todas formas lo que encontré de tu error es que es bastante raro, pero si no te permite trabajar lo revisaré mejor :+1:

**Comment by diegosapunar** [comment]
@aaossa Hola! no tengo muy claro lo que es warning... Sin embargo, mi programa no se cae... solo imprime lo que te mande anteriormente en color rojo... y sigue funcionando bien... te escribo algo similar a lo anterior (No es muy importante asique espero que no sea un problema postearla aca):

```
    directory = os.getcwd() + '\pictures'
    ex = '(*.png)'
    path_blink = QtGui.QFileDialog.getOpenFileName(self,"Abri Archivo", directory, ex)
```

Si sigue funcionando... todo bien? jaja

**Comment by aaossa** [comment]
Bueno, **un warning es como una alerta**. No va a parar tu programa, pero te avisa si es posible que tu programa tenga algún problema. Por ejemplo, los warnings se usan cuando una función en un modulo va a ser eliminada o su funcionalidad va a cambiar. 

Entonces, a ti lo que te sale **es un warning**. Tu programa no "se cae", solo te avisa que algo raro pasa. Ponlo en el README que hagas. Mientras no afecte la funcionalidad de tu tarea no deberías tener mayores complicaciones. 

**PS:** Agrega en el README una referencia a esta issue :+1:

**Comment by diegosapunar** [comment]
@aaossa  Gracias Antonio!!!

**Comment by negebauer** [comment]
@diegosapunar  recuerda cerrar el issue si esta resuelto
