### ISSUE TITLE
Problema importando modulos con un path

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#582]
Tengo el siguiente problema. En un modulo estoy definiendo una interfaz grafica importando un .iu creado con qt designer.
El main importa de este modulo. Pero me ocurre el siguente error. Cuando ejecuto la interfaz grafica desde el modulo especifico  se carga de maner adecuada. Sin embargo cuando lo importo desde el main me ocurre el siguiente error:
`FileNotFoundError: [Errno 2] No such file or directory: "{aqui esta el directorio}"`
No se me ocurrio como buscar esto en internet.

**Comment by mjjunemann** [comment]
Puedes postear como estas haciendo los imports y el filetree ? para tener un poco más de información

**Comment by perojas3** [comment]
¿A que te refieres con filetree?
Así es como tengo organizado mi cliente (muesto solo orden, no codigo):
![screenshot](https://cloud.githubusercontent.com/assets/14139107/16030881/05f89fa4-31cc-11e6-8c11-ca7b0b747790.jpg)

El main inporta un modulo cliente que se encuentra en backend. Que lo primero que hace es importar la clase log de modulo log_in  en interfaz. Y es en esa importacion donde me tira error.
log_in.py importa su .ui así: `pantalla = uic.loadUiType("dessing/log_in.ui")`

Cliente importa  de log_in.py así: `from cliente.frontend.interfaz.log_in import Log`

Y el main importa cliente así:  `import cliente.backend.client as client`

**Comment by ivaniadg** [comment]
Hola @perojas3 ,

En `FileNotFoundError: [Errno 2] No such file or directory: "{aqui esta el directorio}"` el archivo que no encuentra es dessing/log_in.ui ?
Si es así, lo que puede estar ocurriendo es que el programa está buscando el path relativo a main.py y no a log_in.py.
Una opción es que main tenga como parámetro el path de la carpeta que tiene las interfaces de tal forma que ese parámetro lo pueda recibir `Log`. La otra opción es directamente escribir el path absoluto.
