### ISSUE TITLE
Duda enunciado: "Soporte para archivos"

### ISSUE THREAD

**Issue by dtfuller** [IIC2233-2016-1/syllabus#584]
hola a todos! 

En la primera página del enunciado de la t6, dice que blink chat tiene "Soporte para envío de archivos". Esto significa que además del envío de imagenes, hay que permitir envíar archivos de cualquier tipo?

Saludos y gracias de antemano ;)

**Comment by rodolfopalma** [comment]
Efectivamente, enviar cualquier tipo de archivo.

**Comment by perojas3** [comment]
Si nos piden enviar un png que no es en verda png, y nuestro programa no esta preaprado para eso. ¿Bajan puntaje?

**Comment by rodolfopalma** [comment]
@perojas3 no, en #555 se dijo que se usarán los mismos tipos de PNGs que en la AC22 del semestre pasado.

**Comment by dtfuller** [comment]
ok, gracias :(
