### ISSUE TITLE
Error del servidor

### ISSUE THREAD

**Issue by cataschaufler** [IIC2233-2016-1/syllabus#585]
Me aparece este error a veces y no puedo seguir  por mucho tiempo sin embargo hay otras veces que no
que es? como lo podria solucionar?
![error servidor](https://cloud.githubusercontent.com/assets/12243719/16067928/a5739e3c-3297-11e6-8117-0af1c6ed4767.png)

**Comment by cataschaufler** [comment]
<img width="988" alt="error servidor" src="https://cloud.githubusercontent.com/assets/12243719/16067954/e60f8dca-3297-11e6-822f-c10813e157a7.png">

**Comment by IsaacConDosA** [comment]
Quizás sea el puerto que ocupas, te pasa si lo cambias?

**Comment by fgvenegas** [comment]
Lo mas probable es que el proceso de Python no se cerro correctamente y el puerto sigue ocupado (asumiendo que corriste el programa y no lo cerraste bien y lo volviste a correr), prueba cambiando el puerto o cerrando los proceso de python correctamente (desde el admin de tareas)

**Comment by cataschaufler** [comment]
Funciono! Gracias!

**Comment by negebauer** [comment]
@cataherrera recuerda cerrar el issue si esta resuelto
