### ISSUE TITLE
Duda codigo T06

### ISSUE THREAD

**Issue by jtagle2** [IIC2233-2016-1/syllabus#586]
Será posible ver a algún ayudante para mostrarle una duda de mi código? Es sobre la modificación de los png. Que al momento de modificarlo, me lo hace bien hasta cierto punto, y después me pone colores que no son (pero los contornos de la imagen siguen estando). Por ejemplo, la imagen de Mickey me queda así:
![resultado2](https://cloud.githubusercontent.com/assets/6934080/16096139/0883ebe0-331e-11e6-9e95-2fac50eee523.png)

O si algún ayudante me puede hacer un pull y verlo, le estaría infinitamente agradecido. Lo dejé con comentarios que explican bien lo que estoy haciendo en las iteraciones, y con algunos prints para ir corroborando algunas cosas (que no se pierdan bytes, que la matriz sea del porte que debe ser, etc...)
Saludos
**EDIT**: Traté de fijar el byte del filtro para la fila en 0 (un amigo me comentó que el hacía esto y le funcionaba), y no me da tampoco. Después lo traté de fijar en 2, y tampoco funciona.
Si lo dejo en 0, me sale:
![resultado2](https://cloud.githubusercontent.com/assets/6934080/16099068/a8ed4ffa-332c-11e6-9653-864a351505f7.png)

**Comment by IsaacConDosA** [comment]
Me sumo a la petición, me queda así la foto editada
![mi_foto](https://cloud.githubusercontent.com/assets/17582083/16096300/abed5f32-331e-11e6-923f-95f9ff390d0c.png)

Habrá sala de ayuda o algo por el estilo? 
Ya intenté de todo, calculé los crc de todas las maneras posibles que indicaron en una issue pasada.

**Comment by JoseDaroch** [comment]
Me sumo, a mi me sale algo enfermo que me da hasta vergüenza mostrar jaja, pero aun así pareciera que hice todo bien.

**Comment by jtagle2** [comment]
@ifcarrera puede ser que estás omitiendo el primer byte de cada fila? Ese que no nos sirve de mucho, pero que igual está. Eso puede hacer que se te vaya corriendo la imagen, ya que cada vez que bajas 1 pixel, se te podría correr la imagen 1 pixel a la izquierda (y por eso, mientras más abajo, más corrida queda), porque te interpreta algun byte de rgb como el byte de la primera columna que tenemos que ignorar. A mi me pasaba algo parecido, y le metí el primer byte de cada fila, y ahora estoy donde ves jajaja.

**Comment by IsaacConDosA** [comment]
@jtagle2 a qué byte te refieres?, estoy guardándolo como `largo` + `tipo` + `data` + `crc`

**Comment by jtagle2** [comment]
@ifcarrera No, me refiero dentro de data. Ejemplo, si tengo una foto de alto 2 y ancho 3, mi data sería:
byte, R, G, B, R, G, B, R, G, B
byte, R, G, B, R, G. B, R, G, B

Pero, si omito el primer byte (el que en la actividad 22 del semestre pasado dicen que no tomes en cuenta), obtengo:
R, G, B, R, G, B, R, G, B, R
G, B, G, B, R, G. B, R, ?, ?
Los signos de interrogacion, son bytes que no alcanzarías a llenar (porque omitiste el primer byte de todas las filas). Pongo ? porque no tengo idea con que se rellenan (0? 255?)
Por lo que, el filtro en la primera columna queda como R, y el RGB, me queda como GBR, y así se van corriendo todos los pixeles. Si llevo esto un alto 100, quiere decir que me corro 100 pixeles en la imagen.
Igual es raro, porque si yo omito ese pixel, efectivamente me queda corrida la imagen, pero como cambio el filtro (o no se que sea el primer pixel), los colores se me cambian completamente, y me queda algo así.
![resultado2](https://cloud.githubusercontent.com/assets/6934080/16096906/750fe22a-3321-11e6-8fe1-036fb211ce27.png)
Feo, pero supongo que ayuda un poco a entender a lo que me refiero.

**Comment by santiagocruzb** [comment]
El primer byte de cada fila no se tiene que tocar y tiene que ir incluida en el idat que vayas a comprimir.

**Comment by jtagle2** [comment]
@santiagocruzb Si sé. Cuando lo incluyo, me queda como la primera imagen, cuando lo fijo siempre en 0, me queda como la segunda. No creo que esté armando mal mi matriz de pixeles, porque la armo, y después uso una función para guardarla. Y si guardo la matriz (los devuelvo a un archivo) sin haber cambiado los pixeles, me sale bien la imagen, por lo que dudo que haya un error al momento de armar la matriz, y luego reensamblarla en el archivo. Cuando a los pixeles les calculo el promedio, es que me sale con esas líneas de color gris.

**Comment by jtagle2** [comment]
Al final era que la foto estaba mala.... Gracias igual!
