### ISSUE TITLE
Posibles errores

### ISSUE THREAD

**Issue by cataschaufler** [IIC2233-2016-1/syllabus#587]
Es necesario indicar cuual fue el error en el caso de que algo ocurra como por ejemplo que no se agregue un amigo por que no existe un usuario? se que seria lo mejor pero no se indica en el enunciado por lo tanto se nos bajara punto si no se indica o da lo mismo?

**Comment by rodolfopalma** [comment]
@cataherrera La usabilidad (que incluye lo que mencionas) va a ser evaluada en la tarea (aparece en el punto 3.1 del enunciado).

**Comment by cataschaufler** [comment]
ok, gracias :)
