### ISSUE TITLE
Horario examen

### ISSUE THREAD

**Issue by vjmoreno** [IIC2233-2016-1/syllabus#588]
Hola, quisiera saber en que horario se desarrollará el examen final del curso, ya que tengo otro examen pronosticado para el mismo día.

**Comment by IsaacConDosA** [comment]
Yo también necesito saber

**Comment by Pochoclo** [comment]
Si!! ese día tengo examen de procesos de manufactura, también necesito saber la hora!

**Comment by tnmarin** [comment]
el examen de procesos de manufactura es modulo 1 y 2, según el programa de este curso el examen de es a las 9:15, por lo tanto existe tope de examenes.¿que se puede hacer?

**Comment by jneyzaguirre** [comment]
yo también tengo examen de procesos de manufactura ese día.

**Comment by aaossa** [comment]
Hola, el examen será el **5 de Julio a las 9:15**. En caso de que tengan tope con otro examen envíen un mail a @jecastro1 (correo: jecastro1@uc.cl)
