### ISSUE TITLE
Sobre la información que ve el cliente

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#589]
Los datos de los mensajes que tiene un usuario (historial de mensajes), así como su "historia" de blinks y cosas así, no las tiene nunca el usuario mismo, el servidor las manda hacia él ¿verdad? Entonces mi pregunta es ¿la idea sería mandar todos esos datos mediante `send()` o hay otro método que desconozco?

**Comment by santiagocruzb** [comment]
Es todo a través de send :/

**Comment by JoseDaroch** [comment]
También tengo una duda en esta parte, el usuario nunca almacena dentro de "su disco duro" los chats que mantiene cierto?, vale decir, el servidor le envía todos los chats que tiene ese usuario cada vez que se conecta ? o el usuario mantiene esta información guardada en alguna parte de su pc?

**Comment by santiagocruzb** [comment]
Se puede hacer todo a través del servidor po. Cada apretada de click es un enviar datos al servidor, y que él después de analizarlos, los reenvía donde sea necesario
