### ISSUE TITLE
Historial subastas

### ISSUE THREAD

**Issue by isarovic** [IIC2233-2016-1/syllabus#59]
Hola! ¿En el historial de las subastas (en el archivo txt ) aparece el usuario con su mejor apuesta, o puede aparecer un mismo usuario varias veces con distintas apuestas?. ¿En caso de que aparezca varias veces, podemos simplemente guardar la mejor de sus apuestas para poder usar un diccionario?

Saludos!

**Comment by bamavrakis** [comment]
Hola! 
Efectivamente, puede aparecer el mismo usuario varias veces con distintas apuestas, y lamentablemente, TODAS las apuestas de un usuario deben guardarse en el archivo.
Saludos!
