### ISSUE TITLE
Plazo tarea 7

### ISSUE THREAD

**Issue by caackermann** [IIC2233-2016-1/syllabus#590]
Hola, quería saber si, ya que se cambio el plazo de la tarea 6 al 21 de junio, el plazo de la tarea 7 sigue siendo el 23 de junio o se va a cambiar?
Gracias

**Comment by jtagle2** [comment]
Podrían dar un par de días más :). O por lo menos desplazar todo, y subir la tarea 7 mas tarde, y que se entregue mas tarde. 
PIEDAD! Es fin de semestre D:

**Comment by abulnes1** [comment]
+1! de lunes a lunes seria un buen ejemplo jajaja

**Comment by spiza** [comment]
+5

Enviado desde mi iPhone

**Comment by dtfuller** [comment]
+6 :)

**Comment by cataschaufler** [comment]
Por favor :(

**Comment by IsaacConDosA** [comment]
+7 Por lo menos para el viernes, una semana legal

**Comment by gdburky** [comment]
+8

**Comment by jneyzaguirre** [comment]
+9

**Comment by agmardones** [comment]
+10, corran el día de subida del enunciadooo!

**Comment by FernandoPieressa** [comment]
Me uno a la duda

**Comment by negebauer** [comment]
les sugiero que usen la reacción 👍 en el primer comentario (de @caackermann ) para no llenar el issue de mensajes sin contenido

**Comment by aaossa** [comment]
+1 a @negebauer

**Comment by bamavrakis** [comment]
La Tarea se va a subir el Lunes y tendrán plazo hasta el Viernes.
Salu7
