### ISSUE TITLE
Problema con recorrección de control 4

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#593]
Mandé a recorregir el control 4 dentro de los plazos establecidos, pero no recibí ningún cambio de la nota ni tampoco alguna notificación sobre como fue revisada. Mandé un correo a la persona que dio el aviso que ya estaban puestas las notas de ese control, pero no he recibido respuesta aún. También se lo comenté a un ayudante ayer, pero nada ¿qué puedo hacer?

**Comment by ivaniadg** [comment]
Las recorreciones están en el buzón del DCC desde el viernes de la semana pasada.
