### ISSUE TITLE
Error 'sendPostedEvents' en la interfaz

### ISSUE THREAD

**Issue by caackermann** [IIC2233-2016-1/syllabus#594]
Hola, me aparece este error:
QCoreApplication::sendPostedEvents: Cannot send posted events for objects in another thread
al momento de crear un usuario, pero el usuario igual se crea de manera correcta. Cual sera el erorr? 
A alguien le ha pasado lo mismo?

**Comment by bceppi** [comment]
@caackermann Hola, encontraste algo? Estoy con el mismo problema..

**Comment by caackermann** [comment]
Si! Yo tengo una clase cliente (que manda los datos al servidor) que se conecta con la interfaz grafica. El problema es que como cliente ocupa threads, la clase cliente no se puede comunicar directamente con la interfaz. Hay que hacer algo como en la tarea 5 con signals para comunicarse desde el cliente con la interfaz, haces que cliente herede de QObject y que tenga una signal que haga emit cuando quieras comunicarte con la interfaz. Hice eso y se solucionaron todos los problemas
