### ISSUE TITLE
Enviar y recibir datos por partes problema

### ISSUE THREAD

**Issue by DiegoSilvaS** [IIC2233-2016-1/syllabus#598]
Hola, para enviar un objeto desde el servidor al cliente me surgio un problema que antes no me pasaba, y de un momento a otro no para de pasar.
Envió el objeto(que esta serializado en pickle) al cliente por partes (con send()) por los objetos de gran tamaño , y el cliente de igual manera lo recibe por partes (recv()) mediante un while(el tamaño de lo recibido sea constante, sigue recibiendo). mi problema es que después de cierta cantidad de iteraciones (a veces ninguna, pero normal mente un par) esta recibiendo las partes como si se hubieran mandado juntas...
esto lo comprobé mediante prints, y si pongo un time.sleep entre cada vez que envio una parte del archivo, el archivo llega bien (pero se demora infinito), es muy raro...

Si a alguien ya le paso, agradecería un consejo.
Encontré una librería que manda todo sin necesidad de hacerlo manual, "nanomsg" se puede ocupar?, o es parte de la tarea hacer esto manual.

**Comment by rmant** [comment]
Como lo solucionaste? Yo tengo el mismo problema! Gracias!

**Comment by DiegoSilvaS** [comment]
cuando lo recibes con  recv("n"), en "n" tienes que poner el mismo numero que la extensión de los pedazos del archivo que envías, o por lo menos eso me funciono.
