### ISSUE TITLE
Ayuda para Setup de git

### ISSUE THREAD

**Issue by aaossa** [IIC2233-2016-1/syllabus#6]
Alumnos, ayer durante la ayudantía nos dimos cuenta de que algunos de ustedes han tenido **problemas fatales** usando git. Entiéndase por problemas fatales:
- No puede usar git desde consola
- Hay un error durante la instalación de git
- Los comandos no funcionan correctamente
- En algún momento aparece un pantallazo azul
- etc

**Cualquier problema que impida que puedan usar git apropiadamente entra en esta categoria**. Por favor, les pedimos que si tienen alguno de estos problemas comenten aquí los siguiente:
- Una descripción de su error
- Sistema operativo (y versión del mismo) de su computador 
- Una foto del error. 

Es necesario que hagan esto porque **desde la próxima clase las entregas serán SOLO vía git**. Vamos a ayudarles pero necesitamos la información que se les pide.

**Importante:** Esta ayuda NO va enfocada a uso de comandos.

**Comment by laurateuber** [comment]
Hola, yo no he podido usar git porque el terminal me tira un error "illegal instruction 4" por todo. Es Mac OSX. 
![captura de pantalla 2016-03-08 a la s 15 23 26](https://cloud.githubusercontent.com/assets/17599967/13611714/ab8dc9ac-e542-11e5-82de-2b0a9406463e.png)

**Comment by negebauer** [comment]
@laurateuber Según lo que vi en Google ese mensaje tiene relación con que el comando git está intentado hacer algo que tú Mac no reconoce. **Que versión de OS X estás usando?** Si no es 10.11 prueba actualizando OS X

**Comment by dasotosilva19** [comment]
Hola, mi problema con git es que al abrir el git bash para poder usar la consola de comandos, me sale una pantalla azul y se reinicia mi computador. Use el reparador de registro del programa "CCleaner" y parece haberse solucionado ya que al abrir el git bash este funciona, pero al cerrarlo y volver abrirlo se vuelve a reiniciar el computador. (la imagen del error es sacada de internet y no un pantallazo ya que no puedo sacarlo al reiniciarse el computador y el sistema operativo es windows 8.1)
![error-pantalla-azul-windows8](https://cloud.githubusercontent.com/assets/14018456/13624691/27222c88-e58f-11e5-9336-77c721fa7c65.jpeg)

**Comment by andresfdezc** [comment]
@dasotosilva19 ¿Puedes probar abriendo el Comando de Símbolo de Sistema (cmd) en vez de git bash? Lo encontrarás si buscas cmd en la barra lateral derecha. Si git está bien instalado también debiese funcionar allí. Avisa si también sale pantallazo azul con cmd.

**Comment by JoseRomeroi** [comment]
El error que me aparece a mi es el siguiente: "git" no se reconoce como un comando interno o externo, tengo windows 10

![image](https://cloud.githubusercontent.com/assets/13740583/13651802/b725ecd2-e627-11e5-9527-29a3467fa43c.png)

**Comment by aaossa** [comment]
@JoseRomeroi ¿Instalaste `git` siguiendo la guía de [Software Obligatorio](https://github.com/IIC2233-2016-1/syllabus/wiki/Software-Obligatorio)? Si lo instalaste, al hacer click derecho dentro de un directorio te aparece una opción "git bash"?

**Comment by JoseRomeroi** [comment]
@aaossa No lo habia descargado siguiendo la guia. Ahora lo hice y me funcionaron todos los comandos, pero al momento de utilizar el git push, me pide usuario y contraseña (supongo que del github). Escribo mi username, luego cuando me pide la clave no me permite escribir, y cuando ejecuto sin escribir nada me dice invalid password

![image](https://cloud.githubusercontent.com/assets/13740583/13653177/d1629aee-e62e-11e5-80e3-c1907bce2138.png)

**Comment by ivaniadg** [comment]
@JoseRomeroi Cuando escribes la clave no aparece nada por seguridad. Ingresa tu clave y presiona enter :D

**Comment by JoseRomeroi** [comment]
@aaossa @indonoso Listo! ahi pude, muchas gracias a ambos

**Comment by JoseDaroch** [comment]
@JoseRomeroi Donde esta la guía? me pasaba lo mismo y creo que igual lo instale mal!

**Comment by JoseRomeroi** [comment]
@JoseDaroch https://github.com/IIC2233-2016-1/syllabus/wiki/Software-Obligatorio
