### ISSUE TITLE
Problema con la version de python

### ISSUE THREAD

**Issue by gbordoni** [IIC2233-2016-1/syllabus#60]
Hola! No se si sea el lugar indicado para este problema, pero no logro hacer que sublime use la version 3.4 de python...sigue usando la version 2.7 que es la del sistema (ubuntu); busque en google y no encontre mucho, y lo que encontre no me ha servido.

Gracias de antemano

**Comment by aaossa** [comment]
Para partir, puedes ejecutar Python 3.4 desde consola? Si es así, con que comando? Puede ser algo como python o python3

**Comment by andresfdezc** [comment]
También puedes probar insertando lo siguiente en la primera línea del archivo que quieras ejecutar:
`#!/usr/bin/env python3`

**Comment by negebauer** [comment]
Lo que pasa es que el build System de sublime es de Python 2
Tienes que crear un nuevo build System que te corta Python 3
Algo como [esto](http://stackoverflow.com/questions/23257984/python3-4-on-sublime-text-3)

**Comment by gbordoni** [comment]
Buena Nicolas, me sirvio! Muchas gracias
