### ISSUE TITLE
Problema con abrir otra ventana

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#600]
Estoy tratando de cerrar la ventana actual y abrir la siguiente en el cliente. El error que me sale ahora es:
`QCoreApplication::exec: The event loop is already running`
Y tal parece que tiene que ver con la linea
`exit(app.exec_())`
La cual no puede ser ejecutada 2 veces(cuando abro la primera ventana, y cuando abro la segunda).
No entiendo como solucionarlo. Si elimino alguno de los 2, se cierra inmediatamente despues de abrirse.
¿Que hago?
Así lo busque:
https://www.google.com/search?sclient=psy-ab&client=firefox-b&q=QCoreApplication::exec:+The+event+loop+is+already+running&oq=QCoreApplication::exec:+The+event+loop+is+already+running&gs_l=serp.3...694834.705509.0.705982.2.2.0.0.0.0.97.160.2.2.0....0...1c.1.64.psy-ab..0.1.91...0i5i30.HS_e1EatMG4&pbx=1&bav=on.2,or.r_cp.&bvm=bv.124817099,d.Y2I&biw=1252&bih=602&ech=1&psi=Rn1oV9-KLY74wAT_l484.1466462006015.3&ei=Rn1oV9-KLY74wAT_l484&emsg=NCSR&noj=1&gfe_rd=cr

**Comment by fgvenegas** [comment]
Has probado usar una MainWindow que controle el programa y mediante el metodo `setCentralWidget` vaya alternando entre las ventanas para mostrar la que corresponda?

**Comment by perojas3** [comment]
No, y no entiendo a lo que te refieres.

**Comment by fgvenegas** [comment]
Para facilitar el cambio la ventana que estas mostrando, una manera practica de hacerlo es que tu ventana principal no sea un Widget sino una MainWindow, la gracia de esta es que posee un metodo llamado `setCentralWidget()` que recibe como parametros el Widget que quieres que se muestre en la pantalla, entonces no tienes que estar cerrando ventanas sino que solo cambias cual es la que quieres mostrar

**Comment by perojas3** [comment]
El problema, es que esto usando Qt dessigner. Y creo una pantalla diferente para cada menu. Una para el login, otra para crear usuarios,etc. El problema que tengo es cambiar entre ellas. Y tengo un problema para agregar signals con argumentos. Me tira error en eso tambien.

**Comment by fgvenegas** [comment]
La solucion que te planteo funciona aunque uses Qt dessigner, y te facilitara cambiar entre las pantallas, te recomiendo que averigues sobre eso

**Comment by jtagle2** [comment]
Lo que puedes hacer es hacer que cada ventana vaya teniendo un parent, y cuando vas a una sección, haces:
self.hide()
self.ventanahijo.show()

Y cuando cierras la ventana hija haces:
self.hide()
self.parent.show()

Es más feo que la solución de fgvenegas, pero supongo que te podría servir
