### ISSUE TITLE
Problema al obtener issues con la API

### ISSUE THREAD

**Issue by vicentemartintarud** [IIC2233-2016-1/syllabus#601]
Llevo un buen rato tratando de obtener las issues del repositorio y el problema es que el request no acepta mis parámetros, siempre obtengo todas las issues que se encuentran abiertas.
Se agradece cualquier tipo de ayuda!

```
`params = {
    "milestone": "",
    "state": "closed",
    "assignee": "",
    "creator": "",
    "mentioned": "",
    "labels": "",
    "sort": "",
    "direction": "",
    "since": ""
}


url = "https://api.github.com/repos/IIC2233-2016-1/syllabus/issues"
req = requests.get(url, params=params, auth=credentials)`
```

**Comment by aaossa** [comment]
Pudiste arreglar esto?

**Comment by vicentemartintarud** [comment]
Si, era porque le estaba entregando data en vez de params.
