### ISSUE TITLE
Duda enunciado T07

### ISSUE THREAD

**Issue by ManuelSIlvaCav** [IIC2233-2016-1/syllabus#602]
Hola tengo una duda respecto a la primera parte del enunciado (3.2.1), no se si entiendo bien pero.... hay que asignar a una persona, dependiendo del label, a la issue en cuestion? si es asi, no me permite asignar personas a una issue, ni siquiera a mi mismo.... 
Si estoy entendiendo mal este parte, alguien me podría clarificar que hay que hacer ?? :c.

Gracias!

**Comment by aaossa** [comment]
Que te responde GitHub?

**EDIT:** Debería ser porque para hacer estas cosas normalmente hay que ser _contributor_, para lo que tendrían que tener ciertos permisos sobre el repo, como hacer push por ejemplo. Si es esto veré que podemos hacer en el [IIC2233/fake_syllabus](https://github.com/IIC2233-2016-1/fake_syllabus)

**Comment by ManuelSIlvaCav** [comment]
pero es lo primero que dije? mi problema es que no entiendo bien este punto.
Si es asignar a una persona como lo hacen en ciertas issues, deberíamos tener push access para asignar personas o no??. sorry lo chato :c

**Comment by rodolfopalma** [comment]
Manuel, la idea es que tu programa tenga un botón que al clickearlo verifique las issues de un repo y asigne usuarios a éstas, de acuerdo a alguna relación entre labels y usuarios. Un ejemplo: si en el repo alguien crea una issue sobre la T8 (con su respectivo label) y tienes definido que las issues sobre la T8 deberán ser asignados a @Syllabot, la próxima vez que se clickee el botón en tu programa se realizará esa acción (asignar @Syllabot a la nueva issue). Se entiende?

**Comment by tsuarezsaieh** [comment]
@rpalmaotero Es suficiente que lo hagamos con un label y un usuario fijos? o tenemos que hacerlo con más labels y usuarios.

**Comment by JoseDaroch** [comment]
tengo la misma duda de arriba, alguien? :(

**Comment by flobarrios** [comment]
Hola ! se debe dar la opción de crear un label y asignar a un usuario. La idea no es que ustedes cuenten con un label "pre-hecho" si no que el usuario que acceda a la interfaz pueda crear un label con el nombre que quiera y asignar a un usuario también elegido por él. Saludos!

**Comment by fnquinteros** [comment]
Y si ya hay labels creadas sin usuarios asignados, debemos asignarles usuarios a esas labels?

**Comment by icontrerasn** [comment]
y con respecto a la parte del enunciado donde dice "Al momento de crear las relaciones, el programa debe verificar que los usuarios que se relacionarán con dicha label puedan acceder al repositorio", esto a que usuarios se refiere específicamente? no me queda muy claro. gracias!

**Comment by flobarrios** [comment]
@fnquinteros queda a tu criterio si los incluyes o partes "desde cero" creando labels nuevos. 
@icontrerasn se refiere a que utilices solo a usuarios que puedan acceder a ese repo (utilizando los usuarios de syllabus no deberías tener problemas). Saludos!

**Comment by icontrerasn** [comment]
@flobarrios  gracias por la rápida respuesta, es equivalente esto a revisar entre los usuarios que pueden ser asignados a alguna label?

**Comment by flobarrios** [comment]
@icontrerasn si eso mismo !

**Comment by tsuarezsaieh** [comment]
No estoy entendiendo, yo pensaba que había que asignarle un usuario a los issues que tenían cierto label. Es al revés entonces? Le ponemos un label a las issues que tienen cierto usuario asignado

**Comment by flobarrios** [comment]
@tsuarezsaieh no, no es al revés. Tu interfaz debe dar la opción de crear labels y asignar a ciertos usuarios (esta info la tienes que almacenar tu localmente). Aparte de eso, una vez que exista el label, este se puede asignar a algún issue (esto no lo debes hacer por la interfaz, simplemente tu o cualquiera desde el fake_syllabus puede agregar esta label a alguna issue para probar tu programa). Finalmente, por la interfaz debes tener un botón para asignar a los usuarios a las issues que tengan los labels que tu hayas creado.

Te dejo un ejemplo:
1. Creas un label "Dudas T07" y me asignas a mi (@flobarrios).
2. Te metes al fake_syllabus, creas una issue y le añades el label "Dudas T07" (a mano ! jaja)
3. Vuelves a ingresar a tu interfaz y haces click al botón "suscribir usuarios" (o como quieras llamarlo).
4. Revisas el fake_syllabus y para la issue que habías creado, debería aparecer yo (@flobarrios) en la parte de asignados.

Espero que haya quedado más claro. Cualquier cosa preguntas. Saludos!

**Comment by spiza** [comment]
Acabo de entender.. Muchas gracias!

**Comment by fnquinteros** [comment]
yo tambien! mil gracias :smile:

**Comment by tsuarezsaieh** [comment]
Una última duda, puedo pedir al usuario que ingrese el nombre del usuario a asignar y después yo lo verifico con la API?

**Comment by flobarrios** [comment]
Si, es una forma de hacerlo.

**Comment by FernandoPieressa** [comment]
@flobarrios  Tengo una duda, actualmente en mi programa cada vez que inicies el programa tienes que hacer las relaciones y te las asigna, sin embargo al cerrar el programa se pierde esas relaciones. La idea es esa o que tambien cree un archivo donde almacene esa informacion para uso posterior?

**Comment by flobarrios** [comment]
@FernandoPieressa debes crear un crear un archivo u otra cosa para guardar la info para uso posterior.

**Comment by jpdattas** [comment]
@flobarrios es necesario que se guarden las relaciones localmente y se muestren? yo hice que se pueden ir agregando relaciones a una lista (una vez agregada no se ve mas) y con un boton se asignan las issues según las relaciones ingresadas... y aparte hice un boton para crear labels. no basta con eso?

**Comment by flobarrios** [comment]
@jpdattas  no se si entendi bien pero lo que dices es que si se cierra el programa y lo vuelvo a abrir, si hago click en asignar issues, tu programa no tendrá guardada ninguna relación a no ser que haga todo el proceso denuevo? Eso esta mal 😢 debes guardar un registro de estas. Saludos!

**Comment by jpdattas** [comment]
ok, gracias :cry:
