### ISSUE TITLE
Obtener issues API

### ISSUE THREAD

**Issue by Zepk** [IIC2233-2016-1/syllabus#603]
Básicamente tengo el mismo problema que mencionan en la #601, pero como cerraron esa issue sin responder la duda, lo pregunto denuevo

Rasulta que no puedo filtrar las issues segun los datos que se mencionan en la documentacion de la API

```
url = "https://api.github.com/repos/IIC2233-2016-1/fake_syllabus/issues"

params = {
    "state": "closed"
}

req = requests.get(url, data=json.dumps(params), auth=credentials)
print_pretty(req.json())
```

Al ejecutar el codigo, sigue arrojandome las issues que están abiertas

**Comment by ManuelSIlvaCav** [comment]
hola a mi me funciono entregando los parametros asi:

``` python
data = {'state' : 'closed'}
req_get = requests.get(url_get, params=data, auth=credentials)
```

en el fondo data = (algo) es cuando estas haciendo un patch o post, mientras que en get normalmente se entrega params o headers (como diccionario nomas sin json dumps) para determinar ciertas condiciones . 
Pd: no soy ayudante asi que puede que este mal xd

**Comment by Zepk** [comment]
Buena, gracias, así si me funciono, estaba seguro de que habia intentado eso tambien, pero seguramente algo habia hecho mal cuando saque los json dumps :)

**Comment by aaossa** [comment]
En `params` se pasan los parametros por medio de la url, lo que pueden verificar imprimiendo `req.url`. En `data` se pasa la información que se necesita enviar en el _body_ de la request, como JSON.

[En la documentación de la API de Github](https://developer.github.com/v3/#parameters) hay un extracto de eso
