### ISSUE TITLE
No puedo editar issues de fake_syllabus

### ISSUE THREAD

**Issue by Zepk** [IIC2233-2016-1/syllabus#604]
No se si sea porque no tengo privilegios para hacerlo, o porque estoy haciendo algo mal en el codigo, pero al intentar editar una issue (cambiarle el titulo) no me deja hacerlo

```
req = requests.get(url, params=data, auth=credentials)
unico = req.json()[0]
unico["title"] = "Archivos enviados en historial de conversacion tipi"
# Intento cambiar el titulo de la issue
url = "https://api.github.com/repos/IIC2233-2016-1/fake_syllabus/issues/595"
plo = requests.patch(url, data=json.dumps(unico))
print(plo.status_code)
```

Al hacer print del status code, tira el numero 404, lo que segun entiendo significa que no tengo acceso al repositorio. La pregunta es, falta que nos den privilegios en este repo para poder editar las coas, o es que estoy haciendolo mal?

**Comment by FernandoPieressa** [comment]
No estoy seguro, pero la idea según yo es que hagas un clon de ese repositorio para poder trabajarlo por tu cuenta y editarlo. Si todos pudiéramos editar el mismo, alguien se podría equivocar y terminar borrando/editando partes que otros usarian

**Comment by aaossa** [comment]
Estamos en eso, @bamavrakis debería resolver esto pronto, pero es porque ustedes no tiene permisos sobre ese repositorio, no son colaboradores :( Como dijo @FernandoPieressa, creamos el repo para que el Syllabus siga intacto

**Comment by ManuelSIlvaCav** [comment]
hola colgandome de esta issue.... para las issues repetidas, el vector IDF como se calcula exactamente?
Estuve averiguando y en wikipedia aparece que se calcula como log[ (numero de issues)/{1 + (issues en las que aparece la palabra) }] para cada palabra del vector TF.... es asi o alguna forma mas facil?

**Comment by aaossa** [comment]
@ManuelSIlvaCav crea otra issue, esa pregunta no tiene nada que ver con la original, así es mas facil en el futuro encontrar respuestas :wink: 

@Zepk, si imprimes el contenido de la request (`req.json()`) puedes encontrar más detalles de la respuesta, mas contenido que solo el _status code_.

**Comment by FernandoPieressa** [comment]
@aaossa 

Una duda, entonces la idea no es clonarlo, sino editar el repositorio publico?

**Comment by aaossa** [comment]
Cambien el público no mas, la idea es que todo ~~el spam que generen~~ lo que quieran probar lo hagan ahí :grin:. Si quieren probar lo de editar una issue o cambiar el título, hagan una por mientras.

Docs:

> # Issues
> 
> ### Edit an issue
> 
> Issue owners and users with push access can edit an issue.

Podrán editar todas las issues del repo cuando les demos _push access_, pero si quieren probar ahora, creen una.

**BONUS:** También una vez que tengan _push access_ al fake_syllabus podrían entretenerse tratando de hacer un commit al repo. Sus repos no se hicieron a mano :wink:

**Comment by aaossa** [comment]
Agregamos a los inscritos en la T7 a un team con _push access_ al fake_syllabus. Aquellos que no tienen este permiso es porque nunca aceptaron la invitación a la organización a comienzos del semestre (:cry:) o no se inscribieron a la T7 (:scream:)

Si les funciona o no les funciona avisen aquí :grin:

**Comment by Snorlax8** [comment]
Ahora me funciona :grin:

**Comment by Zepk** [comment]
@aaossa Como puedo hacer para ver si soy parte del team? Para ver si no me funciona por penca, o porque no soy parte del team

**Comment by FernandoPieressa** [comment]
@Zepk 

https://github.com/orgs/IIC2233-2016-1/teams/tarea-7

**Comment by icontrerasn** [comment]
@aaossa no había aceptado la invitación a principio de semestre y estoy inscrito para la T07, así que creo que no soy parte del team. Podrías agregarme?

**Comment by aaossa** [comment]
Listo, @icontrerasn :+1:

**Comment by jfcumsille** [comment]
@aaossa creo que yo tampoco soy parte! Podrias agregarme tambien?
Gracias!

**Comment by aaossa** [comment]
@jfcumsille tienes que aceptar la invitación a la organización

**Comment by jfcumsille** [comment]
@aaossa jaja no habia cachado, ahi la acepte!

**Comment by AlfonsoIgnacioV** [comment]
Hola! A pesar que soy parte del team, no me deja cambiarlo, me tira el mismo error 400 que se menciona al principio :'(

**Comment by jagaldames** [comment]
sino me equivoco el error 400 es un problema con json, no por no tener acceso, el que dijieron arriba es 404. eso

**Comment by AlfonsoIgnacioV** [comment]
{
    "documentation_url": "https://developer.github.com/v3/issues/#edit-an-issue",
    "message": "Problems parsing JSON"
}
Ese es, me equivoqué...

**Comment by jpdattas** [comment]
Se puede "vericar que los usuarios que se relacionaran con dicha label puedan acceder al
repositorio" viendo los miembros del team? https://github.com/orgs/IIC2233-2016-1/teams/tarea-7

EDIT:lo dije porque tenia un problema pero ya lo solucione jiji

**Comment by JoseRomeroi** [comment]
@aaossa Creo que tampoco soy parte del team, y que por eso nada me funciona. Te envie un mail tambien

**Comment by aaossa** [comment]
Lo acabo de hacer, no es necesario un mail (por si alguien mas lee esto :sweat_smile: ), avisen por aquí

**Comment by camiolguin** [comment]
Hola!  yo aún no puedo asignar usuarios a los issues, creo que es por que no estoy como colaboradora en el repositorio pero si me inscribi para la tarea

**Comment by gdburky** [comment]
@aaossa Creo que no soy parte del team, podrías invitarme 😅 ?

**Comment by aaossa** [comment]
@camiolguin ya estabas en el team al parecer... y ahora @gdburky también lo está :grin:
