### ISSUE TITLE
Recolección T05

### ISSUE THREAD

**Issue by jtagle2** [IIC2233-2016-1/syllabus#605]
Una pregunta.
En las issues de mi repositorio privado, no me aparece la típica issue que aparece cuando recolectan las tareas o actividades con la tarea 5. No me aparece "T05  opened x hours ago by jecastro1".
Esto quiere decir que no me recogieron la tarea? Porque estaba todo  bien de formato y restricciones D: (nombre de la carpeta, plazo de entrega, etc...). Puede ser que al hacer pull no haya recogido la tarea? La carpeta entera pesaba como 2.3mb (entre las imagenes y los códigos)
Saludos

**Comment by bamavrakis** [comment]
Hola! SI se te recolectó la tarea, así que no te preocupes 😀.
Saludos!
