### ISSUE TITLE
Problema Fecha issues

### ISSUE THREAD

**Issue by Zepk** [IIC2233-2016-1/syllabus#607]
Tengo 2 problemas con esto, el primero es que en el enunciado de la tarea dicen que para ver cuantas issues publica cada usuario "considere solo las issues creadas despues del 25 de Mayo", pero en el repo fake_syllabus" todas las issues fueron creadas en la misma fecha, así que no tiene mucho sentido este alcance.

El otro es que al momento de listar todas las issues que se han publicado, para ver que usuario ha creado cada una, por defecto el numero de issues que se pueden ver es de 30, si bien existe un comando `per_page` para aumentar el numero de datos, el limite de este es de 100, por lo que hasta donde entiendo no se podrían ver las 500+ issues que están publicadas en el repo.

Que debo hacer al respecto a estos 2 problemas?

**Comment by aaossa** [comment]
RIP, cierto, para el primer punto extraelas del Syllabus directamente, pero **por favor** prueba tu programa en fake_syllabus :pray: . Lo de responder en una issue solamente allá :+1:

Para tu segundo punto, tienes que leer un poco mas la documentación y ver bien los ejemplos para poder acceder a todas. Te lo diría pero está todo en los docs :confused:.

**Comment by Zepk** [comment]
Vale :)
