### ISSUE TITLE
Recorreccion T03

### ISSUE THREAD

**Issue by cggutierrez** [IIC2233-2016-1/syllabus#608]
Hola, saben cuando estarán listas las recorrecciones de la T03? Necesito ""optimizar"" mi tiempo esta semana y para eso necesito saber la nota de la tarea :cry:

**Comment by cggutierrez** [comment]
:cry:

**Comment by mjjunemann** [comment]
Revisa la issue T03 en tu repositorio.

**Comment by jneyzaguirre** [comment]
A mi tampoco me ha llegado la recorrección de la Tarea (revise mi repositorio).

**Comment by aaossa** [comment]
@mjjunemann @bamavrakis

**Comment by mglambert** [comment]
¿Se subieron las recorrecciones? también mande a recorregir y aun no me sale nada en mi repo.

**Comment by bamavrakis** [comment]
Si! Mira la issue en tu repo :D

**Comment by leylayunis** [comment]
a mi tampoco me sale nada :(
