### ISSUE TITLE
Problema con modulos

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#61]
Tengo este problema.
Quiero hacer un modulo que se importe desde el main.py, dentro de una carpeta llamada usuarios, este modulo lee el usuarios.txt que esta dentro de la carpeta y convierte sus elmentos en una lista de objetos.
El problema es que me tira distintos errores.
Si deseo importar todo el modulo, e dice que no tiene la funcion para leer el .txt.
Y si importo solo la funcion, no detecta la ruta del .txt dentro de la carpeta usuarios.
¿Que hago?

**Comment by fgvenegas** [comment]
Como lo estas importando actualmente?

**Comment by perojas3** [comment]
```
from usuarios.usuarios import clasear_usuarios

if __name__ == "__main__":
    a = clasear_usuarios()
    print(a)


```

clasear_usuarios lee usuarios.txt que se encuentre en la carpeta usuarios. Devueleve la lista con todos los objetos de la clase usuario.

Me sale este error:

Traceback (most recent call last):
  File "C:/Users/Pablo/Desktop/Progra avanzada github/perojas3-iic2233-repo/Tareas/T01/main.py", line 4, in <module>
    a = clasear_usuarios()
  File "C:\Users\Pablo\Desktop\Progra avanzada github\perojas3-iic2233-repo\Tareas\T01\usuarios\usuarios.py", line 46, in clasear_usuarios
    with open('usuarios.txt', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'usuarios.txt'

**Comment by fgvenegas** [comment]
Tienes que recordar que la funcion va a buscar a tu archivo desde donde la estas ejecutando, en este caso la busca en la carpeta donde esta el main.py, entonces tienes que darle el path desde esa carpeta, lo que seria como 

``` python
with open('.\usuarios\usuarios.txt', 'r') as f:  `
    # Resto de tu codigo
```

El `.\` hace referencia a la carpeta donde esta el modulo que estas ejecutando

**Comment by perojas3** [comment]
Ahora me sale otro error:

Traceback (most recent call last):
  File "C:/Users/Pablo/Desktop/Progra avanzada github/perojas3-iic2233-repo/Tareas/T01/main.py", line 1, in <module>
    from usuarios.usuarios import clasear_usuarios
  File "C:\Users\Pablo\Desktop\Progra avanzada github\perojas3-iic2233-repo\Tareas\T01\usuarios\usuarios.py", line 46
    with open('.\usuarios\usuarios.txt') as f:
                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 1-2: truncated \uXXXX escape

**Comment by andresfdezc** [comment]
Recuerda que `open(path, mode)` lleva 2 parámetros. El error que tienes es porque no le estás diciendo a open que abra `usuarios.txt` en modo de lectura.

**Comment by perojas3** [comment]
Se lo puse, pero el error persiste. No puedo abrir el usuarios.txt desde main.

**Comment by fgvenegas** [comment]
Puedes probar con ''./usuarios/usuario.txt'' (use '/' en vez de '\')?

**Comment by perojas3** [comment]
Me funciono, gracias.
