### ISSUE TITLE
Diccionario palabras vector TF

### ISSUE THREAD

**Issue by vicentemartintarud** [IIC2233-2016-1/syllabus#610]
El diccionario de palabras que debemos usar para formar el vector TF  es el diccionario de habla hispana, o solamente el diccionario de palabras que forman el el título más explicación.
Gracias!

**Comment by ivaniadg** [comment]
El diccionario de palabras que forman el título más la explicación. El diccionario lo deben construir con **todas** las issues.

**Comment by MortizDX** [comment]
¿La idea es formar el diccionario solo con las palabras en su forma "base"? ¿O deberían dejarse tal cuál?

**Comment by ivaniadg** [comment]
El diccionario debe formarse con la forma base

**Comment by fnquinteros** [comment]
y con todas las issues o solo las abiertas? no veo el sentido de comentar issues repetidas cerradas (por algo ya se cerraron)
