### ISSUE TITLE
Recibir repos

### ISSUE THREAD

**Issue by jtagle2** [IIC2233-2016-1/syllabus#611]
En la T07, hago un request para ver todos los repositorios de la persona que está usando el programa, y me lee todos los repos, menos fake_syllabus. La request que hago es:
requests.get("https://api.github.com/user/repos", auth=credenciales)
Obtengo todos los repos (syllabus, el mio, el de arquitectura de computadores, pero no me entrega el fake syllabus)
Se supone que tengo que hacer algo desde mi github para que me aparezca?

**Comment by aaossa** [comment]
> ### [List your repositories](https://developer.github.com/v3/repos/#list-your-repositories)
> 
> List repositories that are accessible to the authenticated user.
> 
> This includes repositories **owned** by the authenticated user, repositories where the authenticated user is a **collaborator**, and repositories that the authenticated user has access to through an **organization membership**.

Tu no cumples ninguna de estas condiciones, por lo que no ves el repo en tu request
