### ISSUE TITLE
Participacion de usuario por issue

### ISSUE THREAD

**Issue by Zepk** [IIC2233-2016-1/syllabus#614]
Es una duda pequeña, pero para ver la participación de usuario por issue, tengo que enviar una solicitud de comentarios para cada issue, como son alrededor de 600 issues esto tarda cerca de 5 minutos, por lo que cada vez que se quiera ver la participacion de usuario por issue se tendra que esperar eso.

Las preguntas son 2, para este item no se considera la restricción de que solo se vean las issues con fechas posteriores al 25 de mayo, verdad? (pregunto porque esto haría el proceso mucho mas rápido al ser menos issues).

Para solucionar este problema pensé que lo ,mejor seria cargar todos los datos la primera vez que se pregunte, y luego hacer un dump con pickle para guardar los datos, y así recuperarlos mas adelante, para quitar la necesidad de cargarlos cada vez desde 0 y darle al usuario la posibilidad de actualizar los datos (cargarlos desde git) o utilizar los guardados localmente, y quería saber si esta es una solución valida, o se considera muy ordinaria.

**Comment by ivaniadg** [comment]
Hola @Zepk,
1. Sí se considera la restricción
2. Es una solución válida, aunque sea muy ordinaria :laughing:
