### ISSUE TITLE
Problema al imprimir las requests y pasarle argumentos a get

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2233-2016-1/syllabus#615]
Hola: cuando intento hacer:
    print([dict_ for dict_ in req.json()])

el programa simplemente no imprime nada. Por otro lado, cuando hago:

```
data = json.dumps({'state': 'closed'})
req = requests.get(url, params=data)
```

En un principio el programa me retornaba igual las issues abiertas y no filtraba... 
¿A qué puede deberse esto? Y ahora no me imprime nada :/

Muchas gracias

**Comment by jtagle2** [comment]
Yo para esos filtros, los agregó en la url.
En la url del request, pongo (url)?since=(string con formato de la fecha)
Ahora no estoy con pc, pero creo que estaba funcionando

**Comment by iguridi** [comment]
Parece que no hay que poner json.dumps. Yo le paso el diccionario así nomás y funciona

**Comment by aaossa** [comment]
Busca un ejemplo de como hacer un get, prueba en [la documentación de requests](http://docs.python-requests.org/en/master/user/quickstart/#quickstart)

**Comment by AlfonsoIgnacioV** [comment]
Resuelto :) , era que no me estaba autentificando.
