### ISSUE TITLE
Problema al asignar a issues

### ISSUE THREAD

**Issue by FernandoPieressa** [IIC2233-2016-1/syllabus#618]
Cuando intento asignar alguien a una issue me tira esto:

415
{
    "documentation_url": "https://developer.github.com/v3/",
    "message": "If you would like to help us test the Multiple Issue Assignees during its preview period, you must specify a custom media type in the 'Accept' header. Please see the docs for full details."
}

Se cual custom media poner pero no se como ponerlo, estuve buscando bastante rato pero en ningun lugar encontre claramente como se ponia.
En donde se ponen los custom media en el accept header?

**Comment by ivaniadg** [comment]
> "message": "If you would like to help us test the Multiple Issue Assignees during its preview period, you must specify a custom media type in the 'Accept' header. Please see the docs for full details."

Ahí te lo está diciendo. Debes especificar un _custom media type_ en el parámetro _Accept_ del header.

**Comment by FernandoPieressa** [comment]
El problema es que no se como acceder al parametro accept del header, si lo hago despues de crearlo ya esta el error, intente ponerlo como busque en google -H "custommedia" y tira error. Eso es lo que ya busque y no encuentro la solucion.

La pregunta es: Como especifico el custom media type @indonoso 

Ya se cual es el custom media type que debo poner y donde pero no se como

**Comment by jtagle2** [comment]
@FernandoPieressa 
http://docs.python-requests.org/en/master/user/advanced/
Ahí hay una forma fácil de hacerlo, usando session.

**Comment by ivaniadg** [comment]
Cuando creas un request especificas el header. Obviamente después de haber ejecutado el request ya no puedes cambiar el header. 

No sé si entiendo tu pregunta. Podrías explicar el pipeline del request?

**Comment by aaossa** [comment]
@FernandoPieressa 

``` python
headers = {
    "Accept": "application/vnd.github.cerberus-preview+json"
}
```

Manda eso como `header` con tu request. **Hint:** Es similar a como mandas las credenciales.

**Nota:** El header puede variar segun la request. Ver la documentación para saber cuál utilizar

**Comment by FernandoPieressa** [comment]
Ahi lo logre hacer con lo que mando jtagle, muchas gracias!
