### ISSUE TITLE
Dudas enunciado

### ISSUE THREAD

**Issue by FernandoPieressa** [IIC2233-2016-1/syllabus#619]
Hay varias dudas que tengo con respecto al enunciado:

1)la idea es que pueda editar cualquier repo? osea dar la opción y todo? o solo del fake_syllabus que nos dieron?

2)_"Dado un nombre de usuario, entregar el total de cada una de las reacciones que generan todas las issues que crea este mismo."_ Esto tambien incluye comentarios? o solo el mensaje original?

3) Las issues closed tambien cuentan en estadisticas?

**Comment by flobarrios** [comment]
Hola! 

1) No es necesario, puedes hacerlo solo para el fake_syllabus.
2) Si, incluye los comentarios.
3) Si, cuentan las cerradas.

Saludos!
