### ISSUE TITLE
Usar values de un diccionario como constructor

### ISSUE THREAD

**Issue by bmarinb** [IIC2233-2016-1/syllabus#62]
Si tengo un diccionario de la forma d = {'atributo':valor, 'atributo2':valor2}
donde atributo y atributo2 son los atributos de una clase (del constructor de la clase)
Es posible instanciar la clase usando el diccionario?
objeto=Clase(d)
y que al hacer
objeto.atributo  ----> valor
objeto.atributo2 ----> valor2

Esto ya que no se me ocurre como instanciar de una forma normal
objeto=Clase(atributo=valor, atributo2=valor2)

considerando que tengo la información solo en el diccionario

**Comment by Geeermy** [comment]
Hola! Sí, se puede, básicamente lo que quieres hacer es:
objeto = Clase(d['atributo'],d['atributo2']) -> Asumiendo que tu diccionario es la variable d.
Para obtener el valor de uno de los atributos de un diccionario, siempre lo haces de la forma d['atributo'], como una lista, pero en vez de una posición, le entregas el nombre del atributo.
Saludos!

**Comment by bmarinb** [comment]
Mi problema es que el largo del diccionario es variable, necesitaría algo así como un for de una linea para poder hacerlo

**Comment by Geeermy** [comment]
¿Por qué sería variable? ¿En algún momento haces que tenga más atributos?
No entiendo muy bien lo que quieres hacer, si me das un poco más de detalles podemos ver qué sucede

**Comment by bmarinb** [comment]
Porque a partir del texto productos.txt genero un diccionario para cada producto (diccionario de atributos y valores), pero cada producto es un tipo de subproducto con distintos atributos, por lo tanto cada diccionario tiene los atributos de cada tipo de producto. 
Al ejecutar el constructor puedo hacer que se ejecute el constructor asociado al subproducto correspondiente, pero no puedo entregarle los atributos.

**Comment by bmarinb** [comment]
Ya lo logre, tenía que usar **d como argumento y estaba usando solo d.
Gracias igual
