### ISSUE TITLE
¿Son sólo esas 3 funcionalidades?

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#620]
Tengo una duda con la parte del enunciado sobre el problema, que dice :

> En esta interfaz, un usuario debería ser capaz de conectarse a su usuario de GitHub (real) **y trabajar sobre este repositorio** (creado para esta tarea)

La interfaz solo debe permitir realizar las 3 funcionalidades descritas, ¿o también debe permitir crear/editar/eliminar issues (tal como lo hago ahora en este issue)? Lamento si la pregunta es muy tonta, pero esa porción del enunciado me hizo considerar esa posiblidad, pero como en el enunciado no se utilizan nunca esas palabras, me dice que no es necesario.

**Comment by flobarrios** [comment]
Hola !! No, no es necesario. Solo te pedimos que implementes las 3 funcionalidades. Ahora, si lo quieres hacer bacan !!! Y podrías ser recompensado (bonus ayudante) saludos!

**Comment by MortizDX** [comment]
Perdón por la tardanza, gracias por la respuesta, veré si puedo hacer un bonus, jaja.
