### ISSUE TITLE
Dudas con enunciado T07

### ISSUE THREAD

**Issue by fnquinteros** [IIC2233-2016-1/syllabus#621]
Mi problema consiste en que no entiendo el enunciado .-. cuando dice: "El programa será capaz de crear relaciones entre ciertos labels y usuarios de Github. Esta relación definirá
a los usuarios que deban ser asignados a las issues con un determinado label." 

¿Qué relación es esa? ¿Qué usuarios deben ser relacionados con los labels?

No entiendo que tengo que hacer exactamente... ¿se supone que tengo que hacer que si existe una label en una issue, automáticamente se le asigne a "cierto usuario"?. Pero, ¿quién es ese usuario y bajo qué condiciones se le debe asignar la issue?

**Comment by flobarrios** [comment]
Hola!! la relación debes crearla tu y queda totalmente a tu criterio a que usuario le asignas cada label, siempre y cuando al añadir esta label a una issue, le asignes el mismo usuario. Las condiciones para asignar a un label las defines tu (usuario x se asigna a label a, usuario y se asigna a label b y así). Y sí, " si existe una label en una issue, automáticamente se le asigne a "cierto usuario". Saludos!

**Comment by fnquinteros** [comment]
hmm, pero yo tengo q saber de la existencia de esos usuarios? debo crearlos? los invento? busco usuarios existentes?

PD: gracias por contestar tan rapido :bow: :sweat_smile:

**Comment by flobarrios** [comment]
Hola ! no puedes inventarlos, tienen que ser usuarios válidos. Puedes usar todos los usuarios que existen en el syllabus (los obtienes con la api). Saludos!

**Comment by fnquinteros** [comment]
yaa perfecto. En ese caso da igual qué usuario asigne a qué label, solo basta con que sea un usuario válido?

**Comment by flobarrios** [comment]
Si!, pero por ejemplo si me asignas a mi @flobarrios al label "Dudas T7" (por ejemplo), tienes que ser consistente y en cada idsue con este label me debes asignar a mi y no a otro cualquiera y así para todos los labes.

**Comment by fnquinteros** [comment]
Ya! ahi entendi :smile: muchas gracias! saludos c:

**Comment by flobarrios** [comment]
Denada !! 😊

**Comment by fnquinteros** [comment]
una ultima duda :sweat_smile: esta asignación se debe hacer independiente del usuario que ingrese mediante la interfaz? Por decirlo de otra forma, al ingresar un usuario las asignaciones ya deben estar hechas? perdón lo cargante :cold_sweat:

**Comment by spiza** [comment]
Otra cosa!!

Según se dice, si se crea una issue nueva, y a esta se le asigna una label, automáticamente el programa asigna a ese usuario??

**Comment by negebauer** [comment]
@spiza #602

**Comment by flobarrios** [comment]
@fnquinteros si es independiente al usuario que ingrese pero no es necesario que estas ya estén hechas al momento de ingresarse. Puedes contar con un botón que realice esta acción (como lo dice el enunciado: "el programa deber ́a contar con algún mecanismo accionado por el usuario (puede ser un botón) para asignar los usuarios de la relación a las issues que correspondan").
Saludos!

**Comment by flobarrios** [comment]
Y lo otro que no se si quedo muy claro, es que la interfaz debe dar la opción de crear un label y asignar a un usuario (no deben estar predefinidos por ustedes). En #602 lo explique !

**Comment by rodolfopalma** [comment]
@fnquinteros no entendí bien a qué te refieres, puedes detallar?

**Comment by fnquinteros** [comment]
Mi pregunta es si, antes de loguear con un usuario, las labels ya deben venir con usuarios asignados, o es algo que se debe hacer despues de haber ingresado usuario y contraseña. Si por ejemplo hay varias labels creadas sin usuarios asignados, debo asignarlos con un boton despues de ingresar con mi usuario y contraseña, o debo asignarles usuarios a esas labels desde antes?

**Comment by flobarrios** [comment]
@fnquinteros quedo mas claro con #602 o aun te quedan dudas ? si no, cierra el issue!

**Comment by fnquinteros** [comment]
la cierro, gracias!
