### ISSUE TITLE
Problema haciendo patch en una issue

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2233-2016-1/syllabus#622]
Hola! El problema que tengo es que me aparece el error 400. Según yo, le estoy pasando todos los argumentos... 

```
{
    "documentation_url": "https://developer.github.com/v3/issues/#edit-an-issue",
    "message": "Problems parsing JSON"
}
```

El documento no dice nada al respecto :'(..Lo googleé también pero no me aparece nada que me ayude.

Gracias

**Comment by aaossa** [comment]
Debe haber un error con el formato de tu json, lo primero que se me ocurre es que puedes estar cerrando mal un string o que estás usando una tilde por ahí, algo así podría ser

**Comment by rodolfopalma** [comment]
@AlfonsoIgnacioV puedes incluir la estructura del JSON que estás enviando?

**Comment by AlfonsoIgnacioV** [comment]
credentials = #usuario, contraseña
req = requests.patch('https://api.github.com/repos/IIC2233-2016-1/fake_syllabus/issues/604',
    auth = credentials, params={'body': 'cuerpo numero 2'})
print_pretty(req.json())

**Comment by aaossa** [comment]
Estás poniendo mal la url

> ### [Edit an issue](https://developer.github.com/v3/issues/#edit-an-issue)
> `PATCH /repos/:owner/:repo/issues/:number`

**Comment by aaossa** [comment]
Cuando haces patch, no tienes que enviar las cosas en params

**Comment by AlfonsoIgnacioV** [comment]
pero si necesito cambiar algo, necesariamente tengo que enviar algo no? Si no por defecto no se cambiaría nada (?)

**Comment by aaossa** [comment]
Cuando tienes que cambiar algo, por ejemplo en un POST, no se envia con params. Params son parametros de la url, tu tienes que enviar información

**Comment by AlfonsoIgnacioV** [comment]
pero... en el material de la tarea 7 sale que:

url = "https://api.github.com/user/repos"
params = {
    "name": "dummy_repo",
    "description": "An example repo using GitHub API v3",
    "homepage": "{}.github.io".format(credentials[0]),
    "private": False,
    "has_issues": True,
    "has_wiki": False,
    "has_downloads": False,
    "auto_init": False
}
req = requests.post(url, data=json.dumps(params), auth=credentials)

params es equivalente a data no?

**Comment by AlfonsoIgnacioV** [comment]
ahora me funcionó, era cambiar params por data y hacer dumps, gracias!
