### ISSUE TITLE
Duda Estadísticas

### ISSUE THREAD

**Issue by spiza** [IIC2233-2016-1/syllabus#623]
Dice claro:

"Dar la opción de desplegar distintas estadísticas:
Dado un nombre de usuario, entregar el número de issues que abre."

Mi duda es.. Este número de issues, son solamente aplicables al fake repo, cierto? O sea, si yo tengo más actividad porque pertenezco a más repos que quizás no tienen que ver con el curso, estas no tienen que verse reflejadas, cierto??

En el fondo es si solo son la issues del repo , ajjaja

**Comment by mjjunemann** [comment]
Exacto.

**Comment by DiegoSilvaS** [comment]
@mjjunemann  entonces las issues de los repos de syllabus y el repo privado no cuentan para estas estadisticas?

**Comment by flobarrios** [comment]
@DiegoSilvaS no, solo del fake_syllabus. Saludos!
