### ISSUE TITLE
Obtener todos las issues

### ISSUE THREAD

**Issue by DiegoSilvaS** [IIC2233-2016-1/syllabus#624]
Hola estoy intentando obtener todas las issues que un usuario pueda acceder mediante:

url = "https://api.github.com/issues"
data = {'filter':'all'}
req = requests.get(url,params=data, auth=credentials)

Lo que deberia funcionar, pero solo me entrega las issues de mi repo privado. Y no obtengo las issues de ningun otro repo, ni los syllabus .
Probablemente hay algo que no estoy entendiendo de las /issues o del filtro, si alguien me lo podria hacer notar se lo agradeceria.
Saludos

**Comment by spiza** [comment]
Tu problema es que estás buscando directo issues.. Tienes que cambiar el path del útil

Enviado desde mi iPhone

**Comment by mjjunemann** [comment]
Para obtener issues de cierto repositorio, estas haciendo get a la url equivocada. 

Te recomiendo que leas esto: 
https://developer.github.com/v3/issues/#list-issues-for-a-repository

**Comment by aaossa** [comment]
@DiegoSilvaS prueba haciendo watch del syllabus, a ver si ahí te aparecen

**Comment by DiegoSilvaS** [comment]
@mjjunemann, @spiza  Ya había visto la guía de developers, y también pensé en analizar cada repo que tuviera el usuario autentificado completando el url con 
GET /repos/:owner/:repo/issues
pero cuando lo intento hacer para syllabus por ejemplo (cambiando :own por "IIC2233-2016-1" y :repo por syllabus) me tira una lista de 30 :(, agragandole "filter" "all" y "state" ("all" o tambien "closed") en los parametros (que son como las ultimas 30 que han aparecido), tambien le puse filtro al "since" por si acaso y nada...
Quizas me falta agregarle un filtro o algo en el url

Perdon @aaossa pero a que te refieres con hacerle watch?

**Comment by aaossa** [comment]
![image](https://cloud.githubusercontent.com/assets/10425834/16316598/b5044a96-395d-11e6-9acd-2fc00aaf9ddf.png)

#AguantePaint

**Comment by Jricci1** [comment]
Tengo el mismo problema, pruebo con tu mismo código pero con este url = "https://api.github.com/orgs/IIC2233-2016-1/issues"
 y filter : all y state : all y tambien me tira 30 y segun lo que  he leido debiese entregarme todas as issues de IIC2233..., si alguien puede decir en que fallo seria buenisimo.

**Comment by JoseDaroch** [comment]
Entiendo que se puede de la forma que se indica ahí [https://developer.github.com/v3/#pagination](url), pero por pagina puedo ver máximo 100, y para ver más de 100, tengo que 'navegar' a través de las paginas, pero mi duda va a como saber cual es el total de paginas (la forma que aparece en la documentación dice que es con octokit, pero ahí ya me enrrede), así que igual tengo la duda!

**Comment by ManuelSIlvaCav** [comment]
cuando hagan req.headers vean la llave de 'Link' y ese tiene las cantidad de paginas para ese Get. Ovio que esa cantidad de paginas cambia de acuerdo a cuantas per_page estan pidiendo :d

**Comment by JoseDaroch** [comment]
@ManuelSIlvaCav pero lo obtienes a la mala? o con algún comando especial?

**Comment by ManuelSIlvaCav** [comment]
a la mala

**Comment by spiza** [comment]
Yo lo hice con un while true, y veo si la request es o no es... Si no es break, si es sigo buscando!

Enviado desde mi iPhone

**Comment by vjmoreno** [comment]
@DiegoSilvaS  pudiste solucionarlo? me está pasando lo mismo

**Comment by DiegoSilvaS** [comment]
Sisi @vjmoreno el problema es que cuando pides una reques te mandan las ultimas que han aparecido que corresponden a la pagina 1 de la informacion que hay, pero puede pedir el resto de la informacion accediendo a otras paginas definiendo 'pages':'numero de pagina que quieres' en los parametros de la request, fijate en lo que dice @ManuelSIlvaCav
