### ISSUE TITLE
Duda enunciado Tarea 7

### ISSUE THREAD

**Issue by jpdattas** [IIC2233-2016-1/syllabus#626]
en el enunciado sale "para asignar los usuarios de la relacion a las issues que correspondan. Para
este item, considere solo las issues creadas despues del 25 de Mayo."

Esto significa que hay que dar las páginas o rango de páginas o simplemente se hace la asignación para todas las issues?

**Comment by flobarrios** [comment]
Hola! la asignación se hace solo a las issues creadas después de esa fecha. No a todas las issues. Saludos!

**Comment by rpalmaotero** [comment]
#607

**Comment by jpdattas** [comment]
ok, gracias! pero como todas se crearon despues de esa fecha pueden ser todasentonces  o no?(eso entendi que decian en otra issue)

edit: no importa. en verdad son un par de palabras que agregar jaja, gracias

**Comment by flobarrios** [comment]
ajjaja ya !! pero para que quede claro, sí, tienes que filtrar (puedes usar el syllabus original para probar tu algoritmo).
