### ISSUE TITLE
Problema derechos administrador

### ISSUE THREAD

**Issue by FernandoPieressa** [IIC2233-2016-1/syllabus#628]
Para sacar la estadistica de las reacciones tengo un problema.

Cuando intento sacar las reacciones de la issue todo funciona perfecto y lo tengo hecho, sin embargo, cuando trato de recolectar las reacciones de los comentarios de la issue al hacerle GET me tira el siguiente error:

{
    "documentation_url": "https://developer.github.com/v3",
    "message": "Must have admin rights to Repository."
}

Necesitare derechos adicionales para poder recolectar esta informacion?

**Comment by aaossa** [comment]
Acabo de probar con [un comentario de una issue en el repo de rails](https://github.com/rails/rails/issues/25423#issuecomment-227926842) y pude obtener las reacciones. Quizás no estás haciendo la request correctamente,

**Comment by FernandoPieressa** [comment]
Sale GET /repos/:owner/:repo/issues/comments/:id/reactions

tengo:

"https://api.github.com/repos/IIC2233-2016-1/fake_syllabus/issues/comments/595/reactions"

No deberia estar mal segun yo, despues es un requests.get normal con un header en accept para que funcione

**Comment by aaossa** [comment]
Esa no es una id de comentario

**Comment by FernandoPieressa** [comment]
aaa muchas gracias jaja pense que se ponia el numero de issue
