### ISSUE TITLE
Verificar si usuario tiene acceso a repo

### ISSUE THREAD

**Issue by tmorales1** [IIC2233-2016-1/syllabus#629]
Para verificar si un usuario tiene acceso a un repositorio, que es lo que se debe ver? Los subscribers del repo? O basta con que el usuario este en "todos los users"?

**Comment by aaossa** [comment]
Quizás [esto](https://developer.github.com/v3/repos/collaborators/#check-if-a-user-is-a-collaborator) sea lo que buscas

**Comment by tmorales1** [comment]
Gracias!

**Comment by icontrerasn** [comment]
@aaossa Tengo una duda con lo que respondes acá, actualmente no aparezco como colaborador del repositorio pero si como un posible usuario a ser asignado a una label (lista de "assignees"). No entiendo por que pasa esto y que lista finalmente es la que debemos considerar para ver si el usuario tiene acceso.

**Comment by aaossa** [comment]
Si apareces como colaborador, que usaste para ver si apareces o no?

**Comment by joaquincastillo** [comment]
@aaossa yo usé https://developer.github.com/v3/issues/assignees/#list-assignees para ver si un usuario es asignable a una issue, está bien?

**Comment by jtagle2** [comment]
@aaossa, yo lo estoy haciendo igual que @joaquincastillo. Es más, para obtener los repos del usuario, hago algo feo también (como que veo las organizaciones de mis repos, y veo los repos de esas orgs a los cuales puedo acceder, ya sea porque son públicos o porque soy colaborador).
Según la respuesta en #611, asumí que no era necesario ser colaborador para tener acceso a un repo, asique ahora veo los assignees o los repos de las organizaciones en las que tengo algun repo

**Comment by icontrerasn** [comment]
@aaossa Ahora si aparezco en ambas, disculpa, era un error mío, pero lo hacía con GET /repos/:owner/:repo/collaborators y ahí no aparecia, pero si lo hacia como @joaquincastillo y @jtagle2 con GET /repos/:owner/:repo/assingees si me encontraba. Al final cuál de estas dos listas será mejor usar?

**Comment by Manuel-uc** [comment]
Tengo la misma duda
