### ISSUE TITLE
No puedo imprimir bien un string

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#63]
Tengo este problema, el ultimo correo de la lista de usuarios es "lurenaweber@simonis-hickle.net".
Sin embargo cuando lo imprimo solo sale "urenaweber@simonis-hickle.net", sin la "l" inicial. 
¿A que se puede deber?

**Comment by fgvenegas** [comment]
Te ocurre en algun otro correo?

Sino tienes que revisar tu codigo paso a paso ya sea con el debugger de Pycharm o mediante "prints" para ver en que momentos ocurre eso. 

Es dificil responder dudas muy especificas de sus codigos sobretodo sin contexto, asique siempre traten de ser lo mas explicativos posibles aunque sea con ejemplos simples, codigo de su tarea no se puede mostrar!  

**PS:** Recuerda que no puedes publicar código de tu tarea en el syllabus

**Comment by perojas3** [comment]
Sí, me ocurre con todos los e-mails que comienzan con "l", si tiene una vocal despues tambien la quita. Tambien pasa con las "t" y las "r".
Utilizo 2 strip() para extraer los correos.

**Comment by otro-felipe** [comment]
El problema es lo que hace strip. Por ejemplo:

``` python
s = 'anita lava la tina'
print(s.strip("tina"))  # imprime " lava la "
```

"Esto es un bug!!! deberian arreglarlo!! python no funciona, mejor cambiemos a java!!!" podrias pensar, pero en realidad, esto no es ningun bug.
Lo que hace la funcion strip es tomar cada caracter que le ingresas como parametro (es decir, tu parametro se toma caracter a caracter y no como un todo).
Siguiendo el ejemplo, lo que hace strip es:
- el string es: "anita lava la tina"
- debo stripearle (quitar del principio y del final) los siguientes caracteres: "tina"
- "anita lava la tina" parte con a, asi que se la quito.
- "nita lava la tina" ahora tiene una n, se la quito.
- y asi hasta que tu string queda completamente mutilado sin que tu sepas que paso.

Mi recomendacion: usa un approach distinto para parsear el json.
