### ISSUE TITLE
Accept header???

### ISSUE THREAD

**Issue by fnquinteros** [IIC2233-2016-1/syllabus#630]
Hola!
Al intentar recuperar las reactions de una issue el programa me pide especificar un "custom media type" en el "Accept" Header... No entiendo qué tengo que hacer en este caso y en la documentación se mencionan estas cosas como si ya las debiera conocer de antes (:cry:). Como se supone que especifique algo en el "Accept" Header? 
saludos

**Comment by rodolfopalma** [comment]
Mira #618.
