### ISSUE TITLE
Comparacion de issues

### ISSUE THREAD

**Issue by bregonesi** [IIC2233-2016-1/syllabus#631]
Creo que hago bien la comparacion (utilizo la formula de #606). Me retorna una issue, pero en general es una issue con pocas palabras, que no tiene mucha relación con la issue a comparar.
Es normal que sea así por lo simple del algoritmo? A alguien mas le pasa?

**Comment by ivaniadg** [comment]
Está bien. El método no es el mejor para medir similaridad entre dos textos, pero no te preocupes en la tarea se evalúa la implementación, no la calidad de los resultados 😸 
Agregué información en la issue #606, revísalo por si acaso.
