### ISSUE TITLE
Duda reactions

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2233-2016-1/syllabus#632]
Es una duda de enunciado: ¿las reacciones que generan las issues de un usuario incluyen las que van en los comentarios de esas issues, o solamente las que son directas a los issues? 
Gracias

**Comment by spiza** [comment]
Está duplicada, ok! Pero cuál es la respuesta?????!??! Si está duplicada donde está la issue que le corresponde?

**Comment by aaossa** [comment]
#616 y #619 , la idea de marcarlas duplicadas es invitarlos a buscar bien :+1:
