### ISSUE TITLE
Que hacer con palabras raras dentro de una issue?

### ISSUE THREAD

**Issue by joaquincastillo** [IIC2233-2016-1/syllabus#633]
Cuando obtengo issues de github, aparecen palabras como "original?\r\n\r\nmi" o "error?\r\n\r\ns". Se deben considerar en el diccionario de palabras o no?

**Comment by aaossa** [comment]
Nop, tienes que limpiarlas

**Comment by joaquincastillo** [comment]
Gracias!

**Comment by jpdattas** [comment]
@aaossa se puede dejar solo lo que tenga exclusivamente letras normales? osea si hay pör éjemplo letrás con acentos se omiten?

**Comment by aaossa** [comment]
#647
