### ISSUE TITLE
Duda enunciado Tarea 7

### ISSUE THREAD

**Issue by jpdattas** [IIC2233-2016-1/syllabus#634]
3.2.1 se llama "creación y sucripción a labels", pero en el contenido no sale que hay que crear labels. Hay que crear tambien?

**Comment by flobarrios** [comment]
Hola, sí, tienes que hacerlo. En #602 se explica bien como hacerlo. Saludos!

**Comment by jpdattas** [comment]
ok, muchas gracias!
