### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by jtagle2** [IIC2233-2016-1/syllabus#635]
"Para todas estas, debera obtener todos los usuarios que tengan permisos en el repositorio (todos los alumnos de IIC2233) y todos los labels existentes en este dependiendo de la estadística a consultar."
Para obtener las estadísticas, es necesario cumplir esto?
A modo de ejemplo: obtener todas las labels: si en el request yo puedo pedir que me entregue solo las issues que tienen cierto label asociado, no es necesario ver todos los labels del repo, sino pedir solo algunas.

**Comment by flobarrios** [comment]
Hola! ese punto hace relación a que por ejemplo, para esta estadística:
- Dado un label, la cantidad de issues con ese label.

Necesitas que en la interfaz, se despliegan todos los labels existentes dentro del repo y a partir de eso, que el usuario pueda seleccionar el que quiere consultar y luego generar la estadística de en cuantas issues está. Lo mismo para las otras estadísticas (dado un usuario ...). Avísame si aún te quedan dudas. Saludos!

**Comment by jneyzaguirre** [comment]
¿Necesariamente tengo que desplegar todos los usuarios y labels, para que los seleccione? que yo lo hice con line edit para que ingrese esa información.

**Comment by flobarrios** [comment]
Es otra opción, pero debes verificar que el usuario se puede "consultar" y que el label existe dentro del repo.

**Comment by JoseRomeroi** [comment]
@flobarrios podemos hacerlo entonces con un lineEdit, e informar oportunamente en caso de que un usuario no tenga acceso al fake_syllabus? o se nos descontara puntaje si no mostramos todos los usuarios

**Comment by flobarrios** [comment]
@JoseRomeroi si pueden ! no se les descontará puntaje pero si les recomiendo que en su README.md den ejemplos de usuarios y labels para facilitar la corrección. Saludos!
