### ISSUE TITLE
problema al obtener las issues

### ISSUE THREAD

**Issue by fnquinteros** [IIC2233-2016-1/syllabus#636]
Hola!
Es normal que cuando pido obtener las issues del repositorio solo me entregue las ultimas 30?

**Comment by aaossa** [comment]
Si, es normal

**Comment by jtagle2** [comment]
Si, es normal. Eso es porque un request, pide una pagina (que por defecto son de 30 issues). Para pedirlas todas (independiente de si son 30 o 1000) puedes iterar sobre el número de las páginas que vas pidiendo. 
https://developer.github.com/v3/#pagination
En ese link se puede entender mas o menos como funciona el sistema de per_page y page

**Comment by fnquinteros** [comment]
perfect, gracias!
