### ISSUE TITLE
Estadisticas 

### ISSUE THREAD

**Issue by JoseDaroch** [IIC2233-2016-1/syllabus#637]
> Para todas estas, debera obtener todos los usuarios que tengan permisos en el repositorio (todos los alumnos de IIC2233) y todos los labels existentes en este dependiendo de la estadstica a consultar.

Con todos los alumnos de IIC2233 se refiere a los que estamos con permisos en el fake_syllabus o los del syllabus original también?, por que no he logrado obtener todos los miembros de IIC2233 si no fuese asi :(

**Comment by flobarrios** [comment]
puedes usar solo los del fake_syllabus. Saludos!
