### ISSUE TITLE
Permiso para hacer push

### ISSUE THREAD

**Issue by jtagle2** [IIC2233-2016-1/syllabus#638]
@aaossa. Se supone que debería tener permiso para hacer push en el fake_syllabus verdad? Que no tengo permiso, y lo único que me deja hacer, es la parte de las estadísticas, pero todo lo que sea asignar cosas no me deja.
Si no es así, estoy muy perdido jajaja

**Comment by aaossa** [comment]
Estás en la lista de invitaciones pendientes. Tendrías permisos si hubieras aceptado el correo-invitación a la organización a comienzos de semestre, pero nunca es tarde. Actualicé la invitación para que, en cuanto la aceptes, ya tengas permisos sobre el repo :grin:
