### ISSUE TITLE
Problema posts (agregar labels y asignar usuarios)

### ISSUE THREAD

**Issue by tmorales1** [IIC2233-2016-1/syllabus#639]
No puedo hacer que me funcione asignar usuarios a los issues, ni tampoco crear labels.

Estoy usando este código:

``` python
label = {
  "name": "hah",
  "color": "f29513"
}

url = "https://api.github.com/repos/IIC2233-2016-1/fake_syllabus/labels"
req = requests.post(url, label, auth=credentials)
```

Como resultado según la documentación me debería dar status "201 Created", pero en vez me da "200 OK"

**Comment by aaossa** [comment]
Quizás tenga que ver con que estás haciendo post y no estás mandando la información como json en data

**Comment by tmorales1** [comment]
Si, no estaba haciendo eso. Pero todavía tengo el mismo problema. Algún otro consejo?

**Comment by aaossa** [comment]
Revisa que estés imprimiendo correctamente (por ejemplo, que efectivamente imprimas la request que estás viendo, yo creo que es esto) y que estés dando el diccionario como json. Acabo de copiar tu código, usar json y me dio un 201 (borraré el _label_ en seguida). Aun no pones el output de la request por ejemplo, qué te retorna `req.json()`
