### ISSUE TITLE
todos los usuarios del repo?

### ISSUE THREAD

**Issue by tblatrille** [IIC2233-2016-1/syllabus#640]
Para las estadísticas se dice que se debe obtener todos los usuarios del repo, pero no entiendo bien con que objetivo o si necesariamente tengo que hacerlo así, está mal si cuando el usuario entrega un nombre que no tiene acceso al repo y salen sus stats en 0 porque simplemente no aparecerá en ningún lado? es decir tengo que seguir estrictamente lo que dice el enunciado ahí?

**Comment by flobarrios** [comment]
Hola! si, debes seguir lo que dice el enunciado. En caso de no tener acceso al repo, debes notificarlo por la interfaz y no decir simplemente que sus estadísticas son 0. Saludos!
