### ISSUE TITLE
obtener issues en que participa un usuario

### ISSUE THREAD

**Issue by fnquinteros** [IIC2233-2016-1/syllabus#641]
Hola!
entre las issues que participa un usuario hay que contar las que ya están cerradas?

saludos!

**Comment by flobarrios** [comment]
Si, debes tomarlas en cuenta!

**Comment by fnquinteros** [comment]
y entonces supongo que no importa si el programa se demora sus 10 minutos o más en realizar esa función? porque son muchas issues que revisar y además muchos comentarios... Al poner en los parametros la fecha desde la cual debe buscar las issues se reduce el tiempo de busqueda? porque aunque ponga que me muestre las issues de hace 2 dias solamente, se demora muchisimo tiempo... :disappointed:

**Comment by fnquinteros** [comment]
además, dicen que tomemos en cuenta solo las issues a partir del 25/05, pero en fake_syllabus el Syllabot publicó todas las issues el mismo dia y eso fue como hace 3 o 4 dias... asi que no cambia nada filtrar las issues de despues del 25/05

**Comment by JoseDaroch** [comment]
es verdad, a mi la tercera consulta (de issues en que participa) se me demora mucho, más que nada por la cantidad de request que tengo que hacer, ya que no encontré una forma mejor de obtener los comentarios que haciendo un request por issue

**Comment by flobarrios** [comment]
Hola !! se les va a evaluar el tiempo desde que tienen los datos y hacen el el output (tiempo de algoritmo, que no se demore infinito en entregar un resultado una vez obtenidos los datos). El tiempo en obtener todos los datos a partir de requests no será evaluado. Saludos!!

**Comment by fnquinteros** [comment]
hmmm o sea estoy muy mal si hago request cada vez que pido un dato? :c

**Comment by flobarrios** [comment]
Haces un request para cada issue?? deberías obtenerlas todas a partir de un request! revisa bien la documentación y ya que puedes pedir todas las issues que cumplan ciertas condiciones. Saludos!!!

**Comment by fnquinteros** [comment]
Noo! pero cada vez que se presiona el boton "obtener issues que abrió el usuario" por ejemplo, se hace un request para obtener las issues del repo y verificar que quien las abrió fue el usuario. Si hiciera un solo request al abrir el programa para obtener las issues, un usuario podria abrir una issue mientras el programa está corriendo, y entonces el programa no tomaría en cuenta esa issue cuando haga click en un boton (pero el programa funcionaria mil veces mas rapido)... que es mejor en ese caso? que funcione bien o que funcione rapido? :sweat_smile:

**Comment by flobarrios** [comment]
ambas soluciones son válidas. Si optas por que funcione rápido, y hacer un solo request para obtener las issues del repo, podrías tener un botón actualizar que haga un nuevo request para tener el último estado de las issues. Queda a tu criterio y especifícalo en el readme!

**Comment by fnquinteros** [comment]
ok, gracias ;D

**Comment by Pochoclo** [comment]
A mi se me demora mucho porque hay que hacer un get por cada issue para obtener los comentarios de las issues. Hay alguna forma de obtener todos los comentarios de todas las issues sin tener que hacer eso?

**Comment by flobarrios** [comment]
probaste con esto?: https://developer.github.com/v3/issues/comments/#list-comments-in-a-repository

**Comment by Pochoclo** [comment]
Ohhh no lo había visto!! gracias!!!

**Comment by flobarrios** [comment]
denada ! 😄
