### ISSUE TITLE
Parametros para Issue

### ISSUE THREAD

**Issue by santiagocruzb** [IIC2233-2016-1/syllabus#643]
Hola! Intentado obtener todas las issues hago lo siguiente:

```
url = 'https://api.github.com/repos/IIC2233-2016-1/fake_syllabus/issues'
param = {'state':'all'}
req = requests.get(url,data=param, auth=credenciales)
```

Y me muestra solo las abiertas. Intentando poner close para ver que ocurre, me sigue mostrando solo las abiertas. Alguien tuvo este problema?
Saludos
@aaossa

**Comment by aaossa** [comment]
Es porque para hacer GET tienes que darle los parámetros en la url, no en el body. Por esto es que tienes que darle el diccionario `param` en `params`, no en `data`.

``` python
>> req = requests.get(url,params=param, auth=credentials)
>> req.url
"https://api.github.com/repos/IIC2233-2016-1/fake_syllabus/issues?state=all"
```

**Comment by santiagocruzb** [comment]
Muchas gracias!
