### ISSUE TITLE
Duda con la fecha

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2233-2016-1/syllabus#644]
Hola! Cuando uso algunua fecha cercana a hoy (por ejemplo, probé usando 24 de junio a las 0:00:00), me arrojaba resultados desde el 20 de junio hacia acá. Sin embargo, consultando por una fecha de 2015 para probar, solo me tiraba del 23 y 24 de junio de este año. ¿A qué puede deberse?
Gracias

**Comment by aaossa** [comment]
Estás usando el formato debido para las fechas?

> ### [Schema](https://developer.github.com/v3/#schema)
> 
> YYYY-MM-DDTHH:MM:SSZ

**Comment by AlfonsoIgnacioV** [comment]
Sí, uso bien el formato

**Comment by MortizDX** [comment]
¿Esto lo estás aplicando con el parámetro since? Si es así, eso te va a tirar los **actualizados** desde esa fecha, no solo los creados. (no soy ayudante, pero quiería mencionarlo por si acaso es eso)

**Comment by IsaacConDosA** [comment]
@AlfonsoIgnacioV lo solucionaste? me pasa lo mismo @aaossa

**Comment by AlfonsoIgnacioV** [comment]
@MortizDX  si, es ese el que uso xD
@ifcarrera aun no lo resuelvo :/

**Comment by aaossa** [comment]
Como dijo @MortizDX 

> since (string): Only issues **updated** at or after this time are returned. This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.

Usandolo sobre el Syllabus, con `sorted: "updated"` tengo:

```
# number | created_at | updated_at
644 2016-06-24T05:59:48Z 2016-06-25T01:11:30Z
657 2016-06-24T22:27:11Z 2016-06-25T01:02:11Z
659 2016-06-25T00:40:03Z 2016-06-25T00:58:21Z
606 2016-06-22T00:55:20Z 2016-06-25T00:05:42Z
```

Quizás les pasó eso porque lo reciben desordenado. Prueben agregando el parametro "sorted" y me cuentan como les va
