### ISSUE TITLE
Instalación nltk

### ISSUE THREAD

**Issue by icontrerasn** [IIC2233-2016-1/syllabus#645]
Estoy teniendo problemas con la instalación. En la página oficial http://www.nltk.org/install.html solo aparece instalación para 32 bits y buscando en internet solo he encontrado opciones que ya expiraron. Grax.

**Comment by aaossa** [comment]
`pip install nltk` debería servirte

**Comment by icontrerasn** [comment]
Gracias @aaossa !

**Comment by spiza** [comment]
Permiso!

Me aparece el siguiente problema! Ya instalé el nltk, pero me pasa esto:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/nltk/corpus/util.py", line 63, in __load
    try: root = nltk.data.find('corpora/%s' % zip_name)
  File "/usr/local/lib/python3.4/site-packages/nltk/data.py", line 641, in find
    raise LookupError(resource_not_found)
LookupError: 

---

  Resource 'corpora/stopwords.zip/stopwords/' not found.  Please
  use the NLTK Downloader to obtain the resource:  >>>
  nltk.download()
  Searched in:
    - '/Users/Sebastian/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'

---

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Sebastian/Desktop/spiza-iic2233-repo/Tareas/T07/utils.py", line 5, in <module>
    class BasicNL:
  File "/Users/Sebastian/Desktop/spiza-iic2233-repo/Tareas/T07/utils.py", line 6, in BasicNL
    words = stopwords.words('spanish')
  File "/usr/local/lib/python3.4/site-packages/nltk/corpus/util.py", line 99, in **getattr**
    self.__load()
  File "/usr/local/lib/python3.4/site-packages/nltk/corpus/util.py", line 64, in __load
    except LookupError: raise e
  File "/usr/local/lib/python3.4/site-packages/nltk/corpus/util.py", line 61, in __load
    root = nltk.data.find('corpora/%s' % self.__name)
  File "/usr/local/lib/python3.4/site-packages/nltk/data.py", line 641, in find
    raise LookupError(resource_not_found)
LookupError: 

---

  Resource 'corpora/stopwords' not found.  Please use the NLTK
  Downloader to obtain the resource:  >>> nltk.download()
  Searched in:
    - '/Users/Sebastian/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************`

**Comment by aaossa** [comment]
> Resource 'corpora/stopwords' not found. Please use the NLTK
> Downloader to obtain the resource: >>> **nltk.download()**
> Searched in:
> - '/Users/Sebastian/nltk_data'
> - '/usr/share/nltk_data'
> - '/usr/local/share/nltk_data'
> - '/usr/lib/nltk_data'
> - '/usr/local/lib/nltk_data'

Hiciste eso?

**Comment by santiagocruzb** [comment]
Hola!
Busqué en internet la solucion a este problema y hay que instalar este paquete desde python haciendo

```
import nltk
nltk.donwload()
```

Y me lleva a esta basura en la que he avanzado esto en 45 minutos
![screen shot 2016-06-24 at 3 54 07 pm](https://cloud.githubusercontent.com/assets/13748925/16349029/32f7c2c2-3a24-11e6-925c-fad4b5e60cd2.png)
Mi internet es VTR asi que es malo por definición, pero a alguien se le demoró tanto la cosa como a mi?
Saludos

**Comment by JoseDaroch** [comment]
Si no me equivoco tienes que instalar solo las partes que salen en el modulo utils que venia con la tarea, son dos y se instalan en nada (conste que no estoy 100% seguro jaja)

**Comment by santiagocruzb** [comment]
Puedo ponerle download general, pero cuando me empiezo a cambiar entre las pestañas se queda pegado y muere (tiene pinta de ser problema de la GUI). No te paso eso?

SOLUCION: nltk.download_shell()

**Comment by spiza** [comment]
Yo todavía no puedo hacer nada.. ya hice `sudo pip3 install -U nltk`, en pycharm se me marcan como modulos importados, pero no corre el código y sigue apareciendo lo de antes

**Comment by santiagocruzb** [comment]
Lo que yo hice funciona perfecto para mac. Uno instala manualmente los
paquetes
