### ISSUE TITLE
No aparezco como colaborador en fake_syllabus ni syllabus

### ISSUE THREAD

**Issue by joaquinricci** [IIC2233-2016-1/syllabus#646]
No soy colaborador de fake_syllabus asique no me permite acceder a la lista de los colaboradores, como puedo hacerme colabordor?

**Comment by aaossa** [comment]
Listo

**Comment by DiegoSilvaS** [comment]
@aaossa yo tampoco aparesco como colaborador :(

**Comment by aaossa** [comment]
Done :ok_hand:
