### ISSUE TITLE
Puntuación en T7

### ISSUE THREAD

**Issue by icontrerasn** [IIC2233-2016-1/syllabus#647]
Al eliminar la puntuación de un string en la Tarea 7 debemos también reemplazar las letras con tilde por la misma letra sin tilde? O no es necesario para usar las funciones en el módulo utils?
 Si no debemos reemplazarlas, entonces asumimos que todo está escrito sin faltar ortográficas en las Issues?

**Comment by ivaniadg** [comment]
Asuman que la ortografía es correcta y no es necesario eliminar los tildes.
