### ISSUE TITLE
Como obtener usuarios con permisos

### ISSUE THREAD

**Issue by jagaldames** [IIC2233-2016-1/syllabus#648]
Ya se que han preguntado esto, pero revise las issues y aun no me resulta. 
hago GET /repos/:owner/:repo/collaborators en fake syllabus pero solo me devuelve 30 personas, que son los ayudantes. Como puedo acceder a los alumnos? se que nosotros tenemos permiso de Push, pero no se como llegar a esa lista.

gracias

**Comment by sitoro** [comment]
En #636 lo explican ;)

**Comment by jagaldames** [comment]
recien habia encontrado eso, antes no lo habia visto porque no decian sobre los colaboradores jajaja gracias!

**Comment by JoseRomeroi** [comment]
@jagaldames como lo hiciste? por más que trato con GET /repos/:owner/:repo/collaborators no me responde ninguna lista, ni siquiera los 30

**Comment by jagaldames** [comment]
la verdad es que hice solo eso, quizas algun problema en el link?

**Comment by JoseRomeroi** [comment]
@jagaldames ya cache como. gracias!
