### ISSUE TITLE
Librerias permitidas y no permitidas en la Tarea 1

### ISSUE THREAD

**Issue by otro-felipe** [IIC2233-2016-1/syllabus#65]
**Recuerden especificar en su README que librerías utilizan**

---

La idea es que pregunten acá todas las dudas respecto a módulos, librerías y funciones de python que deseen saber si pueden usarlas o no.
### Librerías permitidas
- time
- sys.exit
- datetime
- os
- random
- numpy (con precaución)
- pandas (con precaución)
### Librerías no permitidas
- json (deben escribir su propio parser)
- re (regex) (deben escribir su propio validador de mails)
- email_validator
- ast
### Built-ins permitidos
- filter
- reduce
### Built-ins prohibidos
- __dict__
- ast.literal_eval
- eval
- exec
- vars

**Comment by perojas3** [comment]
¿No se puede usar date?

**Comment by Geeermy** [comment]
Sí, se puede :) (es parte de datetime, de hecho)

**Comment by JoseDaroch** [comment]
Perdon la duda, pero que es un parser?

**Comment by otro-felipe** [comment]
[parser](http://searchsoa.techtarget.com/definition/parser). En terminos muy burdos es un script/programa/codigo que convierte un string (que contiene datos en un formato predefinido que el parser puede entender) en un objeto que representa dicho formato y contiene los datos del string input.

**Comment by MortizDX** [comment]
Dice que no podemos usar re para validar los email ¿se puede utilizar para parsear los json?

**Comment by otro-felipe** [comment]
No se puede usar `re` en la tarea. Saludos.

**Comment by ghost** [comment]
se puede importar literal_eval de ast?

**Comment by otro-felipe** [comment]
No se puede usar literal_eval. Saludos.

**Comment by fcorencoret** [comment]
se puede usar random (randint) para generar un numero aleatorio para el id en la funcion crear_apuestas?

**Comment by Geeermy** [comment]
Hola! No, la idea es que se siga un orden con los identificadores, con la técnica que dices se repetirían algunos. Debes guardar, de alguna forma, el último id de apuesta, y al crear una nueva hacerlo una unidad más grande.
Saludos!

**Comment by vbarros2** [comment]
Pero las subastas del txt no tienen ningún orden, se puede hacer un random de 11 cifras exigiendo que no se pueda repetir con las demás subastas?, aunque la probabilidad de que se repitan es muy baja.

Muchas Gracias

**Comment by Geeermy** [comment]
Hola! Hubo un error de logística :( como dices, no tienen ningún orden. Dado esto, pueden hacerlo como prefieran (con random en este caso), pero **deben revisar que no se repita el id.**
Saludos!

**Comment by Iruretagoyena** [comment]
Se pueden usar DataFrames ?

**Comment by caackermann** [comment]
Se puede ocupar numpy?

**Comment by sormazabal** [comment]
se puede usar collections?

**Comment by fgvenegas** [comment]
Que quieres usar de collections?

**Comment by vbarros2** [comment]
Se puede usar timedelta??

**Comment by sormazabal** [comment]
@fgvenegas  de collections quiero usar OrderedDict :D

**Comment by aaossa** [comment]
@vbarros2 Si con `timedelta` te refieres a la clase que es parte del módulo `datetime`, el cual está permitido, deberías poder usarlo sin problemas.

**Comment by aaossa** [comment]
@Diiru, @caackermann: No hay problema en que ocupen `DataFrames` y `numpy`, respectivamente, siempre que especifiquen en su `README.md` de la tarea que hay que instalar librerías y cuáles son las que se deben instalar. Tengan cuidado con la instalación en ambos casos porque a veces se pone "mañosa" la instalación...

Recuerden mantener un diseño orientado a objetos. Si comienzan a ocupar EDDs y quitan diseño orientado a objetos pueden perder puntaje

**PS:** La respuesta en #96 aplica para ambos casos

**Comment by fgvenegas** [comment]
@sormazabal Si puedes :)

**Comment by sitoro** [comment]
Esta permitido el clásico "reduce" de functools :c ?

**Comment by bmarinb** [comment]
Se Puede usar vars(objecto)?

**Comment by diegosapunar** [comment]
se puede usar operator?

**Comment by tamycova** [comment]
@diegosapunar para qué? todo lo del módulo tiene alguna equivalencia en python (creo)

**Comment by bamavrakis** [comment]
Hola! 
@sitoro  está permitido usar reduce
@bmarinb  no está permitido utilizar vars
Saludos!

**Comment by bmarinb** [comment]
y se puede usar **dict**?

**Comment by aaossa** [comment]
Si te refieres a diccionarios, sí, se pueden usar

**Comment by bmarinb** [comment]
@aaossa me refiero a  _ _ dict _ _que es similar a vars

**Comment by aaossa** [comment]
No se puede usar `__dict__`

**Comment by Iruretagoyena** [comment]
@aaossa Estimado, si bien se puede evitar el uso de **dict** , en la programaton algunos ayudantes indicaron que si se podía, por lo que recomiendo ponerlo en el aviso built ins prohibidos

**Comment by gbordoni** [comment]
Hola! Puedo usar fileinput para reescribir los archivos de texto??

saludos

**Comment by aaossa** [comment]
Nop, usa la materia de Introducción a la Programación para esa parte
