### ISSUE TITLE
Reactions T07

### ISSUE THREAD

**Issue by sitoro** [IIC2233-2016-1/syllabus#650]
Hola, al hacer requests de las reactions de un issue me retorna el error 415
Vi que en #618 un compañero le sucedió lo mismo y probé con todas las soluciones allí expuestas y sigo obteniendo exactamente el mismo resultado:
Probé pasar el header Accept como keyword a la función get de requests -> 415
Probé hacer una requests.Session y añadirle los headers con antelación a hacer el get -> 415
Probé incluir el Accept header en la URL tal como en los ejemplos que aparecen en la documentación ( https://developer.github.com/v3/media ) -> 415
Y he probado con todos los Custom Media types mencionados en la documentación y sigo obteniendo el mismo error :c 
De paso corroboré estar usando URL válidas, y efectivamente, al quitarles el "/reactions" del final me retornan los comentarios sin problema, pero al añadirle aquello en vez de las reacciones me retorna siempre el error 415 :/
De seguro que me estoy equivocando en algo súper estúpido xd pero ya no se que más hacer D:
# PleaseHelp

**Comment by aaossa** [comment]
> Probé pasar el header Accept como keyword a la función get de requests -> 415

Cómo hiciste esto? Debes agregar el header:

``` python
headers = {
    "Accept": "application/vnd.github.cerberus-preview+json"
}
```

en tu request así:

``` python
request.get(url, headers=headers)
```

**Comment by sitoro** [comment]
```
requests.get(url, headers = {
    "Accept": "application/vnd.github.cerberus-preview+json"
}, auth=H.credentials)
>> Response [415]
```

**Comment by aaossa** [comment]
Ahh ya, no sé si me confundí en la otra issue o apuntaba a algo distinto, pero estás usando el header incorrecto. Mira [la documentación](https://developer.github.com/v3/reactions/#reactions)

**Comment by sitoro** [comment]
Aah ok xd
Era exactamente eso :p 
AHí me funcionó ;)
