### ISSUE TITLE
Asignar Usuarios

### ISSUE THREAD

**Issue by spiza** [IIC2233-2016-1/syllabus#651]
Estoy teniendo problemas para asignar usuarios a issues.. 

Estoy haciendo:
`requests.post(url, auth=credentials, data=json.dumps(params), headers=header)`

Porfavor que alguien me ayude! Solamente me escupe el código 404, y no sé porqué! El header es `header = {
        "Accept": "application/vnd.github.cerberus-preview+json"
    }`, el mismo que publicó aaossa....

Plis jelp mi!

**Comment by jagaldames** [comment]
application/vnd.github.squirrel-girl-preview

prueba quizas con ese header, aun que no tengo claro si es para lo mismo

**Comment by spiza** [comment]
Ese header es para las reactions.. 

Enviado desde mi iPhone

**Comment by santiagocruzb** [comment]
Debe estar mala la url. Tengo lo mismo que tu y solo poniendo un slash de más, se cae.
Si no te tiraria otro error distinto a 404

**Comment by aaossa** [comment]
Puede ser lo que dice @santiagocruzb , ¿pudiste arreglarlo?

**Comment by spiza** [comment]
No!Qué slash está demás? @aaossa

**Comment by spiza** [comment]
el ulr es `"https://api.github.com/repos/IIC2233-2016-1/fake_syllabus/issues/{}/assignees"`
estoy usando esto que dice acá 
https://developer.github.com/v3/issues/assignees/

**Comment by spiza** [comment]
el corchete se llena con el número de la isssue

**Comment by spiza** [comment]
porfavor ayúdenme :'(

**Comment by santiagocruzb** [comment]
```
parametro = {
            'assignees':
                [
                    '{}'.format(nombre)
                ]
        }
```

yo tengoeso y funciona

**Comment by spiza** [comment]
Me da lo mismo :(... Cuál url estás usando? porfa ayuda.. ayer me quedé pegado en estoy y solo necesito solucionar esto!

**Comment by santiagocruzb** [comment]
https://api.github.com/repos/IIC2233-2016-1/fake_syllabus/issues/{}/assignees

**Comment by spiza** [comment]
@flobarrios :)

**Comment by spiza** [comment]
Es el mismo!! Por la rechucha! Porqué no me funciona!!!

**Comment by spiza** [comment]
estás usando request.post(esa_url, auth=credentials, header=ese_otro_header)??

**Comment by spiza** [comment]
y como data ese parametro dumpeado?

**Comment by santiagocruzb** [comment]
tengo exactamente lo mismo

**Comment by spiza** [comment]
wn, es que no entiendo por qué chucha no funciona esta weá.. me está cagando hacer el ítem 1.. sin esto no puedo hacer ítem 1

**Comment by aaossa** [comment]
Oye @spiza , primero que todo, **regula tu vocabulario**. No eres el único que ve este repositorio.

Segundo, que te retorna `req.json()`?

**PS:** Pushea tu código y voy a ver que pasa

**EDIT:** Y dime qué archivo debo mirar

**Comment by spiza** [comment]
Perdón.. me tiene un poco muy frustrado esto..

Me retorna esto:

`{
    "message": "Not Found",
    "documentation_url": "https://developer.github.com/v3"
}`

El código ya está arriba

**Comment by aaossa** [comment]
En qué archivo tienes esta request?

**Comment by spiza** [comment]
está en prueba request, al final

**Comment by aaossa** [comment]
1) Como dije en otras issues, para POST tienes que enviar tu diccionario como json en **data** (lo haces en params)
2) En la documentación dice `POST /repos/:owner/:repo/issues/:number/assignees`. Es el **número de issue**, no el id.

**Comment by spiza** [comment]
El punto 1 era porque estab desesperado.. 

el punto dos no sabía.. 

Eres un sol :)!

PD: No todos los héroes usan capa
