### ISSUE TITLE
GET /repos/:owner/:repo/labels me entrega solo 30

### ISSUE THREAD

**Issue by tblatrille** [IIC2233-2016-1/syllabus#652]
tengo una duda no sé por qué el comando sugerido por la documentación para hacer "List all labels for this repository" me entrega solo 30 (parece que los primeros 30) está bien? cuando busco obtener todos los del repo debo tomar esos 30 nomás?
ocupo la url
https://api.github.com/repos/IIC2233-2016-1/fake_syllabus/labels

por ejemplo hay muchos labels que me salen not found, ejemplo 'viva shile' que cree yo:
https://api.github.com/repos/IIC2233-2016-1/fake_syllabus/labels/viva_shile

pero bug por ejemplo que estaba antes:
https://api.github.com/repos/IIC2233-2016-1/fake_syllabus/labels/bug

EDIT:
la cierro era con pagination

**Comment by rmant** [comment]
Tengo el mismo problema, como lo solucionaste?? Gracias!

**Comment by tblatrille** [comment]
cuando haces el get obtienes una pagina, tienes que las url agregarle 'parametros' como page=3&per_page=50
para mostrar 50 objetos por pagina y tomando la pagina 3
https://developer.github.com/guides/traversing-with-pagination/#basics-of-pagination
