### ISSUE TITLE
T07 - Issues a revisar

### ISSUE THREAD

**Issue by jagaldames** [IIC2233-2016-1/syllabus#655]
Hola! Queria saber si podemos iterar y buscar solo en las issues abiertas, ya que son mas de 600 las issues totales y se demora muchisimo en filtrar toda la informacion. La implementacion es la misma, es cosa de cambiar un paramtero y hacer todo mas amigable.

gracias

**Comment by santiagocruzb** [comment]
Threads no?

EDIT: no hacer threads, se me acabaron las 5000 requests en nada de tiempo 👎

**Comment by flobarrios** [comment]
Hola !! no, no puedes. La idea es buscar sobre todas las issues. Lo que puedes hacer, es implementar ambos casos (con y sin issues cerradas) y comentar por ejemplo, el con las cerradas. Luego, en tu README dices que para probar con todas las issues, se debe des-comentar la línea 1 y comentar la línea 2. Saludos!
