### ISSUE TITLE
Problema get reactions

### ISSUE THREAD

**Issue by rmant** [IIC2233-2016-1/syllabus#656]
Cuando intento conseguir las reactions de una issue me dice 
`{
    "documentation_url": "https://developer.github.com/v3",
    "message": "If you would like to help us test the Reactions during its preview period, you must specify a custom media type in the 'Accept' header. Please see the docs for full details."
}`
Como puedo solucionar esto?  Gracias!
Me estoy basando en esta documentacion
https://developer.github.com/v3/reactions/#list-reactions-for-an-issue

**Comment by rmant** [comment]
Ya encontre la respuesta

**Comment by JoseRomeroi** [comment]
@rmant donde encontraste la respuesta?? me aparece constantemente eso

**Comment by aaossa** [comment]
> # [Reactions](https://developer.github.com/v3/reactions/#reactions)
> 
> To access the API you must provide a custom media type in the Accept header:
> 
> `application/vnd.github.squirrel-girl-preview`
