### ISSUE TITLE
Muchos requests

### ISSUE THREAD

**Issue by santiagocruzb** [IIC2233-2016-1/syllabus#657]
Hola! Tengo el siguiente problema.
Son 690 issues las que hay que analizar, las que están en 23 páginas. Hay que analizar a cada una de la issues por separado si tiene o no reacciones, lo que se hace con un requests. Y también hay que obtener todos los comentarios en caso que la issue los tenga.
Solo en issue voy en casi 1000 requests, si hago solamente `request.get(url,data=data)` sin entregarle **`auth=credenciales`**, no pierdo requests contables?
Saludos

**Comment by FernandoPieressa** [comment]
Sin credenciales son solo 60 requests contables por hora en todo caso, no te ayudara mucho :confused:

**Comment by cggutierrez** [comment]
en el enunciado creo que dice que hay que considerar issues después del 25 de mayo :s

**Comment by santiagocruzb** [comment]
Todas las issues fueron hechas hace 4 dias. Copiaron antiguas pero el
sistema no tiene como detectar eso.
