### ISSUE TITLE
Error T07

### ISSUE THREAD

**Issue by sitoro** [IIC2233-2016-1/syllabus#658]
Para acelerar las operaciones mas largas del repo (con centenas de requests involucrados) manejo la situación con threads que realizan solicitudes a la Api de github en paralelo.
Al checar la participación de usuarios en issues (si la crearon o comentaron en ella) para ciertos usuarios lo calculo sin problemas pero para otros me salen cientos de errores con este texto:

> ### Exception in thread Thread-118:
> 
> Traceback (most recent call last):
>   File "C:\tools\python\lib\site-packages\requests\packages\urllib3\connection.py", line 142, in _new_conn
>     (self.host, self.port), self.timeout, **extra_kw)
>   File "C:\tools\python\lib\site-packages\requests\packages\urllib3\util\connection.py", line 91, in create_connection
>     raise err
>   File "C:\tools\python\lib\site-packages\requests\packages\urllib3\util\connection.py", line 81, in create_connection
>     sock.connect(sa)
> TimeoutError: [WinError 10060] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "C:\tools\python\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 578, in urlopen
>     chunked=chunked)
>   File "C:\tools\python\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 351, in _make_request
>     self._validate_conn(conn)
>   File "C:\tools\python\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 814, in _validate_conn
>     conn.connect()
>   File "C:\tools\python\lib\site-packages\requests\packages\urllib3\connection.py", line 254, in connect
>     conn = self._new_conn()
>   File "C:\tools\python\lib\site-packages\requests\packages\urllib3\connection.py", line 151, in _new_conn
>     self, "Failed to establish a new connection: %s" % e)
> requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000004DC83C8>: Failed to establish a new connection: [WinError 10060] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder
> During handling of the above exception, another exception occurred:

Y así continua unas 100 veces, aunque no se me cae el programa, . Como puedo evitar esto?, ya que es muy probable que los threads que levantan errores no realicen satisfactoriamente su tarea arruinando mis resultados obtenidos.
Intente poner un try-except en los threads que en caso de fallar realicen de nuevo la petición al server, pero en tal caso el programa simplemente no terminó de ejecutarse :/

**Comment by aaossa** [comment]
Hasta cuantos threads al mismo tiempo tienes corriendo?

**Comment by sitoro** [comment]
En teoría llegan a ser hasta uno por cada issue... es decir... unos 600 :B

**Comment by aaossa** [comment]
Prueba con un número mas pequeño de threads. Quizás a Github no le guste tanto la idea de que lo bombardees con tantas requests

**Comment by sitoro** [comment]
Acabo de probar con máximo 2 threads simultaneos, se demoró 20 veces más xd, y aún así el thread 422 y los subsecuentes levantarón el mismo error u.u
