### ISSUE TITLE
Tarea 7 - Como armar el diccionario

### ISSUE THREAD

**Issue by Pochoclo** [IIC2233-2016-1/syllabus#659]
Hola, estoy tratando de armar el diccionario de palabras, para estoy estoy tomando el title y body de todos los issues y los agrego a un texto, luego le aplico el remove_stopwords y steaming pero me queda una lista con letras muy fea jaja ayiura

**Comment by sitoro** [comment]
prueba a ignorar las "palabras" de una letra
y recuerda que el remove stopwords recibe como argumento una lista con las palabras, y no el string a secas ;)

**Comment by Pochoclo** [comment]
Si!!! ahora cambié lo que estaba haciendo y es mucho mas bonito ahora jaja
