### ISSUE TITLE
Problemas con atributo precio de hipoteca

### ISSUE THREAD

**Issue by bmarinb** [IIC2233-2016-1/syllabus#66]
En el archivo de texto "productos.txt" el "precio de hipoteca" aparece sin los _ lo que impide generar el atributo sin hacer malabares. ¿Está sin los _ por error o intencionalmente?
Gracias de antemano.

**Comment by otro-felipe** [comment]
En el archivo de los usuarios la llave para el mail aparece como `"correo electronico"`. Las llaves aparecen tal como se detallan en el enunciado, es decir, los espacios estan intencionalmente. Recuerda que para tener el puntaje completo tu parser debe ser lo mas generico posible (i.e. leer jsons aunque este todo escrito en una sola linea, siempre manteniendo la estructura de un archivo json).
