### ISSUE TITLE
Issue problemática

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2233-2016-1/syllabus#660]
Hola: hay una issue que no puede ser tratada como un diccionario, creo que es porque tiene acentos fuera de las letras. ¿Asumimos que todas las issues van a tener un formato legible por json()? Hasta hace un rato me hacía bien las consultas, pero ahora siempre se cae en esa issue :/.
Gracias

**Comment by aaossa** [comment]
Que issue?

**Comment by AlfonsoIgnacioV** [comment]
creo que la 626

**Comment by aaossa** [comment]
No debería darte problemas. Seguramente estás haciendo mal una conversión. Puedes mostrar como la llamas y el error que te entrega?

**Comment by FernandoPieressa** [comment]
@aaossa yo encontre otra problematica que me estoy dando cuenta de muchos.

la issue 680 https://github.com/IIC2233-2016-1/fake_syllabus/issues/680

A todo el mundo le esta saliendo con el calculo porque no tiene nada entonces la distancia es mínima, que se hace en ese caso?

**Comment by ivaniadg** [comment]
Debe haber algo extraño, porque no tiene porque dar la menor distancia. Si el vector de la issue 680 es `[0, 0, 0]`, el de ia issue 1 es `[2, 0, 0.5]` y la issue  con la que comparo es `[2, 1, 0.5]`, las distancias serán:
1. 680 con i => (2x2 + 0 + 0.5x0.5) = 4,25
2. 1 con i => (0 + 1 + 0.5x0.5) = 1.25

Y claramente vemos que la distancia a la issue 1 es menor.

**Comment by AlfonsoIgnacioV** [comment]
obtengo una lista de 100 issues, es 

``` python
ruta = 'https://api.github.com/repos/IIC2233-2016-1/fake_syllabus/issues?page={}&per_page=100'
while quedan:
    _100 = self.obtener(ruta.format(contador))
```

donde self.obtener hace un get con los parámetros ya determinados. Entonces esta obteniendo una lista de 100 issues, sin embargo al obtener una llave correspondiente a esa issue (la 626), me tira un error de charmap can't decode character (nombre del caracter). Con ninguna otra me pasa eso.

**Comment by AlfonsoIgnacioV** [comment]
me faltó decir que obtener lo devuelve pasado ya por json() (request.get().json())

**Comment by aaossa** [comment]
Yo no tengo ningún problema con la issue. Revisa el encoding que usas.

**Comment by Meaylwin** [comment]
@indonoso que estas comparando de cada issue? el vector IDF-TF?
tu respuesta la encuentro totalmente logica, pero no se que estas comparando
EDIT: Por lo que entiendo estas comparando los vectores TF, entonces de que nos sirve el vector IDF?

**Comment by ivaniadg** [comment]
Son los TF-IDF. @AlfonsoIgnacioV dice que siempre le aparece la issue que no dice nada como la más similar y yo digo que eso me parece raro, por lo que expliqué arriba.

**Comment by AlfonsoIgnacioV** [comment]
pero json de qué manera lo encodea?? Gracias

**Comment by aaossa** [comment]
@AlfonsoIgnacioV puedes hacer una request a la issue 626, ver si te sigue pasando y si es así mostrar dónde se produce el error?
