### ISSUE TITLE
Issue problemática

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2233-2016-1/syllabus#661]
Hola: hay una issue que uno puede ser tratada como un diccionario, creo que es porque tiene acentos fuera de las letras. ¿Asumimos que todas las issues van a tener un formato legible por json()? Hasta hace un rato me hacía bien las consultas, pero ahora siempre se cae en esa issue :/.
Gracias

**Comment by aaossa** [comment]
Que issue?

**Comment by aaossa** [comment]
Movido a #660
