### ISSUE TITLE
Recorrección T03 y AC12

### ISSUE THREAD

**Issue by jneyzaguirre** [IIC2233-2016-1/syllabus#662]
Hola, me gustaría saber cuando subirán las recorrecciones de la tarea 3, ya que no me ha llegado nada de la mía. También de la AC12.

Saludos, y desde ya gracias!

**Comment by FernandoPieressa** [comment]
Tengo el mismo problema, alguien en otra issue #608 pregunto y le respondieron que vea su repositorio, sin embargo no me llego nada

**Comment by aaossa** [comment]
@mjjunemann @bamavrakis

**Comment by agmardones** [comment]
Hola! a mi tampoco me ha llegado la recorrecion de la T03, y aprovecho para decir que no tengo feedback en la T05 :(

**Comment by mjjunemann** [comment]
@agmardones , te publique tu feedback de la T05 en tu repositorio, y estaba viendo las recorrecciones de la T03, y no aparece como que mandaste el formulario.

**Comment by FernandoPieressa** [comment]
@mjjunemann Puede verificar mi recorrecion de la T03 también? No me llego nada y si mande el formulario

**Comment by agmardones** [comment]
@mjjunemann creo que soy un caso especial, la mandé 30 minutos tarde después de la entrega en un mail a @jecastro1. Me respondió que la revisarían excepcionalmente porque pasó muy poco tiempo después del cierre del cuestionario, por lo mismo quería saber si no la habían pasado por alto.

**Comment by jfcumsille** [comment]
@mjjunemann yo también estoy en las mismas! Mande el formulario de recorreccion y aún no he recibido respuesta. Si es verdad que ya están las recorrecciones, podrías ver que paso con la mía?

**Comment by aaossa** [comment]
@jneyzaguirre, @agmardones, @FernandoPieressa, @jfcumsille : Sus casos serán revisados en la recorrección final, cuya fecha será anunciada después del examen
