### ISSUE TITLE
Recorreccion Tarea 5

### ISSUE THREAD

**Issue by fnquinteros** [IIC2233-2016-1/syllabus#663]
cuando abrirán un cuestionario para la recorrecion de la T05? No sé porqué figura un 1 en mi nota y lo entregué a tiempo y estoy seguro que es mucho más que un 1 la nota que corresponde :sweat_smile:

**Comment by caackermann** [comment]
Aprovecho de preguntar cuando estara disponible el feedback de la misma.

**Comment by isarovic** [comment]
Me paso lo mismo ![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f605.png)

**Comment by jpdattas** [comment]
a mi un  1.15... hay algo raro

**Comment by aaossa** [comment]
Hola, la razón de sus notas están en los feedbacks. Saldrán pronto del horno. De los que han hablado aquí, tienen la nota bien justificada en el feedback, asi que no hay nada raro

**Comment by isarovic** [comment]
Yo hice 2 commit, el primero con toda la tarea y el segundo con solo el readme, y me revisaron solo el del readme.

**Comment by aaossa** [comment]
@isarovic, si se dice que se revisará un commit los cambios que se hicieron antes de este están considerados. Lo que se dice con el commit es: "Revisaremos todo lo que tienes en la carpeta T05 hasta este cambio". Tienes que mandar a recorregir si no estás de acuerdo con tu nota

**Comment by isarovic** [comment]
![comit](https://cloud.githubusercontent.com/assets/13775347/16360605/0cb3841a-3b42-11e6-9bb8-114f4086ca25.png)
![comit2](https://cloud.githubusercontent.com/assets/13775347/16360606/0e509df8-3b42-11e6-8c2d-27e17f107afb.png)

No se que sucedió pero ahí sale que el último commit fue el del readme y que hice otro commit antes (7f1154b) con todos los archivos como se puede ver en la foto. En el feedback sale: Commit a revisar: e5c15e4 y sólo me pusieron 0´s y no habían comentarios!

=(

**Comment by jpdattas** [comment]
A mi me sale "No se ve nada de la interfaz cuando se inicia el juego (http://imgur.com/fEiDhDq) por lo que fue imposible probar la mayoría de las funcionalidades." Pero a mi si me funciona bien. Comento sobre todo para que no sea que mande a recorregir y simplemente no le sirva de nuevo
![imagen juego](https://cloud.githubusercontent.com/assets/13739046/16360842/9a1e0590-3b4d-11e6-8bec-2c3e8300ecb7.png)

**Comment by sialvarez** [comment]
A mí me pusieron que "No aparecen pelotas en el juego, no se puede evaluar gran parte de la tarea." Siendo que a mí si me aparecen, habían dicho en algunas issues que no había que subir las imágenes de las pelotas en la carpeta, ¿habrá sido por eso?

http://imgur.com/oOs2rjJ

**Comment by aaossa** [comment]
@sialvarez , @jpdattas , @isarovic : Como dije, deben mandar a recorregir si no están de acuerdo con su nota, esa es la instancia para hacer llegar sus desacuerdos y dudas, **no el Syllabus**. El formulario será abierto a la brevedad y se les avisará con un anuncio mediante SIDING.
