### ISSUE TITLE
Duda sobre readme

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#664]
Para la tarea 7, hay una parte del código que debí cambiar antes de la hora límite, pero olvidé modificar después ¿si lo menciono en el readme, será considerado? Es sobre la fecha a abarcar con el repositorio, que la tenía a una muy reciente para reducir el volumen de data a trabajar mientras probaba el código :/

**Comment by flobarrios** [comment]
Si! menciónalo en el README para que sea tomado en cuenta (pero tiene que ser un cambio mínimo en el código, como comentar una linea o cambiar la fecha por otro valor). Saludos!
