### ISSUE TITLE
Materia Examen

### ISSUE THREAD

**Issue by vbarros2** [IIC2233-2016-1/syllabus#665]
Que materia entra para el examen y hasta donde?...  habrá énfasis en los últimos tópicos mas que en los primeros??

Saludos y gracias

VBarros

**Comment by ivaniadg** [comment]
La materia del curso es acumulativa, así que sí entra todo :)

**Comment by santiagocruzb** [comment]
@indonoso que pasa con respecto a las lecturas?

**Comment by IsaacConDosA** [comment]
@indonoso Entra uso de API's?

**Comment by indonoso** [comment]
Hola!

Las lecturas **sí** y web services **no**

**Comment by ivaniadg** [comment]
Las lecturas **sí** entran y webservices **no**
