### ISSUE TITLE
Examenes de Semestres pasados?

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#666]
Desearia saber. ¿Tienen examnes de semestre pasados para estudiar para el del martes?

**Comment by ivaniadg** [comment]
Hola! 
Las pautas del año pasado están en los syllabus de cada semestre.

**Comment by perojas3** [comment]
Ok
Pero en el semestre pasado solo estan la I1 y la I2, no el examen.
¿Y no hay más?
