### ISSUE TITLE
Sala de ayudantía examen?

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#667]
En el siding cuando avisaron de la ayudantía, dijeron que lo anunciarían "a la brevedad", pero como no encuentro un nuevo aviso en ningún lado y mañana sería la ayudantía, prefiero asegurarme preguntando aquí.

**Comment by aaossa** [comment]
> Chicos, 
> 
> Les recuerdo que mañana tendrán ayudantía a las 14:00 de repaso para el examen.
> 
> Saludos

La sala se avisará mañana

**Comment by andresfdezc** [comment]
Hola! Será en la A4
