### ISSUE TITLE
Ayuda en el DCC

### ISSUE THREAD

**Issue by ivaniadg** [IIC2233-2016-1/syllabus#668]
Como dije en la ayudantía, los que estén muy perdidos pueden ir a preguntarme hoy de 17:15 a 18 en la sala Álvaro Campos. La sala está muy llena, así que pueden pasar a mi oficina (pecera al lado de la sala notebook friendly).

Saludos!

**Comment by fgvenegas** [comment]
Yo y @btkramm estaremos igual en la Álvaro Campos como una hora si quieren alguna duda más pequeña
