### ISSUE TITLE
Duda recorrección midterm

### ISSUE THREAD

**Issue by dtfuller** [IIC2233-2016-1/syllabus#669]
Hola  a todos! 

Me gustaría saber si algún ayudante puede confirmar que mi midterm efectivamente haya sido recorregido y la nota esté actualizada, ya que (respetuosamente) no me hace mucho sentido que no me haya subido. 

En el caso de que sí haya sido recorregido, podría obtener algún feedback de éste proceso? 

Saludos y muchas gracias de antemano :+1:

**Comment by JoseRomeroi** [comment]
+1
Yo fui a la ayudantia hoy, efectivamente me subió la nota pero tampoco se me actualizó en la planilla

**Comment by ivaniadg** [comment]
Ahora sí! Las pruebas están en el mismo cajón y las pueden pasar a buscar

**Comment by dtfuller** [comment]
Muchas graciass! ahora si me hace sentido :)
