### ISSUE TITLE
Multa

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233-2016-1/syllabus#67]
¿Un usuario puede tener mas de una multa?, si es así, ¿tenemos que arreglarnos para que el usuario decida que multa pagar o si tiene mas de 1, solo se le aumenta el monto de la multa para que así solo tenga 1?

**Comment by otro-felipe** [comment]
Si, puede ser que un usuario tenga mas de una multa. Deben hacer que el usuario decida que multa quiere pagar, ya que estas pueden tener distintas fechas de vencimiento y el usuario quiera cancelar solo la mas cercana a vencer.
