### ISSUE TITLE
Forma de encontrar los mejores de una lista.

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#670]
Esto es algo dificil de explicar. Estoy haciendo el ejericio de la ayudantia y tengo un problema.
Es al principio, cuando se debe encontrar los grupos con el mejor puntaje, y solo debo dejar entrar a los mejores.
Siempre tengo este problema en situaciones similares, que no sé cual es la mejor forma de obtener el "mejor" de una lista de objetos de una clase, basados en un atributo de la clase.
En este caso, no se me ocurre una manera rapida de escribir que el programa busque cual es el grupo con el mejor puntaje.
Mi problema es sobre todo que me gasta mucho tiempo en las interrogaciones, en las actividades, y más del que desearia en las Tareas.
¿Algun consejo?

**Comment by ivaniadg** [comment]
Hola!
En el caso de la ayudantia no es necesario encontrar al mejor. Hay una solución a eso en la modelación que subimos.
En el caso general si quieres buscar al mejor de una lista (el índice, no el valor) lo puedes hacer de la siguiente forma:

``` python
max_index = 0
max_value = 0
for i, v in enumerate(lista):
if max_value < v:
    max_index = i
    max_values = v
```

Esto sirve para objetos de cualquier tipo que implementen `__ge__`.
Si quieres usar una librería que hace esto de forma rápida sobre una lista de números (`int` o `float`) puedes usar el método `argmax` de la librería `numpy`.

**Comment by criscv94** [comment]
Hola!
Yo tenía la misma duda y en una de las actividades en clases me enseñaron que podía hacerlo con sorted de esta manera:
`self.inscritos = sorted(self.inscritos, key=lambda x: x.idea.puntaje, reverse=True)`
En el `key` pones en base a qué atributo quieres ordenarlo. En este caso, `self.inscritos` es una lista con cada grupo y cada grupo tiene en sus atributos la idea con su puntaje.
