### ISSUE TITLE
[Examen Semestre Pasado}

### ISSUE THREAD

**Issue by vbarros2** [IIC2233-2016-1/syllabus#671]
Alguien tiene el enunciado del examen del semestre pasado??, ya que están solo las soluciones.
Falta solo la pregunta 1 en realidad...

Gracias!

**Comment by perojas3** [comment]
Exacto, solo falta la pregunta 1, y la respuesta es una especie de diagrama.

**Comment by perojas3** [comment]
Tambien falta el enunciado de la pregunta 4. Solo esta larespuesta.
