### ISSUE TITLE
Notas T06 y/o T07 antes del examen?

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#672]
Quisiera preguntar lo que indico en el título, si es que esperable tener alguna de ellas antes de la fecha del examen, o mejor asumir a que estarán después lo más probable n.nU

**Comment by bamavrakis** [comment]
Hola!! Efectivamente estamos trabajando para que estén las notas de la T06, T07 y las recorrecciones de la T04 y T05 para el Lunes a medianoche :D.
Saludos!

**Comment by MortizDX** [comment]
Mm, okey, muchas gracias

**Comment by MortizDX** [comment]
¿Ocurrió algo con las notas? Que aún no aparecen en el excel, pero no estoy seguro si es por mi lado (problema de caché?) o aún no las suben.

**Comment by aaossa** [comment]
Hubo un problema administrativo, pero puedes estar seguro de que estarán antes del jueves, para la recorrección final

**PS:** Disculpa las molestias
