### ISSUE TITLE
Threading: prioridad?

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#673]
(No estoy seguro si alguien hizo una pregunta similar antes, no la encontré en el foro)
Viendo la materia de threading, específicamente sincronización, me entra la duda de cuando dos threads quieren intentar interactuar con el buffer **al mismo tiempo** ¿existe alguna forma de saber cuál tendrá la prioridad "siempre"? Que corriendo el 2do ejemplo de esa materia (el que viene antes de "queque"), el orden en que ocurren las cosas varía.

**Comment by robocop6** [comment]
Hola!

La coordinación de threads "a bajo nivel" es muy compleja y requiere de gente especializada trabajando en ello. En el fondo, la pregunta a la que aludes tiene que ver con lo siguiente: dado que en este momento existen ciertos threads corriendo, que yo tengo procesadores limitados, que ciertas tareas tienen que terminar antes de X tiempo, etc., ¿cómo determino a cuál de esos threads "darle permiso" para usar los procesadores disponibles en este momento? Esta labor se conoce como scheduling. Existen muchas formas de implementarlo, pero la "idea intuitiva" es que debe haber una rutina que decide qué hacer a continuación ("scheduler"), y que debe estarse llamando constantemente.

Lo anterior es solo una introducción para que puedas comprender un poco mejor algunas respuestas que se encuentran en internet frente a este tema. El scheduling está fuera de los contenidos del curso (se aborda en arquitectura de computadores). No quiero entrar en detalles, pero imaginarás que el problema es muy complejo (solo a modo de ejemplo, si estoy llamando al scheduler "a cada rato", voy a perder mucho porcentaje del poder de procesamiento en decidir qué hacer a continuación, en lugar de hacer algo verdaderamente productivo!). 

Por esto, generalmente cuando uno trabaja "a alto nivel", no se preocupa mucho de cómo están implementadas las labores como el scheduling. Uno simplemente confía en que la persona que lo implementó hizo bien su pega y las cosas funcionarán como corresponden. De hecho, en [este link](http://stackoverflow.com/questions/11421651/controlling-scheduling-priority-of-python-threads), se dice que, al parecer, no existen formas de controlar, en python, la scheduling priority de los threads. Así que... por eso, a veces uno consigue acceso primero, y otro después. Existen **muchos** factores involucrados en cuál se prioriza, y había que "entrar a picar" en cómo están resueltos estos temas en python para conocer con mayor nivel de certeza qué va a ocurrir en una situación dada.

Así que para resumir... es una pregunta muy interesante, pero saber exactamente qué está ocurriendo, y cómo el corazón de python decide qué prioridad asignar a los threads en cada momento no es para nada trivial. Si estás interesado en conocer más detalles sobre la implementación de threads en python, busca por "global interpreter lock python".

**Comment by MortizDX** [comment]
Muchas gracias por la respuesta! Hacía esta pregunta porque si en el exámen tenemos que aplicar sincronización, quería saber si sería necesario tener eso claro para resolver un problema, ya que parecía algo aletorio cuando lo corría en el computador. Por el momento (para fines del examen), solo me debería preocuparme de los locks mismos y no cómo interactuan al mismo tiempo los threads?

**Comment by robocop6** [comment]
Tener claro en detalle cómo es que en python se determina qué hacer a continuación no es necesario. 

En este curso nos preocupamos de cómo **evitar que varios threads accedan a un mismo recurso simultáneamente**. Lo que debes saber es cómo implementar locks para que no ocurra este problema, pero la pregunta sobre cuál de todos los threads accede a un lock primero, este... ciertamente no es aleatorio, pero dejémosla para el global interpreter lock mejor? ;)

**Comment by MortizDX** [comment]
Dale, muchas gracias por la respuesta!
