### ISSUE TITLE
GET, POST y HTTP en el examen?

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#674]
En el examen del 2015-1 se pregunto que hacen GEY y Post. Y segun la solución, son de HTTP.
Eso no entra en este examen ¿Verdad?

**Comment by aaossa** [comment]
#665 

> Las lecturas sí entran y **webservices no**

Por lo tanto, no entra

**Comment by perojas3** [comment]
Ok, gracias.

**Comment by negebauer** [comment]
@perojas3 Recuerda cerrar el issue si tu pregunta fue respondida 😉

**Comment by perojas3** [comment]
OK, acavo de enterarme que yo puedo cerrar issues.
