### ISSUE TITLE
Duda respecto a las referencias.

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#675]
Me surgio una duda al hacer la peregunta 1 g) del examen del 2015-1
Es sobr ecomo cambian las referencias. El ejercicio consiste en encontrar lo que retorna un codigo. Mi problema esta en esta funcion:

``` python
def f1(_input):
    if type(_input) in [int, float, bool, str]:
        _input = 2
    else:
        _input[0] = _input[-1]
    return True
```

Al cambiar una referencia de una lista en una funcion, se cambia la lista en todas pates. ¿Pero al cambiar un str o un int no?

**Comment by negebauer** [comment]
Puedes hacer un script para probar esto
Para tu suerte, lo hice por ti

``` python
>>> def f1(_input):
...     if type(_input) in [int, float, bool, str]:
...         _input = 2
...     else:
...         _input[0] = _input[-1]
...     return True
... 
>>> a = [0,1,2,3]
>>> b = 3
>>> f1(a)
True
>>> a
[3, 1, 2, 3]
>>> f1(b)
True
>>> b
3
```

En resumen: Si

**Comment by perojas3** [comment]
Ya hice el script. Pero me refiero a más al porque pasa.
Si las listas cambian la referencia al cambiarla en una funcion. ¿Con cuales otras pasa, o no pasa? ¿Y bajo que condiciones?

**Comment by negebauer** [comment]
Depende del tipo, mutable o inmutable
Si quieres leer un poco más http://stackoverflow.com/questions/8056130/immutable-vs-mutable-types

**Comment by ivaniadg** [comment]
Mira [esta issue](https://github.com/IIC2233-2016-1/syllabus/issues/481)

**Comment by perojas3** [comment]
Ok gracias.
