### ISSUE TITLE
Duda metaclases

### ISSUE THREAD

**Issue by JoseDaroch** [IIC2233-2016-1/syllabus#676]
Hola,
Estaba revisando la materia y aún no logro entender cual es la función del _ _init_ _, vale decir, que podría llegar a hacer modificando este en la metaclase, que podría cambiar en mi clase, no se jaja
Gracias!

**Comment by btkramm** [comment]
En general preferirás usar `__new__`, pues te ofrece muchas más libertades. La gracia de `__init__` es que en este punto la clase ya existe, así que puedes hacer referencia a ella ¿Por qué me gustaría tener referencia a ella en la etapa de su creación? Lo desconozco. Todo depende de cuál se tu objetivo.
