### ISSUE TITLE
Problema intentando ver el examen del semestre pasado.

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2233-2016-1/syllabus#678]
Hola! Debido a que el examen del semestre pasado ha sido subido como archivo zip, ¿cómo puede hacerse para abrirse directamente desde el syllabus, sin necesidad de descargarlo? 
Muchas gracias
Saludos

**Comment by perojas3** [comment]
¿Formato zip? ¿A que te refieres?

**Comment by AlfonsoIgnacioV** [comment]
Es como está subido. En la carpeta interogaciones, está el archivo comprimido del examen y no me deja verlo :/

**Comment by ivaniadg** [comment]
Debes descargarlo :/ no conozco una forma de ver los archivos de un zip online.

**Comment by AlfonsoIgnacioV** [comment]
Lo descargué... sin embargo, no sé cómo abrir esos archivos, específicamente, aquellos en formato .ipynb y MD

**Comment by ivaniadg** [comment]
md es un archivo markdown. Lo puedes ver en editor de texto. Para los archivos .ipynb tienes dos opciones: 
- Puedes instalar el interpretador [aquí](http://jupyter.org/). Sigue las instrucciones :). Esta es la opción recomendada, te permite probar el código en el mismo notebook.
- Subirlo a tu git y verlo desde tu repo en github

**Comment by perojas3** [comment]
Los md los puedes leerlos con pycham sin problemas.

**Comment by AlfonsoIgnacioV** [comment]
Lo subí a mi repo...
El problema es que junto con eso se subieron algunos cambios posteriores a la tarea :O .... en la tarea 5 y 7, específicamente... ¿Qué puedo hacer con eso?

**Comment by ivaniadg** [comment]
da lo mismo porque ya fueron recolectadas :+1:

**Comment by AlfonsoIgnacioV** [comment]
ok, muchas gracias!! :)
