### ISSUE TITLE
Feedback T05 (issue)

### ISSUE THREAD

**Issue by tblatrille** [IIC2233-2016-1/syllabus#679]
Hola no me aparece nada en el  issue correspondiente al feedback (o evaluación) de mi T05, pensé que simplemente se estaban demorando en aparecer pero hoy termina la recorrección y aparece todo en blanco sin ninguna asignación de puntaje en nada.

**Comment by aaossa** [comment]
Hola, tu feedback ya habría sido actualizado.  Por favor confirma si fue así y cierra la issue :grin:
