### ISSUE TITLE
Formato fecha

### ISSUE THREAD

**Issue by Zepk** [IIC2233-2016-1/syllabus#68]
En el pdf de la tarea, y en varias respuestas a las issues se menciona que el formato de la fecha para inicio y termino de las subastas es  dd/mm/aa/hh:minmin

Sin embargo en los archivos txt los datos estan escritos en el formato aaaa/mm/dd/hh:mm:ss,  como en el siguiente : "fecha_inicio": "2013-10-16 19:41:35

La pregunta es, si cambiaran los archivos para calzar con el formato que se menciona en el enunciado, cambiaran el enunciado para que calce con los datos entregados, o si se supone que yo tengo que cambiar los datos del formato entregado al pedido en el momento en que yo guarde los datos en el txt.

**Comment by otro-felipe** [comment]
El formato de las fechas seran los que estan en los archivos! Esperamos arreglar el pdf pronto :) (perdon por el error).

**Comment by Zepk** [comment]
Oka, gracias

**Comment by negebauer** [comment]
Lo voy a dejar abierto un rato por si alguien más tiene la misma duda :)

**Comment by jecastro1** [comment]
Fixed en b0b2eb26f37e4509d0b91816a2f49244edbc7764
