### ISSUE TITLE
Duda sobre el control 1.

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#680]
https://github.com/IIC2233-2016-1/syllabus/blob/master/Controles/Control%201.md
Tengo una duda por cada pregunta 3.
Sobre los 3 comando (uniq,grep, sort y echo)
En la ayudantia del viernes me dijieron que era de una consola unix. Pero en la lectura nunca mencionan esos 4 comandos:
https://www.codecademy.com/learn/learn-the-command-line
¿De donde viene esa manteria?

**Comment by ivaniadg** [comment]
Hola @perojas3 .
Ese tutorial tiene 4 unidades. Los 4 comandos aparecen en la unidad 3 :)

**Comment by perojas3** [comment]
Acavo de terminar la lactua. Pero solo la encontre dividada en 3 partes, y no me econtre con el uniq.

**Comment by ivaniadg** [comment]
La unidad 3, sección 9 se llama uniq

**Comment by perojas3** [comment]
ok
