### ISSUE TITLE
Duda Interfaz grafica

### ISSUE THREAD

**Issue by cggutierrez** [IIC2233-2016-1/syllabus#681]
No tengo bien claro que se considera como Front-end y Back-end, he googleado un poco pero no logro entender el concepto, si me pueden explicar con un ejemplo estaria agradecido! (o usando mi tarea 5 como base de ejemplo :C ).

**Comment by indonoso** [comment]
#502

**Comment by ivaniadg** [comment]
Viste esta issue #502 ?

**Comment by cggutierrez** [comment]
Lo habia visto cuando se creo el issue y no habia entendido, pero ahora me quedo mas claro, gracias!!
(y sorry por no recordar ese issue :confused:  )
