### ISSUE TITLE
Dudas sobre pregunta 3 examen 2015-2

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#682]
Tengo unas dudas al respecto. En esta nos piden lo que imprime un codigo respecto a las metaclases. Y tengo algunas dudas.
1.- Cuando imprime la clase en el new e init le salen respectivamente `<class '__main__.Meta'>` y `<class '__main__.A'>`. Desearia saber ¿Que son estas cosas y como se supone que deberiamos saberlas? En la materia aparece de repente cosas como esta al imprimir funciones y clases no instanciadas, pero comunmente son bastante más largas. Es como si esperan que hubisesmos experimentado haciendo print en cada lugar posible.
2.- ¿Porque la bases en el init estan bacias si en el new le agrego el B?
3.- Los atributos impresos en init, cuales son '**module**' y "**qualname**" ¿Que hacen y como llegaron?
4.- Sobre el **mro** del final. En las actividades tubimos que usar el metodo .mro() para determinar si una clase instanciada hereda de otra anterior. ¿Pero que hace al ser llamada aquí? Pues parece que la unica diferencia es que retorna una tupla en vez de una lista.

**Comment by ivaniadg** [comment]
Hola  @perojas3,

Te respondo por partes:
1. En este caso la clase está vacía, así que es normal que no tenga nada extra. El ejercicio de imprimir lo han visto y hecho varias veces. Es parte del material y es parte del trabajo que se espera que hagan para entender esta materia en particular.
2. Esto es parte de la materia. Los atributos del `__init__` son: la clase que fue creada por el `__new__` y luego los mismos parámetros que recibe el `__new__` con los **mismos** valores. 
3. El método `__mro__` entrega la clase actual y las clases de las que hereda.

**Comment by perojas3** [comment]
Perdon, con la primera. pregunta. Es que github no la mostro bien. Eso es lo que tengo duda:
`<class '__main__.Meta'> , <class '__main__.A'>`
¿Que son esas cosas, como llegaron alli? ¿Que significan los simbolos < y >?  ¿Y como se supone que sabriamos que se imprimirian eso?
Sobre el segundo. Si tiene los mismos valores el init con el new, ¿Entonces porque puede hacer cambios al diccionario en el new y se mantienen en el init? Pregunte algo similar hace unos días, pero estamos hablando de diccionarios y tuplas. Ambos inmutables.
¿Y que hay de la tercera, respecto a los metodos  'module' y "qualname"?

**Comment by ivaniadg** [comment]
> ¿Que son esas cosas, como llegaron alli? ¿Que significan los simbolos < y >? ¿Y como se supone que sabriamos que se imprimirian eso?

Es la representación de las clases, se escriben como _<class '{modulo}.{nombreclase}'>_. Los símbolos _<_ y _<_ no signfican nada, solo son la forma en que se imprimen. Si han impreso clases durante el semestre (esperamos que lo hayan hecho al menos una vez). De todas formas no fuimos SUPER estrictos en esa correción. Si te faltaban esos símbolos, igual tenías todos los puntos.

> Sobre el segundo. Si tiene los mismos valores el init con el new, ¿Entonces porque puede hacer cambios al diccionario en el new y se mantienen en el init? Pregunte algo similar hace unos días, pero estamos hablando de diccionarios y tuplas. Ambos inmutables.

No son los mismos objetos, solo tienen los mismos valores.

> ¿Y que hay de la tercera, respecto a los metodos 'module' y "qualname"?

Se me olvidó responderte eso, lo siento :). _module_ tiene el nombre del módulo en donde se está ejecutando. En el caso del ejercicio el módulo es `__main__`
_qualname_ se usa para evidenciar la indentación de los métodos y funciones. En este caso la clase _A_ es la que tiene el mayor nivel, por lo que no imprime nada más.
Con este código se entiende más

``` python
def dec(f):
    def _dec(a, b):
        return f(a, b)*2
    return _dec

@dec
def sumar(a, b):
    return a + b

print(sumar)
```

```
<function dec.<locals>._dec at 0xb497c89c>
```

Si te fijas la función `sumar` fue reemplazada por la función `_dec`. Esta es una función que se define dentro de `dec`

**Comment by perojas3** [comment]
Con su ejemplo <locals> me confunde. Pero entiendo lo otro.
Ok. Ya entendi eso. Lo que me queda de duda es lo de las bases, ¿Si lo que recive el init es lo mismo que recive el new, porque puede cambiar el diccionario de los atributos/metodos? Es que no entiendo porque en el octavo print no es la tupla con el B.
(me equivoque al cerrar el issue)

**Comment by ivaniadg** [comment]
No sé qué es lo que no entendiste :S 

Pero respecto a la segunda pregunta. La respuesta la di arriba, el `__init__` recibe como parámetros los mismos valores que recibió en `__new__`. En este método `bases` es una tupla vacía, por lo que en el `__init__` también es una tupla vacía.

**Comment by perojas3** [comment]
¿Entonces donde se guarda el B para que pueda ser impreso en el mro?

**Comment by ivaniadg** [comment]
Está dentro de la clase. Recuerda que la clase **ya fue creada** antes del `__init__`

**Comment by perojas3** [comment]
En ese caso no no entiendo porque tiene su bases vacias. ¿Cuando ya fue crada deja de tener bases?

**Comment by ivaniadg** [comment]
@perojas3 
El `__init__` recibe los mismos **valores** que el new en los parámetros `name`, `bases` y `attr`. El primer parámetro del `__init__` recibe la clase **ya creada**, que tiene todas las modificaciones a `name`, `bases` y `attr` que se hayan hecho en el `__new__`

**Comment by perojas3** [comment]
Ah.. ok,  ya entiendo entonces. Imprimiria el B, si le hicieramos cls.bases. Gracias.

**Comment by MortizDX** [comment]
Hay algo que no estoy entiendo de metaclases con este ejemplo ¿por qué razón el `__init__` utiliza las variable `name` y `bases` entregadas al `__new__`, pero utiliza el `attr` después de ser modificado en el mismo? ¿tiene alguna utilidad eso?

**Comment by ivaniadg** [comment]
@MortizDX No entiendo la pregunta :confused:

**Comment by MortizDX** [comment]
Que por qué razón el  `__init__` utiliza los valores de las variables `name` y `bases` tal como estaban **antes** de que puedan ser modificadas por el `__new__`, pero el valor de la variable `attr` la recibe tal como estaba **después** de que el `__new__`la haya modificado.

**Comment by ivaniadg** [comment]
Por lo que decía @perojas3. Lo que ocurre es que son las mismas variables, pero `name` y `bases` fueron reemplazados por nuevos valores, en cambio `attr` fue **modificada**. Si hubiesen hecho `attr = {'new': 1}`, entonces `atrr` sería el original y no el modificado.

**Comment by MortizDX** [comment]
Entonces mi pregunta más bien es por qué ocurre o más bien si tiene alguna utilidad. Que yo pensaría que el `__init__` tomaría los valores que entregó el `__new__` luego de modificarlos (o sea, si new modificó o más bien cambió el valor de `name` y `bases`, lo que yo esperaba originalmente es que el init tomaría esos valores, al venir después del new ¿se entiende?)

**Comment by ivaniadg** [comment]
Los valores nuevos igual los tienes en la clase. Al menos, yo nunca lo he usado, pero así es la implementación de python actualmente. Si quieres puedes inscribirte en una de las [mailing list](https://www.python.org/community/lists/) y sugerir el cambio.
