### ISSUE TITLE
Dudas sobre pregunta 1  I2 2015-1

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#683]
Tengo otra pregunta en la I2 del semestre 2015-1.
Es la pregunta 1, la del robot amigo, pero hay que comprimir los bytes que nos manda.
Tengo la siguientes dudas:
1.- ¿Solo me pueden llegar 2 tipos de bytes desde el robot? Es que en ese caso seria tan simple como codificar los 2 bytes como 1 y 0, y decodificarlo.
2.- Tengo la intuicion de ya haber hecho este ejercicio. ¿Lo hicimos en una ayudantia o algo?

**Comment by ivaniadg** [comment]
1. Te dicen que uno de los **_bits**_ se repite con más frecuencia. Los _bits_ solo tienen dos valores, 0 o 1.
2. No lo sé :smile_cat:

**Comment by perojas3** [comment]
¿Tienes el soucionario?
Es que me gustaria ver la respuesta.

**Comment by ivaniadg** [comment]
Nopes :D habían muchas opciones posibles, así que no hubo solución.

**Comment by jtagle2** [comment]
@perojas3 Me suena haber visto la respuesta por ahí. Una opción era obtener los índices de los bits que menos se repites, otra era enviar las distancias entre los bits que menos se repiten. Eran cosas como eso si mal no recuerdo

**Comment by perojas3** [comment]
Ok, lo pensare entonces.
