### ISSUE TITLE
Dudas respecto a los diccionarios por comprensión.

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#684]
Esto viendo el control 2, forma 2, ejercicio 1.
En este aparece un diccionario por comprensión, y no entiendo la forma en que lo definió. Aquí esta e diccionario:

```
l = {}
l.update({k: v for k, v in zip(args, f(*args)) if v > 5})
```

El zip es esto:
`[('Pedro', 5), ('Gustavo', 7)]`
Y deberia dar como resultado el siguiente diccionario:
`{'Gustavo': 7}`
Mis dudas son respecto a como se forma el diccionaro con el v, el k y el for.
1.- `k: v for k` ¿Que es el k?, se supone que el `for` deberia retornar lo que retorna de una iteración del k, lo que seria el v. ¿Porque aquí lo interpreta como el primer elemento de la tupla?
2.- `v in zip(args, f(*args)) if v > 5` Entiendo que aquí esta definiendo el v como un elemento del zip ¿Pero porque lo interpreta como el segundo elemento de la tupla? Digo, solo ese se le puede aplicar al if `if v > 5`, porque es numerico.
Eso seria. Muchas gracias

**Comment by jtagle2** [comment]
@perojas3, creo que estás entendiendo (separando) mal el código, y eso te lleva a confusión.
Cuando recorres un iterable con un for (`for value in iterable`), si tu iterable posee como elementos, otros iterables, puedes separarlos en distintos argumentos haciendo 
`for value1, value2, value3, ... , valueN in iterable`
En donde  `iterable`, deberá tener como elementos, objetos iterables de largo N. Y value1 será elemento[0], value2 será elemento[1] etc...
Es decir, el for anterior, sería similar a hacer algo de la forma:

```
for elemento in iterable
    value1 = elemento[0]
    value2 = elemento[1]
     ........
    valueN = elemento[N-1]
```

Luego, por eso en el ejercicio el k y el v son el primer y segundo elemento del iterable que resulta del zip.
Igual no soy ayudante, asique igual espera la respuesta más oficial de un ayudante, no vaya a ser que yo esté mal y después te equivoques en el examen por que yo entendía mal.

**Comment by negebauer** [comment]
Lo que se está definiendo es un diccionario con llave `k` y valor `v`
`for k, v` toma los valores de la tupla, el primer elemento de la tupla será la llave y el segundo el valor sólo si el valor es mayor a 5

**Comment by perojas3** [comment]
Sobre el primer comentario, lo entiendo, pero no comprendo que tiene que ver con este ejercicio.
Y sobre el comentario de negebauner. Entiendo perfectamente el resultado, ya experimente con el, sé lo que hace. Le estoy preguntando el porqué funciona. ¿Porqué al hacer `k: v for k` a una lista de tuplas de 2, lo interpreta como hacer un diccionario donde el primer elemento es la llave y el segundo el valor? ¿Que hace ese `for` alli? Me confunde que nunca antes definimos el `k`

**Comment by caackermann** [comment]
Al decir`for k,v in lista_tuplas` no estas diciendo que k es la lista, estas diciendo que k,v representan a cada elemento **dentro** de la lista de tuplas (es decir, la tupla) donde k sera el primer elemento de una tupla y v el segundo.
Es equivalente a haber dicho `for (tupla) in [(tupla1), (tupla2), (tupla3),...]`
Donde k,v son el primer y segundo elemento de cada tupla, respectivamente.
Luego para cada tupla de la lista de tuplas, se crea un elemento de dict (ya que lo estas definiendo con las llaves `{}` donde key=k y value=v. Al hacer`l.update()`se "extiende" el diccionario`l` :
Por ejemplo:
`dict = {1:2}`
`dict.update({3:4})`
`print(dict)`
imprime:
`{1:2, 3:4}`
O al menos eso tengo entendido.
Esa era tu duda? @perojas3

**Comment by perojas3** [comment]
No, eso ya lo sabia. No esta haciendo `k,v in lista_tuplas`. Esta haciendo `{k:v for k, v in lista_tuplas}` y crea así el diccionario. y me confunde ese `v for k`.

**Comment by caackermann** [comment]
Esque va todo junto, es `k:v for k,v in lista_tuplas`, podrias haber puesto `k+v for k,v in lista_tuplas` o cualquier otra sentencia que ocupe 2 parametros. En este caso, se ocupan esos 2 parametros para crear un elemento de dict. 
Es como haber dicho `{tupla for tupla in lista_tuplas}` donde cada tupla tiene 2 componentes (k y v)

**Comment by negebauer** [comment]
No te fijes en `v for k`, como dice @caackermann es `k: v for k, v`
Lo importante es `k: v` y `k, v`

**Comment by ivaniadg** [comment]
en una lista por compresión hay varias partes:

``` python
_resultado for _item in _iterable
```

Esas partes son independientes y están separadas por las palabras claves `for` e `in`.

Si quieres agregar condiciones, estas se agregan en `_resultado`. Al final queda lo siguiente

``` python
_resultadoTrue if _condicion else _resultadoFalse for _item in _iterable
```

**Comment by perojas3** [comment]
OK, ahora sí entendi con estas explicaciones. Muchas gracias.
