### ISSUE TITLE
Asistencia Ayudantia

### ISSUE THREAD

**Issue by JoseRomeroi** [IIC2233-2016-1/syllabus#686]
Hola, si mal no recuerdo se dijo que eventualmente habria algun beneficio a quienes tengan cierta cantidad de asistencias a las ayudantias. Será así finalmente?
Yo propongo borrar la peor tarea

**Comment by ivaniadg** [comment]
Hola @JoseRomeroi,

Nunca se dijo eso ni en la ayudantía ni en clases. La asistencia se tomaba para fines estadísticos y no para darle beneficios a los alumnos.

Saludos
