### ISSUE TITLE
Recorrecciones

### ISSUE THREAD

**Issue by augustoal** [IIC2233-2016-1/syllabus#687]
Hola, cuando uno manda a recorregir como sabe si volvieron a revisar la tarea? Es que mande a recorregir la tarea 4 y la 5 por recomendación del ayudante que la revisó (una porque no la pudo abrir y otra porque no pudo revisar unas cosas) pero no supe nada después. Hay alguien a quien le pueda mostrar mis tareas funcionando? Porque mi promedio depende de que me pongan bien esas notas jaja

**Comment by aaossa** [comment]
Hola, cuando uno manda a recorregir se coloca un nuevo feedback en la issue de la tarea/actividad recorregida. Esperamos tener las notas de esas recorrecciones antes de esta noche, junto con las del examen. Cualquier nota faltante se verá mañana.

**Comment by augustoal** [comment]
Ok gracias!
