### ISSUE TITLE
[Última Issue]. Duda Actividad 15

### ISSUE THREAD

**Issue by IsaacConDosA** [IIC2233-2016-1/syllabus#688]
Hola, creo que la distribución de puntajes que usaron para la actividad 15 no corresponde con la del enunciado. 
De hecho no consideraron el bonus y piden que hayamos implementado los comandos `INCR` y `DECR,` los cuales tampoco son pedidos en el enunciado
![ac15](https://cloud.githubusercontent.com/assets/17582083/16642189/6c3c0780-43d6-11e6-834f-c49780fea5f4.png)

**Comment by FernandoPieressa** [comment]
+1

**Comment by jecastro1** [comment]
Ok estamos revisando el tema, atentos

**Comment by perojas3** [comment]
Sí, a mi me pusieron una nota muy baja. Y me funciona perfecto.
Los veo mañana en la recorreccion.

**Comment by jecastro1** [comment]
Efectivamente tuvimos un error. Esto ocurrió porque revisamos con una pauta que teníamos de una versión _con esteroides_ de la misma actividad. 

Por lo tanto, actualizaremos sus notas (en unos minutos) de acuerdo a lo que vieron ustedes en el enunciado. 

Los que recibieron su feedback, podrán revisar si el nuevo cálculo calza multiplicando cada requisito publicado ahí según la siguiente tabla:

| Requisito | Multiplicador |
| :-- | :-- |
| R1 | 4 |
| R2 | 2 |
| R3 | 2 |
| R4 | 0 |
| R5 | 0 |
| R6 | 2 |
| R7 | 2 |
| R8 | 2 |
| R9 | 1 |
| R10 | 1 |

Saludos y gracias por el aviso
