### ISSUE TITLE
Duda varias con recorrecciones

### ISSUE THREAD

**Issue by dasotosilva19** [IIC2233-2016-1/syllabus#689]
con el correo que mandaron informando sobre el cierre del curso, sale que se podrá llegar desde las 10:00 hasta las 13:00 en un lugar por confirmar. Esto es para recorregir todas las tareas, examen y actividades que quedan ? sera presencial ? o es para ver las situaciones pendientes que se mencionó,  cuales serian estas?

duda curiosa:
¿Finalmente para que es usado la asistencia a las ayudantias, (o seguirá siendo un secreto)? :o 

Saludos.

**Comment by aaossa** [comment]
- Para recorregir lo que no se ha podido recorregir: Examen, últimas tareas y últimas ACs
- Es presencial
- #686 : 
  
  > La asistencia se tomaba para **fines estadísticos** y no para darle beneficios a los alumnos.
