### ISSUE TITLE
Productos subasta

### ISSUE THREAD

**Issue by Zepk** [IIC2233-2016-1/syllabus#69]
Del enunciado entiendo que para una subasta en particular es posible que hayan varios productos que se están vendiendo de manera simultanea, como un pack de productos, pero en los archivos de la tarea no logre encontrar ningún caso en que esto pasara, por eso quería saber si efectivamente se pueden subastar packs de productos, y de ser así, cual seria el formato en que estos estarían en el archivo de texto

Supongo que seria así:

```
"productos": [
      33222065852,
      51236685612,
      12894634544
    ],
```

**Comment by otro-felipe** [comment]
El formato de los archivos sera siempre json.
Cualquiera de los siguientes podria ser un formato valido:

```
"productos": [
    33222065852,
    51236685612,
    12894634544
    ]
```

```
"productos": [
    33222065852, 51236685612, 12894634544
    ]
```

```
"productos": [33222065852,
    51236685612,
    12894634544]
```

```
"productos":[33222065852,51236685612,12894634544]
```
