### ISSUE TITLE
Personalizando Atom

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#7]
Buenas, he estado viendo las interfaces de desarrollo que recomendaban en la wiki, y quería personalizar Atom pero no sé en que lugar se escriben esos comandos. Lo primero que pensé sería correrlo en el cmd (utilizo Windows 7), pero no me lo reconoce ¿acaso no es posible en ese OS?

**Comment by mjjunemann** [comment]
Si quieres personalizar Atom, en lo general te recomiendo hacerlo del package manager que viene interno `Ctrl + Shift + P`  => "_install themes_" , hay hartos paquetes que son útiles como de sintaxis , te recomiendo que busques los que te pueden servir a ti ya que te pueden facilitar la existencia. 

Aquí puedes ver los paquetes oficiales para Atom: [Atom Packages](https://atom.io/packages)

Una vez que tengas seteado atom a tu gusto sera grato trabajar en él y hasta aveces mejor que una IDE como pycharm y otras pero es cosa de gustos.

**Comment by MortizDX** [comment]
Oh, ok, es que creí que solo era posible con ese comando.

He estado experimentando con él, y me han estado dando problemas los paquetes instalados y ha instalar, ya que algunos no se me instalan (beautify, linter-pep8) y otros al parecer no me funcionan (no logro hacer correr código python).

Le estoy dando un par de vueltas, pero entre esos problemas y que igual ocupa bastantes recursos en mi note (que no es muy poderoso), voy a probar sublime para terminar... sino, tendré que apañarmelo con notepad++ solamente, jaja.¿alguna recomendación?

**Comment by aaossa** [comment]
Elige hoy alguno y acostúmbrate hoy para mañana no tener problemas durante la AC. Luego de eso tendrás prácticamente una semana para probar nuevas IDEs. Solamente elige una que te sea fácil de manejar y que haga todo lo que quieras hacer.

**Comment by mjjunemann** [comment]
No puedes correr directamente python desde atom (si se puede con atom-terminal y otros paquetes equivalentes, pero es básicamente una shell). Lo que uno hace cuando desarrolla con editores de texto, va en conjunto de una shell/command line. 
Para python3 en general se usa desde la shell :

Windows:  `python path/to/file.py`
Mac OS: `python3 path/to/file.py`
*La diferencia va en la variable de sistema a donde apunta el python 3.4.3 o superior, en general es así en los SO de arriba pero puede variar si haz hecho algunas cosas.

Que algunos paquetes no se te instalen es una real lastima porque los que dijiste (beautify, linter-pep8, y otros de ese estilo), son bastante útiles ya que ayudan con la sintaxis y a autocompletar métodos (linter), sube una foto del error que tiran al instalar en una de esas te podemos dar respuesta y/o puedes googlear el error, puede ser permisos algo de path o algo faltante.

**Comment by MortizDX** [comment]
Aah, es que pensé que eso es lo que hacía el paquete atom-script ¿qué hace exactamente entonces?

Bueno, finalmente logré instalé los paquetes faltantes (al parecer eran solo problemas de conexión)... pero me salen estos problemas:

![ss1](https://cloud.githubusercontent.com/assets/14007315/13725144/cb3f9a04-e877-11e5-85dc-d16920a1d23d.png)

Y al intentar correr el paquete script, ocurre este mensaje:

`Unable to run

python
Did you start Atom from the command line?

  atom .
Is it in your PATH?

PATH: C:\Python34\;C:\Python34\Scripts;C:\Python34\;C:\Program Files (x86)\Java\jre1.8.0_45\bin;C:\Windows\System32\;C:\Windows\;C:\Windows\System32\Wbem;C:\Users\mauricio\AppData\Local\atom\bin`

**Comment by jecastro1** [comment]
Del screenshot no sé bien lo que ocurre con el segundo error.

Para el primer error y el tercero hay que instalar paquetes de python. En este caso `pylint` y `pep8`. Lo instalas con `pip install <nombre del paquete>`.

**Comment by aaossa** [comment]
Hola, te dejo [aqui](https://github.com/IIC2233-2016-1/syllabus/wiki/Interfaces-de-Desarrollo#atom) el link a la wiki que les enviamos hace tiempo, ahí aparece en parte lo que @jecastro1 dice. Prueba a correr **todos** los comandos que aparecen ahí y avísanos si siguen tus errores. Ese es el setup recomendado, para eso está la guía :wink: .

**Comment by MortizDX** [comment]
Ahora pude instalar los paquetes mediante el cmd. No sé que había ocurrido antes pero no me reconocía los comandos pip o atm, así que tuve que reinstalar python y atom y con eso al parecer todo funciona.

Al parecer no me salen los errores anteriores (que antes al iniciar sesión volvían a aparecer), pero me sale el siguiente en cambio:

> **Error: Process execution timed out**
> Error: Process execution timed out
>     at C:\Users\mauricio.atom\packages\linter-flake8\node_modules\atom-linter\lib\helpers.js:79:18

Puedo editar código y correrlo sin mayor problema, así que no sé en que afecta este problema.

Una duda que me surgió usando atom es que al parecer no se puede interactuar con "input()" si el programa lo pide ¿o hay alguien que estoy pasando por alto?

**Comment by andresfdezc** [comment]
El package que está fallando según ese error es linter-flake8. Este package te muestra errores que cometiste en tu código en la parte de abajo de Atom. Puedes prescindir de él si quieres, pero te recomiendo reinstalar todos los packetes linter, pues te harán más fácil escribir.

El package script de Atom que ejecuta el código no tiene soporte para `input()`. Vas a tener que ejecutarlo en otro lado (intérprete de python, consola, etc).

**Comment by MortizDX** [comment]
Mm, lo he desinstalado y reinstalado un par de veces y sigue saliendo el error, por lo que no me muestra errores en mi código ¿qué clase de errores detecta ese paquete?

Oh, ya veo, es una lástima :( ¿alguna de las otras interfaces recomendadas lo permite?

**Comment by andresfdezc** [comment]
Según lo que sale en una [issue oficial de ese package](https://github.com/AtomLinter/linter-flake8/issues/169), es un error del que no te debieses preocupar mucho y que están trabajando para corregir pronto, que ocurre cuando uno de sus procesos demora más de 10 segundos.

Otras IDE's como PyCharm soportan `input()`, pero no soporta otras cosas que veremos más adelante. Te recomiendo aprender a ejecutar archivos de python desde una consola y que no solo te quedes con los IDE's.

**Comment by MortizDX** [comment]
Oh, okey, pero entonces debería estar funcionando correctamente aun con ese mensaje?

**Comment by andresfdezc** [comment]
Acorde a la issue que te deje en la respuesta anterior, sí (en su mayor parte).

**Comment by fgvenegas** [comment]
No queria comentar pero yo sufri mucho con Atom, me pasaba lo mismo y recorri mil issues en github y un dia de la nada se arreglo ._. ... y me cambie a Sublime XD

**Comment by MortizDX** [comment]
Gracias por las respuestas, creo que esperaré un tiempo a ver si solucionan ese problema con el paquete.
