### ISSUE TITLE
Input archivos: secuencias de marcado dentro de strings.

### ISSUE THREAD

**Issue by dtfuller** [IIC2233-2016-1/syllabus#70]
Hola! 

Implementé un parser de texto a diccionario, y hasta ahora funcionaba todo OK. Al intentar parsear un archivo de productos (de los antiguos), me encontré que había un elemento que tenía como valor un string con valores "{" dentro; y que esto me botaba el algoritmo. 

El elemento en cuestión es (nótese el nombre):

`{
    "portatil": false,
    "nuevo": "SI",
    "precio de hipoteca": 344609,
    "rating": 4.6,
    "id": 39865839243,
    "sistema_operativo": "Windows",
    "nombre": "Lot530 Pies rj45cat5 Ethernet cable/cord $Barco Disco {Azul {f",
    "memoria": 10,
    "tipo": "Computacion"
  }`

Revisé el nuevo archivo de productos, y no encontré el elemento, ni tampoco encontré llaves ni valores (strings) con secuencias de marcado ("{", "[","(", etc). Luego, la pregunta en cuestión es: ¿Podemos asumir que los strings en los archivos de texto no tienen dichas estructuras de marcado en su interior? 

Gracias de antemano! ;)

**Comment by otro-felipe** [comment]
Un archivo json podria tener cualquier caracter dentro de las llaves o los valores, por lo que podria existir perfectamente un archivo asi:

```
{
  "nombre": "Lot530 Pies rj45cat5 Ethernet cable/cord $Barco Disco {Azul {f",
  "tipo": "Computacion",
  "precio de hipoteca": 344609,
  "memoria": 10,
  "nuevo": "SI",
  "portatil": false,
  "sistema_operativo": "Windows",
  "id": 39865839243,
  "rating": 4.6
}
```

**Comment by MortizDX** [comment]
¿Es posible que dentro del valor en la llave "nombre", exista una porción del string que también contenga "nombre" tal cuál (con comillas y todo) entonces (y otros casos similares)?

**Comment by otro-felipe** [comment]
Es posible, pero estas comillas van a estar escapadas (con un `\` antes).

```
{
  "nombre": "La $ien$ia y su \"verdad\"",
}
```

**Comment by MortizDX** [comment]
¿Entonces el programa puede diferenciar si le pido buscar en un string `"nombre"` y no `\"nombre\"` o los toma igual?

**Comment by otro-felipe** [comment]
Son distintos strings, si le pides buscar `"nombre"`, no se va a confundir con `"\"nombre\""`

**Comment by dtfuller** [comment]
Oka muchas gracias. Finalmente implementé el parser para cumplir con el caso, fue mucho más sencillo de lo que consideré al principio!
