### ISSUE TITLE
Citar código encontrado en la web

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#72]
¿Es posible utilizar en las tareas código que haya encontrado en la web que me ayude a resolver parte del problema y citar de dónde lo obtuve? ¿Hay un límite/restricción?

**Comment by bamavrakis** [comment]
Hola! No está permitido utilizar código de internet, obviamente lo pueden mirar y basarse en ello para la realización de su tarea (basarse en la IDEA detrás del código que encontraron), pero no lo pueden "copiar/pegar".

**Comment by JoseDaroch** [comment]
Si solo me base en una idea encontrada en internet, se cita igual?

**Comment by bamavrakis** [comment]
Si

**Comment by MortizDX** [comment]
Oh, ok, es que había encontrado la respuesta a una cosa que no sabía que hacer ¿qué hago en ese caso? ¿lo adopto como una función de otra forma, por ejemplo?
