### ISSUE TITLE
Mostrar Subastas y productos de tienda

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233-2016-1/syllabus#73]
En el pdf se indica que para ambos casos se deben mostrar TODAS las subastas disponibles y TODOS los productos de la tienta; luego se menciona que el usuario puede buscar por nombre o tipo.
¿Eso se hace antes de mostrar todo? es decir, si el usuario pide mostrar todas las subastas disponible, le pregunto que quiere buscar y ahí imprimo las subastas o primero se imprimen todas las subastas y ahí el usuario puede indicar una búsqueda mas avanzada para imprimir las subastas que cumplan con ese requisito. 
Esta misma pregunta va para los productos de tienda, ¿se imprimen todos y luego se busca? o ¿se indica el nombre o tipo a buscar y ahí se imprime?

**Comment by otro-felipe** [comment]
Todas estas decisiones quedan a tu criterio y deben ser claramente especificadas en el readme. Mientras exista la opcion de mostrarlas todas y filrarlas, no habra problemas.
