### ISSUE TITLE
problema con escritura de datos idle de python 

### ISSUE THREAD

**Issue by mhaacke** [IIC2233-2016-1/syllabus#74]
tengo un problema en el cual al correr el programa con pycharm funciona y con el terminal funciona y si lo ejecuto con el idle de python me tira error de la incripcion ascii esta relacionado con la escritura de datos pero nose como solucionarlo o que es en especifico este es el error, me sucedió un error similar al poner en el destructor de una clase la escritura de las listas con los datos a un archivo
![error](https://cloud.githubusercontent.com/assets/17596439/13907222/40832f3c-eec8-11e5-82c7-4bce065f3fce.png)

**Comment by otro-felipe** [comment]
A la hora de abrir un archivo puedes especificar el encoding, esto podria solucionar tu problema :) `file = open("usuarios.txt", "r", encoding="utf-8")`

**Comment by mhaacke** [comment]
muchas gracias :D
