### ISSUE TITLE
El programa debe guardar lo que se hace de manera permanente?

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#76]
Osea, cada ves que ejecuto el codigo debe guardarse lo que hise en la secion anterior?

**Comment by bamavrakis** [comment]
Hola!
Efectivamente, cada vez que cierras el programa debes guardar todos los cambios que realizaste para que estos no se eliminen.
Saludines cordiales y espero haber resuelto tu duda :)

**Comment by perojas3** [comment]
Entonces, como escribo en los archivos txt?

**Comment by ivaniadg** [comment]
@perojas3 te refieres al formato del archivo o de cómo escribir archivos en python?

**Comment by perojas3** [comment]
Como escribir archivos en python.

**Comment by aaossa** [comment]
En el pdf de repaso de IIC1103 puedes encontrar eso en la sección 9.4 (página 46). Aquí aparece de hecho:

``` python
miarchivo = open("archivo.txt", "w")
miarchivo.write(string)
miarchivo.close()
```

**Siempre tienes que cerrar el archivo. Recuerda usar** `close()` **para evitar eventuales problemas**

Date una vuelta por el pdf y lee esa sección. No es dificil, pero si tienes cualquier duda vuelve a preguntar por acá :grin:

**Comment by perojas3** [comment]
¿Pero como me aseguro de que solo y unicamente sobrescriva algunas lineas? 
¿Y cual pdf?

**Comment by aaossa** [comment]
Sobre tu primera pregunta, tú tienes que ver como hacer eso, pero por ejemplo podrías escribir todo el archivo de nuevo.

El pdf es el que está [AQUÍ](https://github.com/IIC2233-2016-1/syllabus/tree/master/Repaso-IIC1103)
