### ISSUE TITLE
Productos en subasta activas: un producto en dos subastas?

### ISSUE THREAD

**Issue by andersskog** [IIC2233-2016-1/syllabus#77]
Una pregunta sobre las subastas. Puedo tener un mismo producto en mas de una subasta activa? Ejemplo: al crear una subasta uso el producto 1 y luego al crear otra subasta uso el producto 1. Lo pregunto porque es algo que ocurre en el subastasact.txt entregado.

**Comment by bamavrakis** [comment]
con que producto pasa eso?

**Comment by andersskog** [comment]
Con un producto de los .txt antes de ser modificados. Esto puede ser posible o tendría que estar prohibido por nuestro programa?

**Comment by bamavrakis** [comment]
En los archivos de ahora eso solo podría ocurrir si los vende la misma persona. En ese caso, la subasta que termine primero será la que se lleve a cabo, y la otra será anulada.
Saludos!

**Comment by ehdonoso** [comment]
oe chino no explicaste nada de eso en el pdf, explica bien po

**Comment by MortizDX** [comment]
¿Anularla es igual que quitar del archivo de .txt, no? Es decir, esa subasta no cuenta ya en la trayectoria del producto involucrado, ni para otros efectos de registro ¿no? ¿asumimos como que nunca se hizo?

Otra duda relacionada con el tema ¿un usuario puede tener 2 veces un producto? De ser así, ¿eso se representa con IDs repetidos?
