### ISSUE TITLE
Crear nuevo archivo para guardar trayectorias

### ISSUE THREAD

**Issue by agmardones** [IIC2233-2016-1/syllabus#78]
Por comodidad me gustaría crear un archivo (aparte de los que vienen con la tarea) para guardar las trayectorias de los productos, está permitido?

**Comment by otro-felipe** [comment]
No deberia haber ningun problema en hacer eso.

**Comment by agmardones** [comment]
Gracias felipin =)

**Comment by negebauer** [comment]
@agmardones Acuérdate de especificarlo en el README
