### ISSUE TITLE
Precio subasta Historial vs Precio

### ISSUE THREAD

**Issue by decocco** [IIC2233-2016-1/syllabus#79]
En la información de cualquier subasta, tanto activa como finalizada ocurre que el precio del lote subastado difiere con la ultima apuesta realizada:

```
"precio": 177226, 
"historial": ("salvarado",61759),...,   ("vsanchez1",177225),("agutierrez1",184263)
```

Como debemos trabajar este problema? 
Ignoramos el valor actual que trae la subasta y consideramos el de la ultima apuesta +1 ("precio":184264)?

**Comment by Geeermy** [comment]
Hola! Esta duda fue resolvida aquí: #49 no es un error, está bien así :)
Saludos!
