### ISSUE TITLE
Unas dudas sobre Herencia

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#8]
Tengo unas dudas respecto a herencia

**Primero:** ¿La clase y control del jueves es de herencia?

**Segundo:** ¿Que son, para que sirven y como se usan los `*args` y `**kwargs`? No entiendo la explicación entregada.

**Tercero:** estoy haciendo la segunda actividad del semestre pasado, la de herencia. Tengo duda en el ultimo punto. En el cual te piden que cuando uses el método 'escuchar', te imprima el nombre de la canción, pero no sé como sobrescribir el método para hacer que imprima algo diferente cuando es de la clase Inalambrico o Bluetooth ¿Como lo hago? Quiero adjuntarles el pdf y mi codigo, pero github no me deja.
Eso es todo, muchas gracias.

**Comment by andresfdezc** [comment]
**Primero:** La clase del jueves es de herencia, polimorfismo y clases abstractas. El contenido de cada clase se publicará siempre en el calendario al inicio del syllabus. Los controles son sorpresa.

**Comment by btkramm** [comment]
**Segundo:** Hablando específicamente de `*args` y `**kwargs` (sin tocar el tema de cómo se utilizan ellos en la herencia) es una forma que tienes en Python de hacer que una función/método pueda recibir una cantidad indefinida de argumentos a1, a2, a3,..., ya sea de la forma: `foo(a1, a2, a3, ...)` (aquí usé `*args`) o de la forma `foo(b1 = a1, b2 = a2, b3 = a3, ...)` (aquí usé `**kwargs`).

Si te preguntas cuál es la utilidad del `*` y el `**` es una forma de "descomprimir" una lista/diccionario, es decir, es lo mismo hacer `foo(1, 2, 3)` a que decir `foo(*[1, 2, 3])` y `foo(a = 1, b = 2, c = 3)` a que decir `foo(**{"a": 1, "b": 2, "c": 3})`. No sé si me explico bien.

Más información acá: http://stackoverflow.com/questions/3394835/args-and-kwargs

**Comment by fgvenegas** [comment]
**Tercero:** Para sobreescribir un método basta con volver a escribirlo y modificarlo en la clase que lo esta heredando, por ejemplo:

``` python
class Arbol:

    def __init__(self):
        self.tamaño = 1

    def crecer(self):
        print("soy muy grande")


class Manzano(Arbol):

    def __init__(self):
        super().__init__()

    def crecer(self):
        self.tamaño += 1


class Arce(Arbol):

    def __init__(self):
        super().__init__()

    def crecer(self):
        super().crecer()
        self.tamaño += 1


class Roble(Arbol):

    def __init__(self):
        super().__init__()

    # Para heredar un metodo no es necesario escribirlo, Roble igual tiene el
    # metodo crecer()


arbol0 = Arbol()
arbol0.crecer()   # imprime "soy muy grande"

arbol1 = Manzano()
arbol1.crecer()  # se sobreescribe el metodo, solo modifica el tamaño

arbol2 = Arce()
arbol2.crecer()  # se sobreescribe el metodo, se imprime "soy muy grande" y ademas se modifica el tamaño

arbol3 = Roble()
arbol3.crecer()  # imprime "soy muy grande"

```

**Comment by fgvenegas** [comment]
Quiero aportar a lo de @btkramm con [esta página](http://www.juanjoconti.com.ar/2010/10/13/entendiendo-args-y-kwargs-en-python/) que aunque quizás no es la explicación más formal me sirvió de manera personal para entender args y kwargs.

**Comment by perojas3** [comment]
Muchas gracias a todos, me sirvio bastante lo que me pasaron

**Comment by MortizDX** [comment]
Una consulta, la materia de "Properties" no será evaluada mañana en la actividad entonces?

**Comment by negebauer** [comment]
@MortizDX  La materia de Properties no será evaluada en la actividad de mañana.
