### ISSUE TITLE
Hay subastas repetidas 

### ISSUE THREAD

**Issue by fcorencoret** [IIC2233-2016-1/syllabus#80]
Hola, hay subastas que estan mal hechas. El usuario tgodoy hace dos subastas por el mismo producto y solo tiene 1 cantidad de ese producto. La primera es : 

```
{
    "fecha_termino": "2016-06-26 03:34:41",
    "id": 77862491632,
    "fecha_inicio": "2016-03-12 19:50:22",
    "precio": 176476,
    "vendedor": "tgodoy",
    "productos": [
      51854974720
```

y la segunda es

```
{
    "fecha_termino": "2016-08-01 09:03:43",
    "id": 69922985045,
    "fecha_inicio": "2016-02-18 21:20:55",
    "precio": 184418,
    "vendedor": "tgodoy",
    "productos": [
      51854974720
```

Hay mas subastas repetidas. Que se hace con esto? o es error del archivo?

**Comment by bamavrakis** [comment]
Hola! 
Esto no es un error del archivo, te invito a revisar el issue #77 
Saludos!
