### ISSUE TITLE
Historial que se muestra al seleccionar una subasta

### ISSUE THREAD

**Issue by jpdattas** [IIC2233-2016-1/syllabus#81]
Según el enunciado, "Al seleccionar una subasta, se debe mostrar su información relevante (nombre de producto, precio, historial de apuestas, tiempo restante) y se dará la opción de apostar."

Pero en otra parte sale "Notar que los usuarios no pueden ver el máximo que ha apostado cada uno, solo pueden ver el precio actual de la subasta y el ganador actual"

Esto significa que al seleccionar una subasta se debe mostrar el historial exepto la última apuesta?(pues esta revelaría el máximo apostado)

**Comment by otro-felipe** [comment]
Cuando un usuario 1 realiza una apuesta ingresa un valor X que es el maximo precio que usuario1 esta dispuesto a pagar por el producto que tiene un precio P. En este caso tienes 3 posibles opciones:
- Eres el primero en apostar: en este caso el precio del producto se incrementa en 1 y queda como P+1.
- Hay apuestas antes que la tuya, cuyo ganador puso como precio maximo Y **menor** que tu apuesta: En este caso, al hacer tu apuesta, el precio del producto queda como Y + 1 y tu eres el ganador actual de la apuesta.
- Hay apuestas antes que la tuya, cuyo ganador puso como precio maximo Y **mayor** que tu apuesta:En este caso, al hacer tu apuesta, el precio del producto queda seteado como X + 1 y el ganador va a seguir siendo el ganador anterior.

Como ves hay dos valores: El precio actual de la apuesta, y el precio maximo apostado por un usuario. El valor que debe ser visible es el precio actual de la apuesta y el valor que debe estar escondido es el valor maximo apostado por los demas usuarios.

Espero eso aclare un poco tu duda (y el funcionamiento de las apuestas del sistema).

**Comment by jpdattas** [comment]
Entonces donde sale:
"Al seleccionar una subasta, se debe mostrar su información relevante (nombre de producto, precio, **historial de apuestas**,"

no debo mostrar el historial de apuestas? o se referian a que entre esas cosas elija lo relevante?

**Comment by otro-felipe** [comment]
El historial de apuestas debe ser mostrado, pero **no debes mostrar el monto maximo** que aposto un usuario, sino que debes mostrar el monto con el que termino el producto luego de la apuesta. Aunque las apuestas anteriores pueden ser obviadas y puedes optar por mostrar solo el **precio** actual y el ganador actual.

**Comment by jpdattas** [comment]
Osea el historial pero solo de usuarios sin su apuesta? ok, muchas gracias

**Comment by otro-felipe** [comment]
Sin apuesta maxima, pero con el precio en el que queda el producto despues. De nada.

**Comment by Zepk** [comment]
Y en el caso de la primera apuesta?
Porque no existe un dato con el precio inicial, yo puedo saber el precio en el que quedo el objeto, salvo para la primera apuesta

**Comment by MortizDX** [comment]
¿Cómo debemos expresar el "precio en que queda la apuesta" en el historial? ¿Podemos decir que es lo que "apostó" tal usuario (lo cuál sería una mentira, obviamente)? ¿o solo ponemos "tras x usuario apostó, la subasta quedó en y"?
