### ISSUE TITLE
[T01][Problema con codificacion de archivo productos.txt]

### ISSUE THREAD

**Issue by andresback** [IIC2233-2016-1/syllabus#82]
Hola, al usar "readlines" para leer el archivo productos.txt obtengo el siguiente error:

`UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)`

Este es el único archivo de texto que me genera un error, los demás los puedo leer sin problemas. Aparte de abrir el archivo en modo lectura y guardarlo en una variable no he realizado ningún otro tipo de acción sobre el mismo.

**Comment by santiagocruzb** [comment]
https://github.com/IIC2233-2016-1/syllabus/issues/74

**Comment by andresback** [comment]
Muchas gracias
