### ISSUE TITLE
[T01] [Inicio Sesion]

### ISSUE THREAD

**Issue by vbarros2** [IIC2233-2016-1/syllabus#83]
Al iniciar sesion cuando se cierran las subastas hay que actualizar quien las compro, las multas, los baneados, etc.

**Comment by tamycova** [comment]
A que te refieres con al iniciar sesión? En el enunciado dice claramente que al cerrar sesión deben actualizarse todos los archivos, osea que cuando se inicie sesión se estarán leyendo los archivos actualizados.

**Comment by vbarros2** [comment]
"Al iniciar sesion, automaticamente deberan cerrarse todas las subastas que hayan estado abiertas y cuya fecha de termino esten cumplidas"
Mi duda es que las subastas que ya finalizaron al momento de iniciar sesión, debo actualizar la información de pago del comprador, del intercambio del producto, etc. O todos los archivos están sincronizados??
Pasa lo mismo con los usuarios multados. Me dicen que debo verificar los plazos, y aquellos que ya no pagaron en su fecha que debían tengo que banearlos? O simplemente este es un historial de las multas??

Muchas Gracias

**Comment by otro-felipe** [comment]
Si, al iniciar sesion debes actualizar los archivos (cerrar las subastas expiradas, banear a los multados expirados, etc), pero puedes asumir que la fecha que se ingresara **siempre** sera posterior a la ultima fecha en la que los archivos fueron actualizados.
