### ISSUE TITLE
[T01] [Multados]

### ISSUE THREAD

**Issue by vbarros2** [IIC2233-2016-1/syllabus#84]
Si un multado tiene productos o plata para pagar su multa pero no la paga. El programa tiene que "robarle" sus productos y plata y no banearlo, o tiene que quitarle los productos y banearlo.
Y lo otro es que pasa con la plata de los usuarios baneados??

Muchas Gracias

**Comment by bamavrakis** [comment]
Hola!
Si un usuario no paga su multa es baneado. El dinero del baneado desaparece de la existencia de la humanidad.
Saludos!
