### ISSUE TITLE
Subasta y Baneo

### ISSUE THREAD

**Issue by matnagra** [IIC2233-2016-1/syllabus#85]
Si hay un usuario que debe ser baneado pero este tiene un objeto siendo subastado. ¿El usuario es baneado y su objeto subastandose pasa a MercadoPreso? o se lleva acabo al subasta igual y obviamente es baneado el usuario de tambien.

**Comment by bamavrakis** [comment]
Hola!
Pasa lo primero que dijiste, se "anula" la subasta y los productos subastados se van a la tienda de mercadoPreso.
Saludos!
