### ISSUE TITLE
¿En que orden esta usuarios.txt? ¿Puedo cambiarlo sin problemas?

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#86]
Deseo saber ¿Que segun que orden estan los usuarios en el archivo usuarios.txt?
Y tambien, si lo cambio al momento de guardar los cambios ¿No ocurre ningun problema en la evaluacion?

**Comment by otro-felipe** [comment]
No, los usuarios (y en general todos los archivos) no sirguen ningun orden en especial, por lo tanto, no importa si cambias el orden en tus archivos respecto de los archivos originales.
