### ISSUE TITLE
¿Te deven estregar la fecha actual, o puedo usar un comando?

### ISSUE THREAD

**Issue by perojas3** [IIC2233-2016-1/syllabus#87]
Lo que ocurre es el que pdf dice que "Al momento de ingresar al sistema se deben ingresar la fecha y hora actuales". ¿Eso significa que el usuario deve ingresarlas, o puedo usar la bibliteca time para generar la fecha y hora actual? ¿O devo usar una opcion que permita elejir entre ambos.?

**Comment by otro-felipe** [comment]
El usuario debe entregarle al sistema cual es la fecha actual, saludos.

**Comment by perojas3** [comment]
Y la hora?

**Comment by otro-felipe** [comment]
La hora tambien debe ser especificada, (hora, minutos y segundos) ya que en los archivos, las fechas estan escritas de esta forma.

**Comment by caackermann** [comment]
Vi en otros issues que se puede usar datetime para obtener la fecha actual
automaticamente (sin que el usuario la ingrese), es verdad esto?

2016-03-21 22:50 GMT-03:00 Felipe Pezoa notifications@github.com:

**Comment by aaossa** [comment]
Sí, está permitida, sale en #65 :grin:
