### ISSUE TITLE
Ventas en la tienda de productos

### ISSUE THREAD

**Issue by MortizDX** [IIC2233-2016-1/syllabus#88]
En el enunciado no encuentro si está indicado si el usuario puede saber el precio de los objetos que compra de la tienda de productos ¿no es necesario, está prohibido, queda a decisión de c/u u otro caso? (sé que lo puede saber si quiere realizar una subasta de un producto suyo, pero de uno solo en la tienda no lo menciona el enunciado)

En el caso que quiera comprar algo de la tienda y que no tenga el dinero suficiente ¿se aplican las mismas reglas que las subastas o queda a decisión de c/u que hacer en tal caso?

**Comment by negebauer** [comment]
Fíjate en lo que dice @MainScientist en #81

**Comment by MortizDX** [comment]
Pero yo no me refiero a las subastas, sino a la compra directa de productos de la tienda.

**Comment by Geeermy** [comment]
Hola! El usuario debería poder saber el precio de los objetos de las tiendas (viéndolo del sentido lógico, no puedo comprar algo si no sé el precio jaja). Y por lo otro, no, si no tiene dinero para comprar algo directo de la tienda, simplemente no se le permite comprarlo. Saludos!

**Comment by MortizDX** [comment]
Vale, muchas gracias. Otra duda que me surgió respecto a la lista de productos de la tienda ¿acaso solo hay un id por producto o hay varios id repetidos, representando la cantidad del mismo producto disponible?

**Comment by caackermann** [comment]
Al comprar un producto directamente en la tienda, quien se queda con el dinero de la transaccion? Creamos algun tipo de fondo para la tiienda o este se "pierde"?

**Comment by Geeermy** [comment]
@caackermann por simplicidad, asume que se "pierde" (da lo mismo cuánta plata tenga la tienda, en el programa nunca se le dará una utilidad a ese monto).
@MortizDX Hay un único id (perdón por no responder antes, te recomiendo que para nuevas dudas abras nuevas issues, acá es fácil que se pierdan).
Saludos a ambos!
