### ISSUE TITLE
Duda con los tiempos

### ISSUE THREAD

**Issue by bicarcamo** [IIC2233-2016-1/syllabus#89]
Si cada usuario, al ingresar, debe poner la fecha actual. ¿Se puede asumir que las mete en orden cronológico? Ya que si no la ingresa de ese modo y se pone una fecha a futuro, algunas subastas se van a tomar como finalizadas. Pero si luego, otro usuario, ingresa una fecha anterior, ¿se deben reactivar subastas que se habían dado por finalizadas, pero que en el tiempo actual se deberían encontrar activas?

**Comment by otro-felipe** [comment]
Duplicado, pero si, puedes asumir que las fechas se ingresaran en orden cronologico.

**Comment by flobarrios** [comment]
#35 ahi lo respondí! Pero si, lo puedes asumir. Si quieres también lo puedes hacer de la otra forma pero recuerda especificar en el README como hayas abordado el tema.
