### ISSUE TITLE
Finalización de subastas y creación de multas al ingresar al sistema

### ISSUE THREAD

**Issue by andersskog** [IIC2233-2016-1/syllabus#90]
Al ingresar al sistema, se deben finalizar las subastas (con lo cual se crean multas) y banear a los usuarios que no han pagado su multa. Mis preguntas son:

1)  Estas multas pueden ser pagadas automaticamente por el sistema? o si no son pagadas exclusivamente por el usuario en definitiva este es baneado? Otra alternativa podría ser guardar las multas hasta que el usuario se conecte al sistema y en este momento cobrarle. 
Que opcion se debe realizar?

2) En caso de que el usuario sea baneado y es el vendedor en una subasta posterior en el tiempo, esta subasta debe ocurrir o debe ser cancelada?

3) Se deben finalizar subastas, verificar multas y actualizar baneados de manera cronologica? O queda a disposición nuestra primero finalizar todas las subastas y luego ver las multas? La dificultad y tiempos del progama aumentan mucho en el primer caso.

Gracias!

**Comment by vicentemartintarud** [comment]
También respecto a la finalización de subastas. En caso de que el primer postor sea multado por no tener el dinero para pagar y la subasta sea adjudicada al segundo postor, ¿qué precio paga?

Gracias!

**Comment by otro-felipe** [comment]
- Las multas solo pueden ser pagadas por los usuarios. Si no las pagan se van banea2 y se despiden de su cuenta.
- El usuario que se va banea2 y es vendedor de una subasta, dichas subastas se cancelan y todos sus productos se van a la tienda.
- Deben finalizar subastas, verificar multas y actualziar baneados de forma cronologica, de otra forma, ocurriran inconsistencias (subastas que deberian ser canceladas por algun ban podrian ser llevadas a cabo de todas formas, lo cual no deberia pasar).
- El precio que paga el segundo postor en caso de que el primero sea multado es el precio maximo aposto dicho postor.

**Comment by vlcastillo** [comment]
Si el segundo postor tampoco tiene dinero para pagar pasa a ganar la subasta el tercer postor (y sucesivamente)?

**Comment by otro-felipe** [comment]
Exactamente.

**Comment by MortizDX** [comment]
Cuando un usuario en una subasta es multado por no tener el dinero para pagarla ¿es eliminado del historial de esa subasta? Lo pregunto para fines del ranking de los 10 usuarios que más han vendido en subastas.

**Comment by caackermann** [comment]
@MainScientist Sobre el ultimo punto, tengo una duda: El precio que finalmente paga el ganador de una apuesta es el precio actual de la subasta, no lo que esa persona aposto (segun tengo entendido) entonces, si esta persona no puede pagar , el nuevo ganador deja de pagar el precio actual de la subasta, si no que pagaria lo que el mismo aposto?

**Comment by otro-felipe** [comment]
exactamente, cuando alguien gana una subasta y no puede pagar, el segundo pasa a ser el ganador y debe pagar la cantidad que aposto, y si este tampoco puede pagar sigue pasando lo mismo.

**Comment by otro-felipe** [comment]
@MortizDX  No veo como borrarlo o no afecta el ranking de los 10 usuarios que mas han vendido. Me podrias explicar mejor cual es tu pregunta? :)

**Comment by MortizDX** [comment]
Ahm, no recuerdo ahora exactamente por qué hice esa pregunta en ese contexto ^^u 

Pero ahora me surgió esa duda por otro motivo, cuando estoy terminado una subasta y ocurre el hipotético caso en que TODOS los agostadores terminan con multa, por lo que nadie gana la subasta y se anula.
