### ISSUE TITLE
Fechas para creacion de multas

### ISSUE THREAD

**Issue by caackermann** [IIC2233-2016-1/syllabus#92]
Cuando se ingresa al sistema y se crean las multas de las subastas que fueron finalizadas, estas multas tendrian por fecha de vencimiento 2 dias a partir de la fecha actual (la que ingreso el usuario) o  2 dias a partir de la fecha en que finalizo la subasta?

**Comment by tamycova** [comment]
2 dias a partir de la fecha en que finalizo la subasta!
