### ISSUE TITLE
[Codigo] Diccionarios y métodos

### ISSUE THREAD

**Issue by santiagocruzb** [IIC2233-2016-1/syllabus#93]
Estoy intentando hacer un diccionario que cada key sea un numero y cada value sea un método. Pero se ejecutan todos los métodos.
¿?

```
class C1:
    def m0(self):
        diccionario = {1:self.m1(),2:self.m2(),3:self.m3()}
        return diccionario[3]

    def m1(self):
        print(1)

    def m2(self):
        print(2)

    def m3(self):
        print(3)

c = C1()
c.m0()
```

```
/Users/SantiagoCruzB/Library/Preferences/PyCharm40/scratches/scratch_32
1
2
3
```

@robocop6 @fgvenegas :pray:

**Comment by otro-felipe** [comment]
Para tratar los metodos como objetos debes hacer sin llamarlos. Al hacer `self.m1()` estas llamando al metodo y asignandole el valor que retorna `self.m1()` a la llave 1 del diccionario. Para asignar el metodo debes hacerlo como `diccionario = {1: self.m1}`. De esta forma puedes hacer `diccionario[1]()`. Al poner los parentesis, llamas al metodo que contiene el diccionario en su key 1.

**Comment by santiagocruzb** [comment]
Muchas gracias!
![large](https://cloud.githubusercontent.com/assets/13748925/13971508/8ce3d838-f06f-11e5-8932-42c1347f9f26.gif)
