### ISSUE TITLE
Actualizacion de archivos

### ISSUE THREAD

**Issue by diegosapunar** [IIC2233-2016-1/syllabus#94]
Entiendo que los archivos se deben ir actualizando a medida que van "ocurriendo" cosas en el programa, pero esto puede ocurrir de dos maneras:

1) Cada vez que el usuario realice una operación que implique un cambio en algún archivo se debe editar en "ese momento" el archivo. De esta manera si el usuario cierra el programa (con la "cruz" por decirlo de alguna manera) obviamente los archivos se abran editado.. 

2) Que exista en el menu del usuario una opción "Salir del Sistema"... si el usuario llama esa opción, en ESE MOMENTO se editarian los archivos de texto. Claramente en este caso si el programa se cierra, no se editarian los archivos de texto.

**Comment by tamycova** [comment]
Especificalo y justificalo en el README, aunque lo más correcto y simple en mi opinión sería la número 1 :)
