### ISSUE TITLE
DF

### ISSUE THREAD

**Issue by Iruretagoyena** [IIC2233-2016-1/syllabus#96]
Hola !
Se pueden usar DataFrames para manejar la información ?
Gracias

**Comment by fgvenegas** [comment]
Si la utilizas trata de ser lo mas especifo en el README sobre su instalacion y como la usaste, ya que es una libreria que no viene por defecto en Python.
@mjjunemann por interno me comenta que puede ser dificil de utlizar asi que tal vez te termines complicando demas
