### ISSUE TITLE
clase muebles

### ISSUE THREAD

**Issue by IsaacConDosA** [IIC2233-2016-1/syllabus#98]
Hola!
En el enunciado dice que la clase Muebles, tiene el atributo dimensiones como tupla, pero en los archivos están dados como lista. Está bien así y debemos adaptarlo nosotros? 
Gracias!

**Comment by otro-felipe** [comment]
Ustedes deben adaptarlo ya que en json no existen las tuplas.

**Comment by IsaacConDosA** [comment]
gracias!

**Comment by IsaacConDosA** [comment]
@MainScientist otra duda respecto lo mismo. 
el "rating" de los productos, debe ser un float, pero lo entregan como str, ni siquiera como int. 
Lo adaptamos de todas formas? Porque es el único atributo en que pasa eso. Para los demás, cuando son int los entregan como int

**Comment by Nebula2028** [comment]
me sumo a la duda... a que se refieren con transformar de lista a tupla? Como se hace eso cuando la lista tiene 3 elementos? Una tupla con una tupla y un número? :S No entiendo la idea de complicarse haciendo eso y no dejarlo simplemente como lista de dimensiones. 

Otra cosa, con "los entregan como int o como string" te refieres si el numero viene con o sin comillas cierto?

No sería más fácil si entregaran TODO entre comillas para facilitar asi la lectura de la información ? :(

**Comment by flobarrios** [comment]
Su parser debe ser genérico, un json puede contener strings, int, float, bool, null, etc.

**Comment by flobarrios** [comment]
@ifcarrera puedes hacer que al instanciar el objeto x, reciba el rating como:

``` python
rating = float(valor)
```

**Comment by agmardones** [comment]
@Nebula2028 tuple(lista) transforma la lista en tupla!
