### ISSUE TITLE
Otra duda con "formato" de archivos.txt

### ISSUE THREAD

**Issue by Nebula2028** [IIC2233-2016-1/syllabus#99]
Hola, lei las issues anteriores, pero no me quedaron muy clara algunas cosas.
1.- Nuestro parser debe ser capaz de leer los archivos independiente de los espacios que estos tengan, pero siempre y cuando respeten la estructura de corchetes { } para delimitar cada objeto distinto? 

2.- Pueden haber más signos { o } en los archivos adicionalmente de los que separan cada objeto? 

3.- La información relevante de los archivos "(nombre_atributo)" : "atributo" será siempre entre comillas o no ? Creo haber leido en una respuesta que si, pero revisando el archivo productos.txt por ejemplo, hay 29.980 lineas que tienen solo 2 comillas (en ves de las 4 esperadas). Normalmente esto es en casos donde dice "id" = 1234567890 (el numero no está entre comillas).

Sorry si son dudas tontas pero me he complicado arto haciendo los parser para leer los archivos

**Comment by flobarrios** [comment]
1. Si
2. Si
3. No, un json no necesariamente tiene solo strings en los valores, también puede contener ints, floats, booleans y nulls. El id que pusiste entrega un valor del tipo int

**Comment by gbordoni** [comment]
Una duda con este mismo tema. En que parte del enunciado sale eso? Todo lo que leo es:

_"La revision de la tarea sera realizada con distintos archivos .txt"_

Ahora, por favor, en que parte esto me da a entender como van a ser los archivos con los que van a revisar la tarea? Como se yo que tipo de archivo cae en la categoria de Json y cual no? Como se de que manera van a estar escritos dichos archivos?

Lo que me da a entender esa frase es solo que pueden tener distintos archivos con distintos usuarios, distintas subastas, nose. En lo personal mi parser sirve para leer solo el tipo de archivos que me pasaron. Estaria mas que bueno que, si van a pedir algo, lo especificaran en el enunciado, o no?

saludos

**Comment by flobarrios** [comment]
La idea era que realizaran un parser que fuera genérico, capaz de leer cualquier tipo de archivo json. Lo que quiere decir el enunciado es que se probará con distintos archivos pero siguiendo el mismo formato de los que les entregamos. Puede tener menos usuarios, menos productos, etc pero la estructura es la misma.

 Les dejo el link de JSON por si quieren entender un poco mas de este : http://www.json.org/json-es.html

**Comment by MortizDX** [comment]
Una duda similar pero para la hora de actualizar los datos ¿se puede escribir la estructura en un orden distinto? Por ejemplo, en el caso de "productos.txt", generalmente "id" va al final y "rating" varía su orden un poco dependiendo del tipo de producto ¿puedo ponerlos en el orden que yo quiera esos datos, pero siguiendo la estructura json?

**Comment by flobarrios** [comment]
Hola ! Si se puede, siempre y cuando mantengas la estructura general y cada producto contenga todos sus atributos.

**Comment by cabarra** [comment]
@flobarrios Hola, no entendí lo siguiente. @Nebula2028  preguntó "Pueden haber más signos { o } en los archivos adicionalmente de los que separan cada objeto?" y tú respondiste que sí. El tema es que no se me ocurren muchos casos en los que efectivamente puedan haber más signos "{" o "}" además de los que delimitan los atributos de cada usuario. Subentiendo que la contraseña, el correo, y el nombre de usuario podría contener a los caracteres '{' y/o '}', pero eso siempre respetando la estructura dada por el archivo usuarios.txt, la cual muestra que los atributos de cada usuario siempre estan contenidos dentro de corchetes. Con esto no podría ser que apareciese un corchete en la lista de productos, ni en el atributo dinero, ni en el atributo nombre, ¿o debo ser capaz de manejar errores como esos en los que la información viene mal ingresada en el archivo 'usuario.txt' ?
Saludos.

PD = En el fondo lo que pregunto, de forma muy enredada, es si puedo asumir que los archivos .txt que se usarán para la revisión de la tarea, no contendrán errores como los que mencioné.

**Comment by flobarrios** [comment]
Hola!! Esa respuesta iba orientada a un json cualquiera. Te recomiendo preocuparte de ser capaz de abrir los archivos  y trabajar con ellos en la modelación y si al final te queda tiempo, trabaja en los casos borde.
